### PR TITLE
Skip detecting asset key when asset value is null

### PR DESCRIPTION
**Pull request by Amrysliu**
See: https://progress.opensuse.org/issues/64938

### CODE REVIEW

**Comment by Martchus** [comment]
So reverting https://github.com/os-autoinst/openQA/pull/2861 was unnecessary and didn't even help and the actual culprit was https://github.com/os-autoinst/openQA/pull/2860/files#diff-daeb812b7eb46c12f6ec790a2ec2d399L85 ? It would be great to have some tests for this case.

**Comment by Amrysliu** [comment]
> So reverting #2861 was unnecessary and didn't even help and the actual culprit was https://github.com/os-autoinst/openQA/pull/2860/files#diff-daeb812b7eb46c12f6ec790a2ec2d399L85 ? It would be great to have some tests for this case.

In my test it was. I did the test using the master branch code, when `+ISO=` exists in settings, the ISO will be re-written to a directory. I did some test in my local environment,  the cache service is disabled, I think maybe it does not affect the test result.

**Comment by okurz** [comment]
I think we need to go a bit slower here and invest the time in proper testing. Keep in mind that #2860 was *also* reverted and was brought in again in https://github.com/os-autoinst/openQA/pull/2870

**Comment by okurz** [comment]
I hotpatched openqaworker7 with https://github.com/os-autoinst/openQA/pull/2877 and restarted the only free worker instance `systemctl openqa-worker@5` and retriggered a run from a formerly failed test job with

```
$ openqa-clone-job --skip-chained-deps --within-instance https://openqa.opensuse.org/1218665 TEST=okurz_poo64938_boot_to_snapshot_openqaworker7_hotpatched_openQA_2877 BUILD=poo64938 WORKER_CLASS=openqaworker7
```

Created job #1218700: opensuse-Tumbleweed-DVD-x86_64-Build20200329-gnuhealth@64bit -> https://openqa.opensuse.org/t1218700

test is fine so the fix is helpful. Not sure about other impacts but nevertheless we can move ahead. I will merge the PR. But please make sure to subsequently add better tests to cover this.

**Comment by okurz** [comment]
@mdoucha please be aware of this fix as a followup to your PR https://github.com/os-autoinst/openQA/pull/2870

**Comment by Amrysliu** [comment]
When I am editing this comment,  the pr has been merged. 
I would like to show the test result. 
I used my own test case. The job (id: 513) was run with the master branch code (before this pr merged). And the job(id: 521) was run with this pr code, it did not show the error message reported by `qeum-img`. 
we could see from these pictures,  if the values of an asset key (e.g ISO) is null, they are still be added to  $res (in master branch `sub detect_asset_keys {$res{$key} = $type}`). So the ISO will be re-written in `locate_local_assets` or `cache_assets`(?) (this depends on if enable cache service, but I did not test enabling cache service). 
513_log
513_settings
513_vars
521_log
521_settings
521_vars

**Comment by mdoucha** [comment]
I'm thinking about adding a simple testcase `t/24-worker-engine.t` but I'm not sure what should be the result with these settings:

    {
        ISO => '',
        ISO_URL => 'http://example.net/some/path/to/image.iso'
    }

**Comment by okurz** [comment]
IMHO ISO='' should never arrive at the worker engine but an empty value should be deleted already in an earlier step, e.g. the jobs post handling. But then the asset behind a URL should have been downloaded already by a gru task and ISO (probably) is set internally to the downloaded file.

**Comment by AdamWill** [comment]
So IIRC the intended behaviour of setting `FOO_URL` and `FOO` is that the value of `FOO` is an override for the final target name of the asset - so you could set `ISO_URL = http://example.com/foo.iso` and `ISO = bar.iso` and openQA should download `http://example.com/foo.iso` but name it `bar.iso`.

Obviously in this case explicitly setting an empty value is nonsensical and the 'expected behaviour' would probably be that the value get ignored and we act as if `ISO` was not set at all.

The current code for deciding whether to "figure out" the target file name from the URL, or just use a specified value, uses this test:

        if (!$args->{$short}) {

i.e. it's checking truthiness, not just whether it's defined. The var being set to the empty string should fail that check, and so indeed we should wind up ignoring the empty string value. `create_downloads_list` also overwrites the value *in the hash ref it is working from*, but not anywhere else, so the empty string value will still be there in lots of ways (e.g. the API job `create` method will use the params hash with the empty string value in lots of other calls). I would probably expect that will trip things up somewhere further down the line - I don't know offhand what os-autoinst does when it sees `ISO` set to an empty string, but it's probably nothing good :)

**Comment by AdamWill** [comment]
Hmm, looking into it more closely...it looks to me like *on the `jobs post` path* - i.e. in `Controller/API/V1/Job.pm` `create()` - we create the job via `$self->schema->resultset('Jobs')->create_from_settings` *before* `create_downloads_list` is called, which I think will mean that at the point the job gets created and the settings are stashed to the DB, the value will be the empty string.

But *on the `isos post` path - i.e. in `Controller/API/V1/Iso.pm` `schedule_iso()` - we call `create_downloads_list($args)` before we call `$self->_generate_jobs($args);`, so on *that* path the `_generate_jobs` call should use the hash as modified by `create_downloads_list` (with the empty string value changed out) and the behaviour should be OK...

**Comment by Amrysliu** [comment]
@AdamWill Thanks for your comments and sorry for replaying so late.

>  if you just use `jobs post` and post a job with a `FOO_URL` setting but _no_ `FOO` setting at all, I don't see how that's going to work as intended. I wonder if this path is really used/tested properly?

I did a test with `FOO_URL` but no `FOO`, the job failed.  I am not sure if it is expected or it is handled correctly. I will commit a ticket to record this question and wait for feedback. As you said, if the `_generate_jobs` use the `args` which modified by `create_downloads_list`, it should be ok.

**Comment by AdamWill** [comment]
As we designed the `_URL` stuff, passing just `FOO_URL` with no `FOO` is valid and is in fact the normal use case, openQA is expected to figure out the `FOO` value for itself from the URL (as it does on the `isos post` path). Passing both was intended as a not-typically-used override for the case where you wanted to change the final asset file name from the one that would be derived from the URL, for some reason.

When we first did this stuff I don't think `jobs post` was around at all, I think that got added later, so it's possible the `_URL` stuff has never worked as it was originally intended to work on that path. We don't really use that path in Fedora scheduling, and we're the main users of the `_URL` thing, I think.

**Pull request merged**
