### PR TITLE
Improve error handling when changing priority

### PR DESCRIPTION
**Pull request by Martchus**
* Fix priority being stuck at 0 (see https://progress.opensuse.org/issues/47285)
* Use flash messages

### CODE REVIEW

**Comment by coolo** [comment]
Flash! Flash, I love you!

**Comment by Martchus** [comment]
I'll take that GIF as approval.

**Comment by okurz** [comment]
s/changeing/changing/

**Comment by Martchus** [comment]
Fixed the commit message

**Pull request merged**
