### PR TITLE
docs: Fix documentation for "PARALLEL_CANCEL_WHOLE_CLUSTER"

### PR DESCRIPTION
**Pull request by okurz**
According to t/05-scheduler-cancel.t setting a false value, in this
example 0, prevents the cancellation of the cluster, not a true value.

### CODE REVIEW

**Comment by okurz** [comment]
@AdamWill I would appreciate if you can take a look. You introduced this flag in https://github.com/os-autoinst/openQA/pull/2017 and I think the documentation was the wrong way around.

Also, a colleague tried it out and the flag did not work for him, i.e. siblings were still cancelled despite `PARALLEL_CANCEL_WHOLE_CLUSTER=0` on all jobs of the cluster. Maybe you have an idea?

**Review by Martchus — APPROVED** [review]
This would also match the actual code and the comment there:

```
            my $cancelwhole = 1;
            # check if the setting to disable cancelwhole is set: the var
            # must exist and be set to something false-y
            my $cwset = $p->settings_hash->{PARALLEL_CANCEL_WHOLE_CLUSTER};
            $cancelwhole = 0 if (defined $cwset && !$cwset);
```

Likely the behavior was amended (e.g. requested in a PR review) for compatibility but the documentation has been forgotten.

**Comment by AdamWill** [comment]
:+1: The change is correct, thanks.

On the "does it work?" topic - well, it did when I wrote it, at least :) I am not 100% sure it still does. One note is that it only works for failed or cancelled *children* - it's still the case that if the "parent" (the job the children are parallel with) fails or is cancelled, the whole rest of the cluster is cancelled.

Given how the test case works it's certainly plausible that something got changed that the test case misses, I guess - it uses scheduled (not running) jobs and calls the `done` method on one of the child jobs then checks the parent and the other child. If someone changed something about how we fail or cancel jobs in reality that doesn't match up with that, it could have broken...

**Comment by AdamWill** [comment]
I just did a quick test on this...I cancelled [this job](https://openqa.stg.fedoraproject.org/tests/958081), which is one child in a fairly [large cluster](https://openqa.stg.fedoraproject.org/tests/958079#dependencies) which has `PARALLEL_CANCEL_WHOLE_CLUSTER` set to 0]. It seemed to behave as expected - only that job was cancelled, the parent and the other children are still scheduled.

**Comment by okurz** [comment]
Thanks a lot. That's helping.

**Pull request merged**
