### PR TITLE
Dependencies: Add Getopt::Long::Descriptive to client deps

### PR DESCRIPTION
**Pull request by perlpunk**
Issue: https://progress.opensuse.org/issues/66218

### CODE REVIEW

**Comment by perlpunk** [comment]
OBS complains:
```
[   51s] found conflict of openQA-4.6.1588168579.c0b65ce57-lp151.1.1.noarch with openQA-client-4.6.1588168579.c0b65ce57-lp151.1.1.noarch:
[   51s]   - /usr/share/openqa/public/schema/JobTemplates-01.yaml
```
because the whole `public` directory is already in the main package:
```
%{_datadir}/openqa/public
```

Not sure how to fix this. @okurz ?

**Comment by perlpunk** [comment]
I could try fetching the schema from the web if it doesn't exist in the filesystem...

**Comment by okurz** [comment]
Probably what you can do is make the assignment for the folder "public/" to the main package more specific to not include *everything*, e.g.

```
- public/
+ public/packed/
+ public/*.ico
+ public/robots.txt
```

so that the folder `public/schema/` is not included and you can have the template in the client – if it is actually not necessary in the main package anymore.

Can you please be a bit more specific in your git commit message what you want to achieve here?

**Comment by perlpunk** [comment]
I decided to only fix the Getopt::Long::Descriptive dependency in this PR.
Another PR will follow that allows the script to use a schema url instead of a file.

**Comment by perlpunk** [comment]
https://github.com/os-autoinst/openQA/pull/3020

**Comment by perlpunk** [comment]
> please be a bit more specific in your git commit message what you want to achieve here

Hm, I thought it was clear. The client package needs Getopt::Long::Descriptive.

**Comment by perlpunk** [comment]
@okurz is the commit message ok now?

**Comment by okurz** [comment]
I get it now :) thanks. There is a trivial typo in the commit message. Please fix that and feel free to merge then

**Comment by perlpunk** [comment]
fixed typo in commit message

**Pull request merged**
