### PR TITLE
DO NOT MERGE: Test stability of t/ui/27-plugin_obs_rsync_status_details.t

### PR DESCRIPTION
**Pull request by Martchus**
Same as #3888; before merging https://github.com/os-autoinst/openQA/pull/3882 I amended a detail which might make a difference. Hence I want to run the test again.

### CODE REVIEW

**Comment by okurz** [comment]
https://app.circleci.com/pipelines/github/os-autoinst/openQA/6434/workflows/103bfd6c-7969-48a3-b45c-638ecf353f14/jobs/60586?invite=true#step-108-77

```
Rerun 4 of 50 …
[08:40:47] t/ui/27-plugin_obs_rsync_status_details.t .. 179/? Bailout called.  Further testing stopped:  Wait limit of 60 seconds exceeded for "tr#folder_Proj2appliances .dirtystatuscol .dirtystatus", no change: published on 2021-05-11 08:42:14 +0000 (appliances)
FAILED--Further testing stopped: Wait limit of 60 seconds exceeded for "tr#folder_Proj2appliances .dirtystatuscol .dirtystatus", no change: published on 2021-05-11 08:42:14 +0000 (appliances)
```

**Comment by Martchus** [comment]
With the increased timeout 50 runs passed. I'm re-triggering to be sure. If it works I'll create a PR with the increased timeout.

**Comment by okurz** [comment]
flaky is flaky ;) Do you have an idea how to approach the problem? Would you like to discuss elsewhere?

**Comment by Martchus** [comment]
This didn't take long to fail:

```
Rerun 2 of 200 …
[10:18:46] t/ui/27-plugin_obs_rsync_status_details.t .. 296/? Bailout called.  Further testing stopped:  Wait limit of 240 seconds exceeded for "tr#folder_BatchedProj .dirtystatuscol .dirtystatus", no change: published on 2021-05-18 10:19:21 +0000 (containers)
FAILED--Further testing stopped: Wait limit of 240 seconds exceeded for "tr#folder_BatchedProj .dirtystatuscol .dirtystatus", no change: published on 2021-05-18 10:19:21 +0000 (containers)
make[2]: *** [Makefile:187: test-unit-and-integration] Error 255
```

**Comment by okurz** [comment]
ok, good. So then we know :) Do you see it feasible to follow up with the minion-mocking approach or delete the non-reliable parts of the test code?

**Comment by Martchus** [comment]
I guess I'll try the Minion-mocking a little harder and if it doesn't work I could try to remove non-reliable parts.

**Pull request closed without merging**
