### PR TITLE
Nicely wrap serial text boxes and don't display leading empty line

### PR DESCRIPTION
**Pull request by asdil12**
Before:

After:

### CODE REVIEW

**Review by Martchus — APPROVED** [review]

**Review by perlpunk — APPROVED** [review]

**Comment by perlpunk** [comment]
CircleCI fails because of new dependencies. I retriggered the nightly dependency job, we should see a PR soon

**Comment by perlpunk** [comment]
> CircleCI fails because of new dependencies. I retriggered the nightly dependency job, we should see a PR soon

ah no, actually you need to rebase instead. the updates happened a few days ago

**Comment by asdil12** [comment]
just had another look - this PR *is* rebased

**Comment by perlpunk** [comment]
> just had another look - this PR _is_ rebased

I just fetched your fork.
git log tells me your branch is based on d98ec8708 :)

**Comment by okurz** [comment]
Let's ask an impartial ressource.
@Mergifyio rebase
plz :)

**Comment by okurz** [comment]
@Mergifyio rebase

**Pull request merged**
