### PR TITLE
fixed a typo in openqa Installing.asciidoc

### PR DESCRIPTION
**Pull request by giufus**

### CODE REVIEW

**Review by kalikiana — APPROVED** [review]

**Review by Martchus — APPROVED** [review]
I'm approving but please change the commit message to "Fix a typo in Installing.asciidoc" to follow our conversation.

**Review by Martchus — CHANGES_REQUESTED** [review]
Now you have pushed a merge commit on the branch you want us to merge. Please remove that merge commit again. A simple amendment of your commit message would have been all that was needed.

**Comment by giufus** [comment]
Hi Martchus, I usually do a pull with rebase (-r) from the upstream remote, amend and push with force. I hope it works for you too. I don't have any problem If you close the pr and fix directly, totally fine IMO. I was just trying to play with openQA,  found that typo and thought it could be my nano contribution to the project :) the same as if you pick plastic from the ground. Best, giufus

**Review by perlpunk — APPROVED** [review]
It looks good now :)

**Pull request merged**
