### PR TITLE
limit_assets: never remove assets for scheduled/running jobs

### PR DESCRIPTION
**Pull request by AdamWill**
I'm not at all sure this is correct, but I *think* it may be
needed. AFAICS, limit_assets does not do anything at present
to avoid removing assets associated with pending jobs, and I
think it should, so it doesn't 'clean up' a generated HDD
while a job is still queued up expecting to use it, for e.g.

Please do have someone familiar with this code check this over
and make sure a) it's needed and b) it works right.

### CODE REVIEW

**Comment by coolo** [comment]
if you run into this problem, your job group's size limit is too small. Because what you actually do in this code is ignoring all running job's assets when calculating the job group. As these jobs are the youngest, normally they wouldn't be touched anyway - if all *their* assets fit in the size limit.

And now you ignore the running jobs and that means you remove one of the old assets - limiting the *old* jobs to the size limit. What should really happen in your situation is that it removes *all* old assets as the young jobs's assets already exceed the size limit.

**Comment by AdamWill** [comment]
mm, I guess. I don't actually know if we *are* running into this, it's just something I considered while trying to figure out why uploaded HDD images are mysteriously going missing somehow.

**Comment by coolo** [comment]
it shouldn't touch HDDs that were not generated within openqa. That would be a different bug

**Comment by AdamWill** [comment]
no, these *are* generated within openqa. That's what I mean by 'uploaded': ones uploaded from workers.

**Comment by AdamWill** [comment]
still, let's abandon this for now, if you think it's wrong.

**Pull request closed without merging**
