### PR TITLE
Fix worker's online/offline status

### PR DESCRIPTION
**Pull request by Martchus**
See https://progress.opensuse.org/issues/69784 and particular commit messages.

---

To avoid a regression in the case of a graceful disconnect I added some extra handling for it, so as a bonus we get:

screenshot_20200908_174215

### CODE REVIEW

**Review by okurz — COMMENTED** [review]
To allow an easier way for rollback I suggest you create a PR first with just the schema change, i.e. adding the column. We can merge that PR first and this one like on the next day or so.

**Review by okurz — APPROVED** [review]

**Comment by Martchus** [comment]
@okurz Why not. I'll have to fix some tests anyways. So I'll split the first commit into the database migration and other changes.

**Comment by okurz** [comment]
https://github.com/os-autoinst/openQA/pull/3375 merged

**Review by kalikiana — APPROVED** [review]
It looks odd at first, seeing the `t_seen` column *almost* act as a drop-in replacement for `t_updated`, but it makes sense since its value is more controlled afterall.

And, too, I like the *bonus* feature.

**Pull request merged**
