### PR TITLE
worker job: Add log of second virtio console to upload list

### PR DESCRIPTION
**Pull request by asmorodskyi**
Add log of second virtio console to upload list

### CODE REVIEW

**Comment by jlausuch** [comment]
LGTM

**Comment by okurz** [comment]
@cfconrad?

**Comment by cfconrad** [comment]
Of course this is better then don't have that file and a valid quick problem solver.

But as commented (here)[https://github.com/os-autoinst/openQA/pull/2269#discussion_r314688714], it would not solve the problem when having more virtio consoles. 
Also the (comment)[https://github.com/os-autoinst/openQA/pull/2269#discussion_r314711933] is still valid for me. 
Personally I would prefer the solution of a variable https://github.com/os-autoinst/openQA/pull/2269, as it makes it transparently to understand why certain files are missing or been present.

**Comment by coolo** [comment]
Then we're back to https://github.com/os-autoinst/openQA/pull/2269#issuecomment-525679404

**Comment by cfconrad** [comment]
Agree, so lets do this PR, as it only change the "default" files to be uploaded.
And go with an index file in https://github.com/os-autoinst/openQA/pull/2269

**Pull request merged**
