### PR TITLE
clone_job.pl: Skip downloading generated assets in all cases

### PR DESCRIPTION
**Pull request by okurz**
Related progress issue: https://progress.opensuse.org/issues/19024

### CODE REVIEW

**Comment by coolo** [comment]
LGTM, but the tests fail to compile the script.

**Comment by okurz** [comment]
because I deleted one variable which I thought I would not need. Fixed.

**Comment by coolo** [comment]
Can you please work on the coverage?

**Comment by okurz** [comment]
how?

**Pull request merged**
