### PR TITLE
Follow the 'restart job' link when clicking after save needle

### PR DESCRIPTION
**Pull request by coolo**

### CODE REVIEW

**Comment by okurz** [comment]
where is the test?

If you don't want to add one I can try to do it

**Comment by coolo** [comment]
easy enough 71f330d

**Comment by coolo** [comment]
I'm fixing issues, I don't need code proving me right

**Comment by okurz** [comment]
yes, but we need tests for everyone else but you to prevent them from breaking again what you superhuman fixed

**Comment by coolo** [comment]
Eben

**Pull request merged**
