### PR TITLE
Separate 'Build' from real build display in groups and search results

### PR DESCRIPTION
**Pull request by mimi1vx**
https://progress.opensuse.org/issues/129871
After:
Group overview
Search results

### CODE REVIEW

**Comment by kalikiana** [comment]
@mimi1vx Is there a ticket for this? Maybe we should discuss the motivation first.

**Comment by Martchus** [comment]
Shouldn't this be rather "Build: ..." as normally a colon is used in cases like that? However, maybe we can also get rid of"Build" completely? I'm also wondering about the motivation, though.

**Comment by Martchus** [comment]
If we make it configurable we might as well make the whole prefix configurable. But on which level? This is supposedly not only about the group-related dashboards but also about other tables.

**Review by okurz — CHANGES_REQUESTED** [review]
> If we make it configurable we might as well make the whole prefix configurable. But on which level? This is supposedly not only about the group-related dashboards but also about other tables.

For that I suggest we clarify the use case first

**Pull request closed without merging**
