### PR TITLE
Add pagination for /api/v1/test_suites, /api/v1/machines, and /api/v1/products

### PR DESCRIPTION
**Pull request by kraih**
They all share the same controller and action.

Progress: https://progress.opensuse.org/issues/121105

### CODE REVIEW

**Comment by kraih** [comment]
The `codecov/path` fail is wrong. It complains about `Influxdb.pm`, which i did not change at all. 🙄

**Review by okurz — DISMISSED** [review]
In the test I see duplicate test messages which make it harder to understand TAP output like which specific test step the message "has first page" refers to. I suggest you either extract test helper functions or make more test messages unique, e.g. "first page of test suites on prev link"

**Comment by kalikiana** [comment]
> In the test I see duplicate test messages which make it harder to understand TAP output like which specific test step the message "has first page" refers to. I suggest you either extract test helper functions or make more test messages unique, e.g. "first page of test suites on prev link"

I guess subtests would help with that

**Review by Martchus — APPROVED** [review]
In theory it is a bit problematic that our UI cannot make use of this kind of paging. However, since the default limit is high enough it shouldn't come to this anyways.

**Review by okurz — COMMENTED** [review]
do we really need to repeat all those pagination tests especially because they all use the same code?

**Comment by kraih** [comment]
> do we really need to repeat all those pagination tests especially because they all use the same code?

Yes, i think so. The tests look very similar, but there are subtle differences and each limit is enforced by a completely different SQL query. The link headers themselves are not so important, but the fact that they represent the correct paginated data does in each case.

**Review by okurz — APPROVED** [review]
ok, I hope you checked that there is no significant runtime impact

**Comment by kraih** [comment]
> ok, I hope you checked that there is no significant runtime impact

This is all very cheap and fast.

**Pull request merged**
