### PR TITLE
Prevent loading arbitrary plugins in live view handler

### PR DESCRIPTION
**Pull request by Martchus**
See https://progress.opensuse.org/issues/57113

### CODE REVIEW

**Comment by Martchus** [comment]
This is actually a general problem of the command interface. E.g. the plugin is even loaded when printing the usage via `script/openqa help`. So the problem with Gru is a bit different because it is technically not a different script with its own "run" function. It is just a special command of the regular web API daemon.

Hence I merge this for now and for the Gru (or actually "non-daemon command") case within the regular openQA script we need something different. Maybe @kraih knows how to implement this in the best way.

**Comment by kraih** [comment]
Mojolicious plugins are meant to be loaded for all commands, design your plugins accordingly. And adding routes costs nothing, you're inventing a problem there.

**Comment by kraih** [comment]
In fact, you're breaking features by not adding routes for commands. https://mojolicious.org/perldoc/Mojolicious/Guides/Routing#Introspection

**Comment by Martchus** [comment]
Mh... make sense. I assume "design your plugins accordingly" then means to ensure that the rsync plugin doesn't to anything stupid. That's already the case, right? @andrii-suse Or what do you mean with "I think is not good" (Rocket Chat link is not working)?

Note that if there's a problem which is yet to be solved we should create a ticket instead of having the discussion in this PR.

**Comment by andrii-suse** [comment]
> Or what do you mean with "I think is not good" (Rocket Chat link is not working)?

Somehow I missed that gru doesn't actually start WebServer, so extra routes shouldn't be an issue here.

**Pull request merged**
