### PR TITLE
WIP: Grouping results of a parent group

### PR DESCRIPTION
**Pull request by coolo**
This is a followup of #976 - still in active development and without tests

### CODE REVIEW

**Comment by coolo** [comment]
I only did this to create a more realisistic mockup thinking I can do something quick&dirty, but it turned out the devil is in the detail much more than I expected :)

E.g. for some reason for build2188 you get way less jobs when you query the individual job groups than what is in the summary. The reason is that most, but not all job groups are at the time limit and are skipped.

To me this means we will need to query the jobs for all groups - and then filter them manually.

**Comment by coolo** [comment]
https://w3.nue.suse.com/~coolo/screencapture-gertrude-suse-de-1478844946303.png

**Comment by okurz** [comment]
as you overtook, maybe ask ast about here opinion (maybe you already did).

**Comment by coolo** [comment]
Changed the filtering logic now. We still need to polish this on the CSS level and have the folding, but I think this is the way to go - I like it.

**Comment by coolo** [comment]
we also lack reviews and tags. Tests to be covered:

 - parent group marked reviewed if all groups are
 - parent group not marked if one is missing
 - group reviews appear also below parents
 - tags inherited from job groups (if two have conflicting labels, it's undefined which is shown)
 - showing only tagged shows all groups of a parent tagged through one its children

I suggest to create the groups and jobs for them in a test::more test where we can manipulate the DB freely.

**Comment by coolo** [comment]
https://w3.suse.de/~coolo/screencapture-gertrude-suse-de-1478944694757.png - included collapsing and grouped the maintenance groups to make the dashboard more compact

**Comment by okurz** [comment]
can we make the parent build bar a bit more prominent? E.g. bigger, indent children build bars, etc.

**Comment by coolo** [comment]
indenting should do.

**Comment by coolo** [comment]
got the approval of the RM :)

**Comment by Martchus** [comment]
Index page doesn't even load. Do you want me to rework this? To see how it looks like I'll have to fix it anyways.

**Comment by Martchus** [comment]
The error I'm gettings is

```
Can't locate object method "child_group_ids" via package "OpenQA::Schema::Result::JobGroupParents" at /home/martchus/repos/openQA/script/../lib/OpenQA/BuildResults.pm line 74.
```

Not sure why this is the case because the method should be available.

**Comment by coolo** [comment]
obsolete

**Pull request closed without merging**
