### PR TITLE
Makefile: Allow to skip checkstyle

### PR DESCRIPTION
**Pull request by okurz**
As the 'checkstyle' test can take some time provide a switch to skip it on
demand which can be useful when for example one wants to collect coverage from
a single test and execute this in a faster manner.

Example use: `make CHECKSTYLE=0 PROVE_ARGS=t/full-stack.t coverage-html` to
execute the full stack test and collect coverage without needing to conduct
the long-running style check every time.

### CODE REVIEW

**Comment by coolo** [comment]
I don't consider this more readable - how about just making checkstyle a nop in this case instead of skipping the dependency

**Comment by okurz** [comment]
You mean a nop in shell? Because I can make it an empty target with the same "ifeq" syntax if you like that more than not specifying the dependency.

**Comment by coolo** [comment]
empty target is at least more local than what you are proposing right now

**Comment by okurz** [comment]
agreed, looks better :-) updated

**Comment by okurz** [comment]
@Martchus

**Pull request merged**
