### PR TITLE
Fix group overview when no builds shown

### PR DESCRIPTION
**Pull request by Martchus**
* Fix https://progress.opensuse.org/issues/14136
* Also group name was missing in heading

### CODE REVIEW

**Comment by coolo** [comment]
deserves a test IMO

**Comment by okurz** [comment]
What I would say :-/

**Comment by Martchus** [comment]
Actually the `use Test::Warnings;` already tests the group is defined (which is the bug this commit fixes) because otherwise warnings occur. But I extended the tests to explicitly check whether the heading is rendered correct. I noticed that `limit_builds=0` and fixed it, too.

**Comment by Martchus** [comment]
I guess you have to work around it by using `around 'size_limit_gb' => sub {` syntax. Now `$self` is not the right object, but I'll figure this one, too.

**Pull request merged**
