### PR TITLE
Avoid logging user-input related errors in YAML to server log

### PR DESCRIPTION
**Pull request by Martchus**
* Distinguish between errors caused by user-input (1) and unhandled
  errors (2)
* Report only (1) to the user and log only (2) to the server log
* Treat constraint violations as user-input related as they are most likely
  caused by the input as well
* See https://progress.opensuse.org/issues/106880

### CODE REVIEW

**Comment by perlpunk** [comment]
The CI problems in the fullstack / unstable tests are likely caused by https://progress.opensuse.org/issues/107002 , I commented there

**Comment by okurz** [comment]
Typo in commit message s/unnecassary/unnecessary/

**Comment by Martchus** [comment]
@perlpunk Indeed. At least now we have the video, see https://progress.opensuse.org/issues/106912.

**Comment by kalikiana** [comment]
So this is failing in unstable:

```
Retry 1 of 5 …
[14:10:29] t/05-scheduler-full.t .. 3/? 
    #   Failed test 'Allocated maximum number of jobs that could have been allocated'
    #   at t/05-scheduler-full.t line 225.
    #          got: '9'
    #     expected: '10'
    # Looks like you failed 1 test of 1.
[14:10:29] t/05-scheduler-full.t .. 4/? 
```

And subsequent runs fail due to issues with retries, see https://progress.opensuse.org/issues/107002 but I think this PR doesn't have to block on that.

**Review by kalikiana — APPROVED** [review]

**Review by perlpunk — COMMENTED** [review]
I think I don't see a test case where an unexpected error happens and is logged, (but we also didn't have that before). Do you think it makes sense to add one?
Other than that all good.

**Comment by okurz** [comment]
@mergifyio rebase

**Comment by perlpunk** [comment]
You could rebase now as the unrelated problems with the unstable tests should be fixed.

**Comment by okurz** [comment]
@perlpunk I just asked mergify to do that. It's just weird that it looks like "kraih" would have rebased.

**Review by okurz — CHANGES_REQUESTED** [review]
codecov/patch failed. As this PR is non-critical I recommend to increase patch coverage as part of this work here.

**Comment by Martchus** [comment]
Ok, so I need to cover:

```
        # Push the exception to the list of errors without the trailing new line
        push @$user_errors, substr($_, 0, -1);
```

and 

```
    if (@server_errors) {
        push @$user_errors, 'Internal server error occurred';
        $self->app->log->error(@server_errors);
```

**Review by perlpunk — APPROVED** [review]

**Pull request merged**
