### PR TITLE
Remove deprecated openqa-client calls in openqa-label-all

### PR DESCRIPTION
**Pull request by foursixnine**
Remove deprecated openqa-client calls
Improve logging for openqa-label-all script

### CODE REVIEW

**Comment by foursixnine** [comment]
I wonder why Mergify didn't pick this pr up.

**Comment by okurz** [comment]
If you click the link "Show all checks" and follow the mergify entry entitled with "Summary" you can find the link https://github.com/os-autoinst/openQA/pull/4317/checks?check_run_id=4034460047 which shows which rules are matched already and which are not. Currently `#approved-reviews-by>=2` is not checked because there is only one approval, by me. So this PR is waiting for someone else to approve. It's a bit unfortunate that no one looked at this PR for 13 days but maybe your and my comment motivates people to take a look again :)

**Comment by foursixnine** [comment]
@okurz well good thing nobody else looked at it, looks like there's weird thing here:

```
DEBUG:./script/openqa-label-all:call: ['openqa-cli', 'api', '--host', 'https://openqa.suse.de', '-X POST', 'jobs/7619399/comments', 'text=https://progress.opensuse.org/issues/100940']
Unknown option: X POST

vs 

DEBUG:./script/openqa-label-all:call: ['openqa-cli', 'api', '--host', 'https://openqa.suse.de', '-X POST', 'jobs/7619399/comments', 'text=https://progress.opensuse.org/issues/100940']
Simulating:  openqa-cli api --host https://openqa.suse.de -X POST jobs/7619399/comments text=https://progress.opensuse.org/issues/100940

```

same line (I even replaced the casing). Afaict this didn't happen before. Any hints?

**Comment by foursixnine** [comment]
> @okurz well good thing nobody else looked at it, looks like there's weird thing here:
> 
> ```
> DEBUG:./script/openqa-label-all:call: ['openqa-cli', 'api', '--host', 'https://openqa.suse.de', '-X POST', 'jobs/7619399/comments', 'text=https://progress.opensuse.org/issues/100940']
> Unknown option: X POST
> 
> vs 
> 
> DEBUG:./script/openqa-label-all:call: ['openqa-cli', 'api', '--host', 'https://openqa.suse.de', '-X POST', 'jobs/7619399/comments', 'text=https://progress.opensuse.org/issues/100940']
> Simulating:  openqa-cli api --host https://openqa.suse.de -X POST jobs/7619399/comments text=https://progress.opensuse.org/issues/100940
> ```
> 
> same line (I even replaced the casing). Afaict this didn't happen before. Any hints?

I think I remember why now.

**Comment by perlpunk** [comment]
I'm having some problems understanding this. In one commit exception handling is added, in the next it's removed again. Why?

**Comment by foursixnine** [comment]
@perlpunk https://github.com/os-autoinst/openQA/pull/4317#discussion_r732719135

**Review by okurz — APPROVED** [review]

**Review by Martchus — APPROVED** [review]
I would avoid the global variables and pass the variables as arguments but I suppose the change is generally ok. I assume you've tested it locally before.

**Comment by foursixnine** [comment]
@Martchus Same, but for now I think it's good enough, given that I seem to be the only user for now xD. In any case yeah, last review was done using this version :)

**Comment by mimi1vx** [comment]
why this file is using subprocess to call another tool wheen we have python-OpenQA library? +- half of code can go away?

**Comment by okurz** [comment]
> why this file is using subprocess to call another tool wheen we have python-OpenQA library? +- half of code can go away?

Because I wrote the application as standalone initially and python-openQA is intended for a different purpose. If you think it can be refactored easily to have less duplication I would be happy to see that.

**Pull request merged**
