### PR TITLE
Mark the worker

### PR DESCRIPTION
**Pull request by coolo**

### CODE REVIEW

**Comment by coolo** [comment]
This is actually a very severe problem wasting tons of our worker time - and I'm not even sure my fix is good enough. But let's see what you guys come up with.

```
drwxr-xr-x 4 geekotest nogroup 417792  2. Mär 22:22 00281502-sle-12-SP2-Server-DVD-x86_64-Build1217-sles12_qa_userspace_4
drwxr-xr-x 4 geekotest nogroup 417792  2. Mär 23:34 00281652-sle-12-SP2-Server-DVD-x86_64-Build1217-sles12_qa_userspace_4
drwxr-xr-x 4 geekotest nogroup 417792  3. Mär 00:19 00281657-sle-12-SP2-Server-DVD-x86_64-Build1217-sles12_qa_userspace_4
drwxr-xr-x 4 geekotest nogroup 417792  3. Mär 01:04 00281658-sle-12-SP2-Server-DVD-x86_64-Build1217-sles12_qa_userspace_4
drwxr-xr-x 4 geekotest nogroup 417792  3. Mär 01:49 00281659-sle-12-SP2-Server-DVD-x86_64-Build1217-sles12_qa_userspace_4
drwxr-xr-x 4 geekotest nogroup 417792  3. Mär 02:34 00281663-sle-12-SP2-Server-DVD-x86_64-Build1217-sles12_qa_userspace_4
drwxr-xr-x 4 geekotest nogroup 417792  3. Mär 03:25 00281664-sle-12-SP2-Server-DVD-x86_64-Build1217-sles12_qa_userspace_4
drwxr-xr-x 4 geekotest nogroup 417792  3. Mär 04:13 00281666-sle-12-SP2-Server-DVD-x86_64-Build1217-sles12_qa_userspace_4
drwxr-xr-x 4 geekotest nogroup 417792  3. Mär 05:06 00281667-sle-12-SP2-Server-DVD-x86_64-Build1217-sles12_qa_userspace_4
drwxr-xr-x 4 geekotest nogroup 417792  3. Mär 06:24 00281668-sle-12-SP2-Server-DVD-x86_64-Build1217-sles12_qa_userspace_4
drwxr-xr-x 4 geekotest nogroup 417792  3. Mär 07:11 00281669-sle-12-SP2-Server-DVD-x86_64-Build1217-sles12_qa_userspace_4
drwxr-xr-x 4 geekotest nogroup 417792  3. Mär 08:28 00281670-sle-12-SP2-Server-DVD-x86_64-Build1217-sles12_qa_userspace_4
drwxr-xr-x 4 geekotest nogroup 417792  3. Mär 10:12 00281671-sle-12-SP2-Server-DVD-x86_64-Build1217-sles12_qa_userspace_4
drwxr-xr-x 4 geekotest nogroup 417792  3. Mär 11:04 00281678-sle-12-SP2-Server-DVD-x86_64-Build1217-sles12_qa_userspace_4
drwxr-xr-x 4 geekotest nogroup 417792  3. Mär 12:23 00281679-sle-12-SP2-Server-DVD-x86_64-Build1217-sles12_qa_userspace_4
drwxr-xr-x 4 geekotest nogroup     79  3. Mär 12:17 00281698-sle-12-SP2-Server-DVD-x86_64-Build1217-sles12_qa_userspace_4
```

**Comment by aaannz** [comment]
I'm not sure about `job_update_result`. Doesn't worker open new connection for each update? So in theory, if the DB strikes again there can be once update in progress when another one is started using different mojo worker and can clash?

Btw. I thought as we use mojo in nonblocking manner in worker, that it still sends keep alives even during upload.

**Comment by coolo** [comment]
Yes, but the "# This ugly." comment makes me think that this is not working as expected :)

**Comment by coolo** [comment]
the worker won't open a new connect until the previous result post is done.

**Comment by aaannz** [comment]
Well, it doesn't need to open new connect. WS connection is always kept open. See Common.pm:319. The callback operates on opened `$tx`

Another idea can be that the single threaded WS server is unable to keep up with the higher number of workers (and maybe with DB slowness)

**Comment by coolo** [comment]
0028166-71 are all the same the test - there was nothing else going on the whole morning. Only one active worker with one single test.

**Comment by nadvornik** [comment]
I don't understand why the worker stops sending the keep alive messages. The file is uploaded by 128K chunks (see Mojo/Asset/File.pm) while the event loop is normally running, so it can normally continue to send keepalives.

**Comment by coolo** [comment]
as we still have no log of the websocket service, we can't say when it stopped ;(

**Comment by okurz** [comment]
+1 don't really get the full impact of this but as you are removing more than adding ok for me :-)

**Comment by coolo** [comment]
@aaannz @nadvornik So I stayed home until I caught the job uploading - and if you check openqaw3.qa:/tmp/log you will see at 09:45:17 the first activity on the WS socket. the 5 minutes before of that log are all about POST to artefact route, i.e. upload function.

**Comment by coolo** [comment]
So this async mojo upload doesn't work as reliable as you hoped

**Comment by coolo** [comment]
but the good news is: my work around succeeded: https://openqa.suse.de/tests/282678 has a final result

**Pull request merged**
