### PR TITLE
Remove unused function `set_running`

### PR DESCRIPTION
**Pull request by Martchus**

### CODE REVIEW

**Review by baierjan — APPROVED** [review]

**Review by kalikiana — APPROVED** [review]
Nice find!

**Comment by Martchus** [comment]
Consider this the final refactoring.

**Comment by okurz** [comment]
> This is fun - it's obsolete since [4928543](https://github.com/os-autoinst/openQA/commit/4928543c86dbe204f46f559a621aafcff4c52e36) (2019) and the function saw 3 refactorings since :)

And refactoring of unused functions are risk-free so those are my favorites ;)

**Comment by coolo** [comment]
It had a good test case too

**Pull request merged**
