### PR TITLE
Fix typo in documentation

### PR DESCRIPTION
**Pull request by pevik**
Signed-off-by: Petr Vorel <pvorel@suse.cz>

Just a tiny typo fix.

### CODE REVIEW

**Comment by coolo** [comment]
Now this goes too far as related to commit logs even for me. Please leave off the signed-off - you are not touching copyright worthy code anyway - but make the commit log half way english

**Comment by pevik** [comment]
@coolo sorry (old branch, created before okurz, I forgot to check).

**Comment by coolo** [comment]
What's wrong with statements instead of groups of words? E.g. "Fix typo in documentation"

**Comment by pevik** [comment]
@coolo just used to different approach. Thanks for info, fixed.

**Comment by pevik** [comment]
@coolo I'm sorry for asking for merge twice. It was already merged in #1096. I do silly mistakes today :-(.

**Pull request merged**
