### PR TITLE
Dependency cron 200513

### PR DESCRIPTION
**Pull request by openqabot**

### CODE REVIEW

**Comment by Martchus** [comment]
When trying to reproduce the cache test failure locally I get the exact same error message although I still have `perl-DBD-Pg-3.11.1` installed.

**Comment by okurz** [comment]
good that you crosschecked. Will you continue digging further?

**Comment by Martchus** [comment]
Yes, I'll try to dig a little bit deeper. And not sure about the failing `t/05-scheduler-full.t` test, too. It fails for me locally in a different way.

**Comment by andrii-suse** [comment]
Should we try to restart the CI job or it is 100% reproducible?
@Martchus btw just to make sure you are aware: packages mentioned in ci:base image are not tracked by dependencies.txt, so it may be additional challenge  if one of those causes the problem
https://build.opensuse.org/package/view_file/devel:openQA:ci/base/_service:download_url:Dockerfile?expand=1

**Comment by Martchus** [comment]
Unfortunately I can reproduce the failing `25-cache-service.t` test only sometimes. But it looks that the timeout is just not sufficient. The sleep time has been reduced in b51241a45e but it isn't using `Time::HiRes` so it is not really sleeping at all anymore, e.g. on my machine it takes under a second until all 600 tries are exhausted. It can be also problematic that the test relies on port 9530 being free but then one gets a different error message if that isn't the case.

`t/05-scheduler-full.t` passes locally on the 2nd try and re-triggering in the CI helped as well. So it is likely just unstable but the failure has nothing to do with the upgrade.

**Comment by Martchus** [comment]
Might it be that CircleCI is generally slow today? Because the further test issues within the scheduler fullstack test and scalability test which now show up look like that might be the problem.

**Pull request merged**
