### PR TITLE
Dependency cron 2021-07-30

### PR DESCRIPTION
**Pull request by openqabot**

### CODE REVIEW

**Comment by okurz** [comment]
https://app.circleci.com/pipelines/github/os-autoinst/openQA/7241/workflows/34e4e37b-57e3-411c-8ef0-c7c8b0ea03ed/jobs/68343/steps shows a pretty clear related problem:

```
"sqlite_unicode" attribute will be deprecated. Use "sqlite_string_mode" instead. at /usr/lib/perl5/vendor_perl/5.26.1/x86_64-linux-thread-multi/DBI.pm line 734.
```

**Comment by perlpunk** [comment]
@AdamWill already opened a ticket https://progress.opensuse.org/issues/96317 and an issue https://github.com/DBD-SQLite/DBD-SQLite/issues/87

**Comment by okurz** [comment]
Alright. So do I understand https://github.com/DBD-SQLite/DBD-SQLite/issues/87#issuecomment-889461978 correctly that a new version of DBD-SQLite will remove the warning again and we can expect an auto-updated package version for us in openSUSE to arrive soon?

**Comment by perlpunk** [comment]
A patched DBD::SQLite is on its way to Factory: https://build.opensuse.org/request/show/909336

**Comment by okurz** [comment]
so we can reject this PR here even though other PRs might be blocked as well due to unavailability of the older version

**Pull request closed without merging**
