### PR TITLE
Require at least IO Socket SSL 2.009

### PR DESCRIPTION
**Pull request by SergioAtSUSE**
- Ticket: https://progress.opensuse.org/issues/39032
- Build verification: https://build.opensuse.org/package/show/home:SLindoMansilla:branches:devel:openQA/openQA
- Verification run: (coming soon)

### CODE REVIEW

**Comment by mudler** [comment]
Also https://github.com/os-autoinst/openQA/blob/master/cpanfile#L37 would require the same change

**Comment by coolo** [comment]
I don't think you need to touch cpanfile - it's only required to connect TLS sites, which openQA doesn't on its own

**Comment by mudler** [comment]
I don't know, but maybe it's a bit safer to do IMO, expecially if in future we might want to generate specfile or either way around.. because now we should maintain both, why differing on purpose?

**Comment by coolo** [comment]
if we do that in future, we can still align.

**Pull request merged**
