### PR TITLE
Avoid running out of database IDs - jobs table

### PR DESCRIPTION
**Pull request by Martchus**
* Convert all database ID-columns of the jobs table and related tables
  from integer to bigint
* Adapt code that specifies the types explicitly
* See https://progress.opensuse.org/issues/112265

### CODE REVIEW

**Review by kraih — APPROVED** [review]

**Review by okurz — APPROVED** [review]

**Comment by Martchus** [comment]
This took now around an hour. So one hour less compared to the full migration. Maybe it makes actually sense to do it in two parts then. At least our own setups would benefit as they're updated very regularly.

**Comment by kraih** [comment]
Still struggling to see the benefit, it's going to require a maintenance window either way.

**Comment by okurz** [comment]
> This took now around an hour. So one hour less compared to the full migration. Maybe it makes actually sense to do it in two parts then.

you mean it makes sense how to solve it how you do it with this separate PR?

**Comment by okurz** [comment]
> Still struggling to see the benefit, it's going to require a maintenance window either way.

I fear so. But we don't have an easy way to communicate to all users and customers how to prepare for such migration. Maybe we can come up with a better idea to make the automatic migration more smooth?

**Comment by Martchus** [comment]
> you mean it makes sense how to solve it how you do it with this separate PR?

I don't care. We can merge either PR, it is just that merging this one first isn't as beneficial as one might have thought but it indeed reduces the time a little bit. Merging this one first means the remaining migrations still need to be done. Maybe it is better to have just one disturbance (and not also a second one - although the second one will hopefully be faster).

> Maybe we can come up with a better idea to make the automatic migration more smooth?

I wouldn't know how. We could maybe allow read-only access while the migration is running but that doesn't seem worth the effort. We could operate on a copy of the database but loosing all changed made during the migration seems counterproductive. Note that the migration will hopefully be faster on the production machine (compared to my slow laptop HDD).

**Comment by okurz** [comment]
So we decided in daily 2022-06-15 that you just add a warning message that at least admins are informed why the service does not come up and why it takes long. Then admins can either wait or abort the migration and reconduct it at a convenient time.

Then we merge on Friday afternoon for two reasons:
1. To pick a time when it would be rolled out automatically on accordingly configured instances when most users wouldn't care about a bit longer downtime
2. To prove that no kittens are harmed during a Friday-deployment

**Comment by Martchus** [comment]
I've been adding the warning. I tested it locally. I have also aborted several times with different delays and it didn't break anything.

**Comment by okurz** [comment]
@Martchus I sent a message in https://matrix.to/#/!dRljORKAiNJcGEDbYA:opensuse.org/$lmq-ywz1qJp65YrYV8MOQwfH1wNjrEwVJWWVd03rfYM and https://suse.slack.com/archives/C02CANHLANP/p1655289571311949 as head's up. You can send the message to various other channels as preparation if you like.

**Comment by okurz** [comment]
Merging after waiting period. We expect that continuously deployed instances can use the weekend with likely lower load and availability expectations for the migration without significant impact

**Comment by okurz** [comment]
Logs from deployment on o3:/var/log/openqa:

```
[2022-06-18T07:10:42.883202Z] [info] Listening at "http://127.0.0.1:9528"
[2022-06-18T07:10:42.884031Z] [info] Listening at "http://[::1]:9528"
[2022-06-18T07:10:42.934304Z] [info] Listening at "http://127.0.0.1:9527"
[2022-06-18T07:10:42.934999Z] [info] Listening at "http://[::1]:9527"
[2022-06-18T07:10:43.019713Z] [warn] [pid:23714] Job IDs will be converted to bigint. That may take multiple hours on big databases.  It is safe to stop the service (and start from scratch on the next startup).
[2022-06-18T07:15:35.981054Z] [debug] attempt to open ws proxy for job alp-0.1-kvm-and-xen-x86_64-Build17.1-alp_default@64bit (2420945) where URL to os-autoinst command server is unknown
[2022-06-18T07:15:35.999919Z] [info] Loading external plugin AMQP
[2022-06-18T07:15:36.105433Z] [info] Loading external plugin ObsRsync
[2022-06-18T07:15:36.853091Z] [info] Listening at "http://127.0.0.1:9526"
[2022-06-18T07:15:36.853696Z] [info] Listening at "http://[::1]:9526"
[2022-06-18T07:15:36.853824Z] [info] Manager 23714 started
```

so it took 5 minutes to migrate on o3.

**Comment by kraih** [comment]
That was fast. 🥳

**Comment by Martchus** [comment]
Yes, but let's see what time it needs to migrate OSD.

**Comment by okurz** [comment]
> Yes, but let's see what time it needs to migrate OSD.

18m

**Comment by okurz** [comment]
After the initial migration we ran into a bigger problem on one of our instances. Problem was reported in detail in https://progress.opensuse.org/issues/112718. A general suggestion is to run a manual `vacuum ANALYZE` on all changed tables, here in particular "jobs", "job_modules" and "job_settings".

**Pull request merged**
