### PR TITLE
Add tests if start_job set proper timers and stop_job removes them

### PR DESCRIPTION
**Pull request by aaannz**

### CODE REVIEW

**Comment by aaannz** [comment]
These unexpected changes are unreliable. Seems like sometimes travis run goes through some timeout and test covers more then expected.

**Comment by okurz** [comment]
are you sure? the coverage decrease seems to be related to timers and such so maybe it *is* related?

**Comment by aaannz** [comment]
The websocket server changes I saw number of times, but where it seems they are related to timers?

**Comment by okurz** [comment]
I guess you know better than me :-)

**Comment by coolo** [comment]
yeah, we need to work on making sure we always cover these timeouts. Then the problem is gone

**Pull request merged**
