### PR TITLE
[WIP] Wicked

### PR DESCRIPTION
**Pull request by mwolcendorf**
First attempt at adding a new wicked engine - this should be an alternative engine to the existing isotovideo. 
Currently the new engine is hardcoded and used instead of the isotovideo, the caching is removed, the openQA variables exported to the environment, and the wicked test script is called (but apparently incorrectly). 
Next steps:
- call the wicked script correctly,
- make the engine selectable,
- upload the resulting json file to openQA as the test result,
- put the detailed test result file in assets.

### CODE REVIEW

**Comment by okurz** [comment]
I think the approach in general to support other backends than just isotovideo has a lot of potential. Other than this the current implementation differs of course only very little from the copy sources. Short term the focus can be of course to make it work just for wicked testing, mid-term to support both isotovideo and wicked without duplicating code and long-term to have a generic approach and less reliance on isotovideo.

**Comment by okurz** [comment]
Hi @mwolcendorf the diff looks borked. Can you please rebase on origin/master and ensure only your changes are included?

**Comment by coolo** [comment]
as discussed: this has no future as it is - this should not be done in an engine but in a specific worker

**Comment by okurz** [comment]
why not an engine but a specific worker? Just by reading the names of the files my guess was that another engine would be the right match. Considering that there already is a concept of *engine* which currently points to isotovideo. This asks for alternatives, doesn't it? A name "Worker.pm" does not *really* ask for an alternative. How would it be called, like "WickedWorker.pm"? Granted, the name is inviting for cool ideas ;-)

**Comment by coolo** [comment]
You would have to redo the whole engine thingy *a lot* - for example the upload job function hardcodes the files we expect isotovideo to output.

And taking that the shared requirements between a wicked tester and isotovideo are basically 'can use the workers API' I don't even see the wicked tester as part of openQA itself.

**Comment by coolo** [comment]
and beside that, I wouldn't want a worker engine for every tool we might call

**Comment by okurz** [comment]
so … WickedWorker then and nothing related to engine? And probably that not within the openQA repo itself?

**Comment by coolo** [comment]
... it doesn't even have to be in perl. It's supposed to grab a job and repeatedly report some fake status and at the end a result. That's 3 API functions

**Pull request closed without merging**
