### PR TITLE
Allow admins to fetch the worker status by json

### PR DESCRIPTION
**Pull request by coolo**
https://progress.opensuse.org/issues/26842

### CODE REVIEW

**Comment by okurz** [comment]
Seems like a duplication of the API as we have it so I'm not sure.

**Comment by mudler** [comment]
Not actually a duplication in the API - as in the admin route workers state are extended with additional informations.

**Comment by coolo** [comment]
@okurz: I wouldn't want this to be documented as API - but from this and older tickets (some of yours) it's clear to me that people expect to have pages that display data also available as json. And it's often easily done

**Comment by okurz** [comment]
Sure, it was also my idea to have the .json extension on as many pages as possible. Was just a note. LGTM

**Comment by Martchus** [comment]
Looks good

**Pull request merged**
