### PR TITLE
Refactor resultstats

### PR DESCRIPTION
**Pull request by Martchus**
The [PR about making the 'All tests' table server-side](https://github.com/os-autoinst/openQA/pull/1375) is not ready yet, but this PR already includes some small related changes I made when trying to make the 'All tests' table server-side.

For the actual changes, see the particular commits itself.

### CODE REVIEW

**Comment by Martchus** [comment]
Not sure how the coverage changes relate to my changes. I'm not even 100 % sure how to read it. But maybe just a flaky test?

**Comment by mudler** [comment]
Until WebSockets server is completely covered by tests, we will keep seeing that

**Comment by Martchus** [comment]
Ok, so I think this could be merged.

**Comment by okurz** [comment]
+1

**Comment by Martchus** [comment]
The profiling I'm doing for https://progress.opensuse.org/issues/25814 shows that this PR would also reduce the loading time of the all tests page. At least `job_module_stats` takes around 10 % of the loading time (of the actual page, not AJAX).

**Pull request merged**
