### PR TITLE
Include t/ in our code coverage to prevent test coverage loss

### PR DESCRIPTION
**Pull request by okurz**
Related progress issue: https://progress.opensuse.org/issues/71449

### CODE REVIEW

**Comment by okurz** [comment]
I know I had already proposed to include "t/" in code coverage analysis and at least one person was against. Now we have https://progress.opensuse.org/issues/71449 and nobody realized, meaning we have test code that is never executed. Actually we had that problem already more than once. Again I am convinced that test code should be included in the code coverage analysis along with our goal to reach for the goal to have 100% statement coverage with explicit exceptions marked in the source code.

**Review by perlpunk — APPROVED** [review]

**Review by kalikiana — APPROVED** [review]
I think I'm leaning towards wanting this, also after pondering a few things talking this morning, it's just that prior experience with unreliable coverage targets makes me sceptical in general.

**Review by Martchus — CHANGES_REQUESTED** [review]
Counting tests itself adds a fake boost to the overall coverage percentage. I thought this PR was merely for investigation.

**Comment by okurz** [comment]
> Counting tests itself adds a fake boost to the overall coverage percentage.

It's a boost but I do not see it as fake. You can also see it as "fake" that javascript and template code is not included. But what does that mean to us? I don't think this speaks against including this.

> I thought this PR was merely for investigation.

Nope, it was for real. I expected more discussion before merge though :)

**Pull request merged**
