### PR TITLE
Give failed screenshots back the red border

### PR DESCRIPTION
**Pull request by coolo**

### CODE REVIEW

**Comment by okurz** [comment]
LGTM

**Comment by okurz** [comment]
"AssetPack was unable to fetch related asset" in check

**Comment by AdamWill** [comment]
I had some issues with AssetPack 1.40 yesterday while updating the Fedora packages. 1.39 and 1.41 seemed to be fine. I'm not sure what version the test got.

**Comment by AdamWill** [comment]
I've deployed this to Fedora staging, it seems to be working fine.

**Pull request merged**
