### PR TITLE
Mark the current tab in the hash ref without scrolling

### PR DESCRIPTION
**Pull request by coolo**

### CODE REVIEW

**Comment by aaannz** [comment]
I have no idea what this is supposed to do.

**Comment by coolo** [comment]
travis has its problems too :)

**Comment by coolo** [comment]
the problem is that if you go to tests/X#steps/bootloader/1 and then switch to comments the URL stays. So if you then pass your URL to a colleague, he will get a different page than the one you were looking at.

So the PR makes sure the URL follows the site much closer.

**Comment by okurz** [comment]
missing test. Please also update the commit message with the explanation you gave to aaannz

**Comment by okurz** [comment]
+1

**Pull request merged**
