### PR TITLE
t: Fix coverage of separate process in 25-cache.t

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by okurz** [comment]
A local coverage analysis was inconsistent and hence inconclusive. I would like to wait for the codecov report to crosscheck if this really works.

**Comment by okurz** [comment]
Interesting. The failed codecov/patch is pretty obvious and showing that my change does not address the problem.

@andrii-suse do you have a hint what I could do to ensure that
https://codecov.io/gh/os-autoinst/openQA/src/master/t/25-cache.t#L80 can be covered?

**Comment by andrii-suse** [comment]
> Interesting. The failed codecov/patch is pretty obvious and showing that my change does not address the problem.
> 
> @andrii-suse do you have a hint what I could do to ensure that
> https://codecov.io/gh/os-autoinst/openQA/src/master/t/25-cache.t#L80 can be covered?

My bet is that we never wait for `Devel::Cover::report()` to actually finish, so e.g. sleeping at the end of stop_server() or making sure somehow that $server_instance reached `_exit(0);` should do the trick.

**Review by Martchus — APPROVED** [review]

**Comment by okurz** [comment]
likely the process is terminated/killed/ended early by Mojo-IOLoop-ReadWriteProcess so we should set the process parameters `max_kill_attempts => 0, blocking_stop => 1, _default_blocking_signal => 'TERM'`

**Comment by Martchus** [comment]
Yes, these were my suggestions for sending a single `SIGTERM` and waiting for the termination judging by the code of the `stop` function within `lib/Mojo/IOLoop/ReadWriteProcess.pm`. Note that the signal should be `POSIX::SIGTERM` (not sure whether assigning a string works).

**Comment by andrii-suse** [comment]
Oh, I see we can try adding `wait_stop()` after stop(), like:

    # now kill the worker
    $server_instance->stop();
    $server_instance->wait_stop();

**Comment by Martchus** [comment]
I'd rather just rely on `stop`. With the mentioned parameters it wouldn't do any polling (with sleeps) and instead simply use `waitpid`.

**Comment by okurz** [comment]
I have added the parameters for the process as noted by me and suggested by mkittler. To reach 100% statement coverage I have deleted the duplicate sigint handling code which is already ensured by `END`

**Review by kalikiana — APPROVED** [review]

**Pull request merged**
