### PR TITLE
Specify dev container in file; Allow override in local container build

### PR DESCRIPTION
**Pull request by okurz**
* Install new, additional dependencies if necessary for testing within PR
* Specify development container dependencies in file
* travis_test: Use a FROM tag that is also available locally

### CODE REVIEW

**Comment by okurz** [comment]
https://build.opensuse.org/package/show/home:okurz:branches:devel:openQA:feature:deps_in_file/openQA should show the concept working however for reasons I do not yet understand the docker container build process fails to find packages, e.g. as visible in https://build.opensuse.org/package/live_build_log/home:okurz:branches:devel:openQA:feature:deps_in_file/openQA/containers/x86_64

Help would be appreciated.

**Comment by Martchus** [comment]
I can try to help next week. But did you read my comments from yesterday in Rocket Chat about our current CI problems?

**Comment by okurz** [comment]
> But did you read my comments from yesterday in Rocket Chat about our current CI problems?

no, sorry. Haven't

**Comment by okurz** [comment]
The problem in the container build seem to be the same though still and I have no clue how to continue. I would appreciate help.

**Comment by okurz** [comment]
From chat: Have you tested whether your branched Docker container build succeeds without the modifications? Maybe just the OBS setup of your branched project is missing something. https://build.opensuse.org/package/show/home:okurz:branches:devel:openQA:fix:python_sle12/openQA builds containers just fine so it's either my changes or a broken project setup. I should look into this eventually.

**Comment by coolo** [comment]
kind of obsolete

**Comment by okurz** [comment]
hm, is it? We still have the container files. Do we want to completely delete openqa_dev and travis_test?

**Comment by coolo** [comment]
I think we want to replace them yes. I.e. feed https://build.opensuse.org/package/show/devel:openQA:ci/base from git

**Pull request closed without merging**
