### PR TITLE
Save ipmi sol output as log file

### PR DESCRIPTION
**Pull request by waynechen55**
* **IPMI** SOL console output records important information about system under test, including boot-up process, error messages, unexpected abnormal output and etc, detailed texts of which likely might not be recorded by screenshot or even video clip. 

* **By** saving full output of ipmi sol console to a log file, which will be uploaded at the end of test run, investigation and examination work can be executed much more easily and conveniently without losing any information.

* **Modify**  ```lib/OpenQA/Worker/Job.pm``` to include ```ipmisol-log.txt``` when job starts and ends.

* **Modify** ```lib/OpenQA/Schema/Result/Jobs.pm``` to include ```ipmisol-log.txt``` as result file.

* **This** pull request should be merged together with https://github.com/os-autoinst/os-autoinst/pull/2504.

* **Verification Runs:**
  * [**test run without IPMISOL_LOG** link1](http://10.67.18.153/tests/2842) [link2](http://10.100.228.134/tests/2842) [link3](http://10.100.204.18/tests/2842) [link4](http://10.149.193.170/tests/2842)
  * [**test run with IPMISOL_LOG=0** link1](http://10.67.18.153/tests/2845) [link2](http://10.100.228.134/tests/2845) [link3](http://10.100.204.18/tests/2845) [link4](http://10.149.193.170/tests/2845)
  * [**test run with IPMISOL_LOG=1 passed** link1](http://10.67.18.153/tests/2834) [link2](http://10.100.228.134/tests/2834) [link3](http://10.100.204.18/tests/2834) [link4](http://10.149.193.170/tests/2834)
  * [**test run with IPMISOL_LOG=1 cancelled** link1](http://10.67.18.153/tests/2835) [link2](http://10.100.228.134/tests/2835) [link3](http://10.100.204.18/tests/2835) [link4](http://10.149.193.170/tests/2835)
  * [**test run with IPMISOL_LOG=1 failed** link1](http://10.67.18.153/tests/2843) [link2](http://10.100.228.134/tests/2843) [link3](http://10.100.204.18/tests/2843) [link4](http://10.149.193.170/tests/2843)
  * [**test run with IPMISOL_LOG=1 timed-out** link1](http://10.67.18.153/tests/2844) [link2](http://10.100.228.134/tests/2844) [link3](http://10.100.204.18/tests/2844) [link4](http://10.149.193.170/tests/2844)
  * [**ipmisol-log records full installation and boot-up process** link1](http://10.67.18.153/tests/2834) [link2](http://10.100.228.134/tests/2834) [link3](http://10.100.204.18/tests/2834) [link4](http://10.149.193.170/tests/2834)
  * [**ipmisol-log records full call trace** link1](http://10.67.18.153/tests/2846) [link2](http://10.100.228.134/tests/2846) [link3](http://10.100.204.18/tests/2846) [link4](http://10.149.193.170/tests/2846)

### CODE REVIEW

**Review by Martchus — APPROVED** [review]
It is a bit unfortunate that one has to touch various places and even add a regex for this.

**Comment by Martchus** [comment]
I'm only adding the not-ready label because the PR is marked as WIP but mergify probably doesn't consider that.

**Comment by waynechen55** [comment]
> I'm only adding the not-ready label because the PR is marked as WIP but mergify probably doesn't consider that.

I removed WIP

**Comment by waynechen55** [comment]
@alice-suse @guoxuguang @Julie-CAO @RoyCai7 @nanzhg @tbaev Please have a look.

**Review by okurz — APPROVED** [review]
waiting for more reviews, see https://github.com/os-autoinst/openQA/pull/5699#issuecomment-2177797061

**Comment by czerw** [comment]
Small reminder from older similar PR: https://github.com/os-autoinst/openQA/pull/4401#pullrequestreview-830315619

**Comment by czerw** [comment]
Whole this PR and related PR is duplicate to https://github.com/os-autoinst/openQA/pull/440, where was already found that such approach is not optimal (see whole discussion). And moreover it is duplicating existing `HARDWARE_CONSOLE_LOG` functionality.

**Review by okurz — CHANGES_REQUESTED** [review]
waiting for clarification of https://github.com/os-autoinst/os-autoinst/pull/2504#issuecomment-2180015212

**Comment by waynechen55** [comment]
> waiting for clarification of [os-autoinst/os-autoinst#2504 (comment)](https://github.com/os-autoinst/os-autoinst/pull/2504#issuecomment-2180015212)

I think we can use existing feature.

**Comment by okurz** [comment]
as per https://github.com/os-autoinst/os-autoinst/pull/2504#issuecomment-2181864092

**Pull request closed without merging**
