### PR TITLE
Assets

### PR DESCRIPTION
**Pull request by nadvornik**
Creating pull request for review, not yet finished.

Issues:
- it still does not work for very large images around 4.5 GB, Mojo UserAgent seems to be buggy.
- searching for assets in isotovideo.pm is ugly

### CODE REVIEW

**Comment by aaannz** [comment]
Yes, that's the plan. Vladimir wants to add creator_job_id column to assets, I wanted to add asset_id to JobDependencies table, but so far failed to convince him.

**Comment by coolo** [comment]
What do you need the extra column for? I was just thinking about cleanup and for that, just a jobsassets entry is needed.

**Comment by coolo** [comment]
you need to rebase and re-tidy

**Comment by nadvornik** [comment]
OK.
Menwhile I have solved the UserAgent problem and discussed with Ondrej that I rework the last 2 comits and move the code from isotovideo to scheduler.

**Comment by nadvornik** [comment]
Now it is ready for merging.

**Comment by coolo** [comment]
I assume we need https://github.com/os-autoinst/os-autoinst/pull/229 first?

**Comment by nadvornik** [comment]
it can be merged independently.

**Comment by coolo** [comment]
I see the move now. But this means we even more uncovered code now ;(

**Pull request merged**
