### PR TITLE
Dependency cron 2022-03-19

### PR DESCRIPTION
**Pull request by openqabot**

### CODE REVIEW

**Comment by perlpunk** [comment]
I bisected it, and the problem starts with https://github.com/os-autoinst/os-autoinst/commit/38559ff52dac5eb35cd3bf3ac6ead3d8028ffaec

**Comment by perlpunk** [comment]
I made progress with bisecting. Seems to be the usage of `assert_screen_deadline` in backend::baseclass. Will try to confirm.

**Comment by perlpunk** [comment]
https://github.com/os-autoinst/os-autoinst/pull/1996

**Comment by okurz** [comment]
https://github.com/os-autoinst/os-autoinst/pull/1996 merged. I guess tomorrow's dependency cron will fix it then

**Pull request closed without merging**
