### PR TITLE
Update dependencies for CI

### PR DESCRIPTION
**Pull request by openqabot**

### CODE REVIEW

**Comment by okurz** [comment]
@andrii-suse https://circleci.com/gh/os-autoinst/openQA/4937?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link and others fail because of "The test suite died before a plan was produced. You need to have a plan.". Is this a new error? I am not aware seeing it in before.

**Comment by andrii-suse** [comment]
I'd say that per-Selenium-Remote-Driver-1.36 is causing problems. I opened ssh session to CI, started database server and run `TEST_PG='DBI:Pg:dbname=openqa_test;host=/tmp/tmp.QH1FsJyU7d' prove -l -v t/ui/02-list-group.t` which did show `Could not create new session: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
`. Then I removed the package and installed old perl-Selenium-Remote-Driver-1.27 and the same prove command succeeded without issues

**Comment by okurz** [comment]
sure, sounds likely

**Comment by coolo** [comment]
https://stackoverflow.com/questions/50642308/webdriverexception-unknown-error-devtoolsactiveport-file-doesnt-exist-while-t seems to be related. Possibly we want to freeze the Selenium version until we fancy f***ing with chromedriver.

**Comment by Martchus** [comment]
This is locally reproducible using Tumbleweed which also has version `1.36` of `perl-Selenium-Remote-Driver`.

One just has to make the X session unavailable (e.g. by unsetting `XAUTHORITY`). Then one gets the same error message even though the test was started in non-headless mode.

**Comment by coolo** [comment]
```
not ok 25 - invalid argument: invalid argument
not ok 26 - unknown command: unknown command: Cannot call non W3C standard command while in W3C mode at /usr/lib/perl5/vendor_perl/5.26.1/Selenium/Remote/Driver.pm line 403.

**Comment by Martchus** [comment]
This is also locally reproducible. There's generally an option to disable this W3C mode (https://stackoverflow.com/questions/56111529/cannot-call-non-w3c-standard-command-while-in-w3c-mode-seleniumwebdrivererr). I just have to check how to pass it using the Perl module we use.

**Comment by coolo** [comment]
what non standard command are we passing?

**Comment by Martchus** [comment]
We are not passing any commands directly - the `Selenium::Remote::Driver` does that for us. So it is either a limitation of that Perl module or the chromedriver which might not support all commands. 

Note that this is not about validating our web page against WC3 standards (and hence finding errors on our side). This is just about the protocol used to communicate with chromedriver (either Wc3 protocol or the old JSONWire protocol).

Considering these "funny" release titles chromedriver seems to be generally problematic in WC3 mode: https://github.com/teodesian/Selenium-Remote-Driver/releases

**Comment by Martchus** [comment]
Seems like now it still doesn't like `WebElement::set_selected()` so I'm using `WebElement::click()` instead. I hope it also works with older versions of chromedriver.

**Pull request merged**
