### PR TITLE
t: Disable OpenQA::Test::TimeLimit by ENV variable or when running within debugger

### PR DESCRIPTION
**Pull request by okurz**
* t: Disable OpenQA::Test::TimeLimit when running within debugger
* t: Add option to disable test timeout with env variable

### CODE REVIEW

**Review by Martchus — COMMENTED** [review]
It would be nice to migrate this to the common repository first and apply the change from there.

**Comment by okurz** [comment]
Right. I forgot. How can we prevent that in the future except with a git submodule?

**Comment by okurz** [comment]
https://github.com/os-autoinst/os-autoinst-common/pull/5

**Comment by okurz** [comment]
checking https://codecov.io/gh/os-autoinst/openQA/pull/3555/diff?src=pr&el=tree#diff-dC9saWIvT3BlblFBL1Rlc3QvVGltZUxpbWl0LnBt first. Seems like `$DB::single` is also define when running tests with coverage analysis enabled. Anyone has a hint what we could look for to say "running from perl debugger"?

**Comment by kalikiana** [comment]
> checking https://codecov.io/gh/os-autoinst/openQA/pull/3555/diff?src=pr&el=tree#diff-dC9saWIvT3BlblFBL1Rlc3QvVGltZUxpbWl0LnBt first. Seems like `$DB::single` is also define when running tests with coverage analysis enabled. Anyone has a hint what we could look for to say "running from perl debugger"?

You could try

```
package DB;                                                                      
sub postponed { $DB::imadebug = 1; }
print "imadebuggin: " . ($DB::imadebug // 0) . ' ';
```

I couldn't easily test this under *cover*, though, `cover -select perltest.pl -report compilation` gave me no output... but unless cover runs a real debugger intercepting all statements this might work?

**Comment by okurz** [comment]
interesting. And when would `sub postponed { $DB::imadebug = 1; }` be called?

**Comment by kalikiana** [comment]
> interesting. And when would `sub postponed { $DB::imadebug = 1; }` be called?

Normally it's meant for you to inject code into the running debugger i.e. `perl -d` and [it's more or less documented here](https://perldoc.perl.org/perldebguts#Debugger-Internals) although honestly I just tried it out because I wasn't sure what this wall of text was really trying to tell me. But it *would* be called whenever a module is loaded. Not sure if it's a noticible performance hit but in a debugger you probably don't mind 10 calls to reset a value.

**Pull request closed without merging**
