### PR TITLE
Worker: Fix warning about undefined in "send_artefact"

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by coolo** [comment]
IMO this is hiding a bug. We shouldn't have artefacts without filenames

**Comment by okurz** [comment]
Agreed. But maybe it was always like this? The warning is only popping up now since a recent change by @kraih. Given that there are so many warnings but no obvious missing uploaded thumbnails or anything maybe it's ok.

**Comment by coolo** [comment]
Maybe or maybe not. This way it's just hiding the problem

**Comment by kraih** [comment]
There is always supposed to be a filename. If there isn't then there was an undefined value added to the list of images/files to upload.

**Comment by kraih** [comment]
The subprocess shouldn't matter in this case, the problem probably already existed before my patch. I just added a log message that uses the filename and expects it not to be `undef`. Do we have a test case to replicate the problem? Then i could look into it.

**Comment by Martchus** [comment]
I don't think we have a test case. This warning is likely just something @okurz noticed when reading the production log.

**Comment by okurz** [comment]
yes, test case being `ssh openqaworker-arm-3 'sudo journalctl -f'` and you should see it when enough jobs are running :) Feel free to trigger more jobs by cloning https://openqa.suse.de/tests/3338023

**Pull request closed without merging**
