### PR TITLE
Improve live log

### PR DESCRIPTION
**Pull request by Martchus**
Fixes that the developer mode freezes after a certain time. In fact, the live log has just gotten to long and Chromium and Firefox don't handle that well. I also allow line-wrapping in the live log and fixed some JavaScript errors reported by jshint.

### CODE REVIEW

**Comment by okurz** [comment]
Not sure about the line wrapping. Maybe it would be good to see some openQA example jobs.

**Comment by Martchus** [comment]
If I have a default full HD resolution and use half of the width (e.g. another windows uses the other half) it looks right now like this:
screenshot_20190114_105439

The only options to read the lines are resizing the window or decreasing the zoom level.

This PR changes this to look like this:
screenshot_20190114_105340

Admittedly it looks more cluttered but one can at least read everything. Since each line starts with a timestamp it is not too hard to figure where an actual new line starts.

Alternatively I could also enable a scrollbar:
screenshot_20190114_105509

It would also only take 5 minutes to add yet another check box to switch between the last two variants (checkbox would be called "Enable line wrapping").

**Comment by Martchus** [comment]
@okurz So what should it be? Otherwise I'll hit the merge button and we can do further improvements later (since in my opinion any of the options are better than how it currently is on master).

**Comment by okurz** [comment]
wrapping is fine

**Pull request merged**
