### PR TITLE
wip -- try to reproduce/fix stability problems in t/43-scheduling-and-worker-scalability.t

### PR DESCRIPTION
**Pull request by okurz**
Related progress issue: https://progress.opensuse.org/issues/65082

### CODE REVIEW

**Comment by okurz** [comment]
so in t/43-scheduling-and-worker-scalability.t in line 196 when we get 4 jobs instead of expected 5 , what is the last job doing? is this a test issue only or an issue that only concerns production in theory?

**Comment by Martchus** [comment]
This is hard to tell for sure. There are no errors and much other clues in the log (available under artifacts).

I belief the test is really just too slow at this point. At least the job doesn't look to be stuck in uploading because web UI's response for the artifact upload is still logged after the failing check as well as ongoing upload output from the worker. It also seems that the worker is at least able to react to the sigterm in time.

Considering that it is still failing, the `$polling_tries_jobs + 1` is apparently not enough. You could pick up the commit from https://github.com/os-autoinst/openQA/pull/2882 here to see if 2.5 seconds per job are enough.

**Comment by okurz** [comment]
@Martchus Included the overall polling duration increase from https://github.com/os-autoinst/openQA/pull/2882 and the pair-programmed change to use diag in log_jobs

**Comment by okurz** [comment]
@Martchus We have seen this once locally a well:

```
[09:42:17] t/43-scheduling-and-worker-scalability.t .. 1/? 
    #   Failed test 'each worker has a job assigned'
    #   at t/43-scheduling-and-worker-scalability.t line 165.
    #          got: '1'
    #     expected: '2'

    #   Failed test 'all jobs done'
    #   at t/43-scheduling-and-worker-scalability.t line 196.
    #          got: '0'
    #     expected: '5'

    #   Failed test 'all jobs passed'
    #   at t/43-scheduling-and-worker-scalability.t line 197.
    #          got: '0'
    #     expected: '5'
    # All jobs:
    #  - id: 1, state: assigned, result: none, reason: none
    #  - id: 2, state: scheduled, result: none, reason: none
    #  - id: 3, state: scheduled, result: none, reason: none
    #  - id: 4, state: scheduled, result: none, reason: none
    #  - id: 5, state: scheduled, result: none, reason: none
    # Looks like you failed 3 tests of 3.
[09:42:17] t/43-scheduling-and-worker-scalability.t .. 2/? 
#   Failed test 'assign and run jobs'
#   at t/43-scheduling-and-worker-scalability.t line 199.
```

This looks like the complete process hierarchy gets stuck.

https://19328-20883829-gh.circle-artifacts.com/0/artifacts/43-scheduling-and-worker-scalability.t shows

```
# Subtest: assign and run jobs
[DEBUG] +=----------------=+
[DEBUG] -> Scheduling new jobs.
[DEBUG] 	 Free workers: 2/2
[DEBUG] 	 Scheduled jobs: 5
[DEBUG] need to schedule 1 jobs for 1(50)
[DEBUG] need to schedule 1 jobs for 2(50)
[DEBUG] Job '2' has worker '2' assigned
[DEBUG] [Job#2] Prepare for being processed by worker 2
[debug] [20747ba8] GET "/api/v1/ws/2"
[debug] [20747ba8] Routing to a callback
# Mocking service port for websocket to be 56405
[debug] [20747ba8] 302 Found (0.002089s, 478.698/s)
[debug] [28aa76ec] GET "/ws/1"
[debug] [28aa76ec] Routing to controller "OpenQA::Shared::Controller::Auth" and action "check"
[debug] [28aa76ec] Routing to controller "OpenQA::WebSockets::Controller::Worker" and action "ws"
[debug] [28aa76ec] 101 Switching Protocols (0.011334s, 88.230/s)
[debug] [ce547f13] POST "/api/send_job"
[info] [pid:1119] Registered and connected via websockets with openQA host http://localhost:56225 and worker ID 1
[debug] [ce547f13] Routing to controller "OpenQA::Shared::Controller::Auth" and action "check"
[debug] [ce547f13] Routing to controller "OpenQA::WebSockets::Controller::API" and action "send_job"
[debug] [ce547f13] 200 OK (0.002512s, 398.089/s)
[debug] [0f5686f5] GET "/ws/2"
[debug] [0f5686f5] Routing to controller "OpenQA::Shared::Controller::Auth" and action "check"
[debug] [0f5686f5] Routing to controller "OpenQA::WebSockets::Controller::Worker" and action "ws"
[debug] [0f5686f5] 101 Switching Protocols (0.003527s, 283.527/s)
[debug] [pid:1114] Received from worker "1" worker_status message "{
  "status" => "free",
  "type" => "worker_status"
}
"
[debug] [pid:1114] Updating seen of worker 1 from worker_status
[debug] [pid:1114] Sent population to worker: { population => 2, type => "info" }
[DEBUG] Failed sending job(s) '2' to worker '2'
[info] [pid:1118] Registered and connected via websockets with openQA host http://localhost:56225 and worker ID 2
[debug] [pid:1114] Received from worker "2" worker_status message "{
  "status" => "free",
  "type" => "worker_status"
}
"
[debug] [pid:1114] Updating seen of worker 2 from worker_status
[DEBUG] Job 2 reset to state scheduled
[debug] [pid:1114] Found job 2 in DB from worker_status update sent by worker 2
[debug] [pid:1114] Sent population to worker: { population => 2, type => "info" }
[DEBUG] Job '1' has worker '1' assigned
[DEBUG] [Job#1] Prepare for being processed by worker 1
[debug] [20747ba8] POST "/api/send_job"
[debug] [20747ba8] Routing to controller "OpenQA::Shared::Controller::Auth" and action "check"
[debug] [20747ba8] Routing to controller "OpenQA::WebSockets::Controller::API" and action "send_job"
[debug] [pid:1114] Started to send message to 1 for job(s) 1
[debug] [20747ba8] 200 OK (0.00156s, 641.026/s)
[DEBUG] Sent job(s) '1' to worker '1'
[DEBUG] Scheduler took 0.46900s to perform operations and allocated 1 jobs
[DEBUG] Allocated: { job => 1, worker => 1 }
    # Assigned jobs: [
    #   {
    #     "job" => 1,
    #     "worker" => 1
    #   }
    # ]
    # Remaining jobs: 3
[debug] [pid:1119] Accepting job 1 from http://localhost:56225.
    not ok 1 - each worker has a job assigned
```

especially interesting:

```
[DEBUG] Job '2' has worker '2' assigned
[DEBUG] [Job#2] Prepare for being processed by worker 2
…
[DEBUG] Failed sending job(s) '2' to worker '2'
```

any hint how to continue?

**Comment by Martchus** [comment]
Seems like in this case the web UI thinks the worker has already been registered and already sends a job. However, only after that the worker has actually concluded the registration printing "Registered and connected via websockets with openQA host http://localhost:56225 and worker ID 2".

But looking at the code it doesn't seem like we have a race condition within the worker. Even though the "Registered ..." message is be only printed after returning the control flow back to the event loop (so the first web socket messages might already be processed before that message is shown) that should not be a problem at all. Maybe we have a race condition within the web UI/scheduler/web socket server so it already tries to send jobs after the workers registration but before the web socket connection is established. I'll have a look at the code.

**Comment by Martchus** [comment]
I haven't had the time to look for the mentioned race condition. However, this problem seems *very* uncommon. Usually we see that it is not fast enough. Hence I would suggest to merge my PR which increased the timeout as well as your commit for the `+ 1` in the loop because that's likely already a win.

**Comment by okurz** [comment]
So initial problem solved. Now https://circleci.com/api/v1.1/project/github/os-autoinst/openQA/20258/output/111/0?file=true&allocation-id=5e8bb67360e95d7defd691ec-0-build%2F65FC5FB7 now shows

```
[00:51:05] t/05-scheduler-full.t ..................... 4/? 
    #   Failed test 'closed ws connection logged by worker'
    #   at t/05-scheduler-full.t line 268.
    #          got: '0'
    #     expected: '1'

[00:51:05] t/05-scheduler-full.t ..................... 5/?     # Looks like you failed 1 test of 1.

#   Failed test 'Websocket server - close connection test'
#   at t/05-scheduler-full.t line 276.
# Looks like your test exited with 9 just after 5.

                                                            
[00:51:05] t/05-scheduler-full.t ..................... Dubious, test returned 9 (wstat 2304, 0x900)
Failed 1/5 subtests 
[00:57:01] t/43-scheduling-and-worker-scalability.t .. 
    #   Failed test 'all workers registered'
    #   at t/43-scheduling-and-worker-scalability.t line 148.
    #          got: '0'
    #     expected: '2'
    # Looks like you failed 1 test of 2.

[00:57:01] t/43-scheduling-and-worker-scalability.t .. 1/? 
#   Failed test 'wait for workers to be idle'
#   at t/43-scheduling-and-worker-scalability.t line 155.
Bailout called.  Further testing stopped:  Unable to assign jobs to (idling) workers
```

shows a different problem as well in `t/05-scheduler-full.t`. Anyone ideas about that?

**Comment by Martchus** [comment]
The fail in `t/43-scheduling-and-worker-scalability.t` means that not even the worker registration could happen in the expected time. After the failing check one can see in the log that the workers would actually register but apparently it just took too long:

```
    # Waiting until all workers are registered, try 97
    # Waiting until all workers are registered, try 98
    # Waiting until all workers are registered, try 99
    # Waiting until all workers are registered, try 100
    not ok 1 - all workers registered
    ok 2 - all workers idling
    1..2
not ok 1 - wait for workers to be idle
# Subtest: assign and run jobs
[info] [pid:5102] worker 2:
 - config file:           /tmp/ImKb9n4ygd/t/scalability/config/workers.ini
 - worker hostname:       79c4e24c06d3
 - isotovideo version:    0
 - websocket API version: 1
 - web UI hosts:          http://localhost:59633
 - class:                 ?
 - no cleanup:            yes
 - pool directory:        /tmp/ImKb9n4ygd/t/scalability/openqa/pool/2
[info] [pid:5101] worker 1:
 - config file:           /tmp/ImKb9n4ygd/t/scalability/config/workers.ini
 - worker hostname:       79c4e24c06d3
 - isotovideo version:    0
 - websocket API version: 1
 - web UI hosts:          http://localhost:59633
 - class:                 qemu_i386,qemu_x86_64
 - no cleanup:            yes
 - pool directory:        /tmp/ImKb9n4ygd/t/scalability/openqa/pool/1
[info] [pid:5102] Project dir for host http://localhost:59633 is /tmp/ImKb9n4ygd/t/scalability/openqa/share
[info] [pid:5101] Project dir for host http://localhost:59633 is /tmp/ImKb9n4ygd/t/scalability/openqa/share
[info] [pid:5101] Registering with openQA http://localhost:59633
[info] [pid:5102] Registering with openQA http://localhost:59633
```

---

In `t/05-scheduler-full.t` the web socket server is started and then the worker. The worker is expected to connect to the web socket server but it doesn't because it can not even register with the web UI:

```
# Subtest: Websocket server - close connection test
    # Starting WebSocket service
    # Bogus: 1 | No wait: 0
    # Starting standard worker. Instance: 2 for host http://localhost:58353
[info] Listening at "http://127.0.0.1:58354"
Server available at http://127.0.0.1:58354
    not ok 1 - closed ws connection logged by worker
    # worker log file contained:
    # [info] [pid:5077] worker 2:
    #  - config file:           /tmp/Gba4L1Tzlf/t/scheduler/config/workers.ini
    #  - worker hostname:       79c4e24c06d3
    #  - isotovideo version:    20
    #  - websocket API version: 1
    #  - web UI hosts:          http://localhost:58353
    #  - class:                 ?
    #  - no cleanup:            no
    #  - pool directory:        /tmp/Gba4L1Tzlf/t/scheduler/openqa/pool/2
    # [info] [pid:5077] Project dir for host http://localhost:58353 is /tmp/Gba4L1Tzlf/t/scheduler/openqa/share
    # [info] [pid:5077] Registering with openQA http://localhost:58353
    # [warn] [pid:5077] Failed to register at http://localhost:58353 - connection error: Connection refused - trying again in 10 seconds
    # [info] [pid:5077] Registering with openQA http://localhost:58353
    # [warn] [pid:5077] Failed to register at http://localhost:58353 - connection error: Connection refused - trying again in 10 seconds
[and so on]
```

The web UI was accepting registrations before in the test run but must have dies at some point. That's all what I can say after a brief look.

**Pull request closed without merging**
