### PR TITLE
travis_test: Switch to supported Leap base after 42.3 is EOL

### PR DESCRIPTION
**Pull request by okurz**
All dependencies are now provided in devel:openQA:Leap:15.1

### CODE REVIEW

**Comment by cfconrad** [comment]
What do you think of using a docker image like this for travis in `os-autoinst/os-autoinst` project?

**Comment by cfconrad** [comment]
Ok I was wrong, we already using it :)

**Comment by okurz** [comment]
https://build.opensuse.org/package/show/devel:openQA/openqa_dev would need it now because python3-yamllint is only in Leap since 15.1

Trying to fix https://build.opensuse.org/package/view_file/devel:openQA:TestGithub:PR-2497/openQA/_service?expand=1 manually by pointing to my branch on my fork.

**Comment by okurz** [comment]
no, haven't tried.

**Pull request merged**
