### PR TITLE
limit_assets: don't wipe assets for PENDING jobs

### PR DESCRIPTION
**Pull request by AdamWill**
This adds a protection in the limit_assets gru task that should
prevent it ever deleting an asset that's associated with a job
in any of the PENDING states.

### CODE REVIEW

**Comment by AdamWill** [comment]
So, this seems simple, but there are some interesting little conundrums to do with ordering and so on.

An alternative approach would be to produce the list of assets associated with pending jobs earlier, say before  the big `while` loop, then in the `for my $a (@job_assets) {` block, check each asset ID against that list and don't put it in `$toremove` if it's in that list, but still count its size against `$sizelimit` and `$reduceto`.

The difference is what happens when there are assets 'protected' by association with pending jobs, and we're over the size limit. With the approach I've actually proposed here, `$toremove` would contain a set of assets whose removal would bring us below `$reduceto`, but if there were 'protected' assets we would not in fact remove them all, and for now, the total size of all assets would remain larger than we intended.

With the alternative approach mentioned above, assuming there were some other assets we could throw away, those would get put into `$toremove` instead of the 'protected' assets, and we would still reduce the total size of all assets to the desired level - but by removing some more-recently-used assets than we otherwise would have done.

I think I prefer the approach I've proposed, for a couple of reasons:

* I think it's a bit more efficient (if we had to check each asset against the 'protected asset' list, I think that's slightly less efficient than just running a single DB query as in this approach)
* No asset should remain protected for very *long*, so I don't think the fact that we might not always reduce size as much as we aim to presents a real practical problem. Once the pending jobs complete, the 'protected' assets will no longer be protected and will get cleaned up the next time `limit_assets` runs

But if anyone has other thoughts, please say so...

**Comment by okurz** [comment]
Well, that was fast :)

does this solve https://progress.opensuse.org/issues/19672 ?

**Comment by coolo** [comment]
nope

**Comment by AdamWill** [comment]
Yeah, I was expecting an inquisition!

Are you sure it doesn't fix that problem? Won't the asset have pending jobs against it as soon as the jobs from the smaller group are scheduled, and thus be protected from removal?

If we do want to add a minimum life, though, it should be fairly easy to do, and could simply be an extension of the 'exception' query this commit added.

**Comment by coolo** [comment]
Yeah, I think we should have a minimum life - if we accept that job groups exceed their sizes for a time span, we can also spell it out :)

**Pull request merged**
