### PR TITLE
Package auto-update part on openSUSE only

### PR DESCRIPTION
**Pull request by ggardet**
This is a follow-up of https://github.com/os-autoinst/openQA/pull/3777

Build tested for SLE15-SP2/ https://build.opensuse.org/package/show/home:Guillaume_G:branches:devel:openQA/openQA

### CODE REVIEW

**Review by Martchus — COMMENTED** [review]
I'm wondering how installing this package is causing the additional files to be installed. We have

```
os := $(shell grep opensuse /etc/os-release)
.PHONY: install
ifeq ($(os),)
install: install-generic
else
install: install-opensuse
endif
```
within the `Makefile` but it only checks for `opensuse`.

**Comment by ggardet** [comment]
> I'm wondering how installing this package is causing the additional files to be installed. We have
> 
> ```
> os := $(shell grep opensuse /etc/os-release)
> .PHONY: install
> ifeq ($(os),)
> install: install-generic
> else
> install: install-opensuse
> endif
> ```
> 
> within the `Makefile` but it only checks for `opensuse`.

Indeed, my local test pointed this out as well. I will then skip the `auto-update` part on SLE.

**Review by Martchus — APPROVED** [review]
I'm fine with skipping these systemd files. Alternatively one could also invoke the `install-opensuse` target explicitly or extend the `grep` command to cover SLE as well.

**Comment by okurz** [comment]
Do you have a link on OBS for verification?

**Comment by ggardet** [comment]
> Do you have a link on OBS for verification?

It was a local build. Just did it on OBS: https://build.opensuse.org/package/show/home:Guillaume_G:branches:devel:openQA/openQA

**Comment by ggardet** [comment]
> I'm fine with skipping these systemd files. Alternatively one could also invoke the `install-opensuse` target explicitly or extend the `grep` command to cover SLE as well.

I guess this was on purpose to differentiate openSUSE from other targets.

**Pull request merged**
