### PR TITLE
clone CHAINED children on parent cloning

### PR DESCRIPTION
**Pull request by aaannz**
- this change behaviour when cloning parents with CHAINED children.
  Originally, children were left intact and only dependency recreated (but not 
  in case of cloning due to job asset dependency). Now, when
  parent is being cloned, all children are also cloned.
- reason is to consistently solve cloning issue due to job asset
  previously when job with job asset dependency was cloned, the mandatory
  CHAINED dependency was not recreated. Just recreating it however lead
  to confusion when CHAINED child is cloned and when not (asset
  dependencies are not visualized in WebUI). So we decided to clone
  CHAINED child every time parent is cloned (also useful during test development).
- PARALLEL dependency cloning behaviour is not affected

### CODE REVIEW

**Comment by aaannz** [comment]
I expect this PR to solve exactly this problem https://openqa.opensuse.org/tests/62822
After the cloning, the CHAINED dependency was not recreated, thus clones were unable to find private job asset, failing test setup.

**Comment by coolo** [comment]
you figure how bizarre "chained children" sounds to regular ears, right? :)

**Comment by aaannz** [comment]
I'm counting on that any agency automated parser will consider that as a trolling attempt. :)
So should we change the naming? Or change to codewords like Parent-Children -> A-B.
The text would be:
> - this change behaviour when cloning of A with CHAINED B. Originally, B were left intact and only  dependency recreated (but not in case of cloning due to job asset dependency). Now, when A is being cloned, all Bs are also cloned.

Doesn't sound that bad to me.

**Comment by coolo** [comment]
I think, CHAINED dependencies are fine. Just leave out children :)

**Pull request merged**
