### PR TITLE
git subrepo commit (merge) external/os-autoinst-common

### PR DESCRIPTION
**Pull request by b10n1k**
subrepo:
  subdir:   "external/os-autoinst-common"
  merged:   "38c45f3d1"
upstream:
  origin:   "git@github.com:os-autoinst/os-autoinst-common.git"
  branch:   "master"
  commit:   "db78c615c"
git-subrepo:
  version:  "0.4.6"
  origin:   "???"
  commit:   "???"

### CODE REVIEW

**Review by okurz — APPROVED** [review]

**Comment by okurz** [comment]
Let's see if the perlcritic check is impacted. If passed we can forcefully merged as the commit message check does not (yet) accept the subrepo messages this way

**Review by baierjan — CHANGES_REQUESTED** [review]
Not 100% sure about the correct subrepo usage, but I believe you want to use `git subrepo pull external/os-autoinst-common` (not commit) to avoid rebase/merge conflicts in the future? If we already have a conflict, than it should be probably better to clone the clean version of the external repo. Am I right, @perlpunk ?

**Comment by b10n1k** [comment]
> Not 100% sure about the correct subrepo usage, but I believe you want to use `git subrepo pull external/os-autoinst-common` (not commit) to avoid rebase/merge conflicts in the future? If we already have a conflict, than it should be probably better to clone the clean version of the external repo. Am I right, @perlpunk ?

i just `git subrepo pull`. there were some conflicts which i resolved and then `git commit` as the instruction that provided.

**Review by kalikiana — CHANGES_REQUESTED** [review]
Maybe this seems harsh, but this PR looks very messy and I have no idea what the point is.

1. Please clean up the description. What is this doing? Why do we need it?
2. Check the CI failures.

**Comment by Martchus** [comment]
I'm afraid this needs to be rebased so CI jobs have a chance to pass after the switch to npm.

**Comment by b10n1k** [comment]
Apparently https://github.com/os-autoinst/os-autoinst-common/pull/46/files makes the builds fail. I am struggling to put everything together and i will need more time. 
I see 
```
Test Summary Report
[  866s] -------------------
[  866s] ./t/40-script_openqa-clone-custom-git-refspec.t           (Wstat: 0 Tests: 44 Failed: 0)
[  866s]   TODO passed:   30, 32
[  866s] ./external/os-autoinst-common/xt/00-tidy.t                (Wstat: 6144 (exited 24) Tests: 389 Failed: 24)
[  866s]   Failed tests:  351, 353, 357-360, 362, 364, 366-371, 373
[  866s]                 375, 377-378, 380, 382-384, 386-387
[  866s]   Non-zero exit status: 24
[  866s] Files=106, Tests=5045, 794 wallclock secs ( 4.11 usr  0.65 sys + 659.22 cusr 80.93 csys = 744.91 CPU)
[  866s] Result: FAIL
[  866s] make[1]: *** [Makefile:226: test-unit-and-integration] Error 1
[  866s] make[1]: Leaving directory '/home/abuild/rpmbuild/BUILD/openQA-4.6.1707987465.33a4835'
[  866s] make: *** [Makefile:221: test-with-database] Error 2
[  866s] error: Bad exit status from /var/tmp/rpm-tmp.paF1rG (%check)
[  866s] 
[  866s] RPM build errors:
[  866s]     Bad exit status from /var/tmp/rpm-tmp.paF1rG (%check)
```
https://build.opensuse.org/package/live_build_log/devel:openQA:GitHub:os-autoinst:openQA:PR-5480/openQA/openSUSE_Tumbleweed/x86_64

**Comment by Martchus** [comment]
It seems to execute the developer tests now as part of the package build. I suggest you simply change the line `rm -f t/00-tidy.t` to `rm -f t/00-tidy.t external/os-autoinst-common/xt/00-tidy.t` in `openQA.spec`.

**Comment by perlpunk** [comment]
I rather think the right thing would be to add `t` to `PROVE_ARGS` to only run tests under `t`. It does not make sense to let `prove` search for tests under an "external" repository. All our tests we want to run should be in specific directories.

**Comment by perlpunk** [comment]
https://progress.opensuse.org/issues/138416 is already resolved, and we decided the ticket is only about os-autoinst-distri-example.
What ticket is this for?

**Comment by b10n1k** [comment]
> https://progress.opensuse.org/issues/138416 is already resolved, and we decided the ticket is only about os-autoinst-distri-example. What ticket is this for?

It is the same ticket. But i have done this some time before agree on the final requirements. What do you suggest?
We considered the ticket done as it fullfilled the requirements for os-autoinst-distri-example

**Comment by perlpunk** [comment]
I fixed it here: 
* #5481

**Comment by b10n1k** [comment]
closed as per https://github.com/os-autoinst/openQA/pull/5465#issuecomment-1946109439

**Pull request closed without merging**
