### PR TITLE
wip -- test for https://github.com/os-autoinst/openQA/pull/3536

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by okurz** [comment]
struggle with the cache in circleCI. https://app.circleci.com/pipelines/github/os-autoinst/openQA/4878/workflows/8e5eae08-098c-456d-8974-c50fb93f7fa3/jobs/46316 shows that the cache saving is skipped: "Skipping cache generation, cache already exists for key: v1-YGjDOa2GOkzu_8Xv5UDe+DwCfu2ZmJWJVlb6FbX66XI=-0ctxsgSE3h8sZFrULdZqhQKTjwrMfWf9GrviDcdOQG8=
Found one created at 2020-11-10 22:01:27 +0000 UTC". But I changed ci-packages.txt . Does anyone know what invalidates the cache or why it's considered the same?

**Comment by okurz** [comment]
Andrii suggested "to ignore old caches you can increment version in cache key in the ci config `v2-{{ checksum ..` or `vMyExperiments-{{ checksum"

**Comment by okurz** [comment]
hm, "ci/circleci: build-docs" shouldn't be scheduled here, please ignore :D

**Comment by andrii-suse** [comment]
Can it be that fullstack test fails because qemu needs to be hacked to run in docker?
Currently ci:base contaner installs qemu from :
https://build.opensuse.org/package/show/devel:openQA:ci/qemu

**Comment by okurz** [comment]
yes, likely. I would say doesn't matter because the rest is fine and after merging changes then devel:openQA:ci will auto-update and that one will have the right qemu version. However I did `osc linkpac devel:openQA:ci qemu home:okurz:branches:devel:openQA:pr3536_circleci_cache_base_image_less_packages` so we can also test it here

**Pull request closed without merging**
