### PR TITLE
Dependency cron 2020-11-09

### PR DESCRIPTION
**Pull request by openqabot**

### CODE REVIEW

**Comment by okurz** [comment]
```
[12:05:57] t/44-scripts.t ............................................ 65/? Bailout called.  Further testing stopped:  test exceeds runtime limit of '270' seconds
FAILED--Further testing stopped: test exceeds runtime limit of '270' seconds
```

which is really long. If I believe the changelog then this means a regression in perl-Mojolicious.

**Comment by kalikiana** [comment]
> ```
> [12:05:57] t/44-scripts.t ............................................ 65/? Bailout called.  Further testing stopped:  test exceeds runtime limit of '270' seconds
> FAILED--Further testing stopped: test exceeds runtime limit of '270' seconds
> ```
> which is really long. If I believe the changelog then this means a regression in perl-Mojolicious.

The re-run looks better:

```
[17:06:52] t/44-scripts.t ............................................ ok   197296 ms ( 0.02 usr  0.01 sys + 141.17 cusr 54.20 csys = 195.40 CPU)
```

**Comment by Martchus** [comment]
> If I believe the changelog then this means a regression in perl-Mojolicious.

What particular commit from the [changelog](https://github.com/mojolicious/mojo/compare/v8.63...v8.64) do you think causes it? Maybe the CircleCI VM was also just very slow.

**Comment by okurz** [comment]
Not *that* changelog but the diff of this PR showing just two things, os-autoinst with no relevant changes, and ci-packages.txt with only perl-Mojolicious failed

**Pull request merged**
