### PR TITLE
t: Catch all expected and unexpected warnings

### PR DESCRIPTION
**Pull request by okurz**
Supersedes #539 and #565
* t: Catch all warnings with Test::Warnings
* t: Catch all existing expected warnings
* t: Get rid of test plan to save the counting

### CODE REVIEW

**Comment by okurz** [comment]
updated:
* rebased
* no more warning catching in t/ui/07-file.t thanks to 987e5ef8a1a9595ffbaad11efc85208f09c6a86f

**Comment by aaannz** [comment]
I'm not sure about 'no_plan' mod. I don't mind not counting number of tests, but I kind of like done_testing() check at the end.

**Comment by okurz** [comment]
> but I kind of like done_testing() check at the end.

I thought about it but I did not find a use case where it makes sense. As I stated in the commit message "It is not like we have a paper document which tells us how many tests we
actually wanted to execute, isn't it?".

**Comment by coolo** [comment]
That's how Test::More works - http://stackoverflow.com/questions/690342/why-do-i-need-to-know-how-many-tests-i-will-be-running-with-testmore is a great summary -> long story short: done_testing is the minimum

**Comment by okurz** [comment]
The more I learn perl the more I see how it is inferior to python and less evolved being older:
```bash
$ cat test.py
import sys

def test_foo():
    assert True

def test_bar():
    sys.exit(0)
okurz@linux-28d6:~/local/tmp 0 $ py.test test.py
==================================================================== test session starts =====================================================================
platform linux -- Python 3.4.1, pytest-2.8.5, py-1.4.31, pluggy-0.3.1
rootdir: /home/okurz/local/tmp, inifile: 
plugins: xdist-1.13.1, cov-2.2.0
collected 2 items 

test.py .F

========================================================================== FAILURES ==========================================================================
__________________________________________________________________________ test_bar __________________________________________________________________________

    def test_bar():
>       sys.exit(0)
E       SystemExit: 0

test.py:7: SystemExit
============================================================= 1 failed, 1 passed in 0.01 seconds =============================================================
```

**Comment by coolo** [comment]
that doesn't change a thing :)

**Comment by coolo** [comment]
I guess you should have taken the opportunity when they asked "any further questions" in the job interview and asked for inferior languages in use ;)

**Comment by okurz** [comment]
yes, I always walk into this trap with all my jobs ;-)

**Comment by okurz** [comment]
updated:
* Adjust 'no_plan' to 'done_testing()' everywhere

**Comment by aaannz** [comment]
:+1:

**Pull request merged**
