### PR TITLE
Updates install.asciidoc

### PR DESCRIPTION
**Pull request by sumantro93**
Fixed typo in line 128. Added a line to resolve write permission error while trying to write in client.conf

### CODE REVIEW

**Comment by coolo** [comment]
hmm, I'm not so sure when chmod can help. Our package provides the file as owned by the worker user. As such it's not writeable (or chmodable) by normal users. Root on the other hand is the only user  that can chmod the file, but root can write to the file just fine.

**Comment by sumantro93** [comment]
Yes as a root , I can write to file using cat but in this case I was trying to write the key and secret value using vi editor , which was not happening hence had to do chmod +w. I hope that makes sense.

**Comment by aaannz** [comment]
Well, `vi` will warn you that you are writing to r/o file, but you can force write by using `w!` command (`vi` itself hints to do that). I don't think mentioning `chmod +w` is really necessary.

**Comment by sumantro93** [comment]
It's okay. Thanks for the review!

**Comment by coolo** [comment]
but please update your PR - the typo is still valid and it's your contribution

**Comment by sumantro93** [comment]
@coolo Updated! Thanks.

**Pull request merged**
