### PR TITLE
Dependency cron 2021-09-28

### PR DESCRIPTION
**Pull request by openqabot**

### CODE REVIEW

**Review by okurz — CHANGES_REQUESTED** [review]
Doesn't look fixed

**Comment by Martchus** [comment]
No, it still installs the old version of os-autoinst-devel (see https://app.circleci.com/pipelines/github/os-autoinst/openQA/7857/workflows/65dfad48-7b61-49cc-b519-f7e658703d3c/jobs/74237) despite `HEAD is now at f46f3f9df Merge pull request #4239 from Martchus/prefer-devel-pkgs`.

**Comment by perlpunk** [comment]
If I do this:
```
docker run -it --rm registry.opensuse.org/devel/openqa/ci/containers/base:latest bash

sudo zypper ar --priority 91 -f https://download.opensuse.org/repositories/devel:openQA/openSUSE_Leap_15.2 devel_openQA
sudo zypper ar --priority 90 -f https://download.opensuse.org/repositories/devel:/openQA:/Leap:/15.2/openSUSE_Leap_15.2 devel_openQA_Leap
sudo zypper --gpg-auto-import-keys ref

zypper info openQA-devel os-autoinst-devel                                                
Loading repository data...                                   
Reading installed packages...                                


Information for package openQA-devel:                        
-------------------------------------                        
Repository     : devel_openQA
Name           : openQA-devel                                
Version        : 4.6.1632803445.44df68079-lp152.4428.1                                                                     
Arch           : noarch                                      
Vendor         : obs://build.opensuse.org/devel:openQA                                                                     
Installed Size : 0 B                                         
Installed      : No                                          
Status         : not installed                               
Source package : openQA-4.6.1632803445.44df68079-lp152.4428.1.src
Summary        : Development package pulling in all build+test dependencies
Description    :                                             
    Development package pulling in all build+test dependencies.                                                            


Information for package os-autoinst-devel:                   
------------------------------------------                   
Repository     : devel_openQA
Name           : os-autoinst-devel                           
Version        : 4.6.1632799442.f77d4e14-lp152.863.1         
Arch           : x86_64                                      
Vendor         : obs://build.opensuse.org/devel:openQA
Installed Size : 0 B                                         
Installed      : No                                          
Status         : not installed                               
Source package : os-autoinst-4.6.1632799442.f77d4e14-lp152.863.1.src
Summary        : Development package pulling in all build+test dependencies
Description    :                                             
    Development package pulling in all build+test dependencies.
```
then I get the latest versions.

Where is the difference?

**Comment by Martchus** [comment]
> Where is the difference?

That's also what I don't understand.

**Comment by okurz** [comment]
see https://progress.opensuse.org/issues/98952

**Pull request closed without merging**
