### PR TITLE
Fix tests due to postgres error msg filtered in wrong language

### PR DESCRIPTION
**Pull request by asdil12**
Eg by calling `make test TESTS=t/api/04-jobs.t`

### CODE REVIEW

**Review by Martchus — APPROVED** [review]

**Review by okurz — APPROVED** [review]

**Comment by kalikiana** [comment]
@mergifyio rebase

**Review by Martchus — APPROVED** [review]
I guess last time when this came up we tried to go for the minimum number of variables to override. I personally have `export LANGUAGE= LANG=C.utf8` in my helpers as well as I think setting `LANG` is indeed necessary in some setups. So this is fine for me.

**Comment by Martchus** [comment]
Oh, wait - I've just looked at the diff and commits and changes tabs. This actually *is* the time I remember when this came up.

Let's see whether it will be merged automatically after rebasing.

@Mergifyio rebase

**Comment by asdil12** [comment]
This change seems to affect some table ordering in one of the ui tests. Please have a look in the changes I did and see, if they are acceptable.

**Comment by Martchus** [comment]
I guess this was acceptable. Now the ordering is at least ensured to be consistent via the environment variable.

**Pull request merged**
