### PR TITLE
Fix worker startup (fix #2118)

### PR DESCRIPTION
**Pull request by okurz**
* Fix missing runtime dependency on "DBIx::Class::DeploymentHandler"
* apparmor: Allow unzip-plain to fix worker startup

Related progress issue: https://progress.opensuse.org/issues/53285

### CODE REVIEW

**Comment by okurz** [comment]
@kraih I am not exactly sure what happens here but seems this is needed after #2118, maybe some call for database migration is now needed not during post-package-upgrade but on startup of the worker?

**Comment by okurz** [comment]
https://travis-ci.org/os-autoinst/openQA/jobs/547545896#L1111 about

```
# Subtest: Cache tests
    ok 1 - cache.sqlite is not present
Argument "50;" isn't numeric in int at lib/OpenQA/Worker/Cache.pm line 53.
…
```

is an interesting error but hardly caused by my changes, retriggered the test.

**Comment by nicksinger** [comment]
I fail to find a reason why #2118 (or any other recent change) should have introduced `DBIx::Class::DeploymentHandler` as runtime dep. Do you have any more clues why exactly this is needed? Do you have some log output with a stack trace maybe? Or is this dependency a guess of yours and will not work for sure?

**Comment by okurz** [comment]
Please read the related progress issue: https://progress.opensuse.org/issues/53285

**Comment by Martchus** [comment]
I'm also wondering about that. Looking at the `use`es in the Perl module it looks like that `perl-DBIx-Class` might be required now even though the worker doesn't actually use it. But requiring `DBIx::Class::DeploymentHandler` seems just wrong - we don't want to do any database migrations in the worker.

**Comment by kraih** [comment]
Took me a moment to see where the load order changed. I wasn't aware that the worker shares `OpenQA::Setup` with the webui services. That can make dependency management a little awkward.

**Comment by kraih** [comment]
Applying #2120 should be the safer solution, but this PR would probably be more correct. Since the `DBIx::Class::DeploymentHandler` should always have been a dependency right next to `DBIx::Class`.

**Comment by okurz** [comment]
@kraih do you think we should therefore merge this PR as well or should we try in the .spec file to move the DBIx::Class to the webui sub-package?

**Comment by kraih** [comment]
Probably both should be applied.

**Comment by okurz** [comment]
alright, so let's bring this change in. We can see if we can move the dependency to the webui package then and therefore remove both `DBIx:Class` as well as `DBIx::Class::DeploymentHandler` from the worker.

**Pull request merged**
