### PR TITLE
Show scenario name within results details view

### PR DESCRIPTION
**Pull request by okurz**
Show scenario within results details view

The scenario is becoming more and more important in referencing results. When
working with many test results at the same time or using deep links to
failed modules it was not possible to find out the scenario from the details
view page but one had to click and load the results page.

Fixes https://progress.opensuse.org/issues/12084

Example screenshot:
openqa_job_name_in_details_view_alt2

### CODE REVIEW

**Comment by coolo** [comment]
If you want to have the info available in the step page, find a better solution than putting it in the bread crumb. The place there isn't really expanding

screencapture-localhost-9526-tests-344428-modules-installation_overview-steps-1-src-1464523980453

**Comment by coolo** [comment]
i.e. restrict the navigation to two steps on every level and have all the other infos in a  http://www.w3schools.com/bootstrap/bootstrap_popover.asp

**Comment by okurz** [comment]
OK, will try that.
What about the alternative to put it in another box above the thumbnail bar?

 WDYT about the other changes, e.g. including the machine tag everywhere?

**Comment by coolo** [comment]
I was a bit worried that you change name, because that used to be the key of the directory. But that's fortunately history, nowadays we store an explit result_dir into the test. For simplicity I would avoid \@ in that though - as bash sucks with @ chars when completing :)

**Comment by coolo** [comment]
So an easier alternative I suggested to okurz is having a tooltip (title=) on the test number

**Comment by okurz** [comment]
> So an easier alternative I suggested to okurz is having a tooltip (title=) on the test number

tooltips are nice for explanatory text or help but in this case the scenario is something that would need to be copy-paste-able.

What about *alternative 1*: job name in a box, not wrapping but taking more vspace
openqa_job_name_in_details_view_alt1

**Comment by okurz** [comment]
@coolo you fooled me regarding the wrapping :-/ the user bar (login…) is already wrapping in current design even though there is space so nothing is lost. I am still for my original proposal (for short term) until mid-term the whole design is harmonized using bootstrap.

**Comment by coolo** [comment]
this is the needle editor you're showing - why the heck do you need the scenario name copy&pastable on the needle editor? I consider this just a waste of worthy screen space.

**Comment by coolo** [comment]
and here it starts wrapping at 920px (I already expressed that the breadcrumb is a dead concept) - which is far less than the 1024px I gave your design.

**Comment by okurz** [comment]
Updated:
* Rebased
* Display job scenario as simple text instead of anything more fancy (see updated screenshot in description)

**Comment by coolo** [comment]
now drop the 2nd commit please

**Comment by okurz** [comment]
see #725 for that

**Pull request closed without merging**
