### PR TITLE
Improve test coverage; remove support for old workers relying on redirection for ws route

### PR DESCRIPTION
**Pull request by Martchus**
* Remove uncovered code which was obsolete anyways
* Mark code as uncoverable which we will hardly ever cover
* See particular commit messages

### CODE REVIEW

**Comment by Martchus** [comment]
Seems like one of the `# uncoverable statement` comments didn't work.

By the way, I've also noticed that `# uncoverable subroutine` does not work (in case you're wondering about all these  `# uncoverable statement` comments; the example in the [docs](https://metacpan.org/pod/Devel::Cover#Subroutines) has these as well).

**Comment by Martchus** [comment]
I can not reproduce it by generating the coverage report locally. There the line which is uncovered according to codecov is completely ignored which actually makes sense because it is just a comment. I rearranged the comments. Maybe that helps.

**Comment by okurz** [comment]
full stack test failed fetching the image. I restarted.

**Comment by okurz** [comment]
https://github.com/os-autoinst/openQA/pull/2835 might help with some of the coverage changes that I see in the report on your PR.

**Comment by okurz** [comment]
https://github.com/os-autoinst/openQA/pull/2835 merged, you can rebase

**Comment by Martchus** [comment]
I have no idea why one of the `# uncoverable statement` comments has no effect on the codecov report (it has on a locally generated report). I'd merge it anyways because that's only one spot and I don't know how to workaround the problem.

**Comment by kalikiana** [comment]
I think it'd be good to have the title and description say something meaningful about
- removing the websocket redirect for older workers
- hardening the status update

**Comment by Martchus** [comment]
I updated the PR description. I don't think it is required that the PR description repeats all commit message (one can just click on the commits tab to view them). It doesn't actually harden the status update (in the sense that there's better validation).

**Comment by kalikiana** [comment]
> I updated the PR description. I don't think it is required that the PR description repeats all commit message (one can just click on the commits tab to view them). It doesn't actually harden the status update (in the sense that there's better validation).

In the however unlikely event of a regression it should make it more obvious what the change did when you don't actually know what change you are looking for (I would agree with you in the context of the review only).
Thank you for updating it!

**Pull request merged**
