### PR TITLE
Show added/updated needles in editor

### PR DESCRIPTION
**Pull request by Martchus**
See https://progress.opensuse.org/issues/9906

---

<s>The PR is still WIP:</s>

* [x] Add an entry in the database for needles saved via the needle editor.
* [x] Save tags and the creation date of needles.
    * [x] Make first_seen_module_id and last_seen_module_id of the needles table optional for this purpose.
* [x] When opening the needle editor, a warning is shown if new needles with matching tags have already been created since the job has been started.
    * [x] 'matching tags' means that all needles are considered, which have at least one tag which is also in the list of proposed tags in the needle editor.
    * [x] The needles are also added to the 'Needle based on' selection.
* [ ] <s>Show warnings only 'on needle failure'.</s> Really wanted?
* [x] Add more test cases.
* [ ] Refactor some needle-related code (maybe in additional PR).

### CODE REVIEW

**Comment by Martchus** [comment]
Should be ready to merge. From my side the two remaining open points must not be necessarily part of this PR. Besides, it is maybe better not to have a mega PR.

---

> <s>Show warnings only 'on needle failure'.</s> Really wanted?

Any feedback regarding this point? If not, I'll just skip it as it is only mentioned in the user story but not in acceptance criteria.

---

I can not reproduce the failing `t/05-scheduler-dependencies.t` locally. I don't think it has something to do with my changes. Any other tests have passed.

**Comment by Martchus** [comment]
Seems like the migration didn't work because the timestamps can't be null.

So I patched the migration scripts manually:
```
;
ALTER TABLE needles ADD COLUMN t_created timestamp;
UPDATE needles SET t_created = (TIMESTAMP '-infinity') WHERE t_created IS NULL;
ALTER TABLE needles ALTER COLUMN t_created SET NOT NULL;

;
ALTER TABLE needles ADD COLUMN t_updated timestamp;
UPDATE needles SET t_updated = (TIMESTAMP '-infinity') WHERE t_updated IS NULL;
ALTER TABLE needles ALTER COLUMN t_updated SET NOT NULL;
```

Use of `-infinity` should cause needles created before the migration not to show up.

**Comment by okurz** [comment]
Can you share some screenshots? Maybe update the doc and put screenshots there?

**Comment by Martchus** [comment]
Here are some screenshots:

1. Create a new needle:
screenshot_20180322_103219

2. Just reload the page and it is already there:
screenshot_20180322_103409

I can update the documentation, too.

---

I'd also like to test this on the staging instance `e212.suse.de` to get used to the staging process.

**Comment by Martchus** [comment]
http://e212.suse.de runs now with the changes of this PR. The migration of the database worked and needles are shown as expected.

---

I also get the following warning (locally and on the e212):
```
Mär 22 13:44:37 e212 openqa[10768]: DBIx::Class::Storage::DBI::_gen_sql_bind(): DateTime objects passed to search() are not supported properly (InflateColumn::DateTime formats and settings are not respected.) See ".. format a DateTime object for searching?" in DBIx::Class::Manual::FAQ. To disable this warning for good set $ENV{DBIC_DT_SEARCH_OK} to true at /usr/share/openqa/script/../lib/OpenQA/WebAPI/Controller/Step.pm line 322
Mär 22 13:45:04 e212 openqa[10768]: DBIx::Class::Storage::DBI::_gen_sql_bind(): DateTime objects passed to search() are not supported properly (InflateColumn::DateTime formats and settings are not respected.) See ".. format a DateTime object for searching?" in DBIx::Class::Manual::FAQ. To disable this warning for good set $ENV{DBIC_DT_SEARCH_OK} to true at /usr/share/openqa/script/../lib/OpenQA/WebAPI/Controller/Step.pm line 322
```
It seems to work, though. Apparently those formats and settings are not required here. So I would say let's just ignore/disable the warning.

**Comment by Martchus** [comment]
And after pushing the documentation it is now the fullstack test which is failing.

BTW: There is actually an issue for the previously failing `t/05-scheduler-dependencies.t` test: https://progress.opensuse.org/issues/32854  
After some tries I could also reproduce it locally. But still no clue *why* it fails only sometimes.

**Comment by okurz** [comment]
looks good

**Comment by Martchus** [comment]
When playing around, I've noticed that it might be a good idea to limit this to the most recent needles. Otherwise you would end up with lots of needles when opening the needle editor from an old job.

I also added a 'new: ' prefix for new needles so they are not confused with the actual candidate needles. Otherwise we would might get questions like 'why has this stupid os-autoinst not considered some of the needles'.

Updated the staging instance with the latest changes, too.

The failing CI is just `05-scheduler-dependencies.t ` again.

BTW: Showing the needles in the test details is not implemented yet, but I think we should merge this first so the PR doesn't grow too big.

**Comment by Martchus** [comment]
@foursixnine Of course I can rebase. However, GitHub is not showing any conflicts. So why do I need to rebase? Do we only allow fast-forward merge now?

**Comment by foursixnine** [comment]
@Martchus Naaa, it's just to get  `codecov/patch — 76.31% of diff hit (target 88.75%)` up :)

**Comment by Martchus** [comment]
This time even the tests pass :-)

**Comment by foursixnine** [comment]
Let's do it!

**Pull request merged**
