### PR TITLE
[WIP] -- Add trello as issue tracker

### PR DESCRIPTION
**Pull request by okurz**
Related progress issue: https://progress.opensuse.org/issues/38432

### CODE REVIEW

**Comment by coolo** [comment]
Please document this on https://en.opensuse.org/openSUSE:Packaging_Patches_guidelines

**Comment by coolo** [comment]
(and let's ask @AdamWill if fedora has another way to reference trello)

**Comment by okurz** [comment]
> Please document this on https://en.opensuse.org/openSUSE:Packaging_Patches_guidelines

good idea. Done with https://en.opensuse.org/index.php?title=openSUSE%3APackaging_Patches_guidelines&type=revision&diff=127746&oldid=126590

**Comment by AdamWill** [comment]
I don't think we use Trello itself at all in Fedora as it's a closed-source hosted service. Some teams have instances of Taiga and stuff that they use.

**Comment by Martchus** [comment]
Tidy fails and the comments test:

```
    #   Failed test at ./t/ui/15-comments.t line 212.
    #          got: '23'
    #     expected: '21'
    #   Failed test 'url22'
    #   at ./t/ui/15-comments.t line 234.
    #          got: 'https://trello.com/c/OMdsDiAE'
    #     expected: 'tr#OMdsDiAE'
    #   Failed test 'url23'
    #   at ./t/ui/15-comments.t line 235.
    #          got: 'https://trello.com/c/OMdsDiAE/33-what-can-you-expect-from-this-board'
    #     expected: 'tr#OMdsDiAE'
    # Looks like you failed 3 tests of 25.
#   Failed test 'URL auto-replace'
#   at ./t/ui/15-comments.t line 263.
```

**Comment by kraih** [comment]
Is this PR dead? Can we close it?

**Comment by okurz** [comment]
not yet dead, just rotting ;)

**Pull request closed without merging**
