### PR TITLE
Fix make test

### PR DESCRIPTION
**Pull request by coolo**
picking some out of #177 to create a base for the coverage :)

### CODE REVIEW

**Comment by coolo** [comment]
no idea how coveralls decides when to comment, but the coverage is 64.1% now

**Comment by coolo** [comment]
removed now - let's be honest from the start

**Comment by coolo** [comment]
58.5% ;(

**Comment by ancorgs** [comment]
At least it looks like a trustworthy number now.

**Comment by coolo** [comment]
it's more than the percentage of people voting for governments in Germany - so if 58% of our lines say the commit is good, it must be good :)

**Pull request merged**
