### PR TITLE
Add modprobe.d config for nexted virtualisation

### PR DESCRIPTION
**Pull request by sysrich**

### CODE REVIEW

**Comment by coolo** [comment]
shouldn't this be installed too (i.e. change Makefile)?

**Comment by sysrich** [comment]
Um, yeah, I guess I forgot, will do in the morning unless some very nice kind generous person does it for me :)

**Comment by sysrich** [comment]
Now with makefile goodness...

**Comment by lnussel** [comment]
I don't think this should be individual packages' business

**Comment by sysrich** [comment]
Well, we have openQA workers controlling qemu, we've now got tests that require nested virtualisation in order to function, we have the openQA packages setting up the machine for everything else they need (apache, logrotate, etc) so its logical to me to have openqa-worker also install a modprobe rule to enable nested virtualisation

alternatively, we just have to go around every worker server manually and set it up.. seems silly..

**Comment by lnussel** [comment]
and if the worker host uses an amd processor or another architecture the modprobe rule has no effect. Unfortunately this is a task outside the limits of rpm. Note that we cannot fully configure apache either.

**Pull request closed without merging**
