### PR TITLE
Revert PR 1747

### PR DESCRIPTION
**Pull request by coolo**
There are flaws with the simplified scheduler and the calculation of blocked_by,
but that's no reason to revert to the complicated one

I'll put fixes on top

### CODE REVIEW

**Comment by mudler** [comment]
Why not a separate branch?

**Comment by coolo** [comment]
It was a separate branch for the last 2 sprints, remember the success story?

**Comment by mudler** [comment]
I mean as a separate branch *in this repo*, so when everything is sorted out we can merge to master?

**Comment by coolo** [comment]
I can change the target once I have succeeding tests.

**Pull request closed without merging**
