### PR TITLE
Move constants from Schema::Result::Jobs to a separate package

### PR DESCRIPTION
**Pull request by foursixnine**
Package::Constants could actually be used here

### CODE REVIEW

**Comment by foursixnine** [comment]
Tidy will fail but looks nice :) Just need to rebase on one or two more commits (WIP already)

**Comment by foursixnine** [comment]
Sure thing :)

**Comment by foursixnine** [comment]
@coolo for now I'm ok with OpenQA::Jobs::Constants but in the future I would like to create a proper controller for jobs, wdyt?. Also I think it's not necessary to touch the makefile. Correct me if I'm wrong

**Comment by Martchus** [comment]
> create a proper controller for jobs

What are you talking about? Some kind of state machine?

**Comment by coolo** [comment]
jobs are handled all over the places - and that's a good thing. We used to have Scheduler.pm which did *everything* and it sucked

**Comment by foursixnine** [comment]
@coolo maybe I was wrong with the wording, I actually meant to move these methods that simply don't touch the job itself at all, but perform operations outside of the model (But for now I think we're fine to merge)

**Pull request merged**
