### PR TITLE
Fix scheduling of jobs

### PR DESCRIPTION
**Pull request by coolo**
My refactoring caught uncovered code ;(

### CODE REVIEW

**Comment by sysrich** [comment]
What exactly does this fix? I mean, all scheduling isn't broken, is it? I see jobs being scheduled..

**Comment by coolo** [comment]
the isos controller is not affected. this is clone_jobs not working

**Comment by okurz** [comment]
fix == "needs test", right?

**Comment by coolo** [comment]
That's how the morning started: Dario wanted to write a test. In the evening I wrote a fix - without having a test.

**Pull request merged**
