### PR TITLE
Give Websockets and Scheduler the home of the webapi

### PR DESCRIPTION
**Pull request by coolo**
... so they find the proper /etc and stuff

### CODE REVIEW

**Comment by okurz** [comment]
the change to tidy should be in its own commit, rest fine

**Comment by aaannz** [comment]
:+1:

**Comment by AdamWill** [comment]
I'm not sure this is quite working right still? I've just updated our staging instance to current git - 89e98b716d014d97863a5e222caf93dfc58b569b - which is after this commit, but I still see this in the scheduler and websockets logs:

    Sep 15 00:48:40 openqa-stg01.qa.fedoraproject.org openqa-scheduler[28794]: Failed to open /usr/share/openqa/script/etc/openqa/openqa.ini: No such file or directory at /usr/share/openqa/script/../lib/OpenQA/ServerStartup.pm line 91.

    Sep 15 00:48:42 openqa-stg01.qa.fedoraproject.org openqa-websockets[28795]: Failed to open /usr/share/openqa/script/etc/openqa/openqa.ini: No such file or directory at /usr/share/openqa/script/../lib/OpenQA/ServerStartup.pm line 91.

it's off by one level: it should be looking in `/usr/share/openqa/etc` , not `/usr/share/openqa/script/etc`. Both your RPM spec and ours have this:

    mkdir -p %{buildroot}/usr/share/openqa/etc/openqa
    ln -s /etc/openqa/openqa.ini %{buildroot}/usr/share/openqa/etc/openqa/openqa.ini
    ln -s /etc/openqa/database.ini %{buildroot}/usr/share/openqa/etc/openqa/database.ini

**Comment by AdamWill** [comment]
Huh, it seems like - at least on Mojo 6 - the result of `Mojo::Home->new->detect('OpenQA::WebAPI');` isn't actually the same as the WebAPI app's `$self->home`. I added a couple of log lines. In `script/openqa-scheduler` I added one right under the `detect` line:

        $ENV{MOJO_HOME} = Mojo::Home->new->detect('OpenQA::WebAPI');
        print STDERR "Home: $ENV{MOJO_HOME}";

and in WebAPI I added one right at the top of `startup`:

    sub startup {
        my $self = shift;
        my $home = $self->home;
        print STDERR "Home: $home";

Those log WebAPI's home as `/usr/share/openqa`, but scheduler's home (the detected one) as `/usr/share/openqa/script`...

**Comment by AdamWill** [comment]
OK, no, I see what the problem is here (though I'm not sure why it works for you). Detecting the home from the class uses the `INC` hash, and that's only populated when the module is loaded. So, this works as expected:

    #!/bin/perl

    use Mojo::Home;

    BEGIN { unshift @INC, "/usr/share/openqa/lib" }

    use OpenQA::WebAPI;

    my $home = Mojo::Home->new->detect('OpenQA::WebAPI');
    print "$home\n";

viz:

    [root@openqa-stg01 openqa][PROD]# perl /tmp/test.pm
    /usr/share/openqa

but if you comment out the `use OpenQA::WebAPI;`, it doesn't:

    [root@openqa-stg01 openqa][PROD]# perl /tmp/test.pm
    /tmp

unfortunately, it's not a super easy fix, because apparently you can't do this:

    BEGIN {
        unshift @INC, "$FindBin::Bin/../lib";
        if (!$ENV{MOJO_HOME}) {
            use OpenQA::WebAPI;

because it can't find `OpenQA::WebAPI` if you put it in a BEGIN block like that, even after the `unshift`, apparently. Oh, perl.

**Comment by AdamWill** [comment]
Well, this works:

    BEGIN {
        unshift @INC, "$FindBin::Bin/../lib";
        if (!$ENV{MOJO_HOME}) {
            require OpenQA::WebAPI;

but I'm not sure if it's...stupid.

**Comment by coolo** [comment]
I didn't deploy this yet, I only tested it locally with my patched RPMS and it worked. I look at it again

**Comment by aaannz** [comment]
I'm not sure `require OpenQA::WebAPI;` is completely harmless. Even though `import` is not called, but all `BEGIN {} .. ` stuff is compiled and executed and there is plenty of it in Mojo I'm afraid.

**Comment by coolo** [comment]
Yes, I think the same. But we don't need WebAPI, we need a class living in share - Utils will do I'd think.

**Comment by coolo** [comment]
what's interesting though: it works somehow under systemd, but not when running myself from rpms. But for me it wants to check /var/lib/openqa/...

**Comment by coolo** [comment]
https://github.com/os-autoinst/openQA/pull/876 works for me

**Comment by AdamWill** [comment]
the upstream `detect` code basically says: 'if `MOJO_HOME` is set, just return that; if not, try and figure out the location of the specified class from `%INC`, strip trailing `/lib` or `/blib` components from that path, make it absolute and return that; if we can't do that, just return the current working directory, whatever it is':

https://github.com/kraih/mojo/blob/master/lib/Mojo/Home.pm#L12

so what it returns in any given case is pretty unpredictable, I guess.

**Pull request merged**
