### PR TITLE
Fix jobs so variables with value =0 work again (eg RAIDLEVEL=0)

### PR DESCRIPTION
**Pull request by sysrich**

### CODE REVIEW

**Comment by aaannz** [comment]
I would prefer `next unless defined $l;`. I know that UI is supposed to delete variable if undef, but anyway, this may lead to undefined variable warnings.

**Comment by coolo** [comment]
where would they come from? you can't insert such values into the database

**Comment by aaannz** [comment]
This function handles input from REST API too and AFAIK you can specify URL such as `/api/v1/jobs?TEST=xx&A&DISTRI...`. Our client script handles that, can't say that for others. Wrt. database, we don't have `is_nullable => 0` for `JobSettings` values, but I'm not sure what is default for DBIx, just that `NULL` is represented as `undef`.

**Comment by coolo** [comment]
For reference: this is the code I incorrectly refactored:
```
-    while (my ($k, $v) = each %settings) {
 -        unless ($k eq 'WORKER_CLASS') {
 -            push @{$new_job_args{settings}}, {key => $k, value => $v};
 -            next;
 -        }
 -        for my $l (split(m/,/, $v)) {    # special case for worker class?
 -            push @{$new_job_args{settings}}, {key => $k, value => $l} if $l;
 -        }
 -    }
```

Richard's PR replaced error by warning - but the warning was there in last week's version. If you want to get rid of this warning, I'm fine.

**Comment by aaannz** [comment]
I was actually expecting 'seems like activism' response :D

**Pull request merged**
