### PR TITLE
`limit_assets`: remove asset that breaks limit, not next one

### PR DESCRIPTION
**Pull request by AdamWill**
At present, when looping through the assets for a given job
group, we decide whether to make the asset a deletion candidate
*before* we count its size against the limits. So effectively
we keep the minimum amount of assets needed to *exceed* the
size limit, rather than the maximum amount of assets that can
fit within it. This is clearly incorrect. We can fix it by
counting the asset's size against the limits *before* we decide
whether it should be a deletion candidate.

This is an alternative to #1532 by @coolo - I think this way
of fixing it is clearer and better. It also fixes the tests.
@coolo couldn't figure out what was going on with the tests,
and I don't blame him, because it was quite tricky. In fact
what happened is that my understanding of the interaction
between the code and the assets used in the tests was slightly
wrong, but ironically, *this very bug* happened to exactly
'offset' my faulty understanding, so the tests I wrote happened
to pass. I have added some comments to hopefully explain this
correctly and in detail.

Signed-off-by: Adam Williamson <awilliam@redhat.com>

### CODE REVIEW

**Comment by AdamWill** [comment]
So a fun note on the question of *why* we count against the limit at the end: here's how the `while` loop looked in a very early version of the function looked (after commit a2b851785):

        while (my $a = $assets->next) {
            next if $a->get_column('asset_type') ne 'iso';
            my $file = sprintf("%s/%s/%s", $OpenQA::Utils::assetdir,$a->get_column('asset_type'),$a->get_column('asset_name'));
            my @st = stat($file);
            if (@st && $st[7] > 0) {
                $keep{$a->asset_id} = 1;
                $sizelimit -= $st[7];
            }
            # check after keeping - so we can be sure to keep at least one even if sizelimit too strict
            last if $sizelimit < 0;
        }

And that was written by....@coolo ;) So at least if I understand this correctly, @coolo specifically put the decrement of `$sizelimit` after the initial 'keep' decision, but included the `last if` check, with the intent that we'd usually remain within the size limit (thanks to the `last if` check), *but* if there was only one asset, and it exceeded the size limit, it'd be kept. Simply decrementing `$sizelimit` before the check would've meant that a single asset that exceeded the size limit would be removed.

However, the `last if` check dropped out in commit 104bf719e211073cc6a38072d31bedcbc9c02b9e (also by @coolo ), and this has been wrong ever since.

So we could actually put that `last if` back in, more or less, if we still wanted the behaviour @coolo originally designed. But from the other PR:

"I think this breaks user's expectations - as a limit of 0 in my book means 0 assets and not one asset, no matter what size it is."

it sounds like 2017-model @coolo thinks 2015-model @coolo is an idiot ;)

**Comment by AdamWill** [comment]
WAHAHAHA I AM GENIUS

**Comment by okurz** [comment]
well, why not :)

**Comment by coolo** [comment]
My pleasure! And many thanks for digging

**Pull request merged**
