### PR TITLE
List the needle tags that openqa was looking for

### PR DESCRIPTION
**Pull request by asdil12**
https://progress.opensuse.org/issues/13764

### CODE REVIEW

**Comment by aaannz** [comment]
This is how it looks like for longer/multiple tags. I'm not sure about it. I would like to see this info in some more prominent place, but don't know where. What others think?

spectacle u14635

**Comment by okurz** [comment]
> This is how it looks like for longer/multiple tags. I'm not sure about it. I would like to see this info in some more prominent place, but don't know where. What others think?

* don't display any tags starting with `ENV-`
* limit the list to e.g. 40 characters and write `, …` instead. Note the utf8 character `…`, not three single dots `...`

**Comment by aaannz** [comment]
Really? I think that goes against the core of this feature to display what was looking for. I'm for displaying ENV- tags because I think it exposes some kind of error. Do we look for ENV- somewhere intentionally?

**Comment by asdil12** [comment]
The new commit will filter out the `ENV-` tags.
Also the list will be limited to 40 chars.
The full list will be displayed on mouseover via title attribute.

**Comment by aaannz** [comment]
Ok, now I don't get it. What is the purpose of this feature?

**Comment by asdil12** [comment]
To see, what is expected to be seen on a screenshot.
@aaannz Could you explain in which cases `ENV-` tags will appear in the `tags` list? I thought the `ENV-` tags are only used to unregister all the needles with non-matching `ENV-` tags at the very beginning of a test by `main.pm`.
I thought that `assert_screen` does OR matching - not AND.

**Comment by aaannz** [comment]
> To see, what is expected to be seen on a screenshot.

So why then the limit to 40 characters. I would like to see this in more visible place and unshortened. Like not in the dropbox but next to it on the same line. Then you don't loose the info when switching needles.

> Could you explain in which cases ENV- tags will appear in the tags list? I thought the ENV- tags are only used to unregister all the needles with non-matching ENV- tags at the very beginning of a test by main.pm.
I thought that assert_screen does OR matching - not AND.

See! There is clearly something unusual here. This was btw. some old test of mine so may be broken. But IMO reason not to filter them out. And yes, assert_screen does OR matching.

**Comment by asdil12** [comment]
I don't think that there is enough space in that line - especially when you are logged in and the *Create new needle* link is shown.

**Comment by aaannz** [comment]
Right, and I found one even without ENV- needles with excessive length. But this clearly shows (at least on my instance) a problem with needles so IMO it should be annoyingly visible, but at the same time no like it is some kind of overflow error.

spectacle j13092

**Comment by asdil12** [comment]
So what about removing the `ENV-` filter from the current commit and using that approach until we find a better location?

**Comment by asdil12** [comment]
Updated the commit.

**Comment by coolo** [comment]
What is the example in https://github.com/os-autoinst/openQA/pull/884#issuecomment-247607626 ? We have tests that look for pkcon-20170623?

**Comment by coolo** [comment]
Trying it out, I like the title more than the strange cut text. So I'd suggest (in the light of @okurz's other PR to add more into this line) we switch to icons for this line.

So instead of adding a plain title and more text, we add a small search glass, which opens a nicer popup with more details of tags used and ENV tags.

Then we can also use a + icon or similiar for 'create new needle' and the tracker icons for reporting.

**Comment by aaannz** [comment]
> What is the example in #884 (comment) ? We have tests that look for pkcon-20170623?

2017? I don't see it there I guess you meant 2014. It's on my test container, outdated tests and even results are from older db backup. Nothing to be concerned today I guess.

**Comment by asdil12** [comment]
> So instead of adding a plain title and more text, we add a small search glass, which opens a nicer popup with more details of tags used and ENV tags.

I think this is a nice idea but beyond the scope of this PR. It should be done afterwards in a seperate PR.

**Comment by aaannz** [comment]
I agree its out of scope, but I think it should be done before merging this. This has a potential to break rendering in case of long and/or high amount of looking for needles. (I didn't try the latest changes, if you solved that then disregard)

**Comment by asdil12** [comment]
@aaannz The current commit limits the number of chars to 40 (only for the option - not for the title) - so rendering should be fine.

**Comment by coolo** [comment]
rendering becomes a problem if I'd merge #887 first. We can't disucss these PRs independently.

**Comment by okurz** [comment]
Which PR do you think is more helpful to have in first? I think this PR here is in a more mature state than #887. Feel free to merge this PR and I update my PR to use icons for either only the reporting links or also the "create new needle" and more information in the dropdown.

**Comment by asdil12** [comment]
@coolo: can this be merged now?

**Comment by coolo** [comment]
We can close this PR once @okurz merged it into his branch

**Comment by okurz** [comment]
as discussed with @coolo the way to go is to simplify #887 and provide report links on nice icons without any product mapping for bugzilla to have the UI sorted out first including icons for *this* PR, then extend the report links with a proper way to select a bugzilla product and such.

**Comment by coolo** [comment]
-> #944

**Pull request closed without merging**
