### PR TITLE
Bootstrap dashboard

### PR DESCRIPTION
**Pull request by coolo**
The theme is still incomplete, but it's the way I want to go. Step by step away from grid960 towards bootstrap

### CODE REVIEW

**Comment by lnussel** [comment]
do we really need to mimic java developers and embed copies of all kinds of non-trivial 3rd party components into our source? In the old world I'd put bootstrap into a separate package.

**Comment by lnussel** [comment]
There's a package already, even though not a good one:
systemsmanagement:spacewalk:runtime/bootstrap

**Comment by coolo** [comment]
no, we wouldn't need to if we had a proper web development framework. If we were using rails, we would require 'less-rails-bootstrap' gem and be done.

As there is nothing like that for perl/mojoliocus there is no joy. And copying bootstrap in a different package would only have a meaning if we had several apps using it, which we don't have.

**Comment by lnussel** [comment]
with the same argument we could copy random perl modules into our source as noone else but openqa needs most of them. It's 3rd party code so it should be separate.  okish for small things but 10k lines of code? that feels so wrong.

**Comment by coolo** [comment]
you mean like lib/OpenQA/Plugin/HashedParams.pm ? yes, we do that :)

**Comment by coolo** [comment]
as it seems impossible to have npm-less on travis, I guess we have to either skip the less in git or move that part in an extra repo and only put the generated css in our git

**Comment by coolo** [comment]
the nmp dependency is something I don't really like anyway. so possibly this is the way to go: add the less sources of the "openSUSE bootstrap" in some generic openSUSE repo, but distribute the bootstrap.js and bootstrap.css through a means of git submodule

**Comment by coolo** [comment]
I just learned that mojolicious-plugin-assetpack can download remote css before minimize. So we don't even need them in git at all. we'd need to download them within the _service file though

**Comment by coolo** [comment]
Mojolicious::Plugin::Bootstrap3 looks really interesting for what we want

**Comment by coolo** [comment]
https://github.com/os-autoinst/openQA/pull/280 is the sass port

**Comment by lnussel** [comment]
Stephan Kulow schrieb:
> I just learned that mojolicious-plugin-assetpack can download remote
> css before minimize.

Ouch. We do have package management instead :-)

**Pull request closed without merging**
