### PR TITLE
Refactor worker scripts and add locking support

### PR DESCRIPTION
**Pull request by aaannz**
This PR does two things:
* refactor worker script into several modules under OpenQA::Worker namespace
* add Mojolicious::Lite server for request from os-autoinst test engine

### CODE REVIEW

**Comment by coolo** [comment]
looks reasonable. even though I'm not so sure this is going in the right direction of os-autoinst needs the JOBID

**Comment by aaannz** [comment]
In principle I don't need job id in os-autoinst, but I feared different worker - os-autoinst interferrence.
But as I think about it again, worker_port is probably enought to prevent worker x os-autoinst mixup. Classic iterative over thinking...

**Comment by coolo** [comment]
wow, this just gave us a hit of 6% in the coverage ;(

**Comment by aaannz** [comment]
Yea, I don't know how the coverage is computed, but this indeed created quite new interfaces. But OTOH allows much more testing. Previous worker script wasn't tested at all.
Marked in my todo list.

**Pull request merged**
