### PR TITLE
Fixing the package to build with newer assetpack

### PR DESCRIPTION
**Pull request by coolo**
woff file is no longer fetched

### CODE REVIEW

**Comment by coolo** [comment]
critsit :)

**Comment by foursixnine** [comment]
and @mudler and I yesterday scratching our heads yesterday xD

**Comment by coolo** [comment]
get a proper hair cut - then scratching is gone and you only have to polish :)

**Comment by foursixnine** [comment]
`Could not find input asset "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/fonts/glyphicons-halflings-regular.woff2"` failed again for 42.3 :/ or am I wrong?. Yesterday the errors were with another file... there's something fishy here.

@coolo Been thinking on the haircut part, will also reduce wind resistance and weight!

**Comment by foursixnine** [comment]
Ok, works now :). I was wrong :P

**Comment by coolo** [comment]
some platforms had an outdated assetpack

**Comment by mudler** [comment]
@coolo and also no more barbershop then.. 😄

**Pull request merged**
