### PR TITLE
Restart openqa-worker-cacheservice on failure/wait for network

### PR DESCRIPTION
**Pull request by okurz**
Related progress issue: https://progress.opensuse.org/issues/44105

### CODE REVIEW

**Comment by coolo** [comment]
I'm not so sure it will actually fix the issue though - as these restart=on-failures happen very quickly and if the network is still not there, it will stop the service because it fails too fast.

**Comment by mudler** [comment]
> I'm not so sure it will actually fix the issue though - as these restart=on-failures happen very quickly and if the network is still not there, it will stop the service because it fails too fast.

That won't fix the issue, that's right. But having it restarted on failure sounds good

**Comment by coolo** [comment]
yes, but I dislike touching the systemd services for one line - if two lines would make it even better.

**Comment by nicksinger** [comment]
+1 merging this. In the meantime I'll patch the service-file on the workers itself over salt.

**Comment by coolo** [comment]
If you are all so eager to get this in, why not finally add the network dependency?

**Comment by coolo** [comment]
See https://github.com/os-autoinst/openQA/pull/1884#issuecomment-441164333

**Comment by okurz** [comment]
> If you are all so eager to get this in, why not finally add the network dependency?

I plan to do this but need to get accustomed to a proper testing approach when I have found my development time slot again (besides all the "management" ones).

@nicksinger If you hotpatch any workers already please provide me feedback if the additional network dependency would help and not introduce drawbacks.

**Comment by nicksinger** [comment]
> @nicksinger If you hotpatch any workers already please provide me feedback if the additional network dependency would help and not introduce drawbacks.

Jup, will provide feedback. However I currently struggle to get all states running on staging so it might take another PR in before…
([current approach](https://gitlab.suse.de/nicksinger/salt-states-openqa/tree/fail_restart))

**Comment by coolo** [comment]
They weren't

**Comment by nicksinger** [comment]
Yet another PR for that case: https://github.com/os-autoinst/openQA/pull/1896

**Pull request merged**
