### PR TITLE
Show custom error pages

### PR DESCRIPTION
**Pull request by Martchus**
Issue: https://progress.opensuse.org/issues/13192

The content of the pages could still be improved. Currently there is (beside the error message) just a link to 'New ticket' form under progress.opensuse.org.

Not sure how I would implement the last point mentioned in the issue. Just inserting the message via JavaScript is not possible due to cross-site security.

### CODE REVIEW

**Comment by Martchus** [comment]
Seems like the status code isn't set correctly when custom error pages are in place (that's the reason why the tests fail).

**Comment by okurz** [comment]
seems like you hit an error in the error handler :-D

**Comment by okurz** [comment]
LGTM

you can even update the description in this PR as you already solved the question you had

**Comment by okurz** [comment]
@aaannz ?

**Comment by okurz** [comment]
I tested it again and it is not convincing as the custom templates are missing details and are less nice to look at as the generic ones in development mode. It might make sense to add a custom header bar but my current point of view is that I would rather like the "development" templates being used in any case.

**Comment by aaannz** [comment]
I don't know how to do it, but for development mode I would like the original pages. For production mode I don't think the list of routes is useful. I would rather like to see request info ( path, host, response + data from server, ... ).

**Comment by okurz** [comment]
```bash
for page in exception not_found; do
    ln -s $(rpm -ql perl-Mojolicious | grep debug.html.ep) -> /etc/openqa/templates/${page}.html.ep
done
```
makes the development page also available in production. In development mode it still shows the same page then.
If security is a concern for production then some custom pages might make sense. For osd we can simply use the full info debug pages (let's discuss that in IRC). The idea of showing the routes would be a really easy way to give people an idea what routes are available over the API.

**Comment by coolo** [comment]
I'm fine with having a ticket button on the error page, but I don't want to see perl exceptions in production. No way!

I once encountered a way similiar to this:
```
Sorry, our application crashed - if you want to help the developers, provide them with this information, they will know what to do with it:

RmFrZSBDcmFzaCwgYWxzbyBrbm93biBhcyBUcm
FzaCBCYW5kaWNvb3QsIGlzIGEgY2hhcmFjdGVyIG
Zyb20gdGhlIENyYXNoIEJhbmRpY29vdCBzZXJpZX
MuIEFzIHRoZSBuYW1lIGltcGxpZXMsIGhlIGxvb2tzI
Gxpa2UgYW4gaW1pdGF0aW9uIG9mIENyYXNoIEJ
hbmRpY29vdCwgdGhvdWdoIHRoZXJlIGFyZSBzb2
1lIGtleSBkaWZmZXJlbmNlcyAoc3VjaCBhcyB0aGU
gaHVnZSBleWVicm93cyBhbmQgYmlnIHRlZXRoKS
4gSGUgYWxzbyBoYXMgYSByYXRoZXIgZ29vZnkgd
m9pY2Uu
```

**Comment by okurz** [comment]
We can generate a ticket submit URL with this hash string as well as the timestamp when the issue happened to sync with the logfiles

**Comment by Martchus** [comment]
I removed showing exception messages as these could leak database information, indeed. Using base64 (as proposed) wouldn't solve the problem as everybody can decode it.

However, I've kept the list of available routes in the 404 pages as I think it shouldn't cause any problems. Further information about the request could still be added of course. If you don't like the routes, just discard the corresponding commit.

**Pull request merged**
