### PR TITLE
Fix typo in networking documentation

### PR DESCRIPTION
**Pull request by thehejik**

### CODE REVIEW

**Comment by coolo** [comment]
Can you please rewrite your commit log. Our contribution documentation links https://chris.beams.io/posts/git-commit/, but I give you a summary:  'Fix typo in networking documentation'

**Comment by okurz** [comment]
LGTM

**Comment by coolo** [comment]
I'm not talking about the PR title, I'm talking about the commit log. as in git commit --amend, git push -f

**Comment by thehejik** [comment]
@coolo oh, sorry, done

**Pull request merged**
