### PR TITLE
Distinguish scheduled and blocked jobs on test result overview & Use purple for blocked jobs 

### PR DESCRIPTION
**Pull request by Martchus**
See https://progress.opensuse.org/issues/43112

### CODE REVIEW

**Comment by Martchus** [comment]
By the way, I don't dare to merge this yet because of the color change (which might be controversial).

**Comment by kraih** [comment]
Maybe post a screenshot here to compare before/after. Then everyone can +1/-1. 😉

**Comment by Martchus** [comment]
screenshot_20190821_181843


It looks similar to scheduled (which makes sense because it basically just a "special scheduled") but still well distinguishable. And it is also hard to confuse it with red or dark red for failed and incomplete jobs.

**Comment by okurz** [comment]
s/Dishinguish/Distinguish/

**Comment by okurz** [comment]
But I like the color choice :) you have my approval after you fixed the spelling

**Pull request merged**
