### PR TITLE
Calculate coverage in Selenium

### PR DESCRIPTION
**Pull request by andrii-suse**

### CODE REVIEW

**Comment by andrii-suse** [comment]
> what issue is fixed

Shouldn't we first see actual coverage before doing any assumptions in commit message. But overall - I don't see how any additional information can be helpful in this particular case. If somebody doesn't understand what is coverage or why it should be calculated or what is Selenium - then commit message is not the place to explain that.

**Comment by Martchus** [comment]
Admittedly, I've just looked at the code which looked good. And according to codecov the coverage actually increased by `4.41%` (although it doesn't really tell one the exact lines which are covered and weren't before).  
Suggestion for better commit message title: "Include minion jobs from Selenium tests when computing coverage"

**Comment by andrii-suse** [comment]
> although it doesn't really tell one the exact lines which are covered and weren't before

I can see such diff here https://codecov.io/gh/os-autoinst/openQA/pull/2549/changes (strange that codecov ignores files which has no coverage instead of showing 0% ...)

> Suggestion for better commit message title: "Include minion jobs from Selenium tests when computing coverage"

I believe problem is wider and Controllers were not covered in Selenium as well, (because WebAPI wasn't shut down properly?).

**Comment by Martchus** [comment]
> I believe problem is wider and Controllers were not covered in Selenium as well, (because WebAPI wasn't shut down properly?).

Right, that's what the change in `sub start_app` is for. But is that really so? I would have expected a higher increase in coverage then. But your change certainly doesn't hurt.

**Pull request merged**
