### PR TITLE
Add apache2 because it will not autoselected as dependency

### PR DESCRIPTION
**Pull request by wnereiz**
The package "apache2" need to be installed which did not a dependency of openQA.

### CODE REVIEW

**Comment by okurz** [comment]
-1 

- commit message titles should use proper english
 - why exactly is apache2 required? I don't think it is. openQA uses the perl Mojolicious which can provide a web service on its own so apache2 should not be required

**Comment by aaannz** [comment]
There is one thing making apache basically required: websockets server. It listens on different port since it is different process and apache is proxying it from regular 80. openQA worker uses the same port for regular HTTP requests and WS.

**Comment by aaannz** [comment]
But I would like to fix this in other way than requiring apache. e.g. use WebUI as proxy to WS. I attempted to do it, but apparently it is not working ( https://github.com/os-autoinst/openQA/blob/master/lib/OpenQA/WebAPI.pm#L397 )

**Comment by okurz** [comment]
@aaannz so you are saying openqa-webui + worker can not communicate without apache running? Although I thought different this seems to be true as a quick test showed.
worker log when scheduling a job w/o apache2 running:

```
Jan 06 13:40:15 linux-28d6.suse worker[19025]: Use of uninitialized value in concatenation (.) or string at /usr/share/openqa/script/../lib/OpenQA/Worker/Common.pm line 333.
Jan 06 13:40:15 linux-28d6.suse worker[19025]: Unable to upgrade connection to WebSocket: . proxy_wstunnel enabled? at /usr/share/openqa/script/../lib/OpenQA/Worker/Common.pm line 333.
Jan 06 13:40:15 linux-28d6.suse worker[19025]: Use of uninitialized value in string eq at /usr/share/openqa/script/../lib/OpenQA/Worker/Common.pm line 334.
Jan 06 13:40:25 linux-28d6.suse worker[19025]: Use of uninitialized value in concatenation (.) or string at /usr/share/openqa/script/../lib/OpenQA/Worker/Common.pm line 333.
Jan 06 13:40:25 linux-28d6.suse worker[19025]: Unable to upgrade connection to WebSocket: . proxy_wstunnel enabled? at /usr/share/openqa/script/../lib/OpenQA/Worker/Common.pm line 333.
Jan 06 13:40:25 linux-28d6.suse worker[19025]: Use of uninitialized value in string eq at /usr/share/openqa/script/../lib/OpenQA/Worker/Common.pm line 334.
Jan 06 13:40:35 linux-28d6.suse worker[19025]: Use of uninitialized value in concatenation (.) or string at /usr/share/openqa/script/../lib/OpenQA/Worker/Common.pm line 333.
Jan 06 13:40:35 linux-28d6.suse worker[19025]: Unable to upgrade connection to WebSocket: . proxy_wstunnel enabled? at /usr/share/openqa/script/../lib/OpenQA/Worker/Common.pm line 333.
Jan 06 13:40:35 linux-28d6.suse worker[19025]: Use of uninitialized value in string eq at /usr/share/openqa/script/../lib/OpenQA/Worker/Common.pm line 334.
Jan 06 13:40:45 linux-28d6.suse worker[19025]: Use of uninitialized value in concatenation (.) or string at /usr/share/openqa/script/../lib/OpenQA/Worker/Common.pm line 333.
Jan 06 13:40:45 linux-28d6.suse worker[19025]: Unable to upgrade connection to WebSocket: . proxy_wstunnel enabled? at /usr/share/openqa/script/../lib/OpenQA/Worker/Common.pm line 333.
Jan 06 13:40:45 linux-28d6.suse worker[19025]: Use of uninitialized value in string eq at /usr/share/openqa/script/../lib/OpenQA/Worker/Common.pm line 334.
```

Starting apache2 and then:
```
Jan 06 13:40:55 linux-28d6.suse worker[19025]: duplicating job 69
Jan 06 13:40:55 linux-28d6.suse worker[19025]: got job 70: 00000070-myopensuse-Tumbleweed-x86_64-Build1-foo
Jan 06 13:40:55 linux-28d6.suse worker[19025]: 22371: WORKING 70
```

@wnereiz change is good but the description of the reason should be better. Feel free to add our comments as part of in-source comment why the dependency on apache2 is required.

**Comment by wnereiz** [comment]
@okurz I think the Dockerfile has to be changed, otherwise the build will always failed. There are two way to solve the problem:
1. Install apache2
2. Remove gensslcert and a2enmod
I choose the first one for safe.

**Comment by okurz** [comment]
@wnereiz Yes, I am fine with that. Could you add an according comment in the Dockerfile and update the git commit message? This would help in the future to know why apache2 is specified as requirement.

**Comment by wnereiz** [comment]
@okurz Done!

**Comment by okurz** [comment]
LGTM

thx

**Pull request merged**
