### PR TITLE
Pass the correct asset variable to _handle_asset_processed

### PR DESCRIPTION
**Pull request by perlpunk**
Issue: https://progress.opensuse.org/issues/98577

### CODE REVIEW

**Comment by perlpunk** [comment]
The other effect was that this line:
```
$vars->{$this_asset}
      = $vars->{ABSOLUTE_TEST_CONFIG_PATHS} ? $link_result->{absolute_path} : $link_result->{basename};
```
wasn't doing anymore what it was supposed to, writing to `$vars->{"ARRAY(...)"}` instead of the asset name.
But apparently this also didn't raise any problems, so I'm wondering when this is actually needed.

**Review by kalikiana — APPROVED** [review]

**Comment by perlpunk** [comment]
@foursixnine maybe you can say something about that, as you authored c1aa4937006e1f80eda38da072bf9a98635a313a ?

**Comment by perlpunk** [comment]
Maybe also @Martchus can help with the open question when he's back next week.

**Review by okurz — APPROVED** [review]

**Comment by Martchus** [comment]
We kept `ABSOLUTE_TEST_CONFIG_PATHS` as a feature switch so users can go back to the old behavior of using absolute paths if needed. However, maybe it is time to remove the support for absolute paths at this point. We could check at least our instances whether users still use `ABSOLUTE_TEST_CONFIG_PATHS`.

**Review by Martchus — APPROVED** [review]

**Review by foursixnine — COMMENTED** [review]
I'd add an extra test case to check that defined pflash with undefined uefi, also works, for today and for the future's sake, as there are  no tests verifying that path at all.

Other than that it looks good, hell of a trip down the memory lane

**Comment by perlpunk** [comment]
> I'd add an extra test case to check that defined pflash with undefined uefi, also works

I think I don't understand how such a test would look like.
Can you elaborate?

**Comment by perlpunk** [comment]
I removed the not-ready label to get this merged and will add @foursixnine 's comment to the ticket

**Pull request merged**
