### PR TITLE
.gitignore: Add current temporary files from tests

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by perlpunk** [comment]
How about removing the temp files at the end of the tests instead?

**Comment by Martchus** [comment]
> How about removing the temp files at the end of the tests instead?

That would make sense - tests shouldn't pollute the source directory. And if they do it is actually not a bad thing if Git makes one aware leftovers (which sometimes cause problems in further test runs).

**Comment by okurz** [comment]
I agree with both of you but consider that a different story. I would not just delete the files at the end of test but also think about different, proper temporary directories which means we should change the already existing tests for the already existing entries in .gitignore. Can we do this step first though, then have a check for "no uncommited files after test runs" and then do the test changes?

**Comment by okurz** [comment]
I have created a ticket https://progress.opensuse.org/issues/78046 "Prevent tests polluting openQA working copy source directory" so that we don't forget what you would like to achieve. I suggest we do this PR as a first step and then others later, ok?

**Review by kalikiana — APPROVED** [review]

**Review by Martchus — APPROVED** [review]

**Pull request merged**
