### PR TITLE
Fix deprecation warnings regarding Mojo::Transaction::error

### PR DESCRIPTION
**Pull request by Martchus**
This fixes various tests (tests assert that no warnings are present).

### CODE REVIEW

**Comment by kraih** [comment]
Duplicate of #1861.

**Comment by Martchus** [comment]
@kraih Did you extend you PR in the meantime? I thought it would have only covered a few occurrences. Still, this PR seems to be more extensive (+-20 lines of code vs +-16). So I guess we merge yours first and then rebase mine for the few remaining ones.

**Comment by Martchus** [comment]
@kraih Merged the other PR. This now contains the remaining occurrences and yet another 'Fix formatting' commit because https://github.com/os-autoinst/openQA/commit/60004e2a87ba4de85401639f064c1c8766937fd0 wasn't 'tidy'.

**Comment by Martchus** [comment]
I'm merging because these changes are trivial and it is annoying if tidy isn't passing on master.

**Pull request merged**
