### PR TITLE
Update obs_rsync.js

### PR DESCRIPTION
**Pull request by Lokeshsri11**
There are a few bugs that I can identify.
First, the `controlToShow` parameter is not passed correctly to the error callback function of the `fetchValue` function. It should be passed as a separate parameter instead of being included in the callback function's parameter list.

Second, the `postAndRedrawElement` function doesn't handle the case where the `btn.dataset.geturl` value is not defined. It should check if the value exists before calling the `fetchValue` function.

Third, the `postAndRedirect` function doesn't check if the `redir` parameter is defined before redirecting to the URL.

And here also the way to optimize our code :
1.Use `let` and `const` instead of `var` to declare variables. `let` and `const` provide block-level scoping, which can help avoid variable hoisting and improve code readability.

2.Use arrow functions instead of anonymous functions to improve code readability and reduce typing.

3.Use object destructuring to simplify the code when accessing object properties.

4.Use `const` instead of `var` when declaring constant values.

5.Use template literals to concatenate strings instead of using the + operator.

6.Use default function parameters to simplify function calls and provide default values for parameter

### CODE REVIEW

**Review by Martchus — COMMENTED** [review]
Not sure whether it is required, but also make sure you run `make tidy-js`. Otherwise the CI checks might complain.

I personally also usually use `let` and `const` and the other JavaScript features you've mentioned and gladly accept the PR. However, we usually don't enforce using these for contributions so that's why our JavaScript code which has been touched by many different people is at it is. This is likely not going to change any time soon unless one is willing to modernize it and enforce the style. (Some of our code also simply predates the introduction of certain modern JavaScript features.)

**Comment by Lokeshsri11** [comment]
Wait @martchus i'll update my code and make it in  `tidy-js` format

**Review by Martchus — APPROVED** [review]

**Comment by Martchus** [comment]
Yes, we only need to wait for one more approval from the team. Then I'd merge your changes squashing them into one commit.

**Review by kalikiana — APPROVED** [review]
Nice tweaks!

**Comment by Lokeshsri11** [comment]
Thank you @Martchus @kalikiana for this PR review and I will continue to try and contribute more to this project.

**Comment by Lokeshsri11** [comment]
Okay @Martchus , I will pay attention to all these things from now on :)

**Pull request merged**
