### PR TITLE
DO NOT MERGE: Test stability of t/full-stack.t

### PR DESCRIPTION
**Pull request by Martchus**
For https://progress.opensuse.org/issues/98952

### CODE REVIEW

**Comment by okurz** [comment]
fullstack timed out after 1h after 15 successful runs.

**Comment by Martchus** [comment]
Yes, it ran into the CircleCI time limit. It doesn't look like the test was stuck, it just took that long to execute the (almost) 16 runs. So I'm just restarting the job to get more runs.

**Comment by okurz** [comment]
> Yes, it ran into the CircleCI time limit. It doesn't look like the test was stuck, it just took that long to execute the (almost) 16 runs. So I'm just restarting the job to get more runs.

Or spawn the jobs in parallel, not serial :)

**Comment by Martchus** [comment]
Exact the same result as before, so we have 30 successful runs now.

**Pull request closed without merging**
