### PR TITLE
Remove assets that have been registered 14 days ago

### PR DESCRIPTION
**Pull request by coolo**
And warn about assets that are older than 24 days

### CODE REVIEW

**Comment by aaannz** [comment]
You meant older than 24h, right?

**Comment by okurz** [comment]
no, I think days.

**Comment by aaannz** [comment]
Hmm.. timecond is for images at least one day old (3600s * 24). And the condition then goes - what is older than 14 days -> delete, rest warn it will be deleted in 14 - days.

**Comment by coolo** [comment]
24 hours and 14 days :)

**Comment by aaannz** [comment]
So just update the commit message and :+1:

**Comment by coolo** [comment]
having these extra lines covered would be good, but I miss the time to do so ;(

**Pull request merged**
