### PR TITLE
More prominent color for closed bug references, old ones for open bugs

### PR DESCRIPTION
**Pull request by okurz**
openqa_new_bug_icons

Followup to https://github.com/os-autoinst/openQA/pull/1376/files#r130724832

### CODE REVIEW

**Comment by okurz** [comment]
also linked to the documentation https://progress.opensuse.org/projects/openqav3/wiki/Wiki#Distinguish-product-and-test-issues-bugref-gh708 which should be updated and incorporated into the openQA asciidoc documents.

**Comment by coolo** [comment]
please also fix the hover text to strike out closed bugs as it's done in bugzilla.

**Comment by okurz** [comment]
I will follow on with some documentation, strike out thingy, etc.

**Comment by okurz** [comment]
@coolo recommendations how to easily strike out the hover text as normal "title" attribute does not support html tags?

**Comment by okurz** [comment]
https://github.com/os-autoinst/openQA/pull/1419

**Pull request merged**
