### PR TITLE
Workaround incomplete oldest build on group overview

### PR DESCRIPTION
**Pull request by okurz**
Related issue:
https://progress.opensuse.org/issues/12028

### CODE REVIEW

**Comment by coolo** [comment]
why not fix the problem for real?

**Comment by okurz** [comment]
Who said I won't fix the problem for real? That is why I did not call this "fix". I did not manage to reproduce the issue yet having problems to import and run the database dump. I would not dare to call anything a fix unless I can first reproduce the issue and have a good test which will come … eventually.

**Comment by okurz** [comment]
obsoleted by #688

**Comment by coolo** [comment]
Understood that part. Read my comment as: do we have any pressure to live with work arounds in our code instead of waiting for a fix

**Comment by okurz** [comment]
in that case the pressure would have rather applied last week before the hotfix was overwritten by deployment. After I managed to complete #689 today it's ok to not have the workaround :-)

**Pull request closed without merging**
