### PR TITLE
Step controller: split init into 2 functions

### PR DESCRIPTION
**Pull request by coolo**
one is always called and one only whenever we want a result to avoid
getting a 404 when receiving the module source (issue  12392)

### CODE REVIEW

**Comment by okurz** [comment]
where is the test?

**Comment by okurz** [comment]
I am trying to add a test to t/ui/18-tests-details.t where again I hit the problem to test "running". The actual problem is that phantomjs does not return from the GET because of `var events = new EventSource(livelog.data('url'))` in `assets/javascripts/running.js`.
When I disable the corresponding source code in `running.js` a test that as expected shows a 404 error on trying to click on source links from the running job can look like this:
```perl
$driver->get($baseurl . "tests/99963");
$driver->find_element('Details', 'link_text')->click();
$driver->find_element('isosize', 'link_text')->click();
```
We could either set some magic in phantomjs to prevent it from getting stuck or have some fake code for the livelog/livestream to make it testable. Do you have an idea? Something like the "login" fake?

**Comment by coolo** [comment]
having sync calls to URLs is pretty bad in any case, you should chunk ajax calls.

**Comment by coolo** [comment]
or not - the event source is actually the better method. But at least you can defer the call

**Pull request merged**
