### PR TITLE
t: Simplify 25-cache.t with IPC::Run instead of Mojo::IOLoop::ReadWriteProcess

### PR DESCRIPTION
**Pull request by okurz**
This is an optional follow-up to https://github.com/os-autoinst/openQA/pull/3590 with additionally replacing Mojo::IOLoop::ReadWriteProcess with IPC::Run which we might consider a better long-term choice.

### CODE REVIEW

**Review by kalikiana — APPROVED** [review]
Simper => nicer :+1:

**Review by Martchus — COMMENTED** [review]
Last time I had to work with `IPC::Run` to implement tests failing when the forked web UI has warnings I was rather disappointed by it, e.g. one couldn't even get the PID in a simple way. RWP is more messy but at least also more accessible. Not sure whether it make sense to switch from one bad process library to another.

**Comment by okurz** [comment]
We can vote how many people find which one "more bad" :) I remember your problems to "access the PID" but I understand if that is by design, which I don't consider "bad" just for that reason. At least IPC::Run does what it says :)

**Comment by Martchus** [comment]
I consider it bad design if an abstraction makes the underlying layers inaccessible. This way one can not extend it and is bound to its limitations. It can also make debugging harder. I worked around it by accessing private members in the end. That reminds me of reading `IPC::Run`'s code and it is hard to tell which one is worse compared to RWP.

**Comment by okurz** [comment]
ok. So the current votes are:

* Martchus: undecided
* cdywan: +1
* okurz: +1

waiting for more opinions :)

**Comment by kalikiana** [comment]
> I consider it bad design if an abstraction makes the underlying layers inaccessible. This way one can not extend it and is bound to its limitations. It can also make debugging harder. I worked around it by accessing private members in the end. That reminds me of reading `IPC::Run`'s code and it is hard to tell which one is worse compared to RWP.

iirc it was mention in Rocket that we're in touch with the maintainer and in a position to contribute a patch?

**Comment by okurz** [comment]
yes, that's correct.

**Review by ilausuch — APPROVED** [review]
As far as I know, seems ok to me

**Pull request merged**
