### PR TITLE
t: Add full schema init+upgrade cycle test

### PR DESCRIPTION
**Pull request by okurz**
I found that our statement coverage analysis showed the
"sqlt_deploy_hook" methods that we have in OpenQA::Schema::Result were
never covered. As I learned from my helpful colleagues these methods are
never called from production code but only if users explicitly trigger
"initdb" or "upgradedb" for schema initialization scripts.

This commit adds a corresponding test to t/deploy.t which triggers the
exact same workflow users would follow for a schema version bump with
the mere difference that the test does not change our source files
directly but works with a schema version environment override and
writing the schema initialization and upgrade files into a temporary
directory. With this all "sqlt_deploy_hook" methods are called and
included in code coverage reports. A simple mutation test in these
methods also fails the test as expected.

### CODE REVIEW

**Review by Martchus — CHANGES_REQUESTED** [review]
As mentioned it will most likely not cause any failures in the CI. You would need to invoke `initdb --prepare_init`/`upgradedb --prepare_upgrades` as part of the test suite if you wanted to cover these hooks.

**Comment by okurz** [comment]
Updated:
* Added two commits which add the possibility to override the schema version using an environment variable for testing and command line parameters for both initdb and upgradedb to specify the directory to work to prevent polluting the source directory for testing purposes
* Added test of the complete "initdb+upgradedb" cycle which ensures statement coverage for the sqlt_deploy_hook methods
* Removed the removal commit for sqlt_deploy_hook methods after I could verify that all are called correctly and likely still useful

**Review by Martchus — COMMENTED** [review]
* Tidy doesn't like it.
* Otherwise it looks good - although there are really no checks whether the generated SQL isn't garbage. However, we haven't had any kind of test before so I suppose it is still a plus.

**Comment by okurz** [comment]
>     * Tidy doesn't like it.

fixed

>     * Otherwise it looks good - although there are really no checks whether the generated SQL isn't garbage. However, we haven't had any kind of test before so I suppose it is still a plus.

Correct.

**Review by Martchus — APPROVED** [review]

**Review by kalikiana — APPROVED** [review]

**Pull request merged**
