### PR TITLE
Enable JUnit/ harness on all targets

### PR DESCRIPTION
**Pull request by kalikiana**
Rather than only the named targets.

**NOTE**: This is a **draft** and supposed to **fail** for now :wink:

### CODE REVIEW

**Comment by okurz** [comment]
Sorry, I don't know what you want to achieve. What ticket is this motivated by? And I mean even in just a very remote way "motivated" maybe :)

**Comment by kalikiana** [comment]
> Sorry, I don't know what you want to achieve. What ticket is this motivated by? And I mean even in just a very remote way "motivated" maybe :)

The fact that test results on CI are broken.

**Comment by okurz** [comment]
in master? I can find https://app.circleci.com/pipelines/github/os-autoinst/openQA/2555/workflows/5f047790-54c9-4a45-ab77-903f3a224aca and that seems to be fine. Mainly t/ui/01-list.t was failing lately and that one I hope we have fixed with https://github.com/os-autoinst/openQA/pull/2987

**Comment by kalikiana** [comment]
> in master? I can find https://app.circleci.com/pipelines/github/os-autoinst/openQA/2555/workflows/5f047790-54c9-4a45-ab77-903f3a224aca and that seems to be fine. Mainly t/ui/01-list.t was failing lately and that one I hope we have fixed with #2987

Look at the **api** test in this very PR :wink:

**Comment by okurz** [comment]
you mean like https://app.circleci.com/pipelines/github/os-autoinst/openQA/2555/workflows/5f047790-54c9-4a45-ab77-903f3a224aca/jobs/24032/steps ? This looks all fine to me

**Comment by kalikiana** [comment]
Closing this since it looks like the CircleCI issues have been solved upstream and aren't to do with how we generate them.

**Pull request closed without merging**
