### PR TITLE
Scheduler race conditions

### PR DESCRIPTION
**Pull request by mudler**
This is still WIP because needs more testing. Expecially changes wrt `allocate_network()` since that involves "testing multi-machine tests".
The changes regards two differents Poo issues that seems to be related somehow: [Poo#19806](https://progress.opensuse.org/issues/19806) and [Poo#20002](https://progress.opensuse.org/issues/20002)
In the last commits the `while(1)` loop has been refactorized to `do{...} until {...}` and the job search is retried for a number of attempts since seems having ` blocking=> 1 ` produces no changes, it just exits the loop anyway - can revert if necessary, or default number of attempts tweaked.

### CODE REVIEW

**Comment by coolo** [comment]
having the search in a transation does not make sense to me. It doesn't change the database - or does it?

**Comment by mudler** [comment]
the search itself doesn't change the database, but if the retrieved value is used in the sub-sequents queries, needs to be in the same transaction.
another job_grab could update a worker after the find  and before the worker update has started (this only because https://github.com/os-autoinst/openQA/blob/master/lib/OpenQA/Scheduler/Scheduler.pm#L219 is not only searching, but also picking up the first result).

**Comment by coolo** [comment]
of course

**Comment by mudler** [comment]
but stil not sure if it's relevant to the bugs.. might be the culprit just for ovs multiple/concurrent vlan tag allocation

**Comment by mudler** [comment]
I would remove WIP - i've been running openQA with the patches applied with no problems - but can't tell if they are fixing the issue(s) since i'm not able to reproduce locally (it needs to spawn a sufficient big number of  multi-machine concurrent jobs in the same time)

**Pull request merged**
