### PR TITLE
Revert to usual wording "distri" in YAML schedules

### PR DESCRIPTION
**Pull request by okurz**
Despite we might think that spelling out words is better for
understanding we have to stick to our defined wording and also the API.
http://open.qa/docs/#concepts defines the word "distri" and we also use
that in os-autoinst as well as the actual test distributions, e.g.
os-autoinst-distri-opensuse. In case we really want to change that we
would need to handle all downstream uses as well.

Related progress issue: https://progress.opensuse.org/issues/46667

### CODE REVIEW

**Comment by okurz** [comment]
I kept "priority" as that is used only within the context of openQA and is displayed or changed at less places.

**Comment by coolo** [comment]
I'm against that - 'distri' is an historic error we are not obliged to repeat ad infinitum. Documentation can be fixed and historic compatibility explained.

**Comment by coolo** [comment]
@AdamWill WDYTH?

**Comment by okurz** [comment]
What do you mean with "historic compatibility explained"? What we currently have as in inconsistency between the yaml approach and everything else: We should either revert that minor yaml change (this PR) or align all other references to "distri" (also ok for me, but more effort)

**Comment by AdamWill** [comment]
+1 keep it distri, FWIW. Consistency is better than inconsistency, and I'd say sticking with what we already have is better than a significant effort to change everything from distri to distribution, which comes with very little benefit, let's be honest. 'distri' isn't causing anyone any problems AFAIK.

**Comment by coolo** [comment]
ok then

**Pull request merged**
