### PR TITLE
WIP: Make table of all finished tests server-side

### PR DESCRIPTION
**Pull request by Martchus**
* Builds on top of https://github.com/os-autoinst/openQA/pull/1373
* Loading the first page is much faster, but browsing/searching is now slower.
* Update of DataTables is for https://datatables.net/reference/option/searchDelay
* It is still WIP because I'm not so happy with the performance yet, sorting doesn't work yet and tests likely need to be adjusted.

### CODE REVIEW

**Comment by Martchus** [comment]
Sorting by result stats (passed/softfailed/failed modules) is very hard to implement on the server-side (without loosing performance benefits again). Maybe I'll get an idea how to implement it later, but currently it just seems impossible to me. Problem is that the query requires not only a join with the job modules table - there is also a group-by/count required and the counted values need to be used for sorting.

**Comment by Martchus** [comment]
Would it be a problem if the table could not be sorted by result?

This is currently implemented in JavaScript on the client-side using the following formula: `(parseInt(data['passed']) * 10000) + (parseInt(data['softfailed']) * 100) + parseInt(data['failed'])`

For reasons mentioned in the last comment it would be very hard to implement this for the server-side table without loosing performance again.

**Comment by coolo** [comment]
I use it quite often to find tests that fail late. So let's store this counter in the database to avoid the group-by/count while querying.

**Comment by Martchus** [comment]
Sounds like a good idea. So it would be:

1. Add 4 columns to jobs table for stats which were previously counted in `sub job_module_stats`: passed, failed, softfailed, none
2. Add a migration script to fill the columns for existing jobs.
3. Update stats in job table when its job modules are added/updated.

**Comment by foursixnine** [comment]
This will have some impact on the revamping of the test results view, toadd the new states, but I like the idea of faster loading of the results.

**Comment by Martchus** [comment]
I've just make the sorting work and only need to fix the tests. However, the performance isn't as great as expected. Using the pagination, the search and sorting is now really slow. Maybe I can improve that but if not I'm not sure whether it is worth it making the table server-side.

**Comment by Martchus** [comment]
I'm closing this for now, see the previous comment.

**Pull request closed without merging**
