### PR TITLE
Add new result preview to results page

### PR DESCRIPTION
**Pull request by asdil12**
Use arrow keys to navigate between the results.

### CODE REVIEW

**Comment by coolo** [comment]
I have my doubts the tests will fly as is - but the code looks good

**Comment by coolo** [comment]
wow, our tests don't care at all that there is no longer a step page? :)

**Comment by okurz** [comment]
nice idea, do you have an idea for better tooltips for this? and what about some little help and/or documentation?

**Comment by coolo** [comment]
tooltips where?

**Comment by okurz** [comment]
e.g. over each thumbnail

**Comment by coolo** [comment]
to say what? I guess I'm not following

**Comment by aaannz** [comment]
I have one issue with this. Every time I click on thumbnail to display details the thumbnail line is scrolled to the top. I understand the reasoning as I can see full needle view that way, but it is confusing to me.
I would rather scroll down myself to see full needle, or do some short animated scrolling up of the background so I can keep track where is everything moving.

**Comment by coolo** [comment]
I indeed experienced the same confusion

**Comment by coolo** [comment]
possibly if we animated the jump it would be less confusing? Because in the end I think it makes sense to scroll.

**Comment by asdil12** [comment]
@coolo I implemented the animation in  #727

**Pull request merged**
