### PR TITLE
Speed up 21-admin-needles.t by running all Minion jobs in foreground

### PR DESCRIPTION
**Pull request by kraih**
Followup to #4165.

Progress: Progress: https://progress.opensuse.org/issues/96564

### CODE REVIEW

**Review by Martchus — APPROVED** [review]

**Review by kalikiana — COMMENTED** [review]
Interesting that you're getting rid of the gru part of Selenium. Does that mean those tests no longer use gru? Or is it spawned some other way?
Also, how much speed up should we get from this?

**Comment by kraih** [comment]
> Interesting that you're getting rid of the gru part of Selenium. Does that mean those tests no longer use gru? Or is it spawned some other way?

Gru is Minion.

> Also, how much speed up should we get from this?

Just a few seconds, 35s vs 41s  if i remember correctly. Probably the least out of all converted tests.

**Comment by kalikiana** [comment]
> Gru is Minion.

I guess I should have asked more correctly if there's a drawback to not using the gru service the same way it's used in production. And the answer is probably the same :-D

**Review by kalikiana — APPROVED** [review]

**Comment by kraih** [comment]
> > Gru is Minion.
> 
> I guess I should have asked more correctly if there's a drawback to not using the gru service the same way it's used in production. And the answer is probably the same :-D

Yea. 😀 It shouldn't matter, the test code still runs a full Minion worker, just without the fork.

**Pull request merged**
