### PR TITLE
Needle management

### PR DESCRIPTION
**Pull request by coolo**
To be discussed. There is no delete functionality, because we need to come up with a definition of what is an obsolete needle.

### CODE REVIEW

**Comment by coolo** [comment]
needles

**Comment by coolo** [comment]
all these needles are compared against continuesly - but only 2 of them have matched lately and are excellent candidates for cleanup

**Comment by coolo** [comment]
(the 16 days because my database dump is a bit older)

**Comment by coolo** [comment]
Redid the table - and included filter

blank5

Please review - I would like to see this deployed soonish for real life testing ;)

**Comment by aaannz** [comment]
LGTM, just one question. At one point you are using `use v5.10;`, why?

**Comment by coolo** [comment]
I started from ./script/clean_needles - that's why :)

**Pull request merged**
