### PR TITLE
Allow deleting assets via web UI

### PR DESCRIPTION
**Pull request by Martchus**

### CODE REVIEW

**Comment by coolo** [comment]
doesn't work in production - it only moves the page, but the asset stays

**Comment by Martchus** [comment]
Ok, so it seems the database delete does not automatically delete the asset on the file system.

**Comment by Martchus** [comment]
Actually, my code just calls the existing `DELETE` route of the API. So I assume this is a bug in the delete API method then. Or is it actually supposed to delete the database entry only?

**Comment by Martchus** [comment]
Follow-up built on the assumption that it is ok to change the meaning of the `DELETE` route: https://github.com/os-autoinst/openQA/pull/1553

**Pull request merged**
