### PR TITLE
openqa-label-all: Allow to call without specific build

### PR DESCRIPTION
**Pull request by okurz**
Related progress issue: https://progress.opensuse.org/issues/94714

### CODE REVIEW

**Review by kalikiana — CHANGES_REQUESTED** [review]
Can you please add a test for this in `t/40-script_openqa-label-all.t`?

**Comment by okurz** [comment]
> Can you please add a test for this in `t/40-script_openqa-label-all.t`?

I'd rather not as the test creates a complete process instance, it's not a unit test for a python module or something. In case we decide it's necessary to go deeper then we should rather use a pytest test module. But what I change here is merely parameter parsing which is kinda checking itself with parameter validity checks.

**Review by kalikiana — APPROVED** [review]

**Review by Martchus — APPROVED** [review]
Btw, this should better use URL encoding.

**Comment by okurz** [comment]
> Btw, this should better use URL encoding.

ok. How could this look like?

**Comment by Martchus** [comment]
I'm normally not using Python but there's likely a utility function within the library you're using to do the query.

**Comment by perlpunk** [comment]
> Btw, this should better use URL encoding.

Maybe even just use the existing variable `request_params` instead? Then the library will do that automatically.

**Pull request merged**
