### PR TITLE
Make duplicate keys in Job Templates fatal

### PR DESCRIPTION
**Pull request by perlpunk**
An example of a duplicate mapping key:

    ---
    a: 1
    # .....
    a: 2

So far this has been ignored (and the last key won).

This will now result in an error when loading the YAML.

Issue: https://progress.opensuse.org/issues/71251

### CODE REVIEW

**Comment by okurz** [comment]
Please describe (in your commit message) what's the impact of duplicates in this context

**Comment by perlpunk** [comment]
@okurz edited the commit message and PR.

**Review by okurz — APPROVED** [review]
Let's hope no current user's use cases break here :)

**Comment by perlpunk** [comment]
What could be a use case?
Btw, yamllint will also detect such things.

**Comment by perlpunk** [comment]
All templates in o3 and osd have been fixed.

**Review by kalikiana — APPROVED** [review]
Beautischön!

**Pull request merged**
