### PR TITLE
Optimize job module insertion with raw SQL conflict handling

### PR DESCRIPTION
**Pull request by okurz**
Same as previously for screenshots where we fixed the same error in both
locations where a DB insertion is done already in
https://github.com/os-autoinst/openQA/pull/1792 and
https://github.com/os-autoinst/openQA/pull/2597 we should also prevent
expected conflicts to cause an error entry in postgres logs about job
modules. This is a followup to ecb7d1d50 where the unique constraint for
job modules was introduced.

Related progress issue: https://progress.opensuse.org/issues/60923

### CODE REVIEW

**Comment by coolo** [comment]
hmm, `insert_module` is only called in other places in Jobs.pm (next to tests). So possibly this jobs mangling should actually be done in Jobs as well - and be called directly instead of the hooks.

**Comment by Martchus** [comment]
@okurz Are you still working on this? Otherwise I'd take over on Friday or Monday (as soon as I have time) to fix https://progress.opensuse.org/issues/64298.

**Comment by okurz** [comment]
No, currently not working on this. We could pair up or you try

**Comment by Martchus** [comment]
Due to the (forced) home office pairing up is likely not as productive as usual. I'm following up the chat from yesterday and it seems you might have already started? (Still following up with the chat, mails and Git Hub notifications.)

**Comment by okurz** [comment]
> it seems you might have already started?

Well, I only investigated and did some profiling. This is what I think we could share. What I can say: The fastest test I could find that involves job modules is:

```
while_inotifywait sh -c 'env DBIC_TRACE=1 time perl -I. -Ilib -d:NYTProf t/10-tests_overview.t && nytprofhtml --open'
```

so have DBIx traces as well as profiling for t/10-tests_overview.t which is a bit faster than e.g. t/10-jobs.t . I realized that tests are pretty slow because 
t/fixtures/05-job_modules.pl is pretty big. I would favor to have less job modules by default for functional tests and rather have a performance related test where we dynamically add job modules in a single test module.

**Comment by Martchus** [comment]
Superseded by https://github.com/os-autoinst/openQA/pull/2832

**Pull request closed without merging**
