### PR TITLE
Bump base OS version to Leap 15.2

### PR DESCRIPTION
**Pull request by okurz**
Related progress issue: https://progress.opensuse.org/issues/69154

### CODE REVIEW

**Comment by Martchus** [comment]
```
Package 'perl-Devel-Cover-1.36' not found.
Package 'perl-Mojolicious-8.56' not found.
Package 'perl-Selenium-Remote-Driver-1.37' not found.
'perl-TAP-Harness-JUnit-0.42' not found in package names. Trying capabilities.
No provider of 'perl-TAP-Harness-JUnit-0.42' found.
```

Likely the hardcoded package versions in `ci-packages.txt` need to be removed (for the sake of this PR).

**Comment by okurz** [comment]
> This looks like a straight replace of all occurances of `Leap:/15.1` in CircleCI and Docker configs. Is that what it is?

Kinda. "Straight" replacement but then I reviewed all replaced occurences if that makes sense. And a trivial copyright header update as well ;)

> Also, is it expected to fail in CI?

maybe removing the version pin in `ci-packages.txt` as mentioned in https://github.com/os-autoinst/openQA/pull/3276#issuecomment-662378036 is the solution but also https://build.opensuse.org/projects/devel:openQA:ci/meta still references 15.1 . I wanted to get an approval by you first for the actual code changes and that this is the right time, then I would update the reference in OBS as well. And also I think we can try os-autoinst first in https://github.com/os-autoinst/os-autoinst/pull/1481

I think we should not need to remove the pinned versions in ci-packages.txt as most likely we actually expect the same versions. Let's see what a rebase will tell.

**Comment by okurz** [comment]
The problems still showing up in https://circleci.com/gh/os-autoinst/openQA/35178?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link show that Leap 15.2 is missing some packages or only providing older versions for our dependencies. This means that no one submitted the dependencies to openSUSE:Leap:15.2 in time. Now we have the following choices: Just link to https://build.opensuse.org/project/show/devel:openQA:Leap:15.2 or submit maintenance updates. The first is easier for us in a first step but more work in the future as we need to maintain the additional dependencies in devel:openQA

What do you think?

**Comment by Martchus** [comment]
I'd give the maintenance updates a shot. If they reject them we can still fallback to linking.

**Comment by okurz** [comment]
@Martchus ok. You can follow https://en.opensuse.org/openSUSE:Maintenance_update_process and give it a shot. Will you handle that or should someone else do that?

**Comment by Martchus** [comment]
I'm have still some PRs and would have looked into https://progress.opensuse.org/issues/69058 as next ticket. Since https://progress.opensuse.org/issues/69154 is currently assigned to you and you've already started the work I think it is the easiest if you would continue with it.

**Comment by kalikiana** [comment]
Given that #1481 was merged and both claim to do the same, this is probably obsolete now?

**Comment by okurz** [comment]
#1481 ?

**Comment by okurz** [comment]
one problem is: https://build.opensuse.org/package/show/devel:openQA:Leap:15.2/perl-Mojolicious-Plugin-Status:

```
nothing provides perl(File::Temp) >= 0.2308, (got version 0.2304 provided by perl-File-Temp), (got version 0.2304 provided by perl-base)
```

So I created https://build.opensuse.org/request/show/814747 to bump the version within openSUSE:Leap:15.2 but that got rejected because perl-File-Temp is provided by SLE packages so I created https://build.suse.de/request/show/222141 internally for SLE referencing a bug https://bugzilla.opensuse.org/show_bug.cgi?id=1174050 which was declined because we would need to have an [ECO](https://en.opensuse.org/ECO) which IMHO is an effort we want to avoid.

**Comment by okurz** [comment]
Everything in this PR is ready but we would prefer to wait for https://progress.opensuse.org/issues/68095 and be ready to upgrade all o3 and osd machines along with changing the CI setup.

**Comment by ggardet** [comment]
> Everything in this PR is ready but we would prefer to wait for https://progress.opensuse.org/issues/68095 and be ready to upgrade all o3 and osd machines along with changing the CI setup.

https://progress.opensuse.org/issues/68095 is stalled since June and Leap 15.1 is EOL in November 2020.

**Comment by okurz** [comment]
Yes, you are right. I am ok if we will merge this before https://progress.opensuse.org/issues/68095 but I think it is better if we keep the delta low so I prefer to keep the base on 15.1 (unless you have additional reasons why you would definitely *need* 15.2)

**Comment by ggardet** [comment]
> Yes, you are right. I am ok if we will merge this before https://progress.opensuse.org/issues/68095 but I think it is better if we keep the delta low so I prefer to keep the base on 15.1 (unless you have additional reasons why you would definitely _need_ 15.2)

My need for 15.2 is detailed in https://progress.opensuse.org/issues/69478#note-3

**Comment by Martchus** [comment]
> Or to upgrade at least openqa-aarch64 to Leap 15.2?

I guess we could update the o3 workers independently of the OSD workers. We already provide packages for Leap 15.2 and some tests are executed during the package build.

**Comment by okurz** [comment]
> > Or to upgrade at least openqa-aarch64 to Leap 15.2?
> 
> I guess we could update the o3 workers independently of the OSD workers.

Yes we can do that but it is best to keep the delta low still. Please see https://progress.opensuse.org/issues/72079 as a specific ticket for upgrading openqa-aarch64 only for now.

> We already provide packages for Leap 15.2

yes

> … and some tests are executed during the package build.

but not for Leap. As a matter of fact we also have a ticket for that :) https://progress.opensuse.org/issues/69160

**Comment by okurz** [comment]
One o3 worker machine was upgraded and we are working on the upgrade of o3 machines as well as the firewall migration for osd workers. We now also have a subset of tests running in OBS for openSUSE Leap 15.1 so I think we can go ahead with this PR now.

**Comment by okurz** [comment]
After all o3 machines have been upgraded to openSUSE Leap 15.2 we should merge this as well – don't know why no one approved after this long time, I will go with silent consent :)

**Pull request merged**
