### PR TITLE
WebAPI preforking and OpenQA IPC

### PR DESCRIPTION
**Pull request by aaannz**
Day spent with rebasing and here we go.

- openQA refactored to three parts - OpenQA::WebAPI, OpenQA::Scheduler and OpenQA::WebSockets
- communication using DBus (perl-Net-DBus) using service path org.opensuse.openqa.[Scheduler|WebSockets] and object path /Scheduler resp. /WebSockets
- WebAPI does not provide DBus service, acts only as a client for now
- to communicate first create IPC object ($ipc = OpenQA::IPC->ipc) and call $ipc->scheduler(function_name, options) resp. $ipc->websockets(function_name, options)

What's missing
- no DBus auth so far

### CODE REVIEW

**Comment by aaannz** [comment]
! Configure failed for Net-DBus-v1.1.0. See /home/travis/.cpanm/work/1434384776.2884/build.log for details.

That's unexpected, any travis suggestions?

**Comment by coolo** [comment]
this is just too much to review. Nothing obvious pops up, but I have to see this live. So I would merge, create packages and deploy tortuga

**Comment by aaannz** [comment]
created packages in https://build.opensuse.org/package/show/home:oholecek:branches:devel:openQA/openQA
they are tracking this PR and I also needed to add rpmlintrc to allow packaging dbus policy file

**Comment by aaannz** [comment]
rebased and added 'enable preforking by default (95787d9)'

**Comment by lnussel** [comment]
do we need to use the system dbus? Since only geekotest is allowed to access it anyways it may make sense to launch a private instance.

**Comment by aaannz** [comment]
Session bus is indeed ok, I just need to adapt my testing container. It can spare us the rpmlintrc, right?

**Comment by aaannz** [comment]
I checked the code and I already use Net::DBus->find which should use session bus if available. It will not autospawn one however but use system otherwise.

**Comment by lnussel** [comment]
it's even possible to spawn custom dbus daemons, independent of system or session bus

**Comment by aaannz** [comment]
According to Net::DBus docu it is possible to provide custom dbus address, so this should be possible. So in this case, do you expect openqa to start its own dbus daemon? What is the goal with this approach? It won't solve authentication problem IMO, since anyone can connect to our daemon.

And in the (far) future, if(f) kdbus get merged I expect systemd will assume something like dbus-daemon role.

**Comment by lnussel** [comment]
there is no session bus for geekotest so we'd have to start one anyways. custom dbus daemon would allow to put the socket where we want. access would be restricted to those having access to the socket

**Comment by aaannz** [comment]
updated apache config (use ProxyPass instead of ProxyPassMatch) and added custom secrets to websocket server

**Pull request merged**
