### PR TITLE
Scheduler: low aggressivity on slow workers

### PR DESCRIPTION
**Pull request by mudler**
- Before considering that the worker haven't accepted the job (can be optionally enabled), attempt by retrial mechanism
- Build a run-time cache of seen workers, periodically reset (can be optionally enabled) to try to allocate jobs even if workers are slow and thought dead
- Adds the ability to wake up the scheduler when we receive new jobs or restarts (optionally enabled)
- Handle gracefully quit/restarts

Let's see also if we get some coverage back

### CODE REVIEW

**Comment by AdamWill** [comment]
I'm a *little* concerned at adding so many options to vary behaviour. Every time you add an option, you add as many potential failure paths as there are existing options on the relevant codepath; it has a combinatorial effect. It'd be good (if it wasn't already done) to explicitly consider, every time we consider adding an option, whether the additional complexity, variation between deployments, and difficulty in debugging is outweighed by whatever value the option adds.

It's not particularly clear to me why it's necessary to make behaviour like `KEEPALIVE_DEAD_WORKERS` and `WAKEUP_ON_REQUEST` configurable, as opposed to just making up our minds about whether that's how we want the scheduler to behave; it'd be good to see explicit reasons given for making this a choice. Specifically, what are the real-world, significant use cases of openQA where it makes sense to use one behaviour, and what are the real-world, significant use cases where it makes sense to use the other behaviour? In particular, explaining this in the description of each option both helps people deploying openQA to make a choice, and documents the *reason* why we made these things configurable, when we come back to them in future. And if there *isn't* actually a good reason, we should just pick a choice.

**Comment by coolo** [comment]
It's not really meant for users to change. It's mainly to debug different ways to see a problem.

**Comment by AdamWill** [comment]
OK, then it would be good to explicitly document that admins are not intended to twiddle these settings. To a degree that's implied by them being environment variables and not settable in `openqa.ini`, I guess, but it never hurts to be explicit.

**Comment by coolo** [comment]
do you know the "Do not think about a pink elefant, I repeat do *not* think about a pink elefant!" game? :)

**Comment by coolo** [comment]
http://psych-n-life.blogspot.de/2008/10/dont-think-about-pink-elephant.html

**Comment by coolo** [comment]
that's happen if you mention in the documentation 'admins, do not touch the options ...'

**Comment by AdamWill** [comment]
well, that's worth considering, but I think coming across a bunch of knobs with comments explaining just how to twiddle them is *already* an invitation to twiddle them. I think on balance adding an explicit 'really, don't twiddle with these!' is overall more likely to help than hurt...it's certainly arguable, though.

**Pull request merged**
