### PR TITLE
Optimize all tests page

### PR DESCRIPTION
**Pull request by Martchus**
See https://progress.opensuse.org/issues/41054

* Don't show comments for scheduled or running jobs. This avoids
  a count per job and this info isn't so important for those jobs
  anyways.
* Sorting everything with the database
* Optimize Perl code a little bit

Locally (with OSD data where 2490 jobs are scheduled with 1878 of
them being blocked) the execution time for controller + template
goes down from 24 seconds to 13 seconds.

---

If you really need the comments for those jobs, I think it should be refactored to work like the job module count.

The next step to make this faster would be to use the AJAX approach all over the page.

### CODE REVIEW

**Comment by Martchus** [comment]
I now implemented use of AJAX all over the page. Together with the previous optimizations this gets us a huge speedup from 39 seconds to 4 seconds in case there are lots of scheduled jobs. The figures are again from my local machine using OSD data. The figures are now from the Chromium profiler. So it includes all further AJAX calls and HTML rendering.

Before:  
screenshot_20180919_163518

After first optimizations (first commit):  
screenshot_20180919_164147

After using AJAX everywhere (second commit):   
screenshot_20180919_163504

---

So now I have to adapt the tests and maybe fix some regressions.

**Comment by coolo** [comment]
wow

**Comment by Martchus** [comment]
(I hereby remind myself to use that Java Script linter.)

**Comment by Martchus** [comment]
Seems like all tests are now adapted. The failing worker and server status tests are unrelated.

**Comment by okurz** [comment]
I don't know who is looking into the flaky tests but I recommend to make sure they are stable first before a change like this even though I certainly would favor faster /tests loading :)

**Comment by Martchus** [comment]
@okurz The tests are likely failing because Mojolicoius has been updated to v8.0.

**Pull request merged**
