### PR TITLE
Add clear Add comments button label to make it discoverable

### PR DESCRIPTION
**Pull request by kalikiana**
Also mention that this adds comments to all jobs.

image

### CODE REVIEW

**Comment by okurz** [comment]
Your commit message starts with "Add clear Add comments ..."?

**Review by Martchus — COMMENTED** [review]
I find this feature has the right amount of discoverability as-is. Considering it is an advanced feature that should be used with care it make sense to use an icon-only button in my opinion (and that's also why I initially designed it this way).

**Comment by okurz** [comment]
We might want to reconsider the design anyway with https://progress.opensuse.org/issues/166556. Maybe you want to incorporate that into your ideas?

**Comment by kalikiana** [comment]
> I find this feature has the right amount of discoverability as-is. Considering it is an advanced feature that should be used with care it make sense to use an icon-only button in my opinion (and that's also why I initially designed it this way).

See https://suse.slack.com/archives/C02CANHLANP/p1724915110449239?thread_ts=1724833412.133459&cid=C02CANHLANP for the original feedback suggesting people don't find the feature at all.

**Pull request closed without merging**
