### PR TITLE
Revert "Reduce use of project dir to be more flexible regarding custom test runs"

### PR DESCRIPTION
**Pull request by okurz**
Reverts os-autoinst/openQA#2410 due to problems as described in https://progress.opensuse.org/issues/56789#note-23

### CODE REVIEW

**Comment by okurz** [comment]
@Martchus as I encountered problems in production when going back to the old packages as reported in the discussed ticket I leave it to your discretion to decide if we should merge this revert or have a fix which you already prepared in https://github.com/os-autoinst/openQA/pull/2432

**Comment by Martchus** [comment]
I'll continue working on the fix. To which version did you downgrade production? Maybe something was downgraded inconsistently?

**Comment by Martchus** [comment]
I see why the problem wasn't solved by downgrading: The required part of this revert lies on the worker but according to your comment in the ticket you only downgraded the web UI.

**Comment by okurz** [comment]
@Martchus no, I had also downgraded the worker. I assumed a problem might be if I just clone old jobs with already initialized settings which could set different, unsupported values, e.g. for PRJDIR and such

**Pull request closed without merging**
