### PR TITLE
Adapt to Mojolicious 8.34; explicitly allow empty optional needle params

### PR DESCRIPTION
**Pull request by openqabot**

### CODE REVIEW

**Comment by okurz** [comment]
UI tests fail in https://circleci.com/gh/os-autoinst/openQA/18022?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link which does not look like a known, sporadic issue. We should take this serious and check in detail

**Comment by Martchus** [comment]
I'll test it locally with the new version.

**Comment by Martchus** [comment]
After a brief look I'd say it is the parameter validation (imagedistri and imageversion are not accepted when saving a needle).

@kraih I'll check Mojolicious for relevant changes. If you know immediately what's the issue here let me know.

**Comment by okurz** [comment]
Thank you for taking the test failure serious – and not just brute-force retriggering :) :heart:

**Pull request merged**
