### PR TITLE
Finished psladek's work on #1791

### PR DESCRIPTION
**Pull request by coolo**

### CODE REVIEW

**Comment by aaannz** [comment]
What about moving modules not part of OpenQA namespace directly under lib? Like openqa.pm, Scheduler.pm, Schemas.. (Will save one! unshift for each test :) )

**Comment by coolo** [comment]
I checked and it's actually part of psladek's original proposal. but possibly we can do that step by step? :)

**Comment by ancorgs** [comment]
What @aaannz suggests was part of the agreed proposal

**Comment by coolo** [comment]
now basically everything is below OpenQA::

**Comment by aaannz** [comment]
I'm fine with that. If some statements/expressions seems too long, we can always import them from Scheduler and use without NS prefix. The same with Schemas, but will require to add Exporter ISA.

**Comment by coolo** [comment]
rebased - quite a challenge :)

**Pull request merged**
