### PR TITLE
Move OpenQA::Test::* modules to test directory

### PR DESCRIPTION
**Pull request by mudler**
As for Modern Perl and Perl best practices, to keep the codebase clean and enhance maintenance of tests, helpers and package modules needed just for testing should belong under `t/`. This PR aim to move the OpenQA::Test::* namespace under the `t/` directory, since afaics it's used only by tests files.  Currently WIP, i needed to check CI outputs.

I'm not particularly satisfied on the solution about the usage of FindBin when tests files are in inner directories (like `t/ui/` and `t/api/` )  we could think about using [Test::Class::Load](https://metacpan.org/pod/Test::Class::Load) for that.

### CODE REVIEW

**Comment by coolo** [comment]
the drop in coverage is because the test classes no longer count?

**Comment by mudler** [comment]
seems an [unexpected coverage change](https://codecov.io/gh/os-autoinst/openQA/pull/1325/changes)

**Comment by foursixnine** [comment]
I'm having the same on #1324 and taking a look at the lines, it does not make any sense :/

**Comment by mudler** [comment]
Indeed, seems more a common problem with codecov

**Comment by coolo** [comment]
nah, the Running.pm diff is 'normal' - but it does not account for such a large diff. The large diff is more because of all the lines no longer accounting and they had nice coverage before.

**Comment by kraih** [comment]
Reasonable change. 👍

**Comment by coolo** [comment]
damn, I did it again - merging [WIP]

**Pull request merged**
