### PR TITLE
Ignore module flag 'important'

### PR DESCRIPTION
**Pull request by aaannz**
Important flag evolved from helping TW release process into macking
real errors behind softfailures.
This patch removes treating of important modules differently from
others - failed module fails the job.
Softfailure is now set only when it is done so in test code or by
using workaround property of needle.

See https://progress.opensuse.org/issues/17876

### CODE REVIEW

**Comment by okurz** [comment]
good someone stepped up and proposed a PR ;-)

@AdamWill @lnussel @nilxam @dimstar77 @rbrown you will want to see this ;-)

* as os-autoinst still supports "important", do you plan to make use of the flag somehow differently later on?

* if we accept this, I don't see a problem for SLE because the number of failed and/or softfailed do not have a direct impact on decisions. For maintenance on both oS as well SLE and also staging should not be a problem because afaik every failed module will be "not acceptable". Biggest impact is on Tumbleweed which so far has been released in most if not all cases when there are softfailed jobs with failed modules and especially firefox, chromium, chrome is a constant fight so far. I am investing some time already in fixing these and keeping them fixed but is it sustainable or will the amount of stupid "just get the damn thing green" needles increase even more by doing this?

* I am *for* this change but how do we cover the cases where so far "non-important" modules have been accepted? The "known failures" of totest-manager is a much more brutal weapon because it ignores whole jobs and should therefore be reduced in usage, not increased.

**Comment by AdamWill** [comment]
Hum, this would be quite inconvenient for this. We actually use this feature, most extensively in this test:

https://openqa.fedoraproject.org/tests/67541

note the `freeipa_webui` and `freeipa_password_change` tests are not 'important'. So, the thing is, we need to test those things, but if they fail, we still want to run the `freeipa_client` part of the test, and the main thing in the test - enrolling as a FreeIPA client via cockpit - still worked.

In a sense running these tests as non-important modules 'in the middle of' another test is a bit of a hack, but it does work out rather well. It'd be somewhat inconvenient to try and pull those tests out into separate jobs.

We *could* have the `realmd_join_cockpit` test upload a disk image after `realmd_join_cockpit` runs and create separate tests that start from that disk image, but that's a bit tricky, because then we essentially have two or three tests all claiming to be *the same* FreeIPA client. Which I think may well cause problems. Otherwise, we'd have to create two new tests which go through all the hassle of enrolling themselves as FreeIPA clients, just to run the FreeIPA web UI tests.

**Comment by coolo** [comment]
the tests will still run as before - but if freeipa_webui failed, your realmd_join_cockpit will appear as failed in the dashboard and no longer as softfailed. There is no impact on isotovideo.

And to @okurz - yes, the TTM whitelist will have to be rewritten

**Comment by DimStar77** [comment]
Wow - Seeing that a TW snapshot currently has ~75 'green' and 28 'softfails' I doubt we will have a lot of releases wit this.

or we mark 28 jobs as 'known broken' - which is like 30% of the distro.

Generally seen I'm fine with 'only' asking for green jobs - but before this is merged there has to be a concentrated effort to

  * Get all the current tests actually green (we did a lot in this regards already - but not there yet)
  * Stop the random issues from appearing (e.g.  audio issues, 'textinfo' needs to be resilient against the every now and then occuring 'log file changed while reading (e.g. https://openqa.opensuse.org/tests/374318#step/textinfo/3)

After all, it can't be the goal that a TW Snapshot needs a daily caring hand to mark 'todays random stuff' in order to get a snapshot out - and listing 30 tests in known_broken is definitively also not the way to go - as it would just mask 'important' errors on top

**Comment by coolo** [comment]
you can still white list job modules next to tests in  TTM

**Comment by coolo** [comment]
but removing random failures is a prime goal actually

**Comment by coolo** [comment]
(it helps if you have a issue number, so we can assign it to the milestone or call for volunteers :)

**Comment by okurz** [comment]
agreed to all

**Comment by aaannz** [comment]
Apart from ignoring flag 'important' this PR also changes behaviour of label carry over. Before, when job failed on important or fatal module, this one single failing module was enough to allow for label carry over. In this PR I removed that condition so now whole 'job signature' - job modules and their individual results - is being compared and only in case of match carry over is allowed. This is much more strict and I'm not sure if wanted. @okurz thoughts?

**Comment by coolo** [comment]
the idea was to make sure the reason to fail was used as take over not the noise. Now that every job module is treated alike, what you say makes sense - as non-important modules are no longer noise, but also reason to fail.

**Comment by okurz** [comment]
agreed but please don't try to cover this all in one commit. IMHO please make at least two commits, one for the changed carry over first, then the rest. Is that feasible?

**Comment by coolo** [comment]
I wonder more if we should have a migration to recalculate the job status so we don't have a jump in softfails in the dashboard

**Comment by coolo** [comment]
the change in carry over is implicit

**Comment by okurz** [comment]
fine then

**Comment by AdamWill** [comment]
@coolo "the tests will still run as before - but if freeipa_webui failed, your realmd_join_cockpit will appear as failed in the dashboard"

I know that, but I mean, it's not just "appear as failed in the dashboard", it's not some cosmetic issue. The test will *be* 'failed' by any measure - API query, database query, whatever you like.

Having thought about it some more we *could* just about cope with it, I'll have to tweak how the wiki result transformer thing deals with these kinds of results. But even still, it's much nicer for that case if the result is 'soft failed', not 'failed'. Ah, well.

**Comment by coolo** [comment]
Your use case is actually a different one - you basically want to ignore the job module result but still run it. And I don't think I would have approved such a support if we started from where we are when the PR is merged :)

**Comment by AdamWill** [comment]
"And I don't think I would have approved such a support if we started from where we are when the PR is merged :)"

Well, maybe not, but I'd argue that's not a reasonable comparison. We were using an established, documented and acknowledged feature of the software to achieve what it was documented and acknowledged to do. This change removes that established and acknowledged feature of the software, which is a disruptive change to existing users. I don't think it's a reasonable comparison to say that "removing feature X" has an equal impact to "never having added feature X in the first place".

**Comment by coolo** [comment]
I am aware and it will have a big impact on us as well (see Dimstar getting nervous), but I wouldn't approve it if I wasn't convinced it's the right thing to do. We had a lengthy discussion about it

**Comment by okurz** [comment]
ah man, you are very eager to merge incomplete PRs. such disruptive changes can survive a bit more thinking… (working on checking documentation and thinking about the badges which do not make much sense now)

**Comment by coolo** [comment]
I think your phrase was 'submarine features'

**Comment by coolo** [comment]
the badges still make sense - it's just that one badge will never appear

**Comment by okurz** [comment]
exactly, you are so right, see #1268

**Comment by lnussel** [comment]
what if we kept the flag but don't use it? openQA could still behave as described here if no test had the "important" flag.

**Comment by okurz** [comment]
> what if we kept the flag but don't use it?

I don't get what you mean. IMHO that is what the PR is doing. The flag "important" is still there but it's not used

**Comment by coolo** [comment]
As I understand Ludwig: remove it from all *our* tests and make openQA even more complicated in differing tests without important module to have all important. That would mean yet another badge colour :)

Legit suggestion, but this would be a testing/support nightmare - leave alone the code complexity.

**Comment by AdamWill** [comment]
Some more cases where we were using this, and it's a pain to work around it:

* We have a whole test module whose job is only to collect system information data for later use by an analysis script. We *never* want a test to be 'failed' if any aspect of that test module fails, because its purpose is solely information gathering, the actual *test* always passed if the job reaches that module. 

* We have a test module whose job is just to shut down the system before disk image upload. Again, once we reach that module, the actual thing we wanted to test has already been tested successfully. So if that module fails, we don't want the test to fail.

* We have a test module that runs again after the 'main body' of the test has passed, and checks whether any SELinux denials occurred or ABRT caught any crashes. Again, we never want to consider the overall test as failed if this module failed, because the *thing it was testing* passed. We just want to know if any AVCs or SELinux denials showed up.

I'm really, really still not a fan of this change. :( For most of the affected modules, I think I'm going to try using `Try::Tiny` to just wrap the entire `run()` body in a try block and call `record_soft_failure` if it excepts. I hope that'll work, otherwise it's going to be an awful lot of work to deal with this.

**Comment by AdamWill** [comment]
Yeah, the more I work on adjusting to this, the more of a pain it becomes. The 'try/except' dodge doesn't work with anything that uses `assert_screen` or `assert_and_click`, because those set the overall result to 'failed' directly instead of (or as well as) dying or raising an exception. And there's just frankly no direct substitute for the behaviour `important` let you achieve: make it possible to have a module fail but the overall test pass. I really want that behaviour. It's useful behaviour.

How about if I come up with a way to restore the `important` feature, but make `important => 1` *the default*? So you don't have to add `important => 1` explicitly to every non-fatal test you want to be important, but you have to add `important => 0` explicitly (or `unimportant => 1` or something?) Would that be acceptable?

**Comment by AdamWill** [comment]
@coolo "As I understand Ludwig: remove it from all our tests and make openQA even more complicated in differing tests without important module to have all important."

This is in fact exactly how the old code *already* worked. If the `important` flag was not explicitly set one way or the other for any test module in the job, it treated them all as `important`. This is what the somewhat tricksy logic with `$important_overall` and `$overall` in `calculate_result` did.

**Comment by coolo** [comment]
the calc_result logic was not the pain point. The logic removed in https://github.com/os-autoinst/openQA/pull/1293 is

**Comment by AdamWill** [comment]
Ah, I see. So that's why you'd prefer `ignore_result`. Well, that's fine with me!

**Pull request merged**
