### PR TITLE
Tweak routing again to work for Mojo < 9 or >=9.11

### PR DESCRIPTION
**Pull request by AdamWill**
We cut off support for Mojo before 9 pretty suddenly with #3830,
and it leaves Fedora in an awkward position as F34 shipped with
Mojo 8 and updating to 9 within a stable release would be against
Fedora's update policies. This adjusts the routing to work the
old way (before #3816, #3820 or #3830) for Mojolicious versions
before 9, and the new way for versions newer than 9.10; for
anything in the middle, we die with an error.

Signed-off-by: Adam Williamson <awilliam@redhat.com>

### CODE REVIEW

**Comment by AdamWill** [comment]
@kraih for thoughts. this is a way we could achieve #3892 if we want to.

**Review by okurz — APPROVED** [review]

**Review by Martchus — COMMENTED** [review]
It would be good if the `elsif`/`else` branches would be marked as uncoverable. I'm also wondering why you don't just provide a newer version of Mojolicious and openQA via an extra repository and use that for your deployments.

**Comment by okurz** [comment]
> It would be good if the `elsif`/`else` branches would be marked as uncoverable. I'm also wondering why you don't just provide a newer version of Mojolicious and openQA via an extra repository and use that for your deployments.

are you questioning the development model of all non-rolling-release operating systems? :)

**Comment by kraih** [comment]
Mojolicious 8.55 is almost  a year old (34 releases) and we are not testing new openQA releases with it. So it will definitely break for you every now and then in unexpected ways. Even if there are two separate code paths for the most obvious cases.

**Comment by AdamWill** [comment]
It's just an option. Updating Mojo is another option. I don't particularly like side repositories, but that's also an option. Not merging this but carrying it downstream till F35 is another option.

**Comment by AdamWill** [comment]
oh, btw, we're not using 8.55. I just put the number back to what it was before the change to 9.11. We are on 8.73.
People are pretty heavily against updating F34 to Mojo 9, so I think I'm going to use this one way or another; either merged upstream or carried downstream.

**Comment by okurz** [comment]
I pushed a patch to fix the dependency check

**Comment by AdamWill** [comment]
oh, thanks, sorry, I forgot that needed doing! thanks for the merge. As long as I'm updating the package for F34 I should notice if anything breaks too terribly; once I stop updating to new git bumps I'll try and remember to let you know so we can just drop this and go back to 9 only.

**Pull request merged**
