### PR TITLE
Refactor clone job

### PR DESCRIPTION
**Pull request by Martchus**
Some further refactoring I've come up with when reviewing https://github.com/os-autoinst/openQA/pull/1730.

@okurz Now you've got the reduced indentation you'd like to have in my previous PR :-)

### CODE REVIEW

**Comment by Martchus** [comment]
Seems like the fullstack test is broken again (not related to this PR):

```
not ok 24 - test 1 is passed
#   Failed test 'test 1 is passed'
#   at /opt/testing_area/openqa/t/lib/OpenQA/Test/FullstackUtils.pm line 86.
#                   'Result: incomplete finished 2 minutes ago ( 02:04 minutes )
# Assigned worker: 8c4b1c704113:1'
#     doesn't match '(?^:Result: passed)'
```

**Comment by foursixnine** [comment]
@Martchus yeah, I'm looking at it

**Comment by Martchus** [comment]
I reproduced the failure locally. Multiple of the jobs which are supposed to pass fail as incomplete. Here's the relevant autoinst-log:

Test 1:  
```
[2018-08-06T14:36:49.0538 CEST] [debug] QEMU: qemu-system-i386: terminating on signal 15 from pid 21184 (/hdd/openqa-devel/repos/os-autoinst/isotovideo: backen)
[2018-08-06T14:36:49.0539 CEST] [debug] sending magic and exit
[2018-08-06T14:36:49.0539 CEST] [debug] received magic close
[2018-08-06T14:36:49.0545 CEST] [debug] backend process exited: 0
[2018-08-06T14:36:50.0546 CEST] [info] ::: backend::qemu::do_extract_assets: Extracting (?^:^hd0$)
[2018-08-06T14:36:50.0546 CEST] [debug] running nice ionice qemu-img convert -c -O qcow2 /tmp/GyaQFlOzcA/t/full-stack.d/openqa/pool/1/raid/hd0 assets_public/core-hdd.qcow2UEFI_PFLASH_VARS=/usr/share/qemu/ovmf-x86_64.bin 0
[2018-08-06T14:36:50.0558 CEST] [debug] qemu-img: assets_public/core-hdd.qcow2UEFI_PFLASH_VARS=/usr/share/qemu/ovmf-x86_64.bin: error while converting qcow2: Could not create file: No such file or directory

[2018-08-06T14:36:50.0559 CEST] [debug] extract assets failed: runcmd failed with exit code 1 at /hdd/openqa-devel/repos/os-autoinst/osutils.pm line 118.

[2018-08-06T14:36:50.0559 CEST] [debug] killing backend process 21184
[2018-08-06T14:36:50.0559 CEST] [debug] done with backend process
21174: EXIT 1
```

Test 5 and 6 (log looks basically the same for both):  
```
[2018-08-06T14:43:55.0600 CEST] [debug] GET "/B9ZVg3W2a6Mxk1HS/isotovideo/status" (46bbb652)
[2018-08-06T14:43:55.0601 CEST] [debug] Routing to a callback
[2018-08-06T14:43:56.0870 CEST] [error] can_read received kill signal at /hdd/openqa-devel/repos/os-autoinst/myjsonrpc.pm line 89.

[2018-08-06T14:43:56.0891 CEST] [debug] Template "exception.production.html.ep" not found
[2018-08-06T14:43:56.0892 CEST] [debug] Rendering template "exception.html.ep"
[2018-08-06T14:43:56.0895 CEST] [debug] Rendering template "layouts/error.html.ep"
String found where operator expected at template layouts/error.html.ep line 20, near "asset 'bootstrap.css'"
	(Do you need to predeclare asset?)
String found where operator expected at template layouts/error.html.ep line 21, near "asset 'bootstrap.js'"
	(Do you need to predeclare asset?)
String found where operator expected at template layouts/error.html.ep line 35, near "icon_url 'logo-16.png'"
	(Do you need to predeclare icon_url?)
String found where operator expected at template layouts/error.html.ep line 36, near "icon_url 'logo.svg'"
	(Do you need to predeclare icon_url?)
String found where operator expected at template layouts/error.html.ep line 43, near "icon_url 'logo.svg'"
	(Do you need to predeclare icon_url?)
Mojo::Reactor::Poll: I/O watcher failed: Global symbol "$appname" requires explicit package name (did you forget to declare "my $appname"?) at template layouts/error.html.ep line 13.
Global symbol "$appname" requires explicit package name (did you forget to declare "my $appname"?) at template layouts/error.html.ep line 16.
syntax error at template layouts/error.html.ep line 20, near "asset 'bootstrap.css'"
syntax error at template layouts/error.html.ep line 21, near "asset 'bootstrap.js'"
syntax error at template layouts/error.html.ep line 35, near "icon_url 'logo-16.png'"
syntax error at template layouts/error.html.ep line 36, near "icon_url 'logo.svg'"
syntax error at template layouts/error.html.ep line 43, near "icon_url 'logo.svg'"
8:       <meta name="description" content="openQA is a testing framework mainly for distributions">
9:       <meta name="keywords" content="Testing, Linux, Qemu">
10:       <meta name="author" content="openQA contributors">
11: 
12:       % if ($title) {
13:       <title><%= $appname . ": " . title %></title>
14:       % } else
15:       % {
16:       <title><%= $appname %></title>
17:       % }
18: 
[2018-08-06T14:43:56.0903 CEST] [debug] Client disconnected
[2018-08-06T14:43:56.0907 CEST] [debug] commands process exited: 0
[2018-08-06T14:43:57.0908 CEST] [debug] isotovideo done
[2018-08-06T14:43:57.0910 CEST] [debug] BACKEND SHUTDOWN 1
last frame
[2018-08-06T14:44:00.0003 CEST] [debug] QEMU: qemu-system-i386: terminating on signal 15 from pid 22071 (/hdd/openqa-devel/repos/os-autoinst/isotovideo: backen)
[2018-08-06T14:44:00.0004 CEST] [debug] sending magic and exit
[2018-08-06T14:44:00.0004 CEST] [debug] received magic close
[2018-08-06T14:44:00.0012 CEST] [debug] backend process exited: 0
[2018-08-06T14:44:01.0013 CEST] [info] ::: backend::qemu::do_extract_assets: Extracting (?^:^hd0$)
[2018-08-06T14:44:01.0014 CEST] [debug] running nice ionice qemu-img convert -c -O qcow2 /tmp/GyaQFlOzcA/t/full-stack.d/openqa/pool/1/raid/hd0 assets_public/core-hdd.qcow2UEFI_PFLASH_VARS=/usr/share/qemu/ovmf-x86_64.bin 0
[2018-08-06T14:44:01.0031 CEST] [debug] qemu-img: assets_public/core-hdd.qcow2UEFI_PFLASH_VARS=/usr/share/qemu/ovmf-x86_64.bin: error while converting qcow2: Could not create file: No such file or directory

[2018-08-06T14:44:01.0031 CEST] [debug] extract assets failed: runcmd failed with exit code 1 at /hdd/openqa-devel/repos/os-autoinst/osutils.pm line 118.
```

**Comment by foursixnine** [comment]
@Martchus blame @foursixnine, he didn't double check these spaces when merging `https://github.com/os-autoinst/openQA/blob/master/t/full-stack.t#L146`

**Comment by Martchus** [comment]
So I suppose you'll create a PR fixing those spaces again?

**Comment by foursixnine** [comment]
@Martchus Yeah

**Pull request merged**
