### PR TITLE
docs: Add instructions for personal credentials

### PR DESCRIPTION
**Pull request by okurz**
This change is [Reviewable](https://reviewable.io/reviews/os-autoinst/openqa/915)

### CODE REVIEW

**Comment by aaannz** [comment]
I'm not sure if installation is valid doc here. This may be relevant to people never installing openQA and only using it.

**Comment by okurz** [comment]
On Friday 30 September 2016 02:52:16 Ondřej Holeček wrote:
> I'm not sure if installation is valid doc here. This may be relevant to
> people never installing openQA and only using it.

Would that be GettingStarted?

**Comment by coolo** [comment]
ETIMEOUT?

**Comment by okurz** [comment]
updated

**Comment by coolo** [comment]
:+1:

**Comment by okurz** [comment]
@aaannz ?

**Pull request merged**
