### PR TITLE
Improve needle editor test coverage, action#6562

### PR DESCRIPTION
**Pull request by nilxam**
Testing needle editor based on Selenium::Remote:Driver and phantomjs.

### CODE REVIEW

**Comment by coolo** [comment]
LGTM

**Comment by nilxam** [comment]
the category in 05-job_modules.pl looks wrong, will update it soon

**Comment by nilxam** [comment]
done.

**Comment by coolo** [comment]
Coverage increased (+56.35%) ! I was saying that!

**Pull request merged**
