### PR TITLE
Sort comments to have the youngest comment first

### PR DESCRIPTION
**Pull request by coolo**

### CODE REVIEW

**Comment by aaannz** [comment]
Don't you want `{order_by => {-desc => 'id'}}`.

**Comment by coolo** [comment]
well, it would be more logical I guess. But my PR is correct, as the templates call reverse on the returned set

**Comment by aaannz** [comment]
Hehe, okey. :+1:

**Comment by okurz** [comment]
could you add a test?

**Comment by coolo** [comment]
how do you test "not random"?

**Comment by okurz** [comment]
Add two comments, check the later one is first on generated page

**Comment by coolo** [comment]
ok, then the answer to your initial question is: no

**Comment by okurz** [comment]
*sad face*

**Comment by coolo** [comment]
This is how it looks like :crying_cat_face:

**Comment by coolo** [comment]
I added a check to test that it's not the wrong order - but (unfortunately) it also worked previously. That's the problem with random - most of the time postgresql will return the comments sorted by ID anyway. Only because Richard vaccumed and reindexed, you saw a shuffling.

**Comment by okurz** [comment]
LGTM :sparkling_heart:

**Comment by aaannz** [comment]
Btw. is `test/comments` template used somewhere? Because there the comments are not reversed.

**Comment by okurz** [comment]
@aaannz Yes, it is used. In https://github.com/okurz/openQA/commit/d6bb3c31ea92d24bec037e23f6ef74726285f630 I also wanted to add a test. I will come up with a pull request w/o the "comment icon" including all commits which we might agree on.

So now I am confused. I know that the order of comments is commonly "oldest on top" in test results comments and "youngest on top" in the group overview but apparently not guaranteed. Is this change influencing both?

**Comment by coolo** [comment]
this change is only added a guarantee that we're always have the same sort order and no longer depend on the mood of the DB.

**Comment by okurz** [comment]
fine, what I assumed. still LGTM, go merge it :-)

**Comment by okurz** [comment]
if this was rolled out then it caused all existing comments to be displayed "oldest top" now on openqa.suse.de :confused: :anguished:

**Comment by coolo** [comment]
no, this wasn't rolled out. But now I did - I only broke it to make it more obvious that comments are not supposed to be read on weekends

**Pull request merged**
