### PR TITLE
fix mainloop creation

### PR DESCRIPTION
**Pull request by lnussel**

### CODE REVIEW

**Comment by aaannz** [comment]
Nice catch! I'm wondering how it is that scheduler even worked. Btw. does passing reactor really works? Net::DBus::_new calls $reactor->manage, but there is no such method in Mojo::Reactor.

**Comment by aaannz** [comment]
To answer myself, sure it 'works' since when $reactor is set, the part executing $reactor->manage is not run. So I don't think its correct to pass it like that.

**Comment by lnussel** [comment]
doesn't work without this for me

**Comment by aaannz** [comment]
To be clear, I'm talking about removing the 'reactor => $reactor' part. The '$reactor ? 1 : 0' is of course valid.

I can't see how that is needed. This part is handling this in Net::DBus:
```perl
    unless ($params{nomainloop}) {
        if (exists $INC{'Net/DBus/Reactor.pm'}) {
            my $reactor = $params{reactor} ? $params{reactor} : Net::DBus::Reactor->main;
            $reactor->manage($self->get_connection);
        }
        # ... Add support for GLib and POE
    }
```

Now that is executed only when $params{nomainloop} is false, but that is iff $reactor is false.
Can you debug why it does not work for you?

**Comment by lnussel** [comment]
ah, you are right. I meant the ? operator

**Pull request merged**
