### PR TITLE
Show softfails in previous results

### PR DESCRIPTION
**Pull request by Martchus**
This fixes https://progress.opensuse.org/issues/12126

These commits will conflict with "Fix build tagging when '@' is used". I'll fix the conflict as soon as one of the pull requests is merged.

I'm not sure whether the behavior is correct now, I've just tried to apply the same logic as in the group overview.

### CODE REVIEW

**Comment by coolo** [comment]
No, this is the Xth place where we hack around the fact that softfail is not a final state, which it should be. 

So please don't continue here, we need a migration to introduce softfail as proper state

**Comment by Martchus** [comment]
I've just wanted to ask "BTW: What speaks against against having the softfail as final test result?"

So I agree, it would totally make sense to have softfails as final state.

However, the test I've already implemented could be taken.

**Comment by coolo** [comment]
Sure, that is the good news

**Comment by coolo** [comment]
wait for https://github.com/os-autoinst/openQA/pull/797 to rebase the test. it should just work without further code changes :)

**Comment by coolo** [comment]
I cherry-picked the test and as I expected it worked without code changes. I only had to sort out the conflicts in the test itself.

**Pull request closed without merging**
