### PR TITLE
Test multiple perl versions in travis CI

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by okurz** [comment]
the checks seem to really work, https://travis-ci.org/os-autoinst/openQA/jobs/275070772 is revealing some problems only on perl 5.24

**Comment by coolo** [comment]
And what is so special about 5.24?

**Comment by okurz** [comment]
you mean why we have it? Because at the time this is what was used in openSUSE Tumbleweed as default

**Comment by coolo** [comment]
exactly - past :)

What is interesting as target is the latest release perl version, but I'm not so sure travis offers it.

And the problem with 5.24 you see is a problem of 5.24 - so I don't bother working around a problem of an old perl version we nowhere use.

**Comment by coolo** [comment]
So 5.24.2 is the latest available on travis CI atm. every other perl version had to be compiled - I don't think it matters that much

**Comment by coolo** [comment]
ah, so 5.26.0 is downloaded from some archive - not compiled

**Comment by okurz** [comment]
yes, with perlbrew I assume. So the same error seems to happen for perl 5.26 now. Can we fix that in the openQA source code?

**Comment by coolo** [comment]
yes, we could - but I can't reproduce this, so it's hard

**Comment by coolo** [comment]
obsolete

**Pull request closed without merging**
