### PR TITLE
openQA.spec: multiline macros for services and dependencies

### PR DESCRIPTION
**Pull request by kalikiana**
The extremely long lines tend to cause confusion when it comes to
checking existing dependencies and if something needs to be added.

can use linebreaks here afterall?

### CODE REVIEW

**Comment by coolo** [comment]
Well, as you put a question mark at the end of your comment: build a package and build a container to check

**Comment by kalikiana** [comment]
The sentence was a bit of a facetious reference to the comment at the top of the file... I sanity-checked the changes with `rpmbuild` and built a container so it should be fine. Sadly I don't think we can assume that CI verifies any packaging-related bits.

**Comment by coolo** [comment]
https://build.opensuse.org/package/show/devel:openQA/openQA - I kind of knew it :(

**Comment by coolo** [comment]
Next time point me to your branch

**Pull request merged**
