### PR TITLE
Websocket

### PR DESCRIPTION
**Pull request by coolo**

### CODE REVIEW

**Comment by aaannz** [comment]
During fixing and writing new tests I started to wonder if it would not be better to not remove database backed commands. For e.g. auditing, command status - if done, waiting, failed.
So the workflow would be merge between the old and websocket one:
1) Command_enqueue will create database entry with command state as waiting and send command through websockets.
2) If command is received right away, command will be marked as processed for given worker.  
3) If command times out, it will be marked as not completed.
No command_dequeue by default.

Obvious question is if we want this, then when clean the database of old entries. The main reason for this is to get the state of issued command which I did not yet find solution I like.

**Comment by coolo** [comment]
the question is mainly what commands are really so critical that they deserve this overhead. I guess I would just close the websocket and abort the job in case of an error.

**Comment by ancorgs** [comment]
In the past we also did consider that idea of having states for the commands and all that. We decided to keep it simple and, unless I'm wrong, we have never really missed the "missing" features.

**Comment by ancorgs** [comment]
Nice to see that somebody has taken the time to move the controllers into their own namespace/directory.

Strictly speaking, the files under ```API/V1``` are also controllers. So from my POV it would make sense to move them to ```Controller/API/V1```. Not urgent, of course.

**Comment by coolo** [comment]
I deployed now and there are 2 problems:
  /admin/workers crashes for not having openQA/Worker.pm any more

and the log file is full of:
[Thu Jan  8 11:41:03 2015] [warn] Worker ID not found for given connection during connection close
[Thu Jan  8 11:41:11 2015] [warn] A message received from unknown worker connection

**Comment by aaannz** [comment]
Worker problem is fixed in #122 (finally, I spent too much time on that than it deserved). I'm running test setup with two workers and I can't yet reproduce WS warnings, but obviously current solution is not robust enough.

**Pull request merged**
