### PR TITLE
Stabilize t/ui/27-plugin_obs_rsync_status_details

### PR DESCRIPTION
**Pull request by andrii-suse**
The problem happens when gru is slow performing background task. It is reproducible by injecting sleep(2) into update_obs_builds_text().
Previously the test tried to refresh page in hope to get correct info. But that doesn't work for "obs_builds" column.
The fix performs correct UI action instead.

### CODE REVIEW

**Comment by okurz** [comment]
Great! Let's see how this works then.

**Comment by kraih** [comment]
This PR should not have been merged. It did not pass the perltidy check, which now delays more important fixes.

**Comment by okurz** [comment]
That is correct. However yesterday, before perl-Mojolicious-9.0 was accepted into openSUSE:Factory multiple PRs - I think including the dependency upgrade one - was failing due to recent more sporadic failures in t/ui/27-plugin_obs_rsync_status_details.t

**Comment by Martchus** [comment]
I guess it doesn't matter whether we merge the chicken or the egg first.

**Comment by okurz** [comment]
"merge a chicken"? Funny picture :D

**Comment by kraih** [comment]
> I guess it doesn't matter whether we merge the chicken or the egg first.

Either way, now we've got [waffles](https://github.com/mojolicious/mojo/blob/v9.0/Changes#L3). 😆

**Pull request merged**
