### PR TITLE
Fix random failures in t/api/08-jobtemplates.t

### PR DESCRIPTION
**Pull request by Martchus**
The test was relying on the YAML validation happening in a certain order which is apparently not always the case.

### CODE REVIEW

**Comment by perlpunk** [comment]
Actually it would be nice if we could rely on the validation order.
I would check first where the change in JSON::Validator happened and see if it was an intended change.

**Comment by Martchus** [comment]
I'd like to merge this first so we get green lights in PRs again (the OBS package build already succeeds). It isn't that messy so I see no problem with that. Of course it would be nice if we could rely on the validation order in the long term.

**Comment by perlpunk** [comment]
Just did a quick check: It's passing with JSON::Validator 3.20 and failing since 3.21.
This is the diff:
https://metacpan.org/diff/file?target=JHTHORSEN/JSON-Validator-3.21/&source=JHTHORSEN%2FJSON-Validator-3.20
The following change seems to be the culprit:
```
- my %required = map { ($_ => 1) } @{$schema->{required} || []};
...
-  for my $k (sort keys %required) {
+  for my $k (sort uniq @{$schema->{required} || []}) {
```

**Comment by Martchus** [comment]
So let's merge it to avoid this from interfering with other PRs and CI problems like https://github.com/os-autoinst/openQA/pull/2724#issuecomment-586981761 ?

**Comment by perlpunk** [comment]
Yeah. I created an issue here: https://github.com/mojolicious/json-validator/issues/198

**Pull request merged**
