### PR TITLE
Adopt some bootstrap theme

### PR DESCRIPTION
**Pull request by coolo**
Trying some bootstrap themes - not all of them work with our other colours, but possibly they are still good enough to come up with some theme of our own. These themes are MIT, so we can take pieces of it as we want.

So before we merge, this needs to be reduced to one theme again :)

### CODE REVIEW

**Comment by coolo** [comment]
This is deployed on tortuga.suse.de in case you're lazy ;)

**Comment by okurz** [comment]
In this order of preference:
* simplex
* default
* spacelab
* lumen
* cerulean
* yeti
* (all others)

So you really add a cool theme selector menu and now expect us to come to an unanimous conclusion which one to take and not have access to all others? How about just keeping default and offering every theme as a personal choice selected by a config file entry which then automatically downloads the theme .css file and stores it with cookies in browser cache? ;-)

Honestly, I would take either *default* (old) and make sizes as in *simplex* or take *simplex* and make colors more like in *default* (e.g. red text for test modules is weird)

**Comment by aaannz** [comment]
I'm for (in descending order of preference): default, yeti, lumen, spacelab, ...

In case you want to offer some choice for users to select, I would make sure the job result and state colours are consistent across all themes.

**Comment by coolo** [comment]
note that default is not really what we have. it's rather a completely unthemed bootstrap. The bento theme had rather small font sizes for example

**Comment by coolo** [comment]
I prefer paper for it's navbar, it's tabs and the roboto font in general is a good match for what openQA does :)

but the font sizes of it are a bit insane. 

And no, I have 0 interest to maintain multiple themes - I don't even want to merge this as is. But it's easier to discuss options when there are some :)

**Comment by coolo** [comment]
I.e. yeti looks completely dull to me and I would never even consider it, so it's very suprising that this is the 2nd choice for @aaannz :)

But as I tried to express: we don't have to choose one of these themes as is. it's just a set of building blocks.

**Comment by coolo** [comment]
just for the record: Anja prefers superhero over yeti.

**Comment by okurz** [comment]
I fear you will just remove the "DISCUSSION" tag and merge ;-)

**Comment by coolo** [comment]
screencapture-1
screencapture-2
screencapture-3
screencapture-4

**Comment by okurz** [comment]
Regarding your new screenshots: The black font on progress bar does not suit me well, rest is fine although I don't see much difference to the default now (I guess I need to do a side-by-side again)

**Comment by coolo** [comment]
image

**Comment by coolo** [comment]
Note that it suddenly becomes possible to read the text on the light green :)

**Comment by aaannz** [comment]
OTOH reading failed modules is a little bit harder. But this black is much better than the first one posted on IRC.

**Comment by coolo** [comment]
Only tasteless morons call #3a3a3a "black" :)

**Comment by coolo** [comment]
I'm not so sure if having 2 foregrounds is helpful:

image

**Comment by coolo** [comment]
The alternative is to use the same red tune that we use as background for failed in tests/X

image

**Comment by coolo** [comment]
I tend to the latter version

**Comment by okurz** [comment]
oh, no. not again :crying_cat_face: Please keep the high contrast colors, not this washed out version

**Comment by coolo** [comment]
contrast to what? the background?

**Comment by coolo** [comment]
fine with me

**Comment by coolo** [comment]
that the difference to the default theme isn't large is because I only cherry picked some elements I liked, but left most default

**Pull request merged**
