### PR TITLE
Add description part for api routes at not_found page

### PR DESCRIPTION
**Pull request by krauselukas**
Related to https://progress.opensuse.org/issues/16282

The thought was to make a first step relating this ticket and add a description part to the already existing api routes table on the not_found page.

### CODE REVIEW

**Comment by coolo** [comment]
this really deserves a test case - and IMO a default. Most of the <td>s will contain undef and IMO result in tons of warnings

**Comment by Martchus** [comment]
@krauselukas As @coolo already mentioned, this will produce tons of warnings if you don't check for undefined. Do you still have time to work on this? I'm asking since you changed the team.

If not, I can take over if this approach for implementing [better API documentation](https://progress.opensuse.org/issues/16282) is desired. It actually goes into the same direction as I my proposal in the ticket (extending route introspection).

**Comment by krauselukas** [comment]
@Martchus go for it, i planned to finish all my PR's, but this could take a while, so you are more then welcome to take over :) thank you!

**Comment by Martchus** [comment]
Ok, then I'll finish this. Shouldn't be much effort (only a few things to fix).

**Comment by foursixnine** [comment]
Superseded by #1439

**Comment by Martchus** [comment]
You mean by https://github.com/os-autoinst/openQA/pull/1455

**Comment by foursixnine** [comment]
:P Yeah, that one :)

**Pull request closed without merging**
