### PR TITLE
Catch that last job set done

### PR DESCRIPTION
**Pull request by aaannz**

### CODE REVIEW

**Comment by okurz** [comment]
would this fix the error message seen on o3 in journal

```
on o3 journal from openqa-webui: Aug 03 21:31:34 ariel openqa[14340]: Mojo::Reactor::Poll: Timer failed: org.freedesktop.DBus.Error.Failed: No such method OpenQA::Scheduler->job_set_done
```

**Comment by aaannz** [comment]
Yes, that was the reason I worked on this.

**Comment by coolo** [comment]
LGTM. but this means that all prefork instances do this dance every 20 minutes?

**Comment by aaannz** [comment]
No, timer was set during Mojolicious startup which is executed only once before Mojo spawns other processes.
Now I moved it to the Websockets server as ws server handles workers (and per [this TODO](https://github.com/os-autoinst/openQA/pull/817/files#diff-75cb40919514ba9a462aa3baa2ec212cL126)) and we have only one process for websockets.

**Comment by aaannz** [comment]
There is one think to investigate further though. When jobs are aborted as dead, they are duplicated. In the tests both jobs are duplicated as expected, but log shows that one duplication failed (but there is clone created for that job). This is strange, but has nothing to do with this PR. I'll address that in another PR once I find the culprit.

**Comment by aaannz** [comment]
Eeh.. I screw this up. Mojo timer should be
```perl
Mojo::IOLoop->recurring(1200 => \&_workers_checker);
```
I'm missing \\& prefix here.

**Comment by aaannz** [comment]
fixed by https://github.com/os-autoinst/openQA/pull/821

**Comment by AdamWill** [comment]
I don't think this quite works properly in the real world. See https://progress.opensuse.org/issues/13526 .

Our production instance is running git from before this commit (July 8). Our staging instance is running git from after this commit. On both instances, it seems like the dead worker check sometimes unfortunately catches jobs that are unresponsive because they're in the middle of a large file upload, and kills them. But on the production instance - running the old code - I get the expected log message:

    Aug 28 04:04:32 openqa01.qa.fedoraproject.org openqa[953]: [Sun Aug 28 04:04:32 2016] [12242:error] cancelled dead job 30671 and re-duplicated done

and the job is properly duplicated. But on the staging instance - running this code - I get no log message, and the job is not duplicated.

**Comment by aaannz** [comment]
Autoduplication was removed in #828 intentionally. The log message now should be in openqa-websockets journal. Not ideal, I know.

**Comment by AdamWill** [comment]
No, this isn't the same as 'autoduplication'. This code explicitly tries to duplicate the job, it does not rely on that auto-duplication code.

**Comment by aaannz** [comment]
My mistake. Didn't check the diff. 

`log_warning` will use app instance if defined, which I'm not sure is set for websockets, else prints to stdout or stderr. Isnt that captured by systemd to journal automatically?

**Comment by AdamWill** [comment]
Well, I'm about 95% sure the check is kicking in but not logging on our dev instance; I've been looking just in the whole system journal - not for any unit, just the entire journal - and cannot find any messages in the format used.

However, since posting my comment, I've had several runs where I think the checker kicked in (the job wound up incomplete during asset upload) but the duplication *did* occur, so I'm no longer very sure the duplication is broken...

I'm now spending my energy trying to stop the checker firing when it shouldn't in the first place (by keeping the worker responsive all the time), rather than fiddling with this. I'm working on testing a set of patches which should mitigate that problem quite a lot...

**Pull request merged**
