### PR TITLE
Migrate from FontAwesome to ForkAwesome

### PR DESCRIPTION
**Pull request by Martchus**
See https://github.com/os-autoinst/openQA/issues/4158

### CODE REVIEW

**Review by okurz — CHANGES_REQUESTED** [review]
The commit message could have a bit more details, e.g. what issue is fixed, why this needs to change, to which versions of which product it applies, link to a bug or a fate entry, the choices you made, etc. Also see https://commit.style/ or http://chris.beams.io/posts/git-commit/ as a helpful guide how to write good commit messages.

**Comment by kraih** [comment]
We could just as well use Font Awesome from a CDN, why switch to Fork Awesome? [Here's](https://github.com/mojolicious/mojo/blob/51d18617866de7cf0743e3603fc8a50a43747850/lib/Mojolicious/resources/templates/mojo/debug.html.ep#L16) how the built-in Mojolicious templates use Font Awesome.

**Comment by Martchus** [comment]
We also just use a pre-built version of FontAwesome. I guess the desire is still to use something which can be build from sources, e.g. if it is needed to do changes.

**Review by okurz — APPROVED** [review]

**Comment by Martchus** [comment]
The tests failed downloading the Docker image so I retriggered them. The packaging tests fail with download errors but that's expected. When this PR has been merged I'll update the cache.

**Review by kalikiana — APPROVED** [review]

**Comment by Martchus** [comment]
I hope no assets are missing anymore. I've checked for missing icons via:

```
wget https://forkaweso.me/Fork-Awesome/icons
icons=($(git grep -ohP 'fa-[\w\-]+' | uniq))
for icon in ${icons[@]}; do grep -q "class=\"fa $icon\"" icons || echo "$icon"; done
```

**Pull request merged**
