### PR TITLE
Fix support for symlinked cache dirs

### PR DESCRIPTION
**Pull request by kraih**
While testing #2652 on the staging machines last week, i noticed that symlinked cache directories on workers did not actually work yet. This should resolve the problem.

Progress: https://progress.opensuse.org/issues/55373

### CODE REVIEW

**Comment by okurz** [comment]
Can you please put more details into the *git commit message*, not only the PR description.

**Comment by kraih** [comment]
@okurz Done.

**Comment by kraih** [comment]
I'll actually test the patch on the staging machines first, just to be sure i didn't forget anything else in the new tests.

**Comment by kraih** [comment]
Never change @codecov. 🙄

**Comment by kraih** [comment]
Everything looks good on the staging machines.

**Pull request merged**
