### PR TITLE
workshop presentation

### PR DESCRIPTION
**Pull request by aaannz**
This is the infamous presentation I gave to YaST team with incorporated feedback.

It's written in Markdown and rendered by [remark](https://github.com/gnab/remark), I don't like things to be easy. Unfortunatelly Github don't render pages correctly, but once you open in checked out it should be pretty once more. (Note it downloads remark.js from Github)

To generate pdf if you want use print to file function of you browsers (FF and Chrom[e|ium]).
Contributor guide is lagging behind, it took me too much time to deliver at least this.

### CODE REVIEW

**Comment by lnussel** [comment]
maybe we should collect material like that in a separate repo? (and also move docs/slides there)

**Comment by aaannz** [comment]
Definitely, also take remaining stuff from os-autoinst (except the generated one)

**Comment by aaannz** [comment]
Should I create that repo? Something like openQA-doc?

**Comment by coolo** [comment]
Yeah, go ahead. I would call it documentation though. It's not just documentation for openQA, it's also writing tests, etc. But make sure not to break the web page at http://os-autoinst.github.io/openQA/documentation/ (where it's called documentation too)

**Comment by aaannz** [comment]
ok, created [os-autoinst/documentation](https://github.com/os-autoinst/documentation). Closing this, will reopen there.

**Pull request closed without merging**
