### PR TITLE
worker: Do not remove timer after delay and extend unit tests

### PR DESCRIPTION
**Pull request by Martchus**
A few changes I came up with when investigating https://progress.opensuse.org/issues/96710. See particular commit messages for details.

### CODE REVIEW

**Review by kalikiana — APPROVED** [review]

**Comment by kalikiana** [comment]
I don't know what this **Build Error** is, it's the first time I'm seeing it, so but for the record:

```
#!/bin/sh -eo pipefail
# No configuration was found in your project. Please refer to https://circleci.com/docs/2.0/ to get started with your configuration.
# 
# -------
# Warning: This configuration was auto-generated to show you the message above.
# Don't rerun this job. Rerunning will have no effect.
false

Exited with code exit status 1
CircleCI received exit code 1
```

**Comment by Martchus** [comment]
When I created this PR it only worked on the 3rd attempt. According to GitHub's status page there were inded several problems. So that's likely related. I'll try to retrigger.

**Comment by kalikiana** [comment]
This time *ci/cacheci: cache* failed:

```
+ sudo zypper -n install --download-only aspell-0.60.8 aspell-en-2017.08.24 aspell-spell-0.60.8 cmark-0.28.3 hostname-3.16 jq-1.6 libaspell15-0.60.8 libcmark0_28_3-0.28.3 libjq1-1.6 libonig4-6.7.0 libssh2-1-1.9.0 lsof-4.91 optipng-0.7.7 perl-Algorithm-C3-0.10 perl-Algorithm-Diff-1.1903 perl-aliased-0.34 perl-App-cpanminus-1.7043 perl-Archive-Extract-0.80 perl-Archive-Zip-1.60 perl-bareword-filehandles-0.006 perl-B-Debug-1.26 perl-B-Hooks-EndOfScope-0.21 perl-B-Hooks-OP-Check-0.22 perl-B-Keywords-1.18 perl-BSD-Resource-1.2911 perl-Capture-Tiny-0.46 perl-Carp-Always-0.13 perl-Carp-Clan-6.06 perl-Class-Accessor-0.51 perl-Class-Accessor-Chained-0.01 perl-Class-Accessor-Grouped-0.10012 perl-Class-Accessor-Lite-0.08 perl-Class-C3-0.34 perl-Class-C3-Componentised-1.001002 perl-Class-Data-Inheritable-0.08 perl-Class-Factory-Util-1.7 perl-Class-Inspector-1.32 perl-Class-Load-0.24 perl-Class-Load-XS-0.10 perl-Class-Method-Modifiers-2.12 perl-Class-Singleton-1.5 perl-Class-Tiny-1.006 perl-Clone-0.39 perl-CommonMark-0.290000 perl-common-sense-3.74 perl-Config-Any-0.32 perl-Config-IniFiles-2.94 perl-Config-Tiny-2.23 perl-Context-Preserve-0.03 perl-CPAN-DistnameInfo-0.12 perl-Cpanel-JSON-XS-4.26 perl-CPAN-Meta-Check-0.014 perl-CPAN-Meta-Requirements-2.140000 perl-Crypt-DES-2.07 perl-Crypt-DH-GMP-0.00012 perl-Crypt-Rijndael-1.13 perl-CSS-Minifier-XS-0.09 perl-Data-Dump-1.23 perl-Data-Dumper-Concise-2.023 perl-Data-OptList-0.110 perl-Data-Page-2.02 perl-DateTime-1.45 perl-DateTime-Format-Builder-0.81 perl-DateTime-Format-Pg-0.16013 perl-DateTime-Format-Strptime-1.74 perl-DateTime-Locale-1.170000 perl-DateTime-TimeZone-2.15 perl-DBD-Pg-3.14.2 perl-DBD-SQLite-1.70 perl-DBI-1.643 perl-DBIx-Class-0.082841 perl-DBIx-Class-DeploymentHandler-0.002233 perl-DBIx-Class-DynamicDefault-0.04 perl-DBIx-Class-OptimisticLocking-0.02 perl-DBIx-Class-Schema-Config-0.001011 perl-Devel-Cover-1.36 perl-Devel-Cover-Report-Codecov-0.25 perl-Devel-Cover-Report-Codecovbash-0.04 perl-Devel-GlobalDestruction-0.14 perl-Devel-OverloadInfo-0.005 perl-Devel-StackTrace-2.03 perl-Digest-HMAC-1.03 perl-Digest-SHA1-2.13 perl-Dist-CheckConflicts-0.11 perl-Email-Address-1.912 perl-Encode-Locale-1.05 perl-Eval-Closure-0.14 perl-Exception-Class-1.44 perl-Export-Attrs-0.1.0 perl-Exporter-Declare-0.114 perl-Exporter-Tiny-1.000000 perl-File-chdir-0.1010 perl-File-Copy-Recursive-0.38 perl-File-HomeDir-1.002 perl-File-Listing-6.04 perl-File-Map-0.66 perl-File-Path-2.150000 perl-File-pushd-1.014 perl-File-ShareDir-1.104 perl-Filesys-Df-0.92 perl-File-Touch-0.11 perl-File-Which-1.22 perl-Furl-3.14 perl-Getopt-Long-Descriptive-0.102 perl-Hash-Merge-0.200 perl-HTML-Parser-3.72 perl-HTML-Tagset-3.20 perl-HTTP-Cookies-6.04 perl-HTTP-Daemon-6.01 perl-HTTP-Date-6.02 perl-HTTP-Message-6.14 perl-HTTP-Negotiate-6.01 perl-HTTP-Parser-XS-0.17 perl-Import-Into-1.002005 perl-indirect-0.38 perl-Inline-0.80 perl-Inline-Python-0.56 perl-IO-HTML-1.001 perl-IO-Socket-SSL-2.066 perl-IO-String-1.08 perl-IO-stringy-2.111 perl-IO-Tty-1.12 perl-IPC-Run-0.99 perl-IPC-Run3-0.048 perl-IPC-System-Simple-1.25 perl-JavaScript-Minifier-XS-0.11 perl-JSON-2.97001 perl-JSON-MaybeXS-1.004000 perl-JSON-Validator-3.08 perl-JSON-XS-3.04 perl-libwww-perl-6.31 perl-Lingua-EN-Inflect-1.903 perl-List-MoreUtils-0.428 perl-List-MoreUtils-XS-0.428 perl-local-lib-2.000023 perl-Log-Contextual-0.008001 perl-LWP-MediaTypes-6.02 perl-LWP-Protocol-https-6.06 perl-Meta-Builder-0.003 perl-Minion-10.22 perl-Minion-Backend-SQLite-5.0.5 perl-Module-Build-0.422400 perl-Module-Find-0.13 perl-Module-Implementation-0.09 perl-Module-Pluggable-5.2 perl-Module-Runtime-0.016 perl-Module-Runtime-Conflicts-0.003 perl-Mojo-IOLoop-ReadWriteProcess-0.28 perl-Mojolicious-9.19 perl-Mojolicious-Plugin-AssetPack-2.13 perl-Mojolicious-Plugin-OAuth2-1.59 perl-Mojo-Pg-4.25 perl-Mojo-RabbitMQ-Client-0.3.1 perl-Mojo-SQLite-3.007 perl-Moo-2.003004 perl-Moose-2.2010 perl-MooseX-Role-Parameterized-1.10 perl-MRO-Compat-0.13 perl-multidimensional-0.014 perl-namespace-autoclean-0.28 perl-namespace-clean-0.27 perl-Net-AMQP-0.06 perl-Net-HTTP-6.17 perl-Net-IP-1.26 perl-Net-OpenID-Common-1.20 perl-Net-OpenID-Consumer-1.18 perl-Net-SNMP-6.0.1 perl-Net-SSH2-0.72 perl-Net-SSLeay-1.88 perl-Package-DeprecationManager-0.17 perl-Package-Stash-0.37 perl-Package-Stash-XS-0.28 perl-Package-Variant-1.003002 perl-PadWalker-2.3 perl-Params-Util-1.07 perl-Params-Validate-1.29 perl-Params-ValidationCompiler-0.26 perl-Parse-PMFile-0.41 perl-Parse-RecDescent-1.967015 perl-Path-Class-0.37 perl-Path-Tiny-0.104 perl-Perl-Critic-1.130 perl-Perl-Critic-Freenode-0.026 perl-Perl-Critic-Pulp-96 perl-PerlIO-Layers-0.012 perl-Perl-Tidy-20210717 perl-Pod-MinimumVersion-50 perl-Pod-POM-2.01 perl-Pod-Spell-1.20 perl-PPI-1.236 perl-PPIx-Regexp-0.071 perl-PPIx-Utilities-1.001000 perl-Readonly-2.05 perl-Regexp-Common-2017060201 perl-Role-Tiny-2.000006 perl-Scope-Guard-0.21 perl-Selenium-Remote-Driver-1.41 perl-Socket6-0.28 perl-Socket-MsgHdr-0.04 perl-Sort-Versions-1.62 perl-Specio-0.42 perl-SQL-Abstract-2.000001 perl-SQL-Abstract-Pg-1.0 perl-SQL-SplitStatement-1.00020 perl-SQL-Tokenizer-0.24 perl-SQL-Translator-0.11024 perl-strictures-2.000005 perl-String-Format-1.18 perl-String-ShellQuote-1.04 perl-Sub-Exporter-0.987 perl-Sub-Exporter-Progressive-0.001013 perl-Sub-Identify-0.14 perl-Sub-Install-0.928 perl-Sub-Name-0.21 perl-Sub-Quote-2.004000 perl-Sub-Retry-0.06 perl-Sub-Uplevel-0.240.0 perl-SUPER-1.20141117 perl-TAP-Harness-JUnit-0.42 perl-Task-Weaken-1.06 perl-Test-Deep-1.127 perl-Test-Differences-0.64 perl-Test-Exception-0.430000 perl-Test-Fatal-0.014 perl-Test-LongString-0.17 perl-Test-MockModule-0.13 perl-Test-MockObject-1.20161202 perl-Test-MockRandom-1.01 perl-Test-Mock-Time-0.1.7 perl-Test-Most-0.35 perl-Test-Output-1.031 perl-Test-Strict-0.40 perl-Test-Warn-0.32 perl-Test-Warnings-0.031 perl-Text-Brew-0.02 perl-Text-Diff-1.45 perl-TimeDate-2.30 perl-Time-modules-2011.0517 perl-Try-Tiny-0.30 perl-Types-Serialiser-1.0 perl-UNIVERSAL-can-1.20140328 perl-UNIVERSAL-isa-1.20171012 perl-URI-1.73 perl-URI-db-0.18 perl-URI-Nested-0.10 perl-Variable-Magic-0.62 perl-WWW-RobotRules-6.02 perl-XML-LibXML-2.0132 perl-XML-NamespaceSupport-1.12 perl-XML-SAX-0.99 perl-XML-SAX-Base-1.09 perl-XML-SAX-Expat-0.51 perl-XML-SemanticDiff-1.0006 perl-XML-Simple-2.24 perl-YAML-1.24 perl-YAML-LibYAML-0.83 perl-YAML-PP-0.027 psmisc-23.0 python3-appdirs-1.4.3 python3-packaging-20.3 python3-pathspec-0.7.0 python3-pyparsing-2.2.0 python3-PyYAML-5.3.1 python3-setuptools-40.5.0 python3-yamllint-1.22.1 ShellCheck-0.7.1 sqlite3-3.36.0
Loading repository data...
Reading installed packages...
Package 'perl-Mojolicious-9.19' not found.
```

**Comment by Martchus** [comment]
Because 9.20 is now in Factory. I suppose we need to trigger the dependency update.

**Comment by kalikiana** [comment]
> Because 9.20 is now in Factory. I suppose we need to trigger the dependency update.

Ack, I just saw there is #4117, I wasn't expecting that update and thought it was another circleci breakage :-D

**Comment by Martchus** [comment]
I've only triggered the job to create #4117 after your last comment :-)
The Mojolicious release is actually around for a few days or so.

**Pull request merged**
