### PR TITLE
apache config updates

### PR DESCRIPTION
**Pull request by lnussel**

### CODE REVIEW

**Comment by okurz** [comment]
ok to me although I could think of a more generic solution to hide everything that is under a special prefix folder, e.g. `share/factory/hdd/private`

**Comment by aaannz** [comment]
I'm not particularly fond of this. I'm fine with  b8dedfa, but the rest are highly SUSE specific. What is this server-status?

**Comment by lnussel** [comment]
fine with me. Mind verifying it on o.o.o?

**Comment by sysrich** [comment]
I dont think any of these changes are SUSE specific

The Windows filtering is a good sane default - the only possible openQA user who is likely to have a license allowing the distribution of Windows disk images is Microsoft, and as far as I know they're not using openQA (yet)

**Comment by aaannz** [comment]
I beg to differ. Anyone using openQA not open to public may want to make it accessible. Also the regex assumes similar naming scheme we use. One can in the same way have images starting MSWindows.

Particularly in this file (openqa-common.inc) we should avoid such assumptions. For customisation we ship openqa.conf.template and not openqa.conf.

**Comment by coolo** [comment]
I'm 100% with Ondrej here. the windows regexp has no business in git. The rest is fine

**Comment by aaannz** [comment]
Anything happening here?

**Pull request closed without merging**
