### PR TITLE
VHD and VHDX image support

### PR DESCRIPTION
**Pull request by mnowaksuse**

### CODE REVIEW

**Comment by okurz** [comment]
+1

**Comment by mnowaksuse** [comment]
Are those "failed" checks real? They do not make a lot of sense to me.

**Comment by foursixnine** [comment]
@mnowaksuse: https://travis-ci.org/os-autoinst/openQA/jobs/296820762#L732

**Comment by mnowaksuse** [comment]
@foursixnine Nothing I can do something about, I guess?

**Comment by okurz** [comment]
If I interpret that correctly then it's about the tidy check failing. Can you please try to rebase and run `script/tidy`?

**Comment by mnowaksuse** [comment]
@okurz Yes, it was a tidy problem. Thanks for the explanation!

**Pull request merged**
