### PR TITLE
Split UI tests from !UI tests

### PR DESCRIPTION
**Pull request by coolo**
Merely an experiment for now - but I'm tired of waiting

### CODE REVIEW

**Comment by okurz** [comment]
LGTM

**Comment by coolo** [comment]
So the time saving is less than I expected - It's around 13:30 previously and now it's 11:20 for the longest

**Comment by coolo** [comment]
the 16 lines removed are from the perlcritic policy - that I added to the ignore

**Comment by coolo** [comment]
so this brings us to around 10 minutes as turn around time. Which is still a lot. Most of the time is spent in tests though.

What worries me though: We had like 13 minutes before - I expected the runtime to be halfed, but each half is running slower now.

**Comment by coolo** [comment]
I just verified - the devel:cover overhead is huge and hugely controlled by the regexps you give it.

This is without devel:cover:
```
t/00-tidy.t ............................. ok    16263 ms 
t/01-compile-check-all.t ................ ok    30803 ms 
t/02-pod.t .............................. ok      157 ms 
t/05-scheduler-cancel.t ................. ok     1866 ms 
t/05-scheduler-dependencies.t ........... ok     4354 ms 
t/05-scheduler-restart-and-duplicate.t .. ok     2220 ms 
t/07-api_jobtokens.t .................... ok     8596 ms 
```

(split done in 5:24 minutes).

This is how we used to run it:
```
t/00-tidy.t ............................. ok    16053 ms 
t/01-compile-check-all.t ................ ok    77516 ms 
t/02-pod.t .............................. ok      378 ms 
t/05-scheduler-cancel.t ................. ok     4981 ms 
t/05-scheduler-dependencies.t ........... ok    21876 ms 
t/05-scheduler-restart-and-duplicate.t .. ok     5566 ms 
t/07-api_jobtokens.t .................... ok     4851 ms 
```

(all done in ~13 minutes).

Now with my split and changed regexps:

```
t/00-tidy.t ............................. ok    16542 ms 
t/01-compile-check-all.t ................ ok   113730 ms 
t/02-pod.t .............................. ok      424 ms 
t/05-scheduler-cancel.t ................. ok     8056 ms 
t/05-scheduler-dependencies.t ........... ok    13368 ms 
t/05-scheduler-restart-and-duplicate.t .. ok     8776 ms 
t/07-api_jobtokens.t .................... ok    15170 ms 
```

(all done in 9:33)

As you can see: changing ignore one file to ignore_re one dir gives us a penalty of 4 minutes.

**Comment by coolo** [comment]
especially running the compile-check-all under coverage is a bit nonsense. It has to load all dependencies and verify if they are under coverage or not.

**Comment by coolo** [comment]
So now that I knew what I was looking for, I was able to fine tune the cover options for speed and I'm down to 6:50 as turn around time, which is close enough to 13/2 :)

**Comment by coolo** [comment]
the next thing to split would be all code quality checks. They alone account to 2 minutes. Bug as long as we are below 10 minutes I'm not going to act :)

**Comment by okurz** [comment]
prove supports running tests in parallel, same as make. The code quality checks are not a problem to run in parallel but some other tests that are mangling with files in the local workspace are. I suggest to better invest on these tests.

**Pull request merged**
