### PR TITLE
Fix misleading error message on non-UEFI jobs

### PR DESCRIPTION
**Pull request by okurz**
Related progress issue: https://progress.opensuse.org/issues/42329

### CODE REVIEW

**Comment by okurz** [comment]
@richiejp do you think this is the right approach?

**Comment by okurz** [comment]
hm, could it be there is a big coverage drop reported because I did not rebase my openQA working copy?

**Comment by okurz** [comment]
Seems like it

**Comment by richiejp** [comment]
Well, it is either this or change it to a warning instead of an error if it is UEFI flash that is missing.

**Comment by okurz** [comment]
hm, I don't understand how the warning would help or what it actually warns about when the asset is not expected on non-UEFI jobs.

**Comment by okurz** [comment]
Yes, because the presence of the asset is only required on UEFI, not otherwise. Mentioning this PR to you in the ticket was a mistake by me because aarch64 is always UEFI in this case.

**Pull request merged**
