### PR TITLE
update apparmor profiles for ppc64le

### PR DESCRIPTION
**Pull request by michelmno**
add few lines in two apparmor profiles to avoid errors
as extracted below from journalctl:
```
AVC apparmor="DENIED" operation="exec" profile="/usr/share/openqa/script/openqa" \
name="/usr/bin/unzip-plain" \
pid=34377 comm="openqa" requested_mask="x" denied_mask="x" fsuid=483 ouid=0
===
AVC apparmor="DENIED" operation="open" profile="/usr/share/openqa/script/worker" \
name="/proc/35946/auxv" \
pid=35946 comm="isotovideo" requested_mask="r" denied_mask="r" fsuid=480 ouid=480
===
AVC apparmor="DENIED" operation="open" profile="/usr/share/openqa/script/worker" \
name="/sys/firmware/devicetree/base/cpus/" \
pid=35951 comm="qemu-system-ppc" requested_mask="r" denied_mask="r" fsuid=480 ouid=0
```

Signed-off-by: Michel Normand <normand@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by michelmno** [comment]
I did not validated those changes, sent only for first comments.
I am only doing bypass  with aa-complain

**Comment by coolo** [comment]
I get the worker part - but we don't call unzip. Where is this coming from?

**Comment by michelmno** [comment]
for the unzip  I am OK to ignore related change.
I only identified unzip caller in the journalctl output of last week
I do not have those traces in today's trial, so unable to identify action related to those failure.
I only have:
```
$grep unzip openqa_abanc_journalctl_apparmor_bypass5.log
Sep 13 16:06:42 nohostname audit[1852]: AVC apparmor="DENIED" operation="exec" profile="/usr/share/openqa/script/openqa" name="/usr/bin/unzip-plain" pid=1852 comm="openqa" requested_mask="x" denied_mask="x" fsuid=483 ouid=0
Sep 13 16:06:45 abanc audit[2077]: AVC apparmor="DENIED" operation="exec" profile="/usr/share/openqa/script/openqa" name="/usr/bin/unzip-plain" pid=2077 comm="openqa" requested_mask="x" denied_mask="x" fsuid=483 ouid=0
Sep 14 15:29:57 abanc audit[57937]: AVC apparmor="DENIED" operation="exec" profile="/usr/share/openqa/script/openqa" name="/usr/bin/unzip-plain" pid=57937 comm="openqa" requested_mask="x" denied_mask="x" fsuid=483 ouid=0
Sep 14 15:29:59 abanc audit[58260]: AVC apparmor="DENIED" operation="exec" profile="/usr/share/openqa/script/openqa" name="/usr/bin/unzip-plain" pid=58260 comm="openqa" requested_mask="x" denied_mask="x" fsuid=483 ouid=0
Sep 14 15:51:30 nohostname audit[1895]: AVC apparmor="DENIED" operation="exec" profile="/usr/share/openqa/script/openqa" name="/usr/bin/unzip-plain" pid=1895 comm="openqa" requested_mask="x" denied_mask="x" fsuid=483 ouid=0
Sep 14 15:51:33 nohostname audit[1902]: AVC apparmor="DENIED" operation="exec" profile="/usr/share/openqa/script/openqa" name="/usr/bin/unzip-plain" pid=1902 comm="openqa" requested_mask="x" denied_mask="x" fsuid=483 ouid=0
Sep 16 12:06:33 nohostname audit[1888]: AVC apparmor="DENIED" operation="exec" profile="/usr/share/openqa/script/openqa" name="/usr/bin/unzip-plain" pid=1888 comm="openqa" requested_mask="x" denied_mask="x" fsuid=483 ouid=0
Sep 16 12:06:36 abanc audit[2112]: AVC apparmor="DENIED" operation="exec" profile="/usr/share/openqa/script/openqa" name="/usr/bin/unzip-plain" pid=2112 comm="openqa" requested_mask="x" denied_mask="x" fsuid=483 ouid=0
Sep 19 10:24:38 abanc audit[34005]: AVC apparmor="DENIED" operation="exec" profile="/usr/share/openqa/script/openqa" name="/usr/bin/unzip-plain" pid=34005 comm="openqa" requested_mask="x" denied_mask="x" fsuid=483 ouid=0
Sep 19 10:24:40 abanc audit[34377]: AVC apparmor="DENIED" operation="exec" profile="/usr/share/openqa/script/openqa" name="/usr/bin/unzip-plain" pid=34377 comm="openqa" requested_mask="x" denied_mask="x" fsuid=483 ouid=0
```

**Comment by coolo** [comment]
do you have any related error in /var/log/openqa?

**Comment by michelmno** [comment]
no the related file is empty as appended below, but may be because the worker is still not able to start the test  (as per http://paste.opensuse.org/view/raw/88364483 but probably another problem)
```
$ls -ltra /var/log/openqa
-rw-r--r-- 1 geekotest root 0 Sep 12 12:49 /var/log/openqa
[michel@abanc:~]
$cat /var/log/openqa
```

**Comment by coolo** [comment]
0 is very unusual. the webui should log at least restarts

**Comment by michelmno** [comment]
after the host restart, and a manual webui restart I still have an empty /var/log/openqa
http://susepaste.org/view/raw/35655005

**Comment by mimi1vx** [comment]
on all newer installations of openQA we log to journal.
@michelmno  what says `journalctl -u openqa*`

**Comment by michelmno** [comment]
@mimi1vx, I did a copy/paste of journalctl -u openqa* in http://paste.opensuse.org/view/raw/1336069

**Pull request merged**
