### PR TITLE
Test pausing and resuming test execution

### PR DESCRIPTION
**Pull request by Martchus**
Test for PR: https://github.com/os-autoinst/os-autoinst/pull/966
Based on: https://github.com/os-autoinst/openQA/pull/1661

Note that https://github.com/os-autoinst/openQA/pull/1661 actually passed the CI checks. Only the test coverage wasn't sufficient. Maybe this improves now. However, the fullstack test is supposed to fail here because https://github.com/os-autoinst/os-autoinst/pull/966 would be required.

### CODE REVIEW

**Comment by Martchus** [comment]
Wasn't there a time limit for Travis jobs? The fullstack test runs now almost 40 minutes because it is stuck due to the missing changes in os-autoinst. Maybe I should implement a timeout in the test itself (had assumed Travis would kill it anyways)?

**Comment by okurz** [comment]
Why so impatient? https://travis-ci.org/os-autoinst/openQA/jobs/385145430 was aborted after 49 minutes with the message "The job exceeded the maximum time limit for jobs, and has been terminated."

**Comment by foursixnine** [comment]
@Martchus You can always add a counter to avoid such situations, however you can always go to the travis job and click cancel build yourself :) You've got commit access

**Comment by Martchus** [comment]
@okurz Actually the test run was a little bit too patient. It should have been given up way earlier.

@foursixnine For that particular case it is already fixed on my latest branch (see the other PR). But I can also add a generic counter to handle this.

I restarted the job, let's see whether it works now that the required changes in os-autoinst have been merged.

**Comment by Martchus** [comment]
Mh... seems like the test is just skipped now.

Follow-up PR: https://github.com/os-autoinst/openQA/pull/1676

**Pull request closed without merging**
