### PR TITLE
Fix filter for running jobs in test overview

### PR DESCRIPTION
**Pull request by Martchus**
Fix https://progress.opensuse.org/issues/13640

### CODE REVIEW

**Comment by okurz** [comment]
LGTM

A proper change would be to include a check box row for state

**Comment by aaannz** [comment]
I'm too for using `state` and keep filtering for running.

**Comment by Martchus** [comment]
Included an extra check box row for the state, also added missing results.

**Comment by Martchus** [comment]
Added another commit for showing results/states dynamically like @okurz proposed.

**Comment by okurz** [comment]
LGTM

**Comment by aaannz** [comment]
Hmm.. Tried it for a while and there are few things that bother me:
* the overall summary is calculated only for filtered jobs - ie you filter out only scheduled and the title bar is green even thou build overall has some failures
* there is no other indication filtering is active apart selected checkbox at the bottom of the page. What about add something like 'filtered by state: .. result: ..' to the overall summary bar?
* I would like to avoid the need to click on apply, but in that case the filter box should be somewhere on the  top so it doesn't scroll out of the screen when clicking on state/result to filter for.

**Comment by Martchus** [comment]
- I decided to put the filters at the bottom of the page because I didn't want use too much space before the actual information.
- I can add a summary for the current filter at the top of the page. I can also add a link for scrolling at the bottom when we keep the filter box at the bottom.
- I think having to apply explicitly makes sense. Otherwise every time the user clicks a checkbox the page must reload which is more annoying in my opinion.

**Comment by okurz** [comment]
I agree with point 1 and 2 of @aaannz but not point 3 about "apply" with same reasoning as given by @Martchus . This is also what redmine does. That would be different if the checkbox selection would only alter the rendering w/o a new query and computation.

I recommend to accept the PR when it's ok to merge to fix something and continue discussion in a progress ticket for feature requests.

@Martchus I guess we don't have a ticket for this specific case but because you want to create new tickets anyway please also add one for that purpose, include proposals and ideas by you, me and @aaannz and link the ticket to other related ones

**Comment by aaannz** [comment]
>*  I can add a summary for the current filter at the top of the page. I can also add a link for scrolling at the bottom when we keep the filter box at the bottom.

Please do this and I'll be happy to merge.

**Comment by Martchus** [comment]
I moved the filter to the top, made it expandable/collapsible the currently present filter is displayed.

**Comment by aaannz** [comment]
Yep, this looks good. Thanks :+1:

**Comment by aaannz** [comment]
You still need to adapt tests.

**Comment by Martchus** [comment]
Fixed the tests, but wait with merging because @okurz found another bug.

**Comment by Martchus** [comment]
Ok, this should be fixed now, too.

**Comment by okurz** [comment]
LGTM

@aaannz tests look fine, too, merge it?

**Pull request merged**
