### PR TITLE
softfail + javascript cleanup

### PR DESCRIPTION
**Pull request by okurz**
* Delete w/s at EOL in javascript files
* Use space indendation consistently in javascript files
* Ensure consistent naming of 'failed'+'softfailed' in all occurrences
* Correct 'softfailed' reference to passed (obsoleted)

### CODE REVIEW

**Comment by okurz** [comment]
@Martchus it's a start, more will come eventually

**Comment by okurz** [comment]
check failure `Could not find input asset "https://raw.githubusercontent.com/twbs/bootstrap-sass/5d6b2ebba0c2a5885ce2f0e01e9218db3d3b5e47/assets/javascripts/bootstrap.js"` is probably not because of changes in this PR, I can't request a restart of the travis job

**Comment by coolo** [comment]
just put some real fix in your branch and it will restart

**Comment by Martchus** [comment]
@okurz Ok, I use the first 2 commits of this PR as basis for my further cleanup of the special handling of soft-failures with failing modules.

**Pull request merged**
