### PR TITLE
Add notice in needle editor about exclude areas not taken over

### PR DESCRIPTION
**Pull request by okurz**
openqa_notice_for_take_matches

### CODE REVIEW

**Comment by coolo** [comment]
Nah, this is not supposed to stay

**Comment by okurz** [comment]
It is a short term fix. Also, instead of creating a ticket I wanted to open a PR which has at least some value but also serves as the "issue" on which we track.

**Comment by coolo** [comment]
whatever the value of *that* is.

**Comment by okurz** [comment]
*sigh*, informing the user about a caveat

**Comment by sysrich** [comment]
@okurz @coolo safe to close?

**Comment by coolo** [comment]
it's seen a TODO item

**Comment by okurz** [comment]
rebased

@sysrich @coolo do you have any better reasonable suggestions?

**Comment by coolo** [comment]
my suggestion is asking @Martchus to do fix it for real - oh, already done :)

**Comment by okurz** [comment]
I know, you think we couldn't have made use of this notice in the mean time?

**Comment by coolo** [comment]
right. I've seen too many fake fixes stop people from working on the real fix

**Pull request closed without merging**
