### PR TITLE
Fix test result info spacing

### PR DESCRIPTION
**Pull request by asdil12**
Apply the same spacing for every result type.

### CODE REVIEW

**Comment by coolo** [comment]
I'm missing a why here. I don't even understand *what* you're fixing, leave alone why

**Comment by asdil12** [comment]
On https://openqa.opensuse.org/tests there is a space between the stars and the following number.
But the space is missing between the green star and the chained-dependency icon.

**Comment by coolo** [comment]
Now put that in your commit log

**Comment by asdil12** [comment]
Done.

**Pull request merged**
