### PR TITLE
Allow git for os-autoinst:d29266f

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by coolo** [comment]
does it work?

**Comment by okurz** [comment]
How can I test?

**Comment by coolo** [comment]
enable appamor on lord?

**Comment by okurz** [comment]
+changing paths in apparmor profile to point to local working copy of openQA, oh well …

**Comment by okurz** [comment]
tested by installing `/etc/apparmor.d/usr.share.openqa.script.worker` and adjusting to catch local working copy scripts. Called `sha1sum` and `git` within isotovideo

before:
```
Can't exec "sha1sum": Permission denied at …
```

after:
```
sha1sum b1086cf53fc03f22e528c5ac4a9499be8defbe00 * …
```

**Pull request merged**
