### PR TITLE
Update GettingStarted for some Fedora repo changes

### PR DESCRIPTION
**Pull request by AdamWill**
We changed the Fedora repos around a bit recently, update the
docs for this. We should have a PR to update the Docker bits
coming soonish.

### CODE REVIEW

**Comment by okurz** [comment]
LGTM

**Comment by AdamWill** [comment]
sticker on keyboard: This Documentation Kills Code Coverage

**Comment by Martchus** [comment]
I'm not sure what you are trying to achieve and your comment doesn't seem to relate to the changes of the PR.

**Comment by krystian-hebel** [comment]
I'm trying to follow list of commands modified by this PR:

```sh
cd /var/lib/openqa/share/tests
mkdir fedora
cd fedora
git clone https://bitbucket.org/rajcze/openqa_fedora_tools.git
git clone https://pagure.io/fedora-qa/os-autoinst-distri-fedora.git
./templates --clean                             # <-- this file doesn't exist!
cd ..
chown -R geekotest fedora/
```

**Comment by Martchus** [comment]
Ok, then this is kind of out of scope for me as I am working on the openSUSE-side of things. Most likely the documentation on https://pagure.io/fedora-qa/os-autoinst-distri-fedora/tree/main is more current and the section "FIF template format" looks particularly relevant.

From an openQA upstream point of view I think we have two options with this documentation:

1. @AdamWill updates it.
2. We remove the concrete commands and only refer to https://pagure.io/fedora-qa/os-autoinst-distri-fedora which provides a more up-to-date documentation we probably shouldn't duplicate anyway.

Probably option 2. makes more sense.

**Comment by krystian-hebel** [comment]
Great, thanks for the pointers. It is a pity that such a great tool is so difficult to get started with.

**Comment by krystian-hebel** [comment]
I wanted to test anything known to be working before adding our own stuff, I tried with `/var/lib/openqa/share/tests/opensuse/products/opensuse/templates` which failed, and then decided to give Fedora a try, getting stuck on commands mentioned previously.

I ended up cloning one of the tests from https://openqa.opensuse.org/ which worked, so I'm assuming that openQA has been set up sufficiently, so my only issue is with the documentation. As you noticed, it may be partially be caused by duplicated and somewhat outdated content.

**Comment by perlpunk** [comment]
Have you tried https://github.com/os-autoinst/os-autoinst-distri-example ?

**Comment by krystian-hebel** [comment]
I believe I did as `Create.../Example test` from GUI.

**Comment by AdamWill** [comment]
Sorry, I didn't remember we had this in the upstream documentation so didn't update it when we changed how we handle templates a while back. For the current way to load Fedora templates see "FIF template format" in the readme at https://pagure.io/fedora-qa/os-autoinst-distri-fedora .

Dealing with the test distri is definitely one of the more intimidating parts of onboarding to openQA, I agree. As @perlpunk says, it's definitely a good idea to start with a much smaller "toy" implementation like os-autoinst-distri-example than any of the large real-world distris, as they inevitably get rather complex over time.

**Comment by AdamWill** [comment]
oh, one perhaps unexpected thing about openQA: you don't actually need templates to be loaded to be able to clone a test. As long as the test distri is *present* in the appropriate place, cloning will work. To openQA, all a test really *is* in the end is the list of settings variables you see on the `Settings` tab in the web UI; the template system is "just" a mechanism for creating a bunch of different "lists of variables" in response to a trigger. In theory you could replace it with some entirely different mechanism, if you wanted, and just POST jobs as "lists of variables" to the `/jobs` API endpoint. Just a side note, don't let it distract you. :D

**Pull request merged**
