### PR TITLE
Add anchor for build results on index page

### PR DESCRIPTION
**Pull request by okurz**
Allows easier direct linking for dashboard displays.

### CODE REVIEW

**Comment by coolo** [comment]
that's not an anchor, that's an id. And not a really good one either

**Comment by okurz** [comment]
it works as an anchor or am I using wrong words here? Can you please be more constructive?

**Comment by coolo** [comment]
this is what an anchor looks like:

```
<a name="anchor"></a>

**Comment by okurz** [comment]
So I only updated commit message and PR description now. The feature still works as intended, e.g. http://localhost:9526#build-results

**Comment by Soulofdestiny** [comment]
Doesn't work for me ;)

**Comment by coolo** [comment]
For me neither

**Comment by coolo** [comment]
Even if it does, if you need this you clearly should work on the 'move documentation links out of the jumpatron' issue instead

**Comment by okurz** [comment]
wtf? not working for you? see 
gifrecord_2017-03-22_232659

**Comment by coolo** [comment]
you might have a different localhost then

**Comment by okurz** [comment]
so, anything I need to change here?

**Comment by coolo** [comment]
Yes, I don't want a div wrapping unindented as an anchor when an anchor would do.

**Comment by okurz** [comment]
done

**Pull request merged**
