### PR TITLE
Use textareas in test suite editor

### PR DESCRIPTION
**Pull request by Martchus**
Fix https://progress.opensuse.org/issues/14342

### CODE REVIEW

**Comment by aaannz** [comment]
I'm missing automatic text area size adjustment so that existing variables can fit in when editing.

Example:

↓

**Comment by coolo** [comment]
Not using jquery, but seems to work fine: http://jsfiddle.net/ozccdfqf/1/

**Comment by Martchus** [comment]
Ok, I'll include it.

**Comment by coolo** [comment]
something went wrong. The textarea shrinks once you type

**Comment by okurz** [comment]
Does this change mean that there is less validity checking done as one could write stupid things like

```
FOO=BAR BAZ=BLUB
meeeh
```

?

**Comment by coolo** [comment]
https://github.com/os-autoinst/openQA/pull/961/files#diff-990880ea5fac659da08d7487e5af6273R230 is in the +

**Pull request merged**
