### PR TITLE
Simplify the src view and remove no longer necessary includes

### PR DESCRIPTION
**Pull request by coolo**

### CODE REVIEW

**Comment by okurz** [comment]
every commit that has an "and" in its subject line wants to be more than just *one* commit

**Comment by coolo** [comment]
yeah, possibly. But I don't believe in free will of commits. I'm more with the thought model of Fichte with this. Every commit is just the shadow of the thoughts of its commiters.

**Comment by coolo** [comment]
And the screen is now *very* simple - but we can add on top of that

screencapture-gertrude-suse-de-3000-tests-346493-modules-welcome-steps-2-src-1465458524525

**Comment by coolo** [comment]
There are seveal ideas floating around for it, e.g. https://progress.opensuse.org/issues/8084

**Comment by okurz** [comment]
+1

**Comment by coolo** [comment]
For some strange reason the needle editor is stuck on travis, but works fine locally

**Comment by okurz** [comment]
I also encountered sporadic fails of the needle editor test even before, e.g. after your last changes on the needle editor. I think you should try to call the test sometimes more. Probably some `sleep 1` is a problem ;-)

**Comment by okurz** [comment]
yay … uh, what? are you sure you didn't loose anything? can you reorder?

**Comment by coolo** [comment]
I split this into 3 - this one here will be rebased once the other 2 are in. I'm curious about the coverage drop myself

**Comment by coolo** [comment]
```
@@ -1,15 +1,15 @@
 .../_common/deploy/_any/21-seeds.pl  100.0    n/a    n/a  100.0    0.0  100.0
 ...36-37/02-convert_audit_toJSON.pl  100.0    n/a    n/a  100.0    0.0  100.0
-lib/DBIx/Class/Timestamps.pm         100.0    n/a    n/a  100.0    7.9  100.0
+lib/DBIx/Class/Timestamps.pm         100.0    n/a    n/a  100.0    8.0  100.0
 lib/OpenQA.pm                         36.7    0.0    n/a   66.6    0.0   36.3
 lib/OpenQA/Client.pm                 100.0   72.2   50.0  100.0    0.4   89.6
 lib/OpenQA/IPC.pm                     45.5   12.5   33.3   54.5    0.7   40.3
 lib/OpenQA/Scheduler.pm               63.9   35.7   16.6   59.4    0.2   58.9
 lib/OpenQA/Scheduler/Locks.pm         90.9   64.7   44.4  100.0    0.5   79.4
 lib/OpenQA/Scheduler/Scheduler.pm     94.4   80.3   61.9   96.0    0.9   89.2
-lib/OpenQA/Schema.pm                 100.0   72.2   80.0  100.0    4.0   94.8
-lib/OpenQA/Utils.pm                   79.6   62.5   57.6   87.8    3.0   75.2
-lib/OpenQA/WebAPI.pm                  86.6   47.2   56.0   76.6    1.7   80.5
+lib/OpenQA/Schema.pm                 100.0   72.2   80.0  100.0    4.1   94.8
+lib/OpenQA/Utils.pm                   78.8   60.9   57.6   87.5    3.0   74.2
+lib/OpenQA/WebAPI.pm                  86.6   47.2   56.0   76.6    1.5   80.5
 lib/OpenQA/WebAPI/AssetPipe.pm        96.0   83.3    n/a  100.0    0.8   94.2
 lib/OpenQA/WebAPI/Auth/Fake.pm       100.0    n/a   75.0  100.0    1.2   97.0
 lib/OpenQA/WebAPI/Auth/OpenID.pm      16.2    0.0    0.0   30.7    1.2   13.1
@@ -25,7 +25,7 @@
 ...ebAPI/Controller/API/V1/Table.pm   88.5   71.8   83.3   83.3    1.4   85.2
 ...bAPI/Controller/API/V1/Worker.pm   93.0   77.7    n/a   90.0    1.5   90.0
 ...WebAPI/Controller/Admin/Asset.pm  100.0    n/a    n/a  100.0    1.3  100.0
-...API/Controller/Admin/AuditLog.pm   62.1   16.6    n/a   71.4    1.3   58.0
+...API/Controller/Admin/AuditLog.pm   62.1   16.6    n/a   71.4    1.4   58.0
 ...API/Controller/Admin/JobGroup.pm   92.6   66.6   50.0  100.0    1.3   89.0
 .../Controller/Admin/JobTemplate.pm  100.0    n/a    n/a  100.0    1.3  100.0
 ...bAPI/Controller/Admin/Machine.pm  100.0    n/a    n/a  100.0    1.3  100.0
@@ -36,27 +36,27 @@
 .../WebAPI/Controller/Admin/User.pm   95.6   83.3  100.0  100.0    1.3   94.1
 ...bAPI/Controller/Admin/Workers.pm  100.0  100.0    n/a  100.0    1.3  100.0
 ...enQA/WebAPI/Controller/ApiKey.pm  100.0  100.0  100.0  100.0    1.1  100.0
-...OpenQA/WebAPI/Controller/File.pm   96.1   69.4   63.1  100.0    1.1   87.5
+...OpenQA/WebAPI/Controller/File.pm   96.1   69.4   68.4  100.0    1.1   88.1
 ...OpenQA/WebAPI/Controller/Main.pm   94.3   72.0   79.1  100.0    1.2   88.1
 ...nQA/WebAPI/Controller/Running.pm   18.3    0.0    0.0   40.0    1.2   14.7
 ...nQA/WebAPI/Controller/Session.pm   61.5   50.0   66.6   78.5    1.2   60.8
-...OpenQA/WebAPI/Controller/Step.pm   66.4   39.1   32.2   86.3    1.2   56.6
+...OpenQA/WebAPI/Controller/Step.pm   63.1   36.9   29.0   81.8    1.2   53.6
 ...OpenQA/WebAPI/Controller/Test.pm   97.8   75.5   56.4  100.0    1.3   90.1
 ...OpenQA/WebAPI/Plugin/AuditLog.pm  100.0    n/a    n/a  100.0    1.3  100.0
 lib/OpenQA/WebAPI/Plugin/CSRF.pm     100.0   66.6   33.3  100.0    1.3   91.6
 lib/OpenQA/WebAPI/Plugin/Fedmsg.pm   100.0   50.0   57.1  100.0    1.3   86.4
 lib/OpenQA/WebAPI/Plugin/Gru.pm       96.0   75.0   50.0  100.0    1.3   88.6
-...QA/WebAPI/Plugin/HashedParams.pm   85.7   50.0    n/a  100.0    1.2   78.9
+...QA/WebAPI/Plugin/HashedParams.pm   85.7   50.0    n/a  100.0    1.3   78.9
 lib/OpenQA/WebAPI/Plugin/Helpers.pm   92.8   75.8   67.6  100.0    1.4   86.1
 lib/OpenQA/WebAPI/Plugin/REST.pm      97.2   75.0   33.3  100.0    3.7   91.2
 lib/OpenQA/WebSockets.pm              89.4   50.0   33.3   90.9    0.1   85.1
 lib/OpenQA/WebSockets/Server.pm       29.2   14.2   31.5   52.6    0.4   28.5
-lib/OpenQA/Worker.pm                  61.2    0.0    0.0   71.4    0.4   54.0
+lib/OpenQA/Worker.pm                  61.2    0.0    0.0   71.4    0.3   54.0
 lib/OpenQA/Worker/Commands.pm         18.1    0.0    n/a   80.0    0.5   10.6
-lib/OpenQA/Worker/Common.pm           15.8    0.0    0.0   42.3    0.5   12.0
+lib/OpenQA/Worker/Common.pm           15.8    0.0    0.0   42.3    0.4   12.0
 ...nQA/Worker/Engines/isotovideo.pm   18.1    0.0    0.0   61.5    1.1   15.3
-lib/OpenQA/Worker/Jobs.pm             12.6    0.0    0.0   40.0    0.5   10.2
+lib/OpenQA/Worker/Jobs.pm             12.6    0.0    0.0   40.0    0.4   10.2
 lib/OpenQA/Worker/Pool.pm             40.0    0.0    n/a   66.6    0.5   32.4
-lib/db_helpers.pm                    100.0   50.0   80.0  100.0   21.0   88.6
+lib/db_helpers.pm                    100.0   50.0   80.0  100.0   20.9   88.6
 lib/db_profiler.pm                   100.0    n/a    n/a  100.0    0.0  100.0
-Total                                 70.1   44.6   41.7   78.5  100.0   63.7
+Total                                 69.9   44.3   41.6   78.3  100.0   63.5
```

**Comment by coolo** [comment]
The main drop is in 
-...OpenQA/WebAPI/Controller/Step.pm   66.4   39.1   32.2   86.3    1.2   56.6
+...OpenQA/WebAPI/Controller/Step.pm   63.1   36.9   29.0   81.8    1.2   53.6

**Comment by okurz** [comment]
looks good

**Comment by coolo** [comment]
coveralls seems tired of me rebasing ;)

**Pull request merged**
