### PR TITLE
Install qemu-uefi-aarch64 on aarch64 in bootstrap

### PR DESCRIPTION
**Pull request by asdil12**
Related: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/7505

### CODE REVIEW

**Comment by ggardet** [comment]
LGTM, but is CPU env always defined?

**Comment by asdil12** [comment]
> LGTM, but is CPU env always defined?

It was set in every case that I tried. Even when using a shell of type login.

It is set in `/etc/profile`:

```bash
if test -x /bin/uname ; then
    test -z "$HOST" && HOST=`/bin/uname -n`
    test "$HOST" = "localhost" && HOST=`/bin/uname -n`
    test -z "$CPU"  &&  CPU=`/bin/uname -m`
fi
```

**Comment by asdil12** [comment]
But I just checked and it seems to be a suse specific modification, so I'll change it to `uname -m`.

**Comment by ggardet** [comment]
> But I just checked and it seems to be a suse specific modification, so I'll change it to `uname -m`.

It looks like more generic. Thanks!

**Pull request merged**
