### PR TITLE
worker: Remove tons of work arounds and quirks in upload

### PR DESCRIPTION
**Pull request by coolo**
Just use blocking post - possibly all this was necessary with mojo < 7, but
surely not in current:

http://mojolicious.org/perldoc/Mojolicious/Guides/Cookbook#Large-file-upload

### CODE REVIEW

**Comment by okurz** [comment]
LGTM

**Comment by coolo** [comment]
the coverage increase is fake - I just replaced uncovered code  :)

**Comment by okurz** [comment]
Finally not deleting covered code ;-P

**Comment by coolo** [comment]
I implemented a chksum check - verify link: https://tortuga.suse.de/tests/427#downloads

See the log:
```
uploading test.qcow2
Checksum 3644698332:3644698332 Sizes:1041956864:1041956864
```

Hopefully we can find out the root problem with this - uploading works 100% on my staging instance ;(

**Comment by coolo** [comment]
I applied the patch on 4 workers on openqa.opensuse.org and we didn't see a single failure since then ;(

So I claim f2547e9bcc0a166f993426bceeacd00179116716 is the actual fix - but to prove that we would need to have the two other commits run independent of it.

**Comment by okurz** [comment]
could very well be. LGTM

**Comment by okurz** [comment]
we have this deployed on osd as well as my change to not always auto-duplicate and we see problems saving and uploading images, e.g.
https://openqa.suse.de/tests/522357/file/autoinst-log.txt
https://openqa.suse.de/tests/522368/file/autoinst-log.txt
https://openqa.suse.de/tests/522432/file/autoinst-log.txt

**Comment by aaannz** [comment]
I think this is exactly what @nadvornik was solving by that removed hacks. :)

**Comment by nadvornik** [comment]
I just checked the new Mojo. The default boundary calculation is still the same: Mojo generates a random string and then checks if the file contains it - that means the file is completely read from disk before sending anything. It can take up to several minutes and the server closes the connection meanwhile.

So I think the boundary hack is still needed.

**Comment by nadvornik** [comment]
Maybe the most correct solution is to split the file to ~16MB chunks and upload each in separate request.

**Comment by okurz** [comment]
some of the stuff coolo applied certainly make sense. What he failed to do is reproduce the error first locally to confirm that his "fix" is really a fix. OTOH http://mojolicious.org/perldoc/Mojolicious/Guides/Cookbook#Large-file-upload should still apply. Maybe the images we are handling are still a bit too big and 16MB might make sense.

Maybe these references can help:
* http://mojolicious.org/perldoc/Mojolicious/Guides/Cookbook#Large-file-upload
* http://mojolicious.org/perldoc/Mojolicious/Guides/Tutorial#File-uploads
* https://groups.google.com/forum/#!topic/mojolicious/r8QortTol_A

**Comment by nadvornik** [comment]
This concrete problem is mentioned here:
https://groups.google.com/forum/#!topic/mojolicious/6DNYc3nKAvA/discussion

The official mojo documentation speaks about large files in size of megabytes, we need gigabytes.

I don't see any way how to override the boundary calculation in ua->post() api.

**Comment by okurz** [comment]
I am pretty sure in perl everything can be monkey patched :-)

**Comment by nadvornik** [comment]
See https://github.com/os-autoinst/openQA/pull/843

**Pull request merged**
