### PR TITLE
Make message about clone error unique

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by okurz** [comment]
Considering https://progress.opensuse.org/issues/70720#note-8 I have excluded the second commit for now. So only the part about making the strings unique is relevant now.

**Review by ilausuch — APPROVED** [review]

**Review by Martchus — CHANGES_REQUESTED** [review]
When using the restart API this message is returned as `{"error":"…"}` and the context is quite clear. When using the web UI there's already the prefix "Errors occurred when restarting jobs:" so the context is also quite clear. (Restart and clone have the same meaning. Maybe we should streamline this to use only one term but that's a different issue.)

So this change seems unnecessary and leads to weirdly duplicating the prefix when using the web UI. It also seems inconsistent to add the "Unable to clone:" prefix only in this specific case although it would fit before any error possibly returned by the restart/clone route.

**Comment by okurz** [comment]
Yeah, duplicating the context is also not good. My goal was simply to not use the very same string in two cases which are actually slightly different. This way one is also not getting confused if the message shows up and one calls `git grep` on the source code. Do you have a suggestion how I could phrase differently one of the two occurences of the old string?

**Comment by Martchus** [comment]
I initially chose the same phrasing for consistency because for the user it makes no difference which internal check throws the exception. The first check (directly within `duplicate`) is just a shortcut so we don't need to compute the whole cluster when there's already a clone of the directly specified job. I'm also wondering how this distinction would be useful for our own debugging.

But if you really want different messages, I would actually change the one directly in duplicate from `"Job $orig_id has already been cloned as $clone_id"` to `"Specified job $orig_id has already been cloned as $clone_id"` because this message is really always about the specified job and never about a dependent job. (The message in `_create_clone` can be about both.)

**Review by Martchus — APPROVED** [review]

**Pull request merged**
