### PR TITLE
Dependency cron 2022-05-01

### PR DESCRIPTION
**Pull request by openqabot**

### CODE REVIEW

**Comment by okurz** [comment]
Fails with

```
    #   Failed test 'No tests run for subtest "OAuth provider does not provide all mandatory user details"'
    #   at t/03-auth.t line 115.
    # Looks like you failed 1 test of 8.
[02:25:35] t/03-auth.t ............................................... 6/? 
#   Failed test 'OAuth2'
#   at t/03-auth.t line 125.
A response has already been rendered at /usr/lib/perl5/vendor_perl/5.26.1/Mojolicious/Controller.pm line 154.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 7.
```

that's due to the recent mojo update in https://github.com/mojolicious/mojo/commit/cd6627de4d7fed9d0e08b2a137ed5731eda59c51

@kraih would you have a quick fix ready?

**Comment by kraih** [comment]
> @kraih would you have a quick fix ready?

Looking into it, i already have a suspicion.

**Comment by okurz** [comment]
should be fixed by your PR https://github.com/os-autoinst/openQA/pull/4632

**Comment by perlpunk** [comment]
@mergifyio rebase

**Review by okurz — APPROVED** [review]

**Review by kraih — APPROVED** [review]

**Review by perlpunk — APPROVED** [review]

**Pull request merged**
