### PR TITLE
Fix a small mistake where "if (%foo" was used instead of "if (keys %foo"

### PR DESCRIPTION
**Pull request by kraih**
Probably not a fix for the actual issue. But a small mistake i saw while reading the code.

Progress: https://progress.opensuse.org/issues/94531

### CODE REVIEW

**Review by kalikiana — COMMENTED** [review]
I'm guessing we can't test this easily because this works in some of the cases?

**Comment by kraih** [comment]
While i'm at it, i've fixed a few more cases. This is just a question of good Perl style really.

**Comment by perlpunk** [comment]
Btw, the return value of `scalar %hash` changed in perl 5.26 to return the number of keys:
https://perldoc.perl.org/perl5260delta#scalar(%25hash)-return-signature-changed

What minimum perl version do we require?

**Comment by kraih** [comment]
Should be Perl 5.20 for signatures now.

**Review by okurz — APPROVED** [review]

**Review by Martchus — APPROVED** [review]

**Pull request merged**
