### PR TITLE
Allow anonymous read access to operator tables

### PR DESCRIPTION
**Pull request by Martchus**
See https://progress.opensuse.org/issues/13858

Concerning tables
* Medium types
* Machines
* Test suites
* Job groups and job templates
* Scheduled products

### CODE REVIEW

**Comment by Martchus** [comment]
I will move the menu entries back to the user menu as discussed with oliver. I also need to find out why the full stack test fails.

**Comment by Martchus** [comment]
Also here it makes only sense to continue fixing the tests when it is decided where the menu entries should go.

**Comment by Martchus** [comment]
So this is now in the user menu as oliver likes it. Previous version with extra menu is still on https://github.com/Martchus/openQA/tree/read_access_extra_menu branch, just in case.

**Comment by Martchus** [comment]
The admin test doesn't fail on my workstation with Perl 5.24.0 but on Travis:

> [12:45:46] ./t/ui/13-admin.t ................... 11/? Use of ?PATTERN? without explicit operator is deprecated at template
>	admin/job_template/index.html.ep line 6 (#1)
>    (D deprecated) You have written something like ?\w?, for a regular
>    expression that matches only once.  Starting this term directly with
>    the question mark delimiter is now deprecated, so that the question mark
>    will be available for use in new operators in the future.  Write m?\w?
>    instead, explicitly using the m operator: the question mark delimiter
>    still invokes match-once behaviour.

I tried using brackets and regular if in `templates/admin/job_template/index.html.ep` as workaround but it didn't work.

**Comment by Martchus** [comment]
I added a workaround for the failing test so I runs now with older Perl, too.

**Comment by okurz** [comment]
the test coverage decrease seems to be valid, check
https://codecov.io/gh/os-autoinst/openQA/compare/56121a418ca82cb7dbdfd2c79433364392489a0f...f2367227b132778e751eb3be08630989a2634e50/src/lib/OpenQA/WebAPI/Controller/API/V1.pm

**Comment by Martchus** [comment]
Fix for coverage decrease seems to work.

**Comment by okurz** [comment]
@Martchus please check checks again

**Comment by Martchus** [comment]
Doesn't look related. When I wrote the last comment all checks were successful. I just changed amended again to fix some strings.

**Comment by Martchus** [comment]
Rebased again and all checks pass again. So the last failure was indeed unrelated.

**Pull request merged**
