### PR TITLE
replace multiple DB queries by single one

### PR DESCRIPTION
**Pull request by aaannz**
- avoid 500 variables sqlite limit (issue#421) in dependency query

### CODE REVIEW

**Comment by coolo** [comment]
is this the reason openqa.suse.de/tests times out now? :)

**Comment by aaannz** [comment]
I thought so, but:
1) I took openqa.s.d DB and used in my test machine and was unable to replicate
2) from the log it never make it to list_ajax call and querying it manually on openqa.s.d finished in 16s (then I created #424 and lowered it to 4s)
3) @sysrich queried  Pg server and it stuck on some COUNT(*) query, but I was not able to find original source of it.

**Comment by coolo** [comment]
funny how you make 4s sound like a success :)

I spent a lot of time in march to optimize the lists_ajax call to go from 4s to 0.8s - see 9731d4170633be7a82bdfc7917d6b3b522a5171d

**Comment by coolo** [comment]
I can't reproduce locally either - the COUNT takes 0.11s here

**Comment by coolo** [comment]
the COUNT is https://github.com/os-autoinst/openQA/blob/master/templates/test/list.html.ep#L27 - and locally it shows 500 there while on openqa.suse.de it runs this query:

http://paste.opensuse.org/54799951

**Comment by coolo** [comment]
I wonder if we're victim of http://www.targeted.org/articles/databases/fragmentation.html

**Comment by aaannz** [comment]
I didn't benched the original impl. on my test machine, but 4s is on C2D E8400. The diff between original and fixed by #424 is not so big. :)
But yeah, there should be a comment `#don't touch this, it's optimal` :)

**Comment by coolo** [comment]
your patch is not the problem we see. I reverted the patch locally and it's still broken

**Pull request merged**
