### PR TITLE
Update Installing.asciidoc

### PR DESCRIPTION
**Pull request by Frogrhino**
Added a grey box for the systemctl command in line 367, to make it more clear.
Highlighted all the directory paths or other important information.

### CODE REVIEW

**Comment by Martchus** [comment]
So you're basically replacing the `+` syntax with markdown syntax. It looks indeed better on GitHub (when I remember correctly it ignored the `+` syntax). That's it, right? If not, please split it into multiple commits. It isn't clear to me what you mean with your commit message. Which gray box? You're just talking about styling text as code, right?

And we should check what the generator for the documentation under open.qa makes out of it.

**Comment by Frogrhino** [comment]
Yes, it is only replacing the + syntax with markdown syntax.
Yes, I mean just the styling.
I will test the generator tomorrow.

**Comment by okurz** [comment]
This goes a bit far changing the overall style. I recommend for now to focus on the single occurence of the worker service start command. If you want to change the use of `+` we should do it in all documents however and not just in one. I vaguely remember us changing that style in the not too distant path but could not find a commit, maybe it was in os-autoinst.

**Comment by Frogrhino** [comment]
I close it for now and will commit just the single styling change.

**Pull request closed without merging**
