### PR TITLE
Websocket: wrap database transactions in try catch so we can debug dbus service errors

### PR DESCRIPTION
**Pull request by mudler**
Avoids unpleasant situations were the websocket server might be under
load and bail out - actually stopping the service entirely.

Wrap also dead job detection in a database transaction.

Even tho we observed that auto_duplicate in production caused the timer
to kill completely the dbus service, in this commit we won't disable it
until we can confirm it's the root of the problem. (production instance was hotpatched disabling it)

Important: we need to depend on new Net::DBus 1.1

Update:
Dbus is still heavly loaded from the websocket side - but we recover from errors - and sometime we loose messages, this comes from webui as well:

> [Fri Aug 18 12:22:58 2017] [18259:error] org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply time
> out expired, or the network connection was broken.
> [Fri Aug 18 12:22:58 2017] [16519:error] org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply time
> out expired, or the network connection was broken.
> [Fri Aug 18 12:22:58 2017] [17189:error] org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply time
> out expired, or the network connection was broken.

there is a huge DoS coming on from websocket server - possibly caused  by worker  that increments their timers ( see https://github.com/os-autoinst/openQA/pull/1432 ).

In osd, to have a temporary workaround against denied mutex lock (https://progress.opensuse.org/issues/23320) we use this configuration:

> systemctl edit openqa-scheduler
> cat /etc/systemd/system/openqa-scheduler.service.d/override.conf 
> [Service]
> Environment="OPENQA_SCHEDULER_MAX_BACKOFF=120000"
> Environment="OPENQA_SCHEDULER_CAPTURE_LOOP_AVOIDANCE=520000"

Not a single dbus error message so far since the configuration update  - i suggest to bump it even more to decrease websocket load (at least from the scheduler side) until we control the load generated from the workers

### CODE REVIEW

**Comment by okurz** [comment]
> Important: we need to depend on new Net::DBus 1.1

easy for you to say ;-) You need to specify that version requirement in `cpanfile` then.

But

```
$ osc se --version perl-Net-DBus
####################################################################
matches for 'perl-Net-DBus' in packages:

# Project                            # Package      # Ver   Rev  Srcmd5
SUSE:SLE-12:GA                       perl-Net-DBus  1.0.0   1    72aa8b7c31e8f7ed0ce2df726f86d14b
openSUSE:Factory                     perl-Net-DBus  1.1.0   14   dda084ce4a4cfcf8cfdb49723896cad6
openSUSE:Leap:42.2                   perl-Net-DBus  1.0.0   5    72aa8b7c31e8f7ed0ce2df726f86d14b
openSUSE:Leap:42.3                   perl-Net-DBus  1.0.0   6    72aa8b7c31e8f7ed0ce2df726f86d14b
```

i.e. how about making sure that we have updated packages first in current SLE and Leap with maintenance updates?

**Comment by mudler** [comment]
@okurz i perfectly know that needs to be in the cpanfile (i already touched it few times..). And exactly  for that reason yesterday, before leaving the office - i just added it in the comment, because needs investigation on the packaging side since we already offer Net-DBus 1.1 in openQA repos - this PR is for reference regarding the hotpatch.

**Comment by okurz** [comment]
I see. Sorry, did not want to doubt you knowing about cpanfile more than me of course. Sure, the PR makes sense in general I just wanted to make sure we have the same picture regarding the prerequisities

**Comment by mudler** [comment]
i guess i've just failed missing details in the PR message ;)

**Pull request merged**
