### PR TITLE
Treat ASSIGNED state as in execution

### PR DESCRIPTION
**Pull request by mudler**
Add `ASSIGNED` state inside `EXECUTION_STATES,` allowing the job to be
restarted when stuck

So it will look like:

2017-09-07-113212_5760x1200_scrot

See related Progress issue: https://progress.opensuse.org/issues/23378

### CODE REVIEW

**Comment by coolo** [comment]
while you are at, also change running.js to poll assigned jobs :)

**Comment by mudler** [comment]
@coolo i would, but i'm not sure about js too much, afaics https://github.com/os-autoinst/openQA/blob/master/assets/javascripts/running.js#L17 should already handle it, no?

**Comment by coolo** [comment]
that function is not called as:
```
  if (state == "running" || state == "waiting" || state == "uploading") {
    setupRunning(jobid, status_url, details_url);
  }

**Comment by mudler** [comment]
Closing, superseeded by https://github.com/os-autoinst/openQA/pull/1446

**Comment by foursixnine** [comment]
Reopening due to #1446 not being done yet

**Comment by foursixnine** [comment]
I don't get the unexpected coverage change thing

**Comment by mudler** [comment]
Current coverage is low due to a fail CI - https://codecov.io/gh/os-autoinst/openQA

**Pull request merged**
