### PR TITLE
Increase the inactivity timeout for workers and running jobs

### PR DESCRIPTION
**Pull request by Martchus**
from 2 minutes to 2 days.

See https://progress.opensuse.org/issues/60866 and discussion in Rocket Chat.

### CODE REVIEW

**Comment by okurz** [comment]
I consider git commit messages which just link to an internal, secret chat and just a ticket as not so nice. Please describe in the git commit message the reasoning behind the change. I consider 2 days excessive, or does this have to be longer than any expected test run time? Also, the git commit message subject line should state the benefit from users perspective. I know, we had this discussion already multiple times but please keep the changelog reader in mind.

**Comment by coolo** [comment]
I have to agree, the commit log is not helpful

**Comment by Martchus** [comment]
I added the note about the chat only in the GitHub comment. I've just made the commit message a little bit more detailed.

**Comment by okurz** [comment]
> I have to agree, the commit log is not helpful

this is not what I said. You like to twist my words, I know that :)

The changelog as we have it is helpful for me doing the administration so far.

**Comment by Martchus** [comment]
> A test would be cool.

There are already tests for that variable (which I adapted). Not sure whether it is worth the effort to make this configurable. Maybe we decide to throw out the whole thing completely. We could also just hot-patch one of the production instances.

**Comment by okurz** [comment]
I already hotpatched osd from 2m to 15m.

I meant tests for the issue we want to fix.

**Comment by okurz** [comment]
@Martchus as apparently I am not the only one asking where "2d" comes frome please clarify the selection in the git commit message.

**Comment by Martchus** [comment]
In the ticket I proposed 15 min. In the chat @coolo mentioned I should give it a shot but increase it to 2 days. So that's basically what I did. There's no good explanation why it should be exactly 2 days but that number isn't less arbitrary than the number we had before.

**Comment by kalikiana** [comment]
> In the ticket I proposed 15 min. In the chat @coolo mentioned I should give it a shot but increase it to 2 days. So that's basically what I did. There's no good explanation why it should be exactly 2 days but that number isn't less arbitrary than the number we had before.

Thanks for clarifying. So that might be an argument in favor of making it configurable? Since we might need to try out what works best?

**Pull request merged**
