### PR TITLE
Prevent excessive git logs by using log_trace

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by okurz** [comment]
@perlpunk like this?

**Comment by perlpunk** [comment]
No, as I said we still should debug stderr IMHO. Otherwise it would have been very easy of course.

**Comment by Martchus** [comment]
I'm also not sure whether it makes sense to basically disable and error logging from Git. And just passing `1` as parameter isn't so nice. Maybe it makes more sense to pass the actual log level here.

**Comment by okurz** [comment]
> No, as I said we still should debug stderr IMHO. Otherwise it would have been very easy of course.

ok, then I misunderstood you.

**Pull request closed without merging**
