### PR TITLE
Treat #details tab as all the others to fix back button

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by okurz** [comment]
obsoleting #755

**Comment by okurz** [comment]
@coolo if you have a better proposal how to "update" a PR tell me. I guess without admin rights on the repo I can't update branches so that I can not update your branch.

**Comment by coolo** [comment]
obsoleting the PR is fine IMO, but rewriting my commit is not

**Comment by coolo** [comment]
so please rebase your branch and have a commit of okurz

**Comment by okurz** [comment]
I would like to keep each commit complete by itself, including tidy up and test and fix so that also git bisect can always work. Yesterday I tried to find an issue with git bisect (why 12-needle-edit.t failed for me) and stopped because too many broken commits in between where nothing works. So how should we proceed in general? You can also cherry pick my commit on top of your branch and squash it with your commit if you prefer.

**Comment by okurz** [comment]
For the current PR I separated commits.

**Pull request merged**
