### PR TITLE
docs: Add option to disable test timeout with env variable

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by okurz** [comment]
Also see https://github.com/os-autoinst/os-autoinst-common/pull/7

**Review by perlpunk — CHANGES_REQUESTED** [review]
See https://github.com/os-autoinst/os-autoinst-common/pull/7#issuecomment-882894237

**Comment by okurz** [comment]
Updated and rebased with conflict resolution with

```
git subrepo fetch external/os-autoinst-common
git subrepo pull external/os-autoinst-common
cd .git/tmp/subrepo/external/os-autoinst-common
git checkout --theirs .
git commit
cd -
git subrepo commit external/os-autoinst-common
git push okurz -f
```

**Comment by okurz** [comment]
Updated after https://github.com/os-autoinst/os-autoinst-common/pull/7#issuecomment-882894237 is merged

**Review by Martchus — APPROVED** [review]

**Review by perlpunk — APPROVED** [review]

**Pull request merged**
