### PR TITLE
Add support for new hardware console log

### PR DESCRIPTION
**Pull request by czerw**
Enhancement poo#103903: There is new log hardware-console-log.txt file
to capture console logs on IPMI and PowerVM backends.

Related os-autoinst PR: https://github.com/os-autoinst/os-autoinst/pull/1881

### CODE REVIEW

**Review by okurz — CHANGES_REQUESTED** [review]
Needing to add a file in a manually maintained list in four places is IMHO too much. We need to find a better solution. Anyone has a good suggestion what we could do?

**Comment by Martchus** [comment]
It would make sense to simply extract the list of common log files into a variable (e.g. under utils) and use it everywhere.

Alternatively you could also just avoid the PR altogether and simply put the log under `ulogs`. When I remember correctly, files in that directory are all uploaded implicitly/automatically.

**Comment by okurz** [comment]
> Alternatively you could also just avoid the PR altogether and simply put the log under `ulogs`. When I remember correctly, files in that directory are all uploaded implicitly/automatically.

I would like that as well, yes

**Comment by czerw** [comment]
> It would make sense to simply extract the list of common log files into a variable (e.g. under utils) and use it everywhere.
> 
> Alternatively you could also just avoid the PR altogether and simply put the log under `ulogs`. When I remember correctly, files in that directory are all uploaded implicitly/automatically.

I tried that and files were ignored, placed it into `testresults/ulogs/`.

**Comment by Martchus** [comment]
It is just `ulogs/`, not `testresults/ulogs/.

**Comment by czerw** [comment]
> It is just `ulogs/`, not `testresults/ulogs/`.

Correct, thanks a lot.

**Comment by czerw** [comment]
The downside of `ulogs`: log file is within uploaded logs from SUT, not in `Result files` section, but this is not a big deal.

**Pull request closed without merging**
