### PR TITLE
Use subrepo for update-deps script

### PR DESCRIPTION
**Pull request by perlpunk**
Please see the README for info and instructions:
https://github.com/os-autoinst/os-autoinst-common/blob/master/README.md

This PR creates a subrepo at`os-autoinst-common/`
tools/update-deps is replaced with a symlink to `os-autoinst-common/tools/update-deps`.

See also https://github.com/os-autoinst/os-autoinst/pull/1512

Issue: https://progress.opensuse.org/issues/70654

### CODE REVIEW

**Comment by perlpunk** [comment]
I moved the subrepo to the top dir `os-autoinst-common/`

**Review by okurz — COMMENTED** [review]
+1

**Comment by perlpunk** [comment]
@okurz @Martchus @kalikiana @kraih please decide where you would like to have the subrepo:

1. `external/os-autoinst-common`
2. `os-autoinst-common`

Reply here with a number.

**Comment by okurz** [comment]
1

**Comment by kalikiana** [comment]
4

**Comment by Martchus** [comment]
1

**Comment by kraih** [comment]
1

**Comment by perlpunk** [comment]
Aand we have a winner! `external/os-autoinst-common`
thanks :)

**Comment by perlpunk** [comment]
I updated the directory.

**Review by Martchus — APPROVED** [review]

**Pull request merged**
