### PR TITLE
ci: Add missing dependencies

### PR DESCRIPTION
**Pull request by perlpunk**
After https://github.com/os-autoinst/openQA/pull/3536
we are missing several dependencies for os-autoinst.

### CODE REVIEW

**Review by okurz — APPROVED** [review]

**Comment by okurz** [comment]
@andrii-suse your feedback would be particularly appreciated.

**Comment by andrii-suse** [comment]
@okurz Ugh I see what went wrong with #3536 .
It built new cache on top of old ci:base image, so many packages were not included into cache, because they were not downloaded, because they were already installed.
Then ci:base was rebuilt according to Dockerfile changes, and next PR did pull updated ci:base image and tried to install the cache packages on top of it, which obviously failed.
I guess we can just introduce ci:base_v1 or ci:minimal for such purposes, instead of dealing with chicken/egg problem. :\ Then retry #3536

**Comment by okurz** [comment]
oh, I get it now :D Thanks for your analysis. I will include this hint in https://progress.opensuse.org/issues/67855 but I also wonder what do you think about the approach taken here in this PR. Do you think installing packages like this is ok in the shell script? In the end this could be like a safety net to provide dependencies if the base image and cache based package installation fails to provide all we need, right?

**Comment by andrii-suse** [comment]
I think we didn't want to rely on download.opensuse.org inside every CI test. If we set up cache properly - it should just work.
Alternatively, we can also just completely rely on download.opensuse.org and ignore content of ci-packages.txt if cache is not available.

**Comment by okurz** [comment]
yes, true. But as mentioned elsewhere the problem is already that we rely too much on download.opensuse.org, e.g. someone opens a new pull request and the cache isn't used and we fail to install packages because ci-packages.txt is referencing older versions of files that are already not existant anymore. Also registry.opensuse.org is also really much linked to download.opensuse.org so I don't know if the current approach really helps us anyway. Hm, it's complicated :)

**Pull request closed without merging**
