### PR TITLE
Use the canonical one-liner in both index and overview

### PR DESCRIPTION
**Pull request by kalikiana**
Also fix the use of paragraphs.

### CODE REVIEW

**Comment by okurz** [comment]
The two changes are something independent, better split into two commits. And before merging I think we should have the bigger idea in mind. I think we might find something better than both of the current strings. I would suggest to leave out openSUSE and also extend to "system testing". We can either discuss here or we create a ticket

**Comment by kalikiana** [comment]
> The two changes are something independent, better split into two commits. And before merging I think we should have the bigger idea in mind. I think we might find something better than both of the current strings. I would suggest to leave out openSUSE and also extend to "system testing". We can either discuss here or we create a ticket

[poo#65196](https://progress.opensuse.org/issues/65196)

**Comment by Martchus** [comment]
By the way, the commit message is just not saying at all what this is about. Not even the category is obvious (documentation change). I mean "the canonical one-liner" could not be more unclear.

But I liked the HTML change (although the HTML is not broken).

**Comment by kalikiana** [comment]
> By the way, the commit message is just not saying at all what this is about. Not even the category is obvious (documentation change). I mean "the canonical one-liner" could not be more unclear.
> 
> But I liked the HTML change (although the HTML is not broken).

I assumed docs is implied since the repo contains nothing else :wink:

**Pull request closed without merging**
