### PR TITLE
Carry over also for incomplete and softfailed

### PR DESCRIPTION
**Pull request by coolo**

### CODE REVIEW

**Comment by okurz** [comment]
can you add a test?

**Comment by coolo** [comment]
added one

**Comment by okurz** [comment]
LGTM. Thank you, makes it easier to understand the change. Albeit, we have t/17-labels_carry_over.t. Maybe just move there?

**Comment by coolo** [comment]
the problem is that 17 is a functional test, while unit tests are easier to handle for such complex functions. I don't want to add another 30 fixture jobs and suffer from the same shit that marius went through last week :)

**Comment by coolo** [comment]
travis has massive network problems ;(

**Comment by okurz** [comment]
ok, makes sense - the "unit test" part that is

**Pull request merged**
