### PR TITLE
show text results in correct order

### PR DESCRIPTION
**Pull request by nadvornik**

### CODE REVIEW

**Comment by aaannz** [comment]
LGTM

**Comment by okurz** [comment]
I don't understand where this would have an impact. What does "correct order" mean?

**Comment by aaannz** [comment]
Previously results were displayed in order: images, audio, text, independently when the results were collected during the test. With this Vladimir display them mixed in the order they actually happened.

Make sense to me, but I don't know how it will look like in UI.

**Comment by okurz** [comment]
I wouldn't mind a screenshot :-)

**Pull request merged**
