### PR TITLE
Add basic http-only config for nginx

### PR DESCRIPTION
**Pull request by nicksinger**
I use this config on my local development instance.

What works right now:
- Navigation in the webui (Login, overview page and so on)
- Register remote worker
- Cloning jobs

What does not work yet:
- ~Cloning jobs~

My instance can be seen here: http://openqa.glados.qa.suse.de

### CODE REVIEW

**Comment by Martchus** [comment]
Nice to have an example for configuring Nginx as I personally prefer it over Apache. But this is actually just a proxy configuration. What is the benefit from that beside having the TLS certificate configured in Nginx?

**Comment by sqozz** [comment]
@Martchus: simple. You don't need apache any more. The reason if this is needed of not is not to debate. This just offers developers and users a second option.
Of course we could also just let mojolicious listen to :80 of :443 directly but adding an additional, proper webserver in between is a common standard in hosting web-applications for several reasons:

- proper caching of static content (css, js and even binary blobs like isos and so on)
- no need to implement ssl support in the upstream application (openQA/mojolicious in this case)
- documentation widely available for the component facing the internetz (your application can use whatever exotic framework it desires, as long as it implements a common communication point to the webserver)
- modern technologies available from a software with developers focused for serving webcontent (nginx) while the application developers can focus on their specific use-case (e.g. developing a nice and clean web-frontend for openQA)
- several more I forgot to mention

This does not just apply to openQA but for any application someone wants to put in the internet and tries to explain your question on a more generic level than just openQA and nginx/apache

**Comment by okurz** [comment]
@sqozz how do you know so much about what @nicksinger is doing? ;)

**Comment by sqozz** [comment]
@okurz I just happen to know how webservers work :)

**Comment by nicksinger** [comment]
Hm… with the right "--host" parameter even clone_job works.

**Comment by Martchus** [comment]
> The reason if this is needed of not is not to debate.

I wasn't trying to start a debate. I was just curious about the advantages.

@nicksinger So not WIP anymore? For me it looks good to merge.

**Comment by nicksinger** [comment]
@Martchus well, technically it is not WIP anymore and I just pushed the most recent iteration of this which enables nginx users to access and work with openQA. However, the https example is missing.

I also hoped to get some more feedback on the passed headers since it is _a lot less_ then the apache config has.

**Pull request merged**
