### PR TITLE
Fix Apparmor profile: Webui needs the migrations now

### PR DESCRIPTION
**Pull request by coolo**

### CODE REVIEW

**Comment by aaannz** [comment]
I'm wondering how's that my container based testing didn't catch that? I have apparmor enabled there. Anyway LGTM

**Comment by coolo** [comment]
no idea - @soulofdestiny fell into this trap

**Comment by nilxam** [comment]
I assumed it's the same situation I have been seen in my openqa instance after updated openqa, it was throws in _try_upgrade_db(), see my log from audit and journalctl below,

audit:
type=AVC msg=audit(1459152251.603:20347): apparmor="DENIED" operation="open" profile="/usr/share/openqa/script/openqa" name="/usr/share/openqa/dbi    cdh/SQLite/upgrade/36-37/" pid=1319 comm="openqa" requested_mask="r" denied_mask="r" fsuid=479 ouid=0

journalctl:
Mar 28 16:04:09 tigercity openqa-websockets[5271]: Server available at http://localhost:9527
Mar 28 16:04:10 tigercity openqa-websockets[1318]: [Mon Mar 28 16:04:10 2016] [info] Listening at "http://localhost:9527"
Mar 28 16:04:11 tigercity openqa[1319]: Uncaught exception from user code:
Mar 28 16:04:11 tigercity openqa[1319]: Can't opendir($fh, '/usr/share/openqa/script/../dbicdh/SQLite/upgrade/36-37'): Permission denied at /usr/lib/perl5/vendor_perl/5.18.2/DBIx/Class/DeploymentHandler/DeployMethod/SQL/Translator.pm line 109
Mar 28 16:04:11 tigercity openqa[1319]: DBIx::Class::DeploymentHandler::DeployMethod::SQL::Translator::catch {...} ('autodie::exception=HASH(0x7380930)') called at /usr/lib/perl5/vendor_perl/5.18.2/Try/Tiny.pm line 104
Mar 28 16:04:11 tigercity openqa[1319]: Try::Tiny::try('CODE(0x7353570)', 'Try::Tiny::Catch=REF(0x7356c28)') called at /usr/lib/perl5/vendor_perl/5.18.2/DBIx/Class/DeploymentHandler/DeployMethod/SQL/Translator.pm line 117
Mar 28 16:04:11 tigercity openqa[1319]: DBIx::Class::DeploymentHandler::DeployMethod::SQL::Translator::__ddl_consume_with_prefix('DBIx::Class::DeploymentHandler::DeployMethod::SQL::Translator...', 'SQLite', 'ARRAY(0x7353060)', 'upgrade') called at /usr/lib/perl5/vendor_perl/5.18.2/DBIx/Class/DeploymentHandler/DeployMethod/SQL/Translator.pm line 203
Mar 28 16:04:11 tigercity openqa[1319]: DBIx::Class::DeploymentHandler::DeployMethod::SQL::Translator::_ddl_schema_upgrade_consume_filenames('DBIx::Class::DeploymentHandler::DeployMethod::SQL::Translator...', 'SQLite', 'ARRAY(0x7353060)') called at /usr/lib/perl5/vendor_perl/5.18.2/DBIx/Class/DeploymentHandler/DeployMethod/SQL/Translator.pm line 699
Mar 28 16:04:11 tigercity openqa[1319]: DBIx::Class::DeploymentHandler::DeployMethod::SQL::Translator::upgrade_single_step('DBIx::Class::DeploymentHandler::DeployMethod::SQL::Translator...', 'HASH(0x7353648)') called at /usr/lib/perl5/vendor_perl/5.18.2/x86_64-linux-thread-multi/Moose/Meta/Method/Delegation.pm line 110
Mar 28 16:04:11 tigercity openqa[1319]: DBIx::Class::DeploymentHandler::upgrade_single_step('DBIx::Class::DeploymentHandler=HASH(0x731e880)', 'HASH(0x7353648)') called at /usr/lib/perl5/vendor_perl/5.18.2/DBIx/Class/DeploymentHandler/Dad.pm line 64
Mar 28 16:04:11 tigercity openqa[1319]: DBIx::Class::DeploymentHandler::Dad::__ANON__() called at /usr/lib/perl5/vendor_perl/5.18.2/DBIx/Class/DeploymentHandler/DeployMethod/SQL/Translator.pm line 331
Mar 28 16:04:11 tigercity openqa[1319]: DBIx::Class::DeploymentHandler::DeployMethod::SQL::Translator::__ANON__() called at /usr/lib/perl5/vendor_perl/5.18.2/Context/Preserve.pm line 22
Mar 28 16:04:11 tigercity openqa[1319]: Context::Preserve::preserve_context('CODE(0x734c188)', 'after', 'CODE(0x7352fd0)') called at /usr/lib/perl5/vendor_perl/5.18.2/DBIx/Class/DeploymentHandler/DeployMethod/SQL/Translator.pm line 331
Mar 28 16:04:11 tigercity openqa[1319]: DBIx::Class::DeploymentHandler::DeployMethod::SQL::Translator::txn_do('DBIx::Class::DeploymentHandler::DeployMethod::SQL::Translator...', 'CODE(0x73527a8)') called at /usr/lib/perl5/vendor_perl/5.18.2/x86_64-linux-thread-multi/Moose/Meta/Method/Delegation.pm line 110
Mar 28 16:04:11 tigercity openqa[1319]: DBIx::Class::DeploymentHandler::txn_do('DBIx::Class::DeploymentHandler=HASH(0x731e880)', 'CODE(0x73527a8)') called at /usr/lib/perl5/vendor_perl/5.18.2/DBIx/Class/DeploymentHandler/Dad.pm line 73
Mar 28 16:04:11 tigercity openqa[1319]: DBIx::Class::DeploymentHandler::Dad::upgrade('DBIx::Class::DeploymentHandler=HASH(0x731e880)') called at /usr/share/openqa/script/../lib/OpenQA/Schema.pm line 122
Mar 28 16:04:11 tigercity openqa[1319]: OpenQA::Schema::_try_upgrade_db('DBIx::Class::DeploymentHandler=HASH(0x731e880)') called at /usr/share/openqa/script/../lib/OpenQA/Schema.pm line 82
Mar 28 16:04:11 tigercity openqa[1319]: OpenQA::Schema::deployment_check('OpenQA::Schema=HASH(0x6e66d58)') called at /usr/share/openqa/script/../lib/OpenQA/WebAPI.pm line 227
Mar 28 16:04:11 tigercity openqa[1319]: OpenQA::WebAPI::startup('OpenQA::WebAPI=HASH(0xfc4c98)') called at /usr/lib/perl5/vendor_perl/5.18.2/Mojolicious.pm line 175
Mar 28 16:04:11 tigercity openqa[1319]: Mojolicious::new('OpenQA::WebAPI') called at /usr/lib/perl5/vendor_perl/5.18.2/Mojo/Server.pm line 17
Mar 28 16:04:11 tigercity openqa[1319]: Mojo::Server::build_app('Mojo::Server=HASH(0xebaf38)', 'OpenQA::WebAPI') called at /usr/lib/perl5/vendor_perl/5.18.2/Mojolicious/Commands.pm line 72
Mar 28 16:04:11 tigercity openqa[1319]: Mojolicious::Commands::start_app('Mojolicious::Commands', 'OpenQA::WebAPI') called at /usr/share/openqa/script/../lib/OpenQA/WebAPI.pm line 587
Mar 28 16:04:11 tigercity openqa[1319]: OpenQA::WebAPI::run() called at /usr/share/openqa/script/openqa line 35
Mar 28 16:04:11 tigercity openqa[1319]: DBIx::Class::Storage::TxnScopeGuard::DESTROY(): A DBIx::Class::Storage::TxnScopeGuard went out of scope without explicit commit or error. Rolling back. at /usr/lib/perl5/vendor_perl/5.18.2/DBIx/Class/DeploymentHandler/DeployMethod/SQL/Translator.pm line 116

just for reference.

**Comment by aaannz** [comment]
That seems like it. Thinking (and some google-fu) about it of course my container based openqa didn't triggered it. Since container is like process for the host system it runs under host's apparmor profile and internally can't change it.
That means I should probably revive my hw based test machine. :(

**Pull request merged**
