### PR TITLE
Fix another regression from c9735699 when no sync is needed

### PR DESCRIPTION
**Pull request by okurz**
Related progress issue: https://progress.opensuse.org/issues/46658

### CODE REVIEW

**Comment by okurz** [comment]
@foursixnine as you have more knowledge about the caching implementation

**Comment by okurz** [comment]
All checks have passed and is looking god on hotpatched openqaworker1, e.g. https://openqa.opensuse.org/tests/839640

Could it be that previous checks have "stalled" because I broke the caching implementation?

**Comment by coolo** [comment]
what checks?

**Comment by okurz** [comment]
merging to have it ready for tomorrow's o3 deployment. I will monitor.

**Comment by okurz** [comment]
> what checks?

e.g. https://travis-ci.org/os-autoinst/openQA/jobs/484299462#L1120 in https://github.com/os-autoinst/openQA/pull/1973

**Pull request merged**
