### PR TITLE
Use form validation in Main controller

### PR DESCRIPTION
**Pull request by kraih**
Found a broken `respond_to` call in the Main controller, then a broken type cast, and then i ended up modernising the whole controller.

### CODE REVIEW

**Review by Martchus — APPROVED** [review]

**Comment by okurz** [comment]
I think this is a good time to improve the code coverage :)

**Comment by kraih** [comment]
Sure.

**Review by kalikiana — APPROVED** [review]
That's a lovely improvement. Happy to see the validation in there!

**Review by okurz — APPROVED** [review]

**Comment by Martchus** [comment]
I suppose you haven't rebased on the latest commit to fix the container checks. Likely you can just merge it manually because the failing checks should have nothing to do with your changes.

**Pull request merged**
