### PR TITLE
Fix reschedule isos

### PR DESCRIPTION
**Pull request by coolo**

### CODE REVIEW

**Comment by okurz** [comment]
missing test

**Comment by coolo** [comment]
not my fault

**Comment by okurz** [comment]
you're killing me

**Comment by coolo** [comment]
that was a bit above my expectations :)

**Comment by okurz** [comment]
*killed-off okurz says* LGTM

**Comment by aaannz** [comment]
Just curious, will this (link_to vs. link_post) prevent double POST request sending?

**Comment by coolo** [comment]
Your main bug is indeed the link_post. link_post creates a link with data-remote=true - which is bound globally to POST to the href without any data. This is what we saw - fortunatly the action refused to do anything without data, so it was merely an annoyance in the javascript console.

The return false; is just to avoid that another element up the chain gets the click event too. I.e. if the table has a click handler on rows for selection. That's just best practise, not fixing a bug.

**Comment by coolo** [comment]
small correction: the data-remote=true was additionally in there - link_post adds data-method=post

**Pull request merged**
