### PR TITLE
Allow /api/v1/jobs get request to filter by result

### PR DESCRIPTION
**Pull request by aaannz**
@k0da would like this for some TTM hacking and I think it's generally useful.

This allow `/api/v1/jobs` to accept result parameter either with single value or comma separated values.

### CODE REVIEW

**Comment by coolo** [comment]
you know what okurz would have said, right? :)

**Comment by aaannz** [comment]
hold on a sec, made typo

**Comment by aaannz** [comment]
fixed, ready

**Comment by coolo** [comment]
no, he would have said update the copyright year ;)

**Comment by okurz** [comment]
well, actually I would have asked to write a copyright checker and update script not to come up with the same issue in a manual way over and over again. It is more "what aaannz would have said …" :-)

**Pull request merged**
