### PR TITLE
Makefile: Add YAML linter checks

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by okurz** [comment]
I would like to present the idea and then discuss with you the following:

1. Which files should we cover
2. Which rules should we enforce

For 1. I would try to cover all yaml files except database migration related ones, e.g. exclude directory "dbicdh/". For 2. I would try to enforce all rules except exceeding line length

**Comment by kalikiana** [comment]
> I would like to present the idea and then discuss with you the following:
> 
>     1. Which files should we cover
> 
>     2. Which rules should we enforce
> 
> 
> For 1. I would try to cover all yaml files except database migration related ones, e.g. exclude directory "dbicdh/". For 2. I would try to enforce all rules except exceeding line length

```
$ yamllint public/schema/JobTemplates-01.yaml
  1:1       warning  missing document start "---"  (document-start)
  7:1       error    wrong indentation: expected 2 but found 0  (indentation)
  11:81     error    line too long (92 > 80 characters)  (line-length)
  24:15     error    wrong indentation: expected 16 but found 14  (indentation)
  27:81     error    line too long (139 > 80 characters)  (line-length)
  48:81     error    line too long (116 > 80 characters)  (line-length)
  56:81     error    line too long (87 > 80 characters)  (line-length)
  58:9      error    wrong indentation: expected 10 but found 8  (indentation)
```

Taking the JobTemplates schema as an example, the `---` one is something I would disable. Not sure if we really care about long lines... 

I like the indentation warnings, that's the "tidy" type consistency checks we probably want.

Note sure about this one from `.circleci/config.yaml`:

```yaml
    TRAVIS: yes
```

triggers

      71:15     warning  truthy value should be one of [false, true]  (truthy)

**Comment by perlpunk** [comment]
> Note sure about this one from `.circleci/config.yaml`:
> 
> ```yaml
>     TRAVIS: yes
> ```
> 
> triggers
> 
> ```
>   71:15     warning  truthy value should be one of [false, true]  (truthy)
> ```

If the value expected there should be a boolean, then we should use `true`.
if it's supposed to be the string `yes`, then it should be quoted.
Bakground: YAML 1.1 accepts a whole lot of strings as booleans (which was a bad design in retrospective), and it's good to use only `true` and `false` for consistency. These are the canonical boolean values. It will also make the adoption of YAML 1.2 easier.

**Comment by perlpunk** [comment]
> I like the indentation warnings, that's the "tidy" type consistency checks we probably want.

That would mean that we'd have to write this:
```
required:
- products
- scenarios
```
like this:
```
required:
  - products
  - scenarios
```

I personally like the zero-indentation of sequences, so I don't like yamllint complaining here.

**Comment by kalikiana** [comment]
> > I like the indentation warnings, that's the "tidy" type consistency checks we probably want.
> 
> That would mean that we'd have to write this:
> 
> ```
> required:
> - products
> - scenarios
> ```
> 
> like this:
> 
> ```
> required:
>   - products
>   - scenarios
> ```
> 
> I personally like the zero-indentation of sequences, so I don't like yamllint complaining here.

Ah, I hadn't realized that's what it meant. I thought there was some inconsistency there ie. not having the same indentation throughout the document.

**Comment by okurz** [comment]
@perlpunk "zero-indentation of sequences" now allowed.

**Comment by okurz** [comment]
hm, trouble to find selenium in https://app.circleci.com/jobs/github/os-autoinst/openQA/5351/parallel-runs/0/steps/0-108 . Does this mean I need a rebase?

**Comment by okurz** [comment]
I added an OBS test project manually: https://build.opensuse.org/package/show/home:okurz:feature:yamllint/openQA which looks all good.

**Pull request merged**
