### PR TITLE
Dependency cron 200422

### PR DESCRIPTION
**Pull request by openqabot**

### CODE REVIEW

**Comment by okurz** [comment]
Tests fail here, maybe due to the update:

```
#   Failed test 'GET /'
#   at t/ui/14-dashboard.t line 148.
Can't use an undefined value as a HASH reference at t/ui/14-dashboard.t line 148.
```

**Comment by Martchus** [comment]
I haven't seen any comments in the chat or here that someone will take care of it so I'll have a look (it is reproducible locally).

**Comment by okurz** [comment]
thank you. Haven't managed to check myself due to child care ;)

**Comment by Martchus** [comment]
This test mixes `Mojo::Test` and Selenium. That means the database is initialized twice. I'm not sure why it is not working but using Selenium here entirely would fix it and also decrease the initialization time.

**Comment by Martchus** [comment]
The single test failure you've pointed out is not the only problem caused by the new version: https://progress.opensuse.org/issues/65975

So I'm closing this PR as we should better skip this release.

**Comment by okurz** [comment]
@Martchus I think it's the right choice to skip but keep in mind that closing this PR *only* has the effect for circle CI jobs (I think), anyone installing the update from distribution packages, like us in openSUSE, is already affected.

**Comment by andrii-suse** [comment]
Yes, purpose of .circleci/dependencies.txt is to control CI environment only. It has nothing to do with release and I agree that this is good opportunity to review the whole process.

**Comment by Martchus** [comment]
@okurz Of course I'm aware that it is currently broken under Tumbleweed. In fact any similar Mojo app is broken under Tumbleweed. To resolve this we need to bring the fixed release as soon as possible into Tumbleweed.

**Pull request closed without merging**
