### PR TITLE
Add docs for using text consoles and serial term

### PR DESCRIPTION
**Pull request by richiejp**
Cover switching to another console and using a serial terminal

### CODE REVIEW

**Comment by aaannz** [comment]
:+1:

**Comment by richiejp** [comment]
I need to add some info about setting the VIRTIO_CONSOLE var to this.

**Comment by okurz** [comment]
@foursixnine that could be interesting for you

**Comment by foursixnine** [comment]
@okurz what do you mean? the feature? or the docs?

**Comment by okurz** [comment]
the docs

**Pull request merged**
