### PR TITLE
Fix admin layout for test suites with long keys

### PR DESCRIPTION
**Pull request by kravciak**
Currently test suites slenkins-tests-ceph-control and s390_hsi-l2

### CODE REVIEW

**Comment by okurz** [comment]
I am sure the rule had been put there for a reason. Can you show "before" and "after" screenshots for comparison?

**Comment by kravciak** [comment]
before: http://imagebin.suse.de/2137
after: http://imagebin.suse.de/2141

**Comment by okurz** [comment]
LVGTM aka. looks *very* good to me ;-)

**Comment by kravciak** [comment]
Do not merge yet please, we need to somehow highlight keys

**Comment by okurz** [comment]
highlight keys? You mean have the first column more distinct? looks good enough for me or at least unrelated but @aaannz might want to have his opinion?

**Comment by kravciak** [comment]
It is not very readable, at least we need to underline keys http://imagebin.suse.de/2145

**Comment by kravciak** [comment]
Underline it is - under we figure out something better

**Comment by nilxam** [comment]
it looks weird to me if the variable name had underline eg. HDD_1, UEFI_BIOS, etc.

**Comment by aaannz** [comment]
Personally I'm more for `font-weight: bold`:

screenshot_20160819_144012


vs. underline:

screenshot_20160819_144100

**Comment by kravciak** [comment]
@aaannz - I was considering exactly those 2 options

**Comment by okurz** [comment]
IMHO should be two individual commits but good enough for me

**Comment by aaannz** [comment]
:+1:

**Comment by okurz** [comment]
@Soulofdestiny I think you will like this :-)

**Pull request merged**
