### PR TITLE
Update perl-Mojolicious to 8.25 in CI

### PR DESCRIPTION
**Pull request by andrii-suse**

### CODE REVIEW

**Comment by andrii-suse** [comment]
We can skip this PR as well and merge dependency changes in batches e.g. weekly

**Comment by okurz** [comment]
I guess Mojo as a dependency change is big enough to look into itself

**Comment by coolo** [comment]
I think I should have been more clear on how to squash these commits - because the default 'merge' creates 2 commits. One speaking and one cron generated

**Comment by okurz** [comment]
so, what do you want? Pushing the commit to master instead of merging?

**Comment by Martchus** [comment]
When I remember correctly, you could use the "squash" feature of GitHub to rename the commit.

**Comment by coolo** [comment]
Right. Don't click 'Merge' but switch to 'Squash & commit'

**Comment by perlpunk** [comment]
> we will never remember this

It's possible to only allow one merge method in the repo settings, maybe we should do that. Unless there are cases where we don't want to squash.

**Comment by okurz** [comment]
On Wednesday, 2 October 2019 17.44.30 CEST Tina Müller (tinita) wrote:
> > we will never remember this
> 
> It's possible to only allow one merge method in the repo settings, maybe we
> should do that. Unless there are cases where we don't want to squash.

this here is exactly the only case where it seems that coolo wants to squash 
but have merge for others. I would stay with merge for all.

**Comment by coolo** [comment]
> > we will never remember this
> 
> It's possible to only allow one merge method in the repo settings, maybe we should do that. Unless there are cases where we don't want to squash.

I squash when there is one commit only in the PR - and merge otherwise

**Pull request merged**
