### PR TITLE
add the margin and match field to needleeditor

### PR DESCRIPTION
**Pull request by nilxam**

### CODE REVIEW

**Comment by coolo** [comment]
These fields are a bit unmotivated in the UI. Match: "<empty>" leaves random users pretty clueless what to enter there.

And you show the + and - (that you should use font awesome icons for instead IMO) even for non-operators giving 403 if clicked.

And if I press + the needle is saved? That's highly suprising as it looks like just related to the JSON shown. BTW: what area do these fields relate to?

**Comment by nilxam** [comment]
it's needle's match rate and the margin search value, relate to https://progress.opensuse.org/issues/2864

when you press +/- it just change the value, when you save the needle via the Save button then it do the real saving thing as what we know about needle editor, and only the operator can press that Save button.

**Comment by nilxam** [comment]
and Match:"" ie. empty should not happens, it load the value from needle or results when loading the page.

**Comment by coolo** [comment]
I created a new needle. And it most definitely saved on clicking +

I'm aware what's written in the issue - but it's impossible for the user to find out.

**Comment by nilxam** [comment]
hmm...are you mean when you clicking + button it saved a needle? strange, doesn't happen here.

but anyway, I'd close this PR until we've the direction for this function.

**Comment by coolo** [comment]
https://github.com/os-autoinst/openQA/pull/230 is the jquery version of this

**Pull request closed without merging**
