### PR TITLE
add "w" to sub-dir under of pooldir

### PR DESCRIPTION
**Pull request by nilxam**
worker script needs permission to create new directory for pool/*

### CODE REVIEW

**Comment by nilxam** [comment]
and I think we need to modify specfile a little bit like below

--- openQA.spec (revision 3)
+++ openQA.spec (revision 938)
@@ -189,7 +189,6 @@
 if test -e /run/openqa_needs_user_migration; then
   rm /run/openqa_needs_user_migration
   systemctl stop openqa-worker.target
-  chown _openqa-worker /var/lib/openqa/pool
   chown -R _openqa-worker --from=geekotest /var/lib/openqa/pool/*
 fi
 %service_add_post openqa-worker.target
@@ -293,8 +292,8 @@
 %dir %{_datadir}/openqa
 %dir %{_datadir}/openqa/script
 %{_datadir}/openqa/script/worker
-%defattr(-,_openqa-worker,root)
 %dir %{_localstatedir}/lib/openqa/pool
+%defattr(-,_openqa-worker,root)
 # own one pool - to create the others is task of the admin
 %dir %{_localstatedir}/lib/openqa/pool/1

**Comment by coolo** [comment]
your spec file diff is reverted - and it's actually meant to be this way. To add more workers the admin is supposed to create the pool directories himself. At least that's how Ludwig wanted it

**Comment by nilxam** [comment]
oops...I was did a way around rdiff :(

the correct one below:

    @@ -189,6 +189,7 @@
     if test -e /run/openqa_needs_user_migration; then
       rm /run/openqa_needs_user_migration
       systemctl stop openqa-worker.target
    +  chown _openqa-worker /var/lib/openqa/pool
       chown -R _openqa-worker --from=geekotest /var/lib/openqa/pool/*
     fi
     %service_add_post openqa-worker.target
    @@ -292,8 +293,8 @@
     %dir %{_datadir}/openqa
     %dir %{_datadir}/openqa/script
     %{_datadir}/openqa/script/worker
    -%dir %{_localstatedir}/lib/openqa/pool
     %defattr(-,_openqa-worker,root)
    +%dir %{_localstatedir}/lib/openqa/pool
     # own one pool - to create the others is task of the admin
     %dir %{_localstatedir}/lib/openqa/pool/1

**Comment by nilxam** [comment]
ok, if that is the deal. closing then.

**Pull request closed without merging**
