### PR TITLE
Add UI for pausing on assert screen timeout

### PR DESCRIPTION
**Pull request by Martchus**
* based on https://github.com/os-autoinst/openQA/pull/1724
* requires https://github.com/os-autoinst/os-autoinst/pull/993

---

screenshot_20180720_131203

### CODE REVIEW

**Comment by Martchus** [comment]
So I now have integration/fullstack test for pausing on assert screen timeout. It works locally, however, I don't expect it to pass on Travis because it requires https://github.com/os-autoinst/os-autoinst/pull/993.

I'll also have to extend the tests to cover opening the needle editor when paused on `assert_screen` failure.

**Comment by coolo** [comment]
it's merged now - please rebase?

**Comment by Martchus** [comment]
Rebased and since https://github.com/os-autoinst/os-autoinst/pull/993 has been merged tests pass.

**Comment by Martchus** [comment]
I think it can be merged as soon as the overall fallout is cleaned. The successive PR is deployed on e212.

**Comment by foursixnine** [comment]
@Martchus please rebase :)

**Comment by foursixnine** [comment]
I just love how flaky the fullstack test is now :)

**Pull request merged**
