### PR TITLE
Make all modules pass Perl::Critic::Freenode with severity level 4

### PR DESCRIPTION
**Pull request by kraih**
Running `perlcritic --theme freenode --stern lib` against openQA showed some interesting potential bugs. Using the varibles `$a`/`$b` outside of their intended purpose, or doing `for my $item (%hash) {` would have most defnitely resulted in unintended side effects (maybe already have). Similarly the use of implicit `$_` is fine for one-liners, but has no place in real applications.

If there are no objections i would like to propose that we try to follow the rules from [Perl::Critic::Freenode](https://metacpan.org/pod/Perl::Critic::Freenode) in the future for openQA. (I have made no changes in that regard yet, and will be waiting for feedback first) There are still quite [a few rules that openQA breaks](https://gist.github.com/kraih/09ebe5083b52eb62a5e17c4f520ae748), but they are all low severity.  I do think all of them make sense and would result in more maintainable code.

### CODE REVIEW

**Comment by Martchus** [comment]
I don't see any Makefile changes so I assume this is not enforced for future changes yet. I suggest this would be the next step. Or do some false-positives prevent you do add the perlcritic check to the Makefile?

**Comment by kraih** [comment]
@Martchus That is indeed the next step, but i wanted to get feedback from @os-autoinst/tools-team first. And i will count your question as a vote in favour. 😃

**Comment by coolo** [comment]
So far only no brainers.

**Comment by kraih** [comment]
The thing about bare returns (`return;`) is that it was encouraged earlier in the book Perl Best Practices (commonly referred to as PBP). It is now very much discouraged in the Perl community however (after we learned a few very painful security lessons), and even the author of Perl Best Practices has revised his position and now encourages returning undef or an empty list (depending on what other return values the function has). Some tools might still be sticking to the original text of PBP, but they are wrong.

P.S.: If you have a Safari subscription you can watch the video about the revised Perl Best Practices [here](https://www.safaribooksonline.com/videos/modern-perl-best/9781491910719).

**Pull request merged**
