### PR TITLE
Sort scheduled and running too based on time

### PR DESCRIPTION
**Pull request by coolo**
This makes it a bit more predictable what happens.

### CODE REVIEW

**Comment by okurz** [comment]
Improving the table label, good. Comparing the position in table and looking at the time gives additional information (e.g. job was triggered at one time but started much later and others in between) that is now lost, isn't it?

**Comment by coolo** [comment]
what's the value of that information?

**Comment by okurz** [comment]
On Thursday 14 July 2016 06:41:41 Stephan Kulow wrote:
> what's the value of that information?

I don't have a clear use case in mind now but you could also argue what is the 
benefit of having the "finished" or "started" time. nevermind.

**Comment by coolo** [comment]
ok, then let's continue with the benefits :)

**Pull request merged**
