### PR TITLE
Use consistent data structures in worker logs

### PR DESCRIPTION
**Pull request by kraih**
There is no need to depend on `YAML::XS`. The worker logs were already using `Data::Dumper` everywhere else.

### CODE REVIEW

**Comment by okurz** [comment]
That's funny. Please see https://build.opensuse.org/public/build/devel:openQA:TestGithub:PR-2766/openSUSE_Tumbleweed/x86_64/openQA/_log complaining about

```
[  945s] #   Failed test 'Empty template - no errors'
[  945s] #   at ./t/16-utils-job-templates.t line 41.
[  945s] #          got: '1'
[  945s] #     expected: '0'
[  945s] 
[  945s] #   Failed test 'Invalid schema file'
[  945s] #   at ./t/16-utils-job-templates.t line 43.
[  945s] #                   ''
[  945s] #     doesn't match '(?^:JSON::Validator)'
[  945s] # Error: [JSON::Validator] YAML::XS 0.67 is missing or could not be loaded. at /usr/lib/perl5/vendor_perl/5.30.1/JSON/Validator.pm line 303, <$fh> line 42.
[  945s] 
[  945s] #   Failed test 'Valid template - no errors'
[  945s] #   at ./t/16-utils-job-templates.t line 49.
[  945s] #          got: '1'
[  945s] #     expected: '0'
[  945s] # Error: [JSON::Validator] YAML::XS 0.67 is missing or could not be loaded. at /usr/lib/perl5/vendor_perl/5.30.1/JSON/Validator.pm line 303, <$fh> line 34.
[  945s] 
[  945s] #   Failed test 'Valid template with testsuite null - no errors'
[  945s] #   at ./t/16-utils-job-templates.t line 55.
[  945s] #          got: '1'
[  945s] #     expected: '0'
[  945s] # Looks like you failed 4 tests of 4.
[  945s] ./t/16-utils-job-templates.t ..................... 
[  945s] not ok 1 - Empty template - no errors
[  945s] not ok 2 - Invalid schema file
[  945s] not ok 3 - Valid template - no errors
[  945s] not ok 4 - Valid template with testsuite null - no errors
[  945s] 1..4
[  945s] Dubious, test returned 4 (wstat 1024, 0x400)
[  945s] Failed 4/4 subtests 
```

To me this sounds like `JSON::Validator` is depending on YAML::XS but isn't properly specifying this as runtime requirement.

**Comment by Martchus** [comment]
Yes, seems like some tests still depend on that module.

**Comment by perlpunk** [comment]
> To me this sounds like `JSON::Validator` is depending on YAML::XS but isn't properly specifying this as runtime requirement.

Yes, JSON::Validator is depending on YAML::XS, but only for loading a schema from a YAML file directly. That's why it is not a hard dependency.
As far as I understand, JSON::Validator will add YAML::XS as a dependency in the future, but not sure (depending on an XS module has disadvantages).

**Comment by kraih** [comment]
Yes, it is `JSON::Validator`. We use a schema in YAML format which makes it load `YAML::XS` as a runtime dependency.

**Comment by kraih** [comment]
Ok, updated the PR with comments for why `YAML::XS` is still required.

**Pull request merged**
