### PR TITLE
Add web socket console for isotovideo commands

### PR DESCRIPTION
**Pull request by Martchus**
* Accessible via `/tests/:testid/developer/ws-console`
  (admin-only)
* See
    * https://progress.opensuse.org/issues/36442#note-2
    * https://progress.opensuse.org/issues/36454

---

screenshot_20180523_174150

---

Not sure whether I handle the port correctly. I use `($worker->get_property('QEMUPORT') // 20012) + 1`. In my case `QEMUPORT` isn't actually set in openQA, but the worker log says it is 20012 so I used that as default.

I currently just use the public folder for `developer.js` so this file isn't included in every page. But I can change it to be a regular asset of course.

### CODE REVIEW

**Comment by coolo** [comment]
you can just put it as extra asset. Only bootstrap.js is included in every page

**Comment by Martchus** [comment]
And `bootstrap.js` contains everything. But I could try making it a separate asset. On the other hand, when making use of the JavaScript for handling the web socket connection later, it must be present on the regular tests page anyways.

**Comment by coolo** [comment]
yeah, moving this later is surely an option. but for now having it assetpack.def has the adventage that it's tagged and is reloaded by the browser reliably

**Comment by Martchus** [comment]
Using a regular asset now. I'm wondering whether I should add tests for this (codecov complains). I could either extend the full stack test or create a mock server for the web socket server somehow.

I also created a commit to get rid of the `/developer` route in your os-autoinst branch: https://github.com/Martchus/os-autoinst/commit/cf7527cd4be032eb7f800edc0c1ebd9989866708

**Pull request closed without merging**
