### PR TITLE
docs: Delete reference to inactive stable repo

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by sysrich** [comment]
@okurz please explain to me why codecov is complaining about unexpected changes not visible in diff

**Comment by okurz** [comment]
reason is the full stack test is not deterministic. Sometimes it stops earlier where it did not do all the required worker interaction to reach the coverage threshold. Definetly not because of my changes.

**Comment by sysrich** [comment]
A test that is not deterministic is a test that determines nothing

What's the point of a test that determines nothing?

**Comment by okurz** [comment]
On Tuesday, 28 February 2017 16:12:04 CET Richard Brown wrote:
> A test that is not deterministic is a test that determines nothing
> 
> What's the point of a test that determines nothing?

ask @coolo

**Comment by coolo** [comment]
The problem is in the part that it's not meant to test, but still runs from time to time.

**Pull request merged**
