### PR TITLE
Only fetch job groups when delivering HTML

### PR DESCRIPTION
**Pull request by perlpunk**
Save unnecessary database queries

Issue: https://progress.opensuse.org/issues/61919

### CODE REVIEW

**Comment by okurz** [comment]
s/delievering/delivering/

**Comment by okurz** [comment]
please also the git commit message subject line, rest is LGTM

**Comment by perlpunk** [comment]
> s/delievering/delivering/

oops, fixed (title & commit)

**Comment by Martchus** [comment]
Good idea. This could likely be further optimized because we don't even need for some HTML routes. Let's see whether the tests still pass (I suppose it is easy to overlook something here).

**Pull request merged**
