### PR TITLE
Prevent sponsor logo overflow

### PR DESCRIPTION
**Pull request by realcharmer**
Included fixes:

- Overflowing sponsor logo
- Sponsor text not disappearing with the logo on narrow viewports
- Image having a margin in the bitmap itself
- Centering and alignment

### CODE REVIEW

**Comment by Martchus** [comment]
How is this currently overflowing? It looks good on my browser, e.g. on https://openqa.opensuse.org. Can you share some screenshots (e.g. before and after this change)?

**Comment by realcharmer** [comment]
Before:

After:

**Comment by realcharmer** [comment]
The overflow could be extreme in some cases, for example:

**Comment by Martchus** [comment]
Ah, the overflow is only visible when using the development tools.

**Review by Martchus — APPROVED** [review]

**Review by pdostal — APPROVED** [review]
First PR, nice! 🎉

**Review by okurz — APPROVED** [review]

**Pull request merged**
