### PR TITLE
Sync needles when caching is enabled

### PR DESCRIPTION
**Pull request by foursixnine**
This is a quick try to solve poo#19408

A verification run: http://deimos.suse.de/tests/6104#step/bootloader/6 that's showing just the needle that was created in interactive mode.

### CODE REVIEW

**Comment by foursixnine** [comment]
I basically duplicated the code from [isotovideo engine](https://github.com/os-autoinst/openQA/blob/master/lib/OpenQA/Worker/Engines/isotovideo.pm#L168). May be it calls for refactoring, but for now it works.

**Comment by sysrich** [comment]
As discussed with @foursixnine -1 from me

**Comment by okurz** [comment]
Great. You found a way to make it work and you know how to test. Now to reduce the duplication I suggest to implement that call as a isotovideo RPC command which can then be called from all locations where necessary.

**Comment by coolo** [comment]
Actually, interactive mode with caching is IMO just nice to have. So refactor with ease

**Comment by foursixnine** [comment]
Time to work on a full-stack-ui test suite?

**Comment by coolo** [comment]
the whole idea of the full stack test was born to be able to test the interactive mode *at all*. But I never came around it, because https://progress.opensuse.org/issues/14818 needs to be fixed first

**Comment by coolo** [comment]
but if you could put it in record: did you test this manually with and without caching enabled?

**Comment by foursixnine** [comment]
Yep, tested on both scenarios, no problems so far*signs with blood*
When caching is enabled, this will be the output:
```
[DEBUG] Calling flock /var/lib/openqa/cache/deimos.suse.de/needleslock rsync -avHP rsync://deimos.suse.de/openqa-tests/ --delete /var/lib/openqa/cache/deimos.suse.de/tests/
receiving incremental file list                                         
opensuse/products/sle/needles/                                                                                                         
opensuse/products/sle/needles/failed-to-boot-20170810.json                                                                             
            217 100%  211.91kB/s    0:00:00 (xfr#1, ir-chk=8438/16702)                                        
opensuse/products/sle/needles/failed-to-boot-20170810.png                                                                              
          1,193 100%    1.14MB/s    0:00:00 (xfr#2, ir-chk=8437/16702)                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                               
sent 431 bytes  received 450,909 bytes  902,680.00 bytes/sec                                                                            
total size is 2,066,964,415  speedup is 4,579.62                                                                                                                                                               
[DEBUG] RSYNC: Synchronization of tests directory took 0.00 seconds                                                                                        
[DEBUG] needles will be reloaded
```
When it is disabled, it still is:
`[DEBUG] needles will be reloaded`

**Comment by okurz** [comment]
LGTM

**Comment by foursixnine** [comment]
Life is sexy again now, let's live with that small coverage drop for the time being, as we would need to improve the fullstack test to also cover the needle editor with and without caching.

**Pull request merged**
