### PR TITLE
Re-add boundary hack

### PR DESCRIPTION
**Pull request by nadvornik**
- partially reverted f2547e9bcc0, the boundary calculation has
not changed in new Mojo so this might be still useful.

On my machine I have seen upload failures even with this
patch, but maybe it improves the situation.

Please test.

### CODE REVIEW

**Comment by okurz** [comment]
so it does *not* improve the situation for you? How did you test and how did it fail?

**Comment by nadvornik** [comment]
I have found another problem on my machine - I had modified the webui unit file and the correct commandline arguments were not merged during rpm update. After fixing this and with this boundary calculation hack everything seems to work reliably.

**Comment by okurz** [comment]
LGTM

**Comment by aaannz** [comment]
:+1:

**Comment by okurz** [comment]
Wanna deploy to test?

**Comment by aaannz** [comment]
I'm all for it. There are also those webui fixes. @sysrich?

**Comment by AdamWill** [comment]
FWIW, even with this patch, our staging deployment is still getting 'incomplete' for disk upload tests, e.g. https://openqa.stg.fedoraproject.org/tests/34881 . We are still on Mojo 6. Note, I also have 
https://github.com/os-autoinst/openQA/pull/802 applied.

    18:46:34.1174 9271 ||| finished _console_shutdown tests at 2016-08-29 18:46:34 (23 s)
    18:46:34.3865 9263 awaiting death of testpid 9271
    18:46:34.3903 9263 got sigchld
    18:46:34.3903 9263 test process exited: 9271
    18:46:34.3903 9263 isotovideo done
    18:46:34.3914 9263 BACKEND SHUTDOWN 1
    waitpid for 9294 returned 0
    sending TERM to qemu pid: 9294
    waitpid for 9294 returned 9294
    18:46:35.4771 9288 QEMU: qemu-system-x86_64: terminating on signal 15 from pid 9288
    18:46:35.4775 9288 sending magic and exit
    18:46:35.4776 9263 received magic close
    18:46:35.4999 9263 got sigchld
    18:46:35.5006 9263 preparing hdd 1 for upload as disk_Server-dvd-iso_64bit.qcow2 in qcow2
    18:47:06.3873 9263 got sigchld
    18:47:06.3874 9263 sha1sum 62ed469c18be6f81711961b4afa49a85ed6fd5a6 *assets_private/disk_Server-dvd-iso_64bit.qcow2
    EXIT 0
    18:47:06.3879 9270 sysread failed: Connection reset by peer
    18:47:06.3881 9263 awaiting death of commands process
    18:47:06.3985 9263 commands process exited: 9270

**Comment by aaannz** [comment]
That's interesting since the image is uploaded fine in your tests. The checksum at the and of the log matches. So I think there is another reason for incomplete result.

**Comment by aaannz** [comment]
If you manage to get openqa webui logs from that time it would be perfect. :D There was a change in calculating overall result some time ago: #801 and #813 but I think that calculation is correct now.

Btw. the `sysread failed: Connection reset by peer` is not unusual. os-autoinst prints that during exit.

**Comment by AdamWill** [comment]
I can try, but the incompletions seem to have gone away since I fully reverted the upload commit. I suspect one thing is getting bored waiting for some other thing. I'll see if I can find any interesting logs in a minute...

**Comment by AdamWill** [comment]
I see this in the `openqa-webui` service log:

    Aug 29 18:47:44 openqa-stg01.qa.fedoraproject.org openqa[26092]: [Mon Aug 29 18:47:44 2016] [26115:warn] 34881 got an asset but has no worker. huh?
    Aug 29 18:48:58 openqa-stg01.qa.fedoraproject.org openqa[26092]: [Mon Aug 29 18:48:58 2016] [26121:warn] 34881 got an artefact but has no worker. huh?
    Aug 29 18:48:58 openqa-stg01.qa.fedoraproject.org openqa[26092]: [Mon Aug 29 18:48:58 2016] [26121:warn] 34881 got an artefact but has no worker. huh?
    Aug 29 18:48:58 openqa-stg01.qa.fedoraproject.org openqa[26092]: [Mon Aug 29 18:48:58 2016] [26121:warn] 34881 got an artefact but has no worker. huh?
    Aug 29 18:48:58 openqa-stg01.qa.fedoraproject.org openqa[26092]: [Mon Aug 29 18:48:58 2016] [26121:warn] 34881 got an artefact but has no worker. huh?
    Aug 29 18:48:58 openqa-stg01.qa.fedoraproject.org openqa[26092]: [Mon Aug 29 18:48:58 2016] [26118:warn] 34881 got a status update but has no worker. huh?

The Apache logs are very noisy, but grepping for the job ID and cutting out the earlier messages which happen while the test is in progress, I see:

    10.5.124.157 - - [29/Aug/2016:18:46:26 +0000] "POST /api/v1/jobs/34881/status HTTP/1.1" 200 56 "-" "Mojolicious (Perl)"
    10.5.124.157 - - [29/Aug/2016:18:47:06 +0000] "POST /api/v1/jobs/34881/status HTTP/1.1" 200 56 "-" "Mojolicious (Perl)"
    10.5.124.157 - - [29/Aug/2016:18:47:08 +0000] "POST /api/v1/jobs/34881/artefact HTTP/1.1" 200 104 "-" "Mojolicious (Perl)"
    10.5.124.157 - - [29/Aug/2016:18:48:58 +0000] "POST /api/v1/jobs/34881/ack_temporary HTTP/1.1" 200 2 "-" "Mojolicious (Perl)"
    10.5.124.157 - - [29/Aug/2016:18:48:58 +0000] "POST /api/v1/jobs/34881/artefact HTTP/1.1" 200 2 "-" "Mojolicious (Perl)"
    10.5.124.157 - - [29/Aug/2016:18:48:58 +0000] "POST /api/v1/jobs/34881/artefact HTTP/1.1" 200 2 "-" "Mojolicious (Perl)"
    10.5.124.157 - - [29/Aug/2016:18:48:58 +0000] "POST /api/v1/jobs/34881/artefact HTTP/1.1" 200 2 "-" "Mojolicious (Perl)"
    10.5.124.157 - - [29/Aug/2016:18:48:58 +0000] "POST /api/v1/jobs/34881/artefact HTTP/1.1" 200 2 "-" "Mojolicious (Perl)"
    10.5.124.157 - - [29/Aug/2016:18:48:58 +0000] "POST /api/v1/jobs/34881/status HTTP/1.1" 200 86 "-" "Mojolicious (Perl)"
    10.5.124.157 - - [29/Aug/2016:18:48:58 +0000] "POST /api/v1/jobs/34881/artefact HTTP/1.1" 200 2 "-" "Mojolicious (Perl)"
    10.5.124.157 - - [29/Aug/2016:18:48:58 +0000] "POST /api/v1/jobs/34881/artefact HTTP/1.1" 200 2 "-" "Mojolicious (Perl)"
    10.5.124.157 - - [29/Aug/2016:18:48:58 +0000] "POST /api/v1/jobs/34881/artefact HTTP/1.1" 200 2 "-" "Mojolicious (Perl)"
    10.5.124.157 - - [29/Aug/2016:18:48:58 +0000] "POST /api/v1/jobs/34881/artefact HTTP/1.1" 200 2 "-" "Mojolicious (Perl)"
    10.5.124.157 - - [29/Aug/2016:18:48:58 +0000] "POST /api/v1/jobs/34881/artefact HTTP/1.1" 200 2 "-" "Mojolicious (Perl)"
    10.5.124.157 - - [29/Aug/2016:18:48:58 +0000] "POST /api/v1/jobs/34881/artefact HTTP/1.1" 200 2 "-" "Mojolicious (Perl)"
    10.5.124.157 - - [29/Aug/2016:18:48:59 +0000] "POST /api/v1/jobs/34881/artefact HTTP/1.1" 200 2 "-" "Mojolicious (Perl)"
    10.5.124.157 - - [29/Aug/2016:18:48:59 +0000] "POST /api/v1/jobs/34881/artefact HTTP/1.1" 200 2 "-" "Mojolicious (Perl)"
    10.5.124.157 - - [29/Aug/2016:18:48:59 +0000] "POST /api/v1/jobs/34881/artefact HTTP/1.1" 200 2 "-" "Mojolicious (Perl)"
    10.5.124.157 - - [29/Aug/2016:18:48:59 +0000] "POST /api/v1/jobs/34881/artefact HTTP/1.1" 200 2 "-" "Mojolicious (Perl)"
    10.5.124.157 - - [29/Aug/2016:18:48:59 +0000] "POST /api/v1/jobs/34881/set_done HTTP/1.1" 200 15 "-" "Mojolicious (Perl)"
    10.5.126.88 - - [29/Aug/2016:18:52:11 +0000] "GET /tests/34881 HTTP/1.0" 200 55234 "https://openqa.stg.fedoraproject.org/tests/overview?distri=fedora&groupid=1&version=Rawhide&build=Fedora-Rawhide-20160829.n.0" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
    10.5.126.88 - - [29/Aug/2016:18:52:13 +0000] "GET /image/0a/.thumbs/f06cfb2fa1d0bcc292fff1096c2b08.png HTTP/1.0" 200 1656 "https://openqa.stg.fedoraproject.org/tests/34881" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
    10.5.126.88 - - [29/Aug/2016:18:52:13 +0000] "GET /image/c6/.thumbs/7e9590459e185b2d578c02463e8cf2.png HTTP/1.0" 200 1620 "https://openqa.stg.fedoraproject.org/tests/34881" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
    10.5.126.88 - - [29/Aug/2016:18:52:13 +0000] "GET /image/c1/.thumbs/d0540fcd3cf5e97189e74d4277a992.png HTTP/1.0" 200 1605 "https://openqa.stg.fedoraproject.org/tests/34881" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
    10.5.126.88 - - [29/Aug/2016:18:52:13 +0000] "GET /image/c2/.thumbs/0f65b3174d30de366880d0c743a811.png HTTP/1.0" 200 1594 "https://openqa.stg.fedoraproject.org/tests/34881" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
    10.5.126.88 - - [29/Aug/2016:18:52:13 +0000] "GET /image/7c/.thumbs/615615ecfecf024067c704aeca1408.png HTTP/1.0" 200 1253 "https://openqa.stg.fedoraproject.org/tests/34881" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
    10.5.126.88 - - [29/Aug/2016:18:52:13 +0000] "GET /image/09/.thumbs/1fd60bb61a0476553874fb8494c340.png HTTP/1.0" 200 1681 "https://openqa.stg.fedoraproject.org/tests/34881" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
    10.5.126.88 - - [29/Aug/2016:18:52:13 +0000] "GET /image/8f/.thumbs/4714d3d6ccc473ed8dc271b2560574.png HTTP/1.0" 200 758 "https://openqa.stg.fedoraproject.org/tests/34881" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
    10.5.126.88 - - [29/Aug/2016:18:52:13 +0000] "GET /image/15/.thumbs/fa05e44028ccf3d3edef7b4f75954a.png HTTP/1.0" 200 1729 "https://openqa.stg.fedoraproject.org/tests/34881" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
    10.5.126.88 - - [29/Aug/2016:18:52:13 +0000] "GET /image/47/.thumbs/25ef22279dc75a443ef1d9ef80593f.png HTTP/1.0" 200 1729 "https://openqa.stg.fedoraproject.org/tests/34881" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
    10.5.126.88 - - [29/Aug/2016:18:52:13 +0000] "GET /image/86/.thumbs/ffb520f512addd219e9d266bf7c54a.png HTTP/1.0" 200 806 "https://openqa.stg.fedoraproject.org/tests/34881" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
    10.5.126.88 - - [29/Aug/2016:18:52:13 +0000] "GET /image/bd/.thumbs/20049fe25806f9cb691bce7860cda7.png HTTP/1.0" 200 907 "https://openqa.stg.fedoraproject.org/tests/34881" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
    10.5.126.88 - - [29/Aug/2016:18:52:13 +0000] "GET /image/c4/.thumbs/42f08a006efc7c3d9a23187da11923.png HTTP/1.0" 200 868 "https://openqa.stg.fedoraproject.org/tests/34881" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
    10.5.126.88 - - [29/Aug/2016:18:52:13 +0000] "GET /image/c0/.thumbs/c3b89ec21864ef8d7686e54e356bb5.png HTTP/1.0" 200 911 "https://openqa.stg.fedoraproject.org/tests/34881" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
    10.5.126.88 - - [29/Aug/2016:18:52:13 +0000] "GET /image/9b/.thumbs/34e5328090e6d3d8b7749c86b3a4ae.png HTTP/1.0" 200 127 "https://openqa.stg.fedoraproject.org/tests/34881" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
    10.5.126.88 - - [29/Aug/2016:18:52:13 +0000] "GET /image/09/.thumbs/51fcbe0106e78c22d0ab367b41162c.png HTTP/1.0" 200 127 "https://openqa.stg.fedoraproject.org/tests/34881" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
    10.5.126.88 - - [29/Aug/2016:18:52:13 +0000] "GET /image/da/.thumbs/6b1139ab38621e89604b95ccd941b4.png HTTP/1.0" 200 127 "https://openqa.stg.fedoraproject.org/tests/34881" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
    10.5.126.88 - - [29/Aug/2016:18:52:13 +0000] "GET /image/ab/.thumbs/a287469a184234665626688a24e2e2.png HTTP/1.0" 200 127 "https://openqa.stg.fedoraproject.org/tests/34881" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
    10.5.126.88 - - [29/Aug/2016:18:52:13 +0000] "GET /image/26/.thumbs/a89eca570dc89e01624f77df33cf88.png HTTP/1.0" 200 1736 "https://openqa.stg.fedoraproject.org/tests/34881" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
    10.5.126.88 - - [29/Aug/2016:18:52:13 +0000] "GET /image/46/.thumbs/de064ad8ef132467cbbb91158db320.png HTTP/1.0" 200 1218 "https://openqa.stg.fedoraproject.org/tests/34881" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
    10.5.126.88 - - [29/Aug/2016:18:52:13 +0000] "GET /image/c5/.thumbs/f15f7f404e951b83f17e5d3bde1717.png HTTP/1.0" 200 127 "https://openqa.stg.fedoraproject.org/tests/34881" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
    10.5.126.88 - - [29/Aug/2016:18:52:13 +0000] "GET /image/37/.thumbs/1f26f3f9c02b2c5ab89f9c917c7603.png HTTP/1.0" 200 127 "https://openqa.stg.fedoraproject.org/tests/34881" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
    10.5.126.88 - - [29/Aug/2016:18:52:13 +0000] "GET /image/fd/.thumbs/4f2bb0d43613b4b28780db3654d552.png HTTP/1.0" 200 127 "https://openqa.stg.fedoraproject.org/tests/34881" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
    10.5.126.88 - - [29/Aug/2016:18:52:13 +0000] "GET /image/27/.thumbs/aeef784db3ef40328483cac42f73f6.png HTTP/1.0" 200 127 "https://openqa.stg.fedoraproject.org/tests/34881" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
    10.5.126.88 - - [29/Aug/2016:18:52:13 +0000] "GET /image/c6/.thumbs/2b4b509195895f2fddedeabfa1ae10.png HTTP/1.0" 200 127 "https://openqa.stg.fedoraproject.org/tests/34881" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
    10.5.126.88 - - [29/Aug/2016:18:52:13 +0000] "GET /image/4b/.thumbs/ec9b42233be156ed4a45c8856efd77.png HTTP/1.0" 200 127 "https://openqa.stg.fedoraproject.org/tests/34881" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
    10.5.126.88 - - [29/Aug/2016:18:52:13 +0000] "GET /image/48/.thumbs/0e4d6b0ad382b375ad8dc24fcc99c2.png HTTP/1.0" 200 127 "https://openqa.stg.fedoraproject.org/tests/34881" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
    10.5.126.88 - - [29/Aug/2016:18:52:13 +0000] "GET /image/2d/.thumbs/63377ec710cad0807f2ad464ea3e8b.png HTTP/1.0" 200 241 "https://openqa.stg.fedoraproject.org/tests/34881" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
    10.5.126.88 - - [29/Aug/2016:18:52:19 +0000] "GET /tests/34881/file/autoinst-log.txt HTTP/1.0" 200 136435 "https://openqa.stg.fedoraproject.org/tests/34881" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
    10.5.126.88 - - [29/Aug/2016:18:54:43 +0000] "GET /tests/34881/file/autoinst-log.txt HTTP/1.0" 304 - "https://openqa.stg.fedoraproject.org/tests/34881" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"

**Comment by AdamWill** [comment]
If we compare to a successful test from after I fully reverted the upload commit - https://openqa.stg.fedoraproject.org/tests/34986 - the `os-autoinst.log` looks basically identical, but there are no 'has no worker' errors in the `openqa-webui` service log. The Apache logs look very similar:

    10.5.124.157 - - [29/Aug/2016:19:59:18 +0000] "POST /api/v1/jobs/34986/status HTTP/1.1" 200 56 "-" "Mojolicious (Perl)"
    10.5.124.157 - - [29/Aug/2016:19:59:28 +0000] "POST /api/v1/jobs/34986/status HTTP/1.1" 200 56 "-" "Mojolicious (Perl)"
    10.5.124.157 - - [29/Aug/2016:20:00:42 +0000] "POST /api/v1/jobs/34986/status HTTP/1.1" 200 56 "-" "Mojolicious (Perl)"
    10.5.124.157 - - [29/Aug/2016:20:00:44 +0000] "POST /api/v1/jobs/34986/artefact HTTP/1.1" 200 102 "-" "Mojolicious (Perl)"
    10.5.124.157 - - [29/Aug/2016:20:04:30 +0000] "POST /api/v1/jobs/34986/ack_temporary HTTP/1.1" 200 2 "-" "Mojolicious (Perl)"
    10.5.124.157 - - [29/Aug/2016:20:04:30 +0000] "POST /api/v1/jobs/34986/artefact HTTP/1.1" 200 2 "-" "Mojolicious (Perl)"
    10.5.124.157 - - [29/Aug/2016:20:04:32 +0000] "POST /api/v1/jobs/34986/artefact HTTP/1.1" 200 2 "-" "Mojolicious (Perl)"
    10.5.124.157 - - [29/Aug/2016:20:04:32 +0000] "POST /api/v1/jobs/34986/artefact HTTP/1.1" 200 2 "-" "Mojolicious (Perl)"
    10.5.124.157 - - [29/Aug/2016:20:04:32 +0000] "POST /api/v1/jobs/34986/artefact HTTP/1.1" 200 2 "-" "Mojolicious (Perl)"
    10.5.124.157 - - [29/Aug/2016:20:04:33 +0000] "POST /api/v1/jobs/34986/status HTTP/1.1" 200 226 "-" "Mojolicious (Perl)"
    10.5.124.157 - - [29/Aug/2016:20:04:33 +0000] "POST /api/v1/jobs/34986/artefact HTTP/1.1" 200 2 "-" "Mojolicious (Perl)"
    10.5.124.157 - - [29/Aug/2016:20:04:33 +0000] "POST /api/v1/jobs/34986/artefact HTTP/1.1" 200 2 "-" "Mojolicious (Perl)"
    10.5.124.157 - - [29/Aug/2016:20:04:33 +0000] "POST /api/v1/jobs/34986/set_done HTTP/1.1" 200 15 "-" "Mojolicious (Perl)"

**Comment by aaannz** [comment]
I checked the sources and those worker warning should not affect the individual calls, but are most definitely symptom of some problem. But how this can affect changes in worker upload code? /me confused

**Comment by AdamWill** [comment]
well, I'm figuring it's this block that helps somehow:

    # This ugly. we need to "block" here so enter ioloop recursively
    while (!$res && Mojo::IOLoop->is_running) {
        Mojo::IOLoop->one_tick;
    }

but I don't know exactly what it is that achieves. Just so we're clear on what I mean by 'reverting', the patch I'm using on top of current git is:

    diff --git a/lib/OpenQA/Worker/Jobs.pm b/lib/OpenQA/Worker/Jobs.pm
    index 2364945..ddfa0a0 100644
    --- a/lib/OpenQA/Worker/Jobs.pm
    +++ b/lib/OpenQA/Worker/Jobs.pm
    @@ -146,7 +146,17 @@ sub upload {
         $boundary =~ s/\W/X/g;
         $tx->req->headers->content_type("$ct; boundary=$boundary");
     
    -    my $res = $OpenQA::Worker::Common::ua->start($tx);
    +    my $res;
    +    $OpenQA::Worker::Common::ua->start(
    +        $tx => sub {
    +            my ($ua, $tx) = @_;
    +            $res = $tx;
    +            return;
    +        });
    +    # This ugly. we need to "block" here so enter ioloop recursively
    +    while (!$res && Mojo::IOLoop->is_running) {
    +        Mojo::IOLoop->one_tick;
    +    }
     
         if (my $err = $res->error) {
             my $msg;

**Comment by aaannz** [comment]
Yeah, I thought the same.
Just an idea, but without calling one_tick and using blocking POST request we may timeout from regular worker update and webui or websocket server may unregister the worker. That would explain missing worker for job. But there are some loose questions like the Mojo::UA is still single threaded so it will block in one_tick eventually anyway.

**Comment by aaannz** [comment]
Thinking further, did you encountered incomplete results regularly even after applying the first patch? Building on the previous though, the check for dead workers is triggered once in 20mins where the worker has 10s to send keep alive message. This countdown starts after worker is registered and doesn't matter if with or without job. So you may be unlucky and hit in this time frame.

Proper solution to this would IMO be to upload the file per parts. But no one started any work on this so far.

**Comment by AdamWill** [comment]
"Thinking further, did you encountered incomplete results regularly even after applying the first patch?"

Yeah, as I said in this discussion: "FWIW, even with this patch, our staging deployment is still getting 'incomplete' for disk upload tests". 34881 was run with the partial reversion from git master - a50e86ac665 , "Re-add boundary hack" - in place.

And again, just to emphasize it: we're still on Mojo 6. It's possible this works OK without the workarounds on Mojo 7, but not Mojo 6. I was at first working on the basis that the changes were Mojo 7-only and was planning out how to get our instances upgraded to Mojo 7 before bumping to current git, but @okurz (IIRC) told me that they're intended to still work with Mojo 6, and you still have instance(s) running on Mojo 6.

**Comment by AdamWill** [comment]
FWIW, https://github.com/os-autoinst/openQA/pull/386 is the PR / commit that introduced that 'blocking' behaviour, but it does not say exactly *why*, beyond the comment text. AFAICS the old bits it replaced did not do the same.

**Comment by aaannz** [comment]
> And again, just to emphasize it: we're still on Mojo 6. It's possible this works OK without the workarounds on Mojo 7, but not Mojo 6. 

I checked the Mojo 6.66 to 7 diff and there isn't anything I think should impact this.

> Yeah, as I said in this discussion: "FWIW, even with this patch, our staging deployment is still getting 'incomplete' for disk upload tests". 

This very well could mean 'we ran one test and it was incomplete". Hence I asked if it is regular.

> FWIW, #386 is the PR / commit that introduced that 'blocking' behaviour, but it does not say exactly why, beyond the comment text. AFAICS the old bits it replaced did not do the same.

Don't know the reasoning either, however previous code was blocking as well. When you call `start()` without callback it is blocking - which was used in old bits. @lnussel changed that to use call back for some reason and thus needed to 'block' by interfering with Mojo::IOLoop.

**Comment by coolo** [comment]
he didn't remember when I removed the workaround :)

I would actually prefer us using plain $ua->post and if there is a problem with it, report it to mojo instead of adding tons and tons of workarounds noone really understands. Vladimir's tests don't really convince me.

@aaannz's theory on the webui shutting down the connection sounds reasonable - even though it wouldn't explain why it's not happening on openqa.opensuse.org, where this code runs peacefully since weeks now.

**Comment by aaannz** [comment]
It was discussed few years back in https://groups.google.com/forum/#!topic/mojolicious/6DNYc3nKAvA/discussion No follow-up since then and I don't know how would anyone solve that besides splitting the file in parts.

**Comment by nadvornik** [comment]
Here is the mojo code:
https://github.com/kraih/mojo/blob/master/lib/Mojo/Content/MultiPart.pm#L40
https://github.com/kraih/mojo/blob/master/lib/Mojo/Asset/File.pm#L53

**Comment by AdamWill** [comment]
@aaannz I only did one full run with the current git master code, and got no successful uploads, I think either two or three failures (the other upload tests failed before attempting to upload the disk). If it's really important I can downgrade and do a couple more runs, but I kinda do need the staging instance to work so I can test other stuff on it (we use it for testing out new tests and so on).

**Comment by AdamWill** [comment]
Hmm, so some more info here. It seems like I'm still getting incompletions even now, so the 'full revert' may not be helping. Here's one that happened overnight:

https://openqa.stg.fedoraproject.org/tests/35802

It has those same tell-tale 'huh?' messages in the server journal:

    Aug 31 14:16:29 openqa-stg01.qa.fedoraproject.org openqa[27165]: [Wed Aug 31 14:16:29 2016] [10359:warn] 35802 got a status update but has no worker. huh?
    Aug 31 14:17:15 openqa-stg01.qa.fedoraproject.org openqa[27165]: [Wed Aug 31 14:17:15 2016] [10359:warn] 35802 got an asset but has no worker. huh?
    Aug 31 14:18:07 openqa-stg01.qa.fedoraproject.org openqa[27165]: [Wed Aug 31 14:18:07 2016] [10712:warn] 35802 got an artefact but has no worker. huh?
    Aug 31 14:18:07 openqa-stg01.qa.fedoraproject.org openqa[27165]: [Wed Aug 31 14:18:07 2016] [10712:warn] 35802 got an artefact but has no worker. huh?
    Aug 31 14:18:07 openqa-stg01.qa.fedoraproject.org openqa[27165]: [Wed Aug 31 14:18:07 2016] [10712:warn] 35802 got an artefact but has no worker. huh?
    Aug 31 14:18:08 openqa-stg01.qa.fedoraproject.org openqa[27165]: [Wed Aug 31 14:18:08 2016] [10712:warn] 35802 got an artefact but has no worker. huh?
    Aug 31 14:18:08 openqa-stg01.qa.fedoraproject.org openqa[27165]: [Wed Aug 31 14:18:08 2016] [10712:warn] 35802 got a status update but has no worker. huh?

I also like @aaannz 's theory about the dead worker check, but I do see one problem with it. Per the source, it seems to log when it aborts a job:

                if ($res) {
                    log_warning(sprintf('dead job %d aborted and duplicated', $job->id));
                }
                else {
                    log_warning(sprintf('dead job %d aborted as incomplete', $job->id));
                }

and I have no such log messages in my journal, AFAICS. I checked the server's journal (the entire thing, not just one unit); is there anywhere else where that message might have wound up?

**Comment by AdamWill** [comment]
in fact, now I know what to look for, I have at least one seemingly identical case in production, which is running git from July 8:

https://openqa.fedoraproject.org/tests/30636

but before 21307cdec3974c334ec5aac30f9508b19d5b6fb2 , this was being hidden: auto-duplication would kick in and re-do the job, so I never really noticed the incompletions. With current git there's no auto-duplication, so it's more obvious and more of a problem.

Let's move discussion somewhere else, I guess, as the failures I've been poking into here don't really seem to be related to the changes to the upload code.

**Comment by coolo** [comment]
yeah, that removing auto-duplication would uncover problems was known. All your logs point into the direction of regular timeouts, but from what you paste it's hard to rebuild the timestamps related to one job.

**Comment by AdamWill** [comment]
After it became clear the stuff I was seeing wasn't really to do with this commit, I moved my follow-ups to https://progress.opensuse.org/issues/13526 , https://github.com/os-autoinst/openQA/pull/844 and https://github.com/os-autoinst/os-autoinst/pull/574 . There's a lot more data there.

I don't actually think auto-duplication has much to do with this at all, because the dead worker checker doesn't rely on the auto-duplication code that was removed; it actually tries to duplicate any job it reaps itself. The dead job checker did get changed recently too; it was moved into the websocket server and the way it worked was changed a bit. The fact that I had several jobs wind up `INCOMPLETE` without being duplicated makes me suspect it doesn't always work properly now, but I decided to focus on stopping jobs from getting erroneously reaped by that check in the first place instead of making sure that it always restarts them properly when it *does* reap them, so I can't prove that for sure. It may have been something transient, because later on I did see some jobs which got `INCOMPLETE`d being duplicated.

**Pull request merged**
