### PR TITLE
Fix time display regression introduced by f127654

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by okurz** [comment]
@Martchus bug introduced by you in f127654. Any idea why you deleted the 'UTC' part?

I am still investigating how a test can catch this.

**Comment by Martchus** [comment]
Because travis says no:

```
#   Failed test 'correct entries shown'
#   at ./t/ui/15-admin-workers.t line 93.
#     Structures begin differing at:
#          $got->[2] = 'NaN years ago'
#     $expected->[2] = 'about an hour ago'
```

Can you describe the regression?

When deleting the UTC part I checked other occurances and there was either ` + "Z"` or no suffix at all. So for consistency I decided to remove the suffix here, too.

**Comment by okurz** [comment]
updated:
* test fixed
* tests extended
* Add "Show absolute time in tests list for finished as well"
* Add "Harmonize running/scheduled time string also in UTC"

**Comment by okurz** [comment]
@colo please check. test coverage regression is certainly not my fault.

**Comment by okurz** [comment]
@aaannz please check. test coverage regression is certainly not my fault.

**Pull request merged**
