### PR TITLE
action #2996 - ensure well formed json for needles

### PR DESCRIPTION
**Pull request by psladek**
validating needle json using module JSON::Schema, and schema definition in 'templates/json/needle.schema'

### CODE REVIEW

**Comment by ancorgs** [comment]
Tidy up :wink:

**Comment by coolo** [comment]
i.e. call ./script/tidy and commit --amend

**Comment by coolo** [comment]
the JSON::Schema package is unpackable. So I decline this

**Comment by psladek** [comment]
yes, sorry for not doing tidy, next time :)
also, what is the cause of JSON::Schema not being packable? Is there really no way to use this module?

**Comment by coolo** [comment]
rule of thumb: only use perl modules you installed from openSUSE package.

**Pull request closed without merging**
