### PR TITLE
fetchneedles: Try to repair needle git repos on detached HEADs

### PR DESCRIPTION
**Pull request by okurz**
Tested on o3

Related progress issue: https://progress.opensuse.org/issues/58373

### CODE REVIEW

**Comment by okurz** [comment]
WDYT?

**Comment by coolo** [comment]
I think we really should have git pull support as minion job, so fetchneedles is nothing but a mojo command to trigger it. And then git pull and git push are protected by minion locks. Doing a git commit and a git rebase in parallel will never be safe

**Comment by Martchus** [comment]
We actually proposed that already: https://progress.opensuse.org/issues/45302#note-3

**Comment by okurz** [comment]
@coolo @Martchus we can do and plan to do what you propose but for now I would go with this. Updated the code after I tested on o3.

**Pull request merged**
