### PR TITLE
travis replacement; docs improvement; spec fix

### PR DESCRIPTION
**Pull request by okurz**
* Replace all references of "TRAVIS" with a generic term or CircleCI
* docs: Move whole .circle CI README into docs/ to include in generated and published content
* docs: Focus on openQA-devel for easier test setup
* docs: Fix reference to "docker/travis_test"
* .circleci: Use common repo aliases
* spec: Specify missing "chromedriver" in -devel

### CODE REVIEW

**Comment by okurz** [comment]
@andrii-suse I missed to ask you for your opinion. What do you think about the change?

**Comment by andrii-suse** [comment]
Looks solid, the only thing I am strongly against is hard requirement on chromedriver, but I guess this approach was accepted long time ago by everyone else, so I must accept it as well.

**Comment by okurz** [comment]
sure, but the chromedriver package is *only* required for the "devel" package, i.e. neither build nor run time dependencies for the package itself, only when we as humans want to develop+test or CI systems. We could of course split these further and make chromedriver a recommends

**Comment by andrii-suse** [comment]
It was in recommended package and everyone could develop and run backend tests without it. My point is that it may be a challenge to get chromedriver in some cases in some environments where we what to e.g. test or troubleshoot only worker-side behavior.

**Comment by okurz** [comment]
true but the challenge should only be met when one installs openQA-devel which is the "full" environment. If needed we can of course also split the devel package per other subpackages but that's certainly more development and testing effort for us to ensure working

**Comment by andrii-suse** [comment]
yes, openQA-devel becomes "full" after adding packages into it like here. And I do not like it and think we could keep openQA-devel as "essential' with "of course we can create also maintain full devel package but that's certainly more development and testing effort for us to ensure both are working"

**Comment by Martchus** [comment]
I agree with @okurz about the meaning of the openQA-devel package. Note that this is also just a meta package. So if you don't need all of its dependencies in a particular case just install what you need manually.

**Pull request merged**
