### PR TITLE
Drop OpenQA::WebAPI::Plugin::HashedParams

### PR DESCRIPTION
**Pull request by asdil12**
Ticket: https://progress.opensuse.org/issues/64412

This will drop the legacy support for `application/x-www-form-urlencoded` requests handled via the AdminTables code on the server side.
Instead only the new `application/json` requests will be supported.
This is only affecting `POST` and `PUT` requests.
`GET` requests can still filter using query parameters.

This is mostly due to the odd way that nested hashes for settings variables were encoded in the flat `x-www-form-urlencoded` structure (e.g. `settings[FOO]=bar&settings[baz]=abc`).

The webui is already moved to the new json requests.

This change will remove backwards compatibility with the old requests for these API routes:

```
/api/v1/products
```

```
/api/v1/machines
```

```
/api/v1/test_suites
```

Importing job templates should continue to work fine as this PR also updates `openqa-load-templates` to json.

@AdamWill @phil-hands @marmarek FYI

### CODE REVIEW

**Review by okurz — CHANGES_REQUESTED** [review]
Failed CI tests related to your changes

**Comment by kalikiana** [comment]
```
[13:39:35] t/ui/23-audit-log.t ........................ 11/? 
    #   Failed test '200 OK'
    #   at t/ui/23-audit-log.t line 100.
    #          got: '400'
    #     expected: '200'

    #   Failed test '200 OK'
    #   at t/ui/23-audit-log.t line 101.
    #          got: '400'
    #     expected: '200'

    #   Failed test '200 OK'
    #   at t/ui/23-audit-log.t line 102.
    #          got: '400'
    #     expected: '200'

    #   Failed test 'event emitted'
    #   at t/ui/23-audit-log.t line 110.

    #   Failed test 'all rows displayed without filter and before posting job/comment'
    #   at t/ui/23-audit-log.t line 41.
    #          got: '5'
    #     expected: '8'

    #   Failed test 'most rows filtered out when searching for table create events'
    #   at t/ui/23-audit-log.t line 41.
    #          got: '1'
    #     expected: '3'
    # Looks like you failed 6 tests of 10.
[13:39:35] t/ui/23-audit-log.t ........................ 12/? 
#   Failed test 'clickable events'
#   at t/ui/23-audit-log.t line 151.
findChildElement: no such element: Unable to locate element: {"method":"css selector","selector":".audit_event_details"} at /home/squamata/project/t/ui/../lib/OpenQA/SeleniumTest.pm:78 at /home/squamata/project/t/ui/../lib/OpenQA/SeleniumTest.pm line 81.
```

**Review by Martchus — APPROVED** [review]

**Comment by Martchus** [comment]
The TW package check fails:

```
[  451s] usermod: group 'kvm' does not exist
[  451s] error: %prein(openQA-worker-4.6.1728050994.ac438c0d-7249.1.x86_64) scriptlet failed, exit status 6
[  451s] error: openQA-worker-4.6.1728050994.ac438c0d-7249.1.x86_64: install failed
```

You probably need to rebase to have at least 1acf501cdf6c8dde84053c102b15b38fdb98fe33.

**Comment by kalikiana** [comment]
@mergifyio rebase

**Review by kalikiana — APPROVED** [review]

**Review by Martchus — APPROVED** [review]

**Review by okurz — APPROVED** [review]

**Comment by perlpunk** [comment]
This is causing problem for scripts using openqa-load-templates from the regular repo, like https://build.opensuse.org/projects/devel:openQA:ci:Tooling/packages/qam-openqa-yaml-ci/files/Dockerfile?expand=1

**Pull request merged**
