### PR TITLE
Prevent experimental use of keys on scalar

### PR DESCRIPTION
**Pull request by okurz**
Fixes perl warning on more recent version.

### CODE REVIEW

**Comment by coolo** [comment]
As in past sle10 version? :)

This is just a bug - and newer perl versions somewhat make it work as beginners often do this wrong.

**Comment by okurz** [comment]
yep, it's my baby perl with errors

**Comment by coolo** [comment]
this route doesn't seem to be covered at all - because when I call it here I get "Experimental keys on scalar is now forbidden at template admin/workers/show.html.ep line 31.", which is just 5 lines deeper in that template

**Comment by okurz** [comment]
the route certainly is covered by tests. I verified with `t/ui/15-admin-workers.t` but on Leap, i.e. perl 5.18, not tumbleweed version (5.22?). see what I wrote in #742

**Comment by coolo** [comment]
but t/ui/15-admin-workers.t doesn't barf on TW either, but going there does. Mocking data vs. real data I suppose

**Comment by coolo** [comment]
ok, I take that back - it does barf. fixed now

**Pull request merged**
