### PR TITLE
Fix download of fixed assets from web UI

### PR DESCRIPTION
**Pull request by AdamWill**
The function which constructs URL redirects for test assets
wasn't adapted to the addition of fixed asset directories, so
fix that. Extend the relevant tests to cover this stuff.

Just to explain the gru `limit_assets` test change, in case it's not obvious: we now have a real fake fixed asset, so we don't need to mock up `is_fixed` to check that fixed assets are skipped by `limit_assets`; if that stops working, all the `limit_assets` tests will stop working because the 'fixed' asset will be included in the calculations and so the expected math will be off and more stuff will be removed than we expected. Hope that makes sense.

### CODE REVIEW

**Comment by AdamWill** [comment]
@coolo

**Comment by AdamWill** [comment]
fuck you, tidy. fuck your whole fucking existence.

**Comment by AdamWill** [comment]
the changes tidy is suggesting seem bizarre. The only change I made to `01-jobs.pl` was to the `jobs_assets` line, but tidy suddenly wants to change a whole bunch of other stuff. anyone know what the hell it's on about?

**Comment by coolo** [comment]
Yeah, tidy's behaviour of reindenting everything for hash assignments is a bit noisy. But it's the way we want it (for now).

But there are some things in your PR I didn't like, so I edited it for #985

**Pull request closed without merging**
