### PR TITLE
circleci: Strip down base image to prevent "cache" jobs failing

### PR DESCRIPTION
**Pull request by okurz**
The combination of a heavy image in combination with downloading from slow
registry.opensuse.org to circleCI workers have a significant impact causing
frequent failures in the "cache" step of circleCI when the 542MB blob of the
base image is downloaded. As we can not configure circleCI to retry the
download or apply a longer timeout than 20 minutes this means that manual
interaction is necessary to retry. Even if the download works the initial
container image download is normally not cached whereas we do cache the rpm
packages. Downloading a smaller container image and installing all packages
from the internal cache is faster than trying to put as much as possible into
the base container image.

This commit strips down the base image to the bare minimum to only provide what
circleCI needs to save/restore the cache. At time of writing the result
container image size is 42MB (vs. 542MB). Then we rely on the package install
within the "cache" step to install all dependencies for which we can also apply
timeouts and retry values ourselves in case that ever causes a problem.

In before the "cache" job took some minutes up to 20 minutes and jobs
like "t" take an equal emount for "Spin up environment" downloading the
big container image.with "Install cached packages" taken around 6s. With
this commit "cache" should only take seconds for "Spin up environment"
and "Generate packaged assets" taking around 4m to install packages that
go into the cache. Jobs like "t" then also take seconds for "Spin up 
environment" and around 1m in "Install cached packages" installing more
packages.

Related progress issue: https://progress.opensuse.org/issues/67855

### CODE REVIEW

**Review by andrii-suse — APPROVED** [review]
If we accept it - the nightly job will probably try to manage exact versions of added packages, I guess it is OK.

**Comment by okurz** [comment]
that's my assumption as well, yes.

**Review by Martchus — APPROVED** [review]
Considering that `chromedriver` updates broke our tests in the past it actually seems beneficial to track its version explicitly. For the other dependencies it can not hurt as well.

**Comment by okurz** [comment]
@Martchus the nightly dep update should put the specific versions there. But if we never merge this PR here then the nightly dep update will be so unstable that it hardly has a chance to finish :D

As now mergify failed due to the base branch not being up-to-date I will rebase. Maybe the PR will then be automatically merged.

**Comment by Martchus** [comment]
> the nightly dep update should put the specific versions there.

I know that we don't add the versions manually.

Unfortunately the CI fails downloading from https://registry.opensuse.org - likely related to the Nürnberg/Maxfeld outage.

**Pull request merged**
