### PR TITLE
activity view: populate jobs in batches

### PR DESCRIPTION
**Pull request by kalikiana**
This is to avoid hitting resource limits by making too many ajax requests at the same time.

With a sufficient amount of `job_` events in the activity view, the browser may become unresponsive and also throw errors because the requests fail.

See: https://progress.opensuse.org/issues/58304

### CODE REVIEW

**Review by Martchus — COMMENTED** [review]
Definitely better than before, also the limit to 5000 results. I'm only wondering whether it would be better to create a new route which returns all the data we want to show at once (although it is also kind of nice to see already the first jobs while the rest is still loading).

**Review by okurz — COMMENTED** [review]
You managed to introduce four different magic numbers in this seemingly simple change. This looks it could be done better. Also, do we really need to manually call a for loop and do the calculation this way in javascript code? Isn't that such a common problem that a better approach must exist including the backing off with timeout?

**Comment by kalikiana** [comment]
> You managed to introduce four different magic numbers in this seemingly simple change. This looks it could be done better. Also, do we really need to manually call a for loop and do the calculation this way in javascript code? Isn't that such a common problem that a better approach must exist including the backing off with timeout?

I'm not aware that standard Javascript has a natural solution for that. I think we can hold off on this for now anyway since it only affects extreme cases and regular users seem to be okay with the current code. And we can revisit it later if needed.

**Comment by Martchus** [comment]
I would at least add `&length=5000` to the query. It is really not nice to have a page which doesn't scale or has no limit.

**Comment by kalikiana** [comment]
> I would at least add `&length=5000` to the query. It is really not nice to have a page which doesn't scale or has no limit.

That on its own will not address the issues. Even the search can handle more than that with more data. It's the two many individual requests being made.

**Pull request closed without merging**
