### PR TITLE
Migrate to Bootstrap 5 with minor UI tweaks and improvements of the darkmode

### PR DESCRIPTION
**Pull request by Martchus**
I kept the first three commits separate because those are from @b10n1k. However, it makes most sense to review the overall diff and checkout the particular commits only for the commit messages.

This PR supersedes https://github.com/os-autoinst/openQA/pull/5621.

Related ticket: https://progress.opensuse.org/issues/159408

### CODE REVIEW

**Comment by Martchus** [comment]
I'll provide screenshots tomorrow but it would be best if you try it out locally. Note that the darkmode is still messy but at least better than it was before.

**Review by okurz — COMMENTED** [review]
Given the huge amount of changes I couldn't actually review all specific changes but overall this looks good an also an improvement to before. Won't approve before CI failures are fixed

**Comment by perlpunk** [comment]
Is there anything else besides `make node_modules` that I have to run?
When I checkout your branch, it looks like no CSS is loaded at all.

**Comment by perlpunk** [comment]
Ah, I missed an error in the webui log:
```
Error: $color: "var(--bs-emphasis-color-rgb)" is not a color for `rgba'
        on line 746 of /home/tina/openqa-toolbox/repos/openQA/node_modules/bootstrap/scss/_variables.scss
        from line 8 of /home/tina/openqa-toolbox/repos/openQA/node_modules/bootstrap/scss/bootstrap.scss
        from line 12 of standard input
  Use --trace for backtrace.
```
What should I do about it?

**Comment by Martchus** [comment]
Ok, maybe something is actually still broken. That may also explain the CI failures which I couldn't reproduce locally so far.

**Comment by perlpunk** [comment]
I also tried out a fresh leap 15.5 container and see the same as in Tumbleweed now.

**Comment by Martchus** [comment]
I'm actually also getting

```
t/ui/10-tests_overview.t .. Error: $color: "var(--bs-emphasis-color-rgb)" is not a color for `rgba'
        on line 746 of /opt/testing_area/repo/node_modules/bootstrap/scss/_variables.scss
        from line 8 of /opt/testing_area/repo/node_modules/bootstrap/scss/bootstrap.scss
        from line 12 of standard input
  Use --trace for backtrace.
t/ui/10-tests_overview.t .. 1/? clickElement: element not interactable at /opt/testing_area/repo/t/ui/../lib/OpenQA/SeleniumTest.pm:78 at /opt/testing_area/repo/t/ui/../lib/OpenQA/SeleniumTest.pm line 81.
        OpenQA::SeleniumTest::__ANON__(Test::Selenium::Chrome=HASH(0x560a7052c910), "Error while executing command: clickElement: element not inte"..., HASH(0x560a706ff620)) called at /usr/lib/perl5/vendor_perl/5.26.1/Selenium/Remote/Driver.pm line 356
```

when running e.g. `make test TESTS=t/ui/10-tests_overview.t` in our CI container. The first error is probably preventing my change for disabling scroll animations to work and thus we then run into the error about the element being not interactable. I'm not yet sure why we get this error, tough. It should be able to resolve the variable which does contain a valid value.

**Comment by Martchus** [comment]
Here a few random screenshots - not much has changed:
grafik
grafik

Here the darkmode - it still needs improvement but it already looks better on the selection page:
grafik
grafik
grafik

**Comment by Martchus** [comment]
Hopefully the tests will pass after my latest change. Technically only [Migrate validation code of job group form to Bootstrap 5](https://github.com/os-autoinst/openQA/pull/5678/commits/15d521b5e6f666e7547091c922bfbee3d6629698) is required but since I was modernizing and tweaking anyway I also added [Fix validation of job/parent group forms](https://github.com/os-autoinst/openQA/pull/5678/commits/b1c1478c1fdbe042751c4134bdf5038fd6c04f36).

When testing I noticed that it is not possible to set the "Keep … for" durations of parent groups anymore. However, this is not a regression of my changes, e.g. it also doesn't work on https://openqa.suse.de/admin/edit_parent_group/15. However, maybe that should be part of another PR as it is probably a problem on the backend side and not a UI tweak.

**Comment by perlpunk** [comment]
> When testing I noticed that it is not possible to set the "Keep … for" durations of parent groups anymore. However, this is not a regression of my changes, e.g. it also doesn't work on https://openqa.suse.de/admin/edit_parent_group/15. However, maybe that should be part of another PR as it is probably a problem on the backend side and not a UI tweak.

I created https://progress.opensuse.org/issues/161957

**Comment by okurz** [comment]
https://github.com/os-autoinst/openQA/pull/5683 including the fix for https://progress.opensuse.org/issues/161957 was merged. Will trigger rebase

**Comment by okurz** [comment]
@mergifyio rebase

**Comment by okurz** [comment]
CI failed in https://app.circleci.com/pipelines/github/os-autoinst/openQA/13754/workflows/771b4766-dcee-44e2-859d-6fe9325d4c7d/jobs/129197/parallel-runs/0/steps/0-108?invite=true#step-108-11290_65

**Review by okurz — APPROVED** [review]

**Review by kalikiana — APPROVED** [review]
I like the incidental dark mode fixes 😎

**Pull request merged**
