### PR TITLE
Dependency cron 2021-01-29

### PR DESCRIPTION
**Pull request by openqabot**

### CODE REVIEW

**Comment by okurz** [comment]
@kraih tests fail due to a timeout in t/deploy.t. As I do not remember seeing that fail in before I suspect the perl-Mojolicious changes to cause this. Another problem are many new warnings like:

```
[02:28:29] t/03-auth.t ............................................... 5/? Use of uninitialized value $expr2 in substitution (s///) at /home/squamata/project/t/lib/OpenQA/Test/PatchDeparse.pm line 43.
Use of uninitialized value $expr2 in concatenation (.) or string at /home/squamata/project/t/lib/OpenQA/Test/PatchDeparse.pm line 44.
Use of uninitialized value $expr2 in substitution (s///) at /home/squamata/project/t/lib/OpenQA/Test/PatchDeparse.pm line 43.
Use of uninitialized value $expr2 in concatenation (.) or string at /home/squamata/project/t/lib/OpenQA/Test/PatchDeparse.pm line 44.
Use of uninitialized value $expr2 in substitution (s///) at /home/squamata/project/t/lib/OpenQA/Test/PatchDeparse.pm line 43.
Use of uninitialized value $expr2 in concatenation (.) or string at /home/squamata/project/t/lib/OpenQA/Test/PatchDeparse.pm line 44.
Use of uninitialized value $expr2 in substitution (s///) at /home/squamata/project/t/lib/OpenQA/Test/PatchDeparse.pm line 43.
Use of uninitialized value $expr2 in concatenation (.) or string at /home/squamata/project/t/lib/OpenQA/Test/PatchDeparse.pm line 44.
Use of uninitialized value $expr2 in substitution (s///) at /home/squamata/project/t/lib/OpenQA/Test/PatchDeparse.pm line 43.
Use of uninitialized value $expr2 in concatenation (.) or string at /home/squamata/project/t/lib/OpenQA/Test/PatchDeparse.pm line 44.
Use of uninitialized value $expr2 in substitution (s///) at /home/squamata/project/t/lib/OpenQA/Test/PatchDeparse.pm line 43.
Use of uninitialized value $expr2 in concatenation (.) or string at /home/squamata/project/t/lib/OpenQA/Test/PatchDeparse.pm line 44.
Use of uninitialized value $expr2 in substitution (s///) at /home/squamata/project/t/lib/OpenQA/Test/PatchDeparse.pm line 43.
Use of uninitialized value $expr2 in concatenation (.) or string at /home/squamata/project/t/lib/OpenQA/Test/PatchDeparse.pm line 44.
Use of uninitialized value $expr2 in substitution (s///) at /home/squamata/project/t/lib/OpenQA/Test/PatchDeparse.pm line 43.
Use of uninitialized value $expr2 in concatenation (.) or string at /home/squamata/project/t/lib/OpenQA/Test/PatchDeparse.pm line 44.
Use of uninitialized value $expr2 in substitution (s///) at /home/squamata/project/t/lib/OpenQA/Test/PatchDeparse.pm line 43.
Use of uninitialized value $expr2 in concatenation (.) or string at /home/squamata/project/t/lib/OpenQA/Test/PatchDeparse.pm line 44.
Use of uninitialized value $expr2 in substitution (s///) at /home/squamata/project/t/lib/OpenQA/Test/PatchDeparse.pm line 43.
Use of uninitialized value $expr2 in concatenation (.) or string at /home/squamata/project/t/lib/OpenQA/Test/PatchDeparse.pm line 44.
```

could you take a look?

**Comment by Martchus** [comment]
Seems like our patching for the `B::Parse` module needs to be adjusted. Maybe also a new version of `perl-base` causes this (which contains that module)? We don't track the `perl-base` package so it could be possible. By the way it looks like it eventually fails due to the timeout and not because of these warnings.

**Comment by perlpunk** [comment]
I will update the B::Deparse patch.

**Comment by perlpunk** [comment]
See #3701 for the updated patch and the dependency update for Mojolicious

**Pull request closed without merging**
