### PR TITLE
Tests parser - general parsing framework to map external tests results from external sources

### PR DESCRIPTION
**Pull request by mudler**
this PR includes the parser object and its self-tests, also exposes an api endpoint (not used still) that will parse uploaded tests as openQA running test modules using the parser.

I still need to finish documenting its usage/extension - every class comes with a POD documentation illustrating it's usage, this was done to allow us extending with different formats in the future and mainly to help with https://github.com/os-autoinst/openQA/pull/1492 ( for the brave, the usage is shown in the unit tests ).

The parser is capable of reading files, and mapping them to an internal representation that can be translated to an OpenQA test module - it also allows to serialize and deserialize itself using Storable and JSON, allowing to store the results of the parsing for a later reuse.

As for now supports XUnit and JUnit (separated, to avoid breaking current tests),  LTP format v1, v2 (backward compatible) and they came with unit tests against the format. ~~( planning to add support for also XUnit in this PR )~~

Currently serialization (should) support also deep nested result objects (since it's implemented recursively)
it will map them automatically during deserialization resolving them to the respective type ~~but this is not fully supported yet since need to write specific unit tests for that~~

---

The parser is a base class that acts as a serializer/deserializer for the elements inside of it,  it allows to be extended so we can always include new formats to our mapping process.

It is not the ultimate solution for parsing, and it's not perfect but i believe it's extensive enough to allow us to use it long-term.

It is split in 2 parts that are isolated in the code (schema for structured data, and parser for it), allowing us to:

- read a generic/custom format with different base (XML, JSON)
- map the file structure to an internal format, that can be understood later by openQA - used to translate into tests
- declare specific Perl classes that are going to fit the data (as in DBI, or other schema-oriented frameworks, but it is optional)

In case of unstructured data, there is no need of declaring the structure that will hold the data, it will be always parsed, but you won't be able to use any methods provided by base classes.

## OOP Interface

Every specific parser implementation (JUnit, XUnit, LTP, ecc.. ) has the freedom of choosing what data to retain and how to access them. So, when providing support for a specific format, documentation on how to access the data _needs_ to be provided as well with the specific parser.

The base class is exposing 4 Mojo::Collections available, according to what openQA would require to map the results correctly, 1 extra collection is provided for arbitrary data that can be exposed. The collections represents respectively: test results, test definition and test output.

### Structured data

In structured data mode, elements of the collections are objects. They can be of any type, even tho subclassing or objects of type of ```OpenQA::Parser::Result``` are prefered. 

Indeed there is one caveat with structured data: in case you need to parse deeply nested objects, as in form of hash of hashes, array of hashes, or more nested data types you can think of - all of them needs to subclass ```OpenQA::Parser::Result``` or ```OpenQA::Parser::Results``` to represent Hashes or arrays respectively.

```perl
use OpenQA::Parser::Format::JUnit;

my $parser_result = OpenQA::Parser::Format::JUnit->new->load("file.xml");

# Now we can access to parsed tests as seen by openQA:

$parser_result->tests->each(sub { 

   my $test = shift;
   print "Test name: ".$test->name;

});

my @all = $parser_result->tests->each;
my @tests = $parser->tests->search(name => qr/1_running_upstream_tests/);
my $first = $parser->tests->search(name => qr/1_running_upstream_tests/)->first();

my $binary_data = $parser->serialize();

# Now, we can also store $binary_data and retrieve it later.

my $new_parser_from_binary = OpenQA::Parser::Format::JUnit->new->deserialize($binary_data);

# thus this works as expected:
$new_parser_from_binary->tests->each( sub { 

   my $test = shift;
   print "Test name: ".$test->name;

});

# We can also serialize all to JSON

my $json_serialization = $parser->to_json;

# save it and access it later

my $from_json = OpenQA::Parser::Format::JUnit->from_json($json_serialization);

```
As JUnit supports tests and testcases, the parser provides a specific option to join the results together, but it's shown later.

As an example, in the webapi change that is included in this PR, we parse the JUnit and add running module test to the job in a general way, without relaying on how to actually parse the data:

```perl

    $parser->load($tmp_extra_test)->results->each(
        sub {
            my $result = shift;
            my $t_info = $result->test->to_hash;
            $self->insert_module($t_info);
            $self->update_module($result->test->name, $result->to_hash);
        });

    $parser->write_output($self->result_dir); # generates openQA files relative to the tests/results
```

### Unstructured data

To parse unstructured data, declaring a specific parser implementation is needed, since we need to _map_ a format inside a representation that we can use, and openQA can understand as well.

e.g. this is a light (useless, just educative) and small implementation that will just add one result:

```perl
{
    package OpenQA::Parser::Dummy;
    use Mojo::Base 'OpenQA::Parser'; # This is required
    sub parse { 
       my $parser = shift;
       $parser->_add_result(name => 'test'); 
    }
}
.....

# Then you can load the parser and access to the result

my $parsed_res = OpenQA::Parser::Dummy->new;

$parsed_res->parse;

my $count=$parsed_res->results->size() # yields 1

my $t_name = $parsed_res->results->first->get('name')->val(); # yields to test

 $parsed_res->results->first->{'name'}; # yields to test
```

Now let's see a more useful custom parsing solution for unstructured data. Let's suppose we want to decode results from one JSON file format ( taking the web-app/ servlet-name example in http://json.org/example.html ) .

The file looks like this:

```JSON
...
"web-app": {
  "servlet": [  
    {
      "servlet-name": "cofaxCDS", 
      "servlet-class": "org.cofax.cds.CDSServlet",
      "init-param": {
        "configGlossary:installationAt": "Philadelphia, PA",

```

servlet is our array of results that we want to provide, each of them has a servlet-name and an optional 'init-param'.

So we could just focus on how to map the data, and write:
```perl
{
    package OpenQA::Parser::UnstructuredDummy;
    use Mojo::Base 'OpenQA::Parser';
    use Mojo::JSON 'decode_json';

    sub parse() {
        my ($self, $json) = @_;
        die "No JSON given/loaded" unless $json;
        my $decoded_json = decode_json $json;

        foreach my $res (@{$decoded_json->{'web-app'}->{servlet}}) {
            $self->_add_result($res);
            # equivalent to $self->results->add(OpenQA::Parser::Result->new($res));
            # is this a test definition?   $self->tests->add(..);
        }
        $self;
    }

}
```

and using it like this:

```perl
    my $parser = OpenQA::Parser::UnstructuredDummy->new();

    $parser->load("my-json-file");
    
    my $count = $parser->results->size;

    $parser->results->each(
        sub {
            my $result = shift;
            print $result->get('servlet-name')->val."\n";
            # or even $result->{'servlet-name'};
        });

    my $serialized   = $parser->serialize();
    my $deserialized = OpenQA::Parser::UnstructuredDummy->new()->deserialize($serialized);

    # this works as expected:
    $deserialized->results->each(
        sub {
            my $result = shift;
             print $result->get('servlet-name')->val."\n";
            # or even $result->{'servlet-name'};
        });
    my $count = $deserialized->results->size;

    # Keep accessing to nested data, without having much to care.
    # get() returns a OpenQA::Parser::Result::Node, it will try to autoload your data (best-effort)
    # so in case it maps nicely, you can

    $deserialized->results->first->get('init-param')->nestedattribute();

   # if your structure have nestedattribute { init-param => { nestedattribute => 42 }
```

To note: arguments to Results constructor gets mapped automatically, so you can add results that contains nested structures, and access to them.

Going back to the simplest example, we could add more data to our result:

```perl
{
    package OpenQA::Parser::Dummy;
    use Mojo::Base 'OpenQA::Parser'; # This is required
    sub parse { 
       my $parser = shift;
       $parser->_add_result(name => 'test', test => { foo=> 1 } ); 
    }
}


my $parsed_res = OpenQA::Parser::Dummy->new;

$parsed_res->parse;

my $count=$parsed_res->results->size() # yields 1

my $t_name = $parsed_res->results->first->get('test')->val->{foo}; # yields to 1
```

This also means that we can **split** specific custom parsing solution even in test repositories, if we don't want to provide them in the openQA package itself.

## Alternative / Functional interface

An alternative / functional interface is also provided to be able to resolve different parsers without loading them explictly:

```perl
   use OpenQA::Parser 'parser'; # no need to 'use' every single parser implementation

   my $parsed_file = parser( JUnit => "my.xml"); # equivalent to parser("JUnit")->load("my.xml");
   $parsed_file->results->each(
        sub {
            my $result = shift;
             # Access to single result
        });

```
This can be particularly useful e.g. when gathering stats from multiple files, with different type format.

As collections are [Mojo::Collections](https://metacpan.org/pod/Mojo::Collection) they inheritate all the properties from it, and all operations can be performed (_map_, _reduce_, _reverse_, _shuffle_, _sort_, ecc.. ) but keep in mind that inside the parser collection there can be any arbitrary type of data, so operations must be performed within a subroutine checking the right data type (e.g. ```each->(sub { operation })``` as they get serialized automatically.

## Extending / Adding support for other formats

In case of providing support for a new format, and if we want also to structure the data, aside from writing the custom parser for it, we just need to declare objects that fits the data, in a pseudo-DBI-schema style as for e.g. LTP is as defined:

```perl
{
package OpenQA::Parser::Result::LTP::Test;
use Mojo::Base 'OpenQA::Parser::Result'; # to note - subclass of OpenQA::Parser::Result

# Our main result object

 # we have an environment, that has it's own type
has environment => sub { OpenQA::Parser::Result::LTP::Environment->new() };

# we have a test with a specific default schema - we need to specify it
has test        => sub { OpenQA::Parser::Result::LTP::SubTest->new() };

# those are going to contains just strings, so let's just declare them as attributes of the object
has [qw(status test_fqn)];

# we could also rewrite this as:
# has 'status';
# has 'test_fqn';

}

{
    package OpenQA::Parser::Result::LTP::SubTest;
    use Mojo::Base 'OpenQA::Parser::Result';

    # same - those are going to contains just string, so let's just declare them as attributes of the object
    has [qw(log duration result)];
}

{
    package OpenQA::Parser::Result::LTP::Environment;
    use Mojo::Base 'OpenQA::Parser::Result';

    # same - those are going to contains just string, so let's just declare them
    has [qw(gcc product revision kernel ltp_version harness libc arch)];
}

```

As we add the items during the parsing phase, they get mapped and at the end they can be serialized (both with JSON and Storable). 

### Search and retrieve data from multiple files (serialized/not)

```perl
use feature 'say';

use OpenQA::Parser qw(parser);

foreach my $file (qw( new_ltp_result_array.json ltp_test_result_format.json )) {

	my $parser = parser( LTP => $file );

	# E.g serialize it and retrieve (normally it would be only retrieved)

	my $frozen=$parser->serialize();

	# ...save $frozen on a file, DB field, ...
	# and take it back 

	my $data = parser('LTP')->deserialize($frozen);

	say '[file: '.$file.'] Searching for tests that contains "syscalls" in the "test_fqn" field';


	my $syscalls_results = $data->results->search( test_fqn => qr/syscalls/ );

	# $syscalls_results->each(..) or 
	# you can also chain all
	$data->results->search( test_fqn => qr/syscalls/ )->each(sub {
			say "\t Test name: ".$_->name().' Status: '.$_->status;
		});
}

# Now let's cut results to the ones that took more than 0.2
foreach my $file (qw( new_ltp_result_array.json ltp_test_result_format.json )) {

	my $parser = parser( LTP => $file );

	my $frozen=$parser->to_json();

	# It can be also saved as plain json

	my $data = parser('LTP')->from_json($frozen);

	say '[file: '.$file.'] Searching for tests that last more than 0.2';

	$data->results->each( sub {
		say "\t [".$_->test->duration."] Test name: ".$_->name().' Status: '.$_->status if $_->test->duration > 0.2;
	});

}
```

### Join result and save results to retrieve it back later

```perl
use feature 'say';

use OpenQA::Parser qw(parser p); # p is an alias to parser() constructor

my $join = p('Base'); # If nothing specified, Base format is implied

foreach my $file (qw( new_ltp_result_array.json ltp_test_result_format.json )) {

	my $parser = parser( LTP => $file );

	my $frozen=$parser->serialize();

	my $data = parser('LTP')->deserialize($frozen);

	my $syscalls_results = $data->results->search( test_fqn => qr/syscalls/ );

	$data->results->search( test_fqn => qr/syscalls/ )->each(sub {
		$join->results->add($_);
	});
}


foreach my $file (qw( new_ltp_result_array.json ltp_test_result_format.json )) {

	my $parser = parser( LTP => $file );

	my $frozen=$parser->to_json();

	my $data = parser('LTP')->from_json($frozen);

	$data->results->each( sub {
		$join->results->add($_)  if $_->test->duration > 0.2;
	});
}

# Store again the result of our search
my $frozen=$join->to_json();
my $data = parser('Base')->from_json($frozen);

say $data->results->size.' results';

$data->results->each( sub {
	say $_->name;
});
```

### Combine different parser's results into one

```perl
use OpenQA::Parser qw(parser p);

my $join = p();

foreach my $file (qw( new_ltp_result_array.json ltp_test_result_format.json )) {

	my $parser = parser( LTP => $file );

	# E.g serialize it and retrieve (normally it would be only retrieved)
	my $frozen=$parser->serialize();

	# ...save $frozen on a file, DB field, ...
	# and take it back 

	my $data = parser('LTP')->deserialize($frozen);

	# We can even do this:
	$join->results()->add($data);
}

my $frozen=$join->serialize();	
my $data = parser()->deserialize($frozen);

$data->results->first->results->each( sub {
	say $_->name;
});

$data->results->last->results->each( sub {
	say $_->name;
});
```

[contd]

### CODE REVIEW

**Comment by richiejp** [comment]
I haven't read it in detail, but this looks really good from a top level view! The English is not so good in places, but I will wait until the code is signed off before commenting on that.

I am wondering if the UI can somehow be generated from the parsers (in a very limited way). Perhaps the parser could provide display hints which decide what columns to display and which type to display them as. This would mean that we could just update the parser for _basic_ display or format changes without having to touch the UI code.

**Comment by mudler** [comment]
Yeah, it will be a hard road for me to document it properly :-)

To answer to your question, that can be implemented inside the schema: since the parser will reconstruct the tree with all the objects type respecting it, you can just add a method that renders the data (this is actually **how** everything is serialized with JSON and Storable) or an extra attribute that you can access later .

E.g. to your schema definition, you can add '_to_html()_' (silly example, just displaying the status)
```perl
{
   package OpenQA::Parser::Result::LTP::Test;
   use Mojo::Base 'OpenQA::Parser::Result';

   has environment => sub { OpenQA::Parser::Result::LTP::Environment->new() };
   has test        => sub { OpenQA::Parser::Result::LTP::SubTest->new() };
   has [qw(status test_fqn)];
   has 'display_columns'; # we could create an extra field as well, and we can control even if needs to be hidden when exported to JSON or with Storable (yet to be documented)

   sub to_html {
        "<pre>".shift()->status."</pre>"
    }

}

# ..  you can use it later after deserialization, or after parsing:

   use OpenQA::Parser 'parser'; # no need to 'use' every single parser implementation

   my $parsed_file = parser( 'LTP ')->deserialize($bin);
   $parsed_file->results->each(
        sub {
            my $result = shift;
             my $html = $result->to_html;
        });

```

**Comment by richiejp** [comment]
Makes sense except that it might be better to produce some intermediate format (model) which the UI (view) consumes and turns into a pretty webpage. Instead of producing HTML directly from the parser which you may want to decouple from the CSS and Javascript which the UI is using.

On the other hand we could easily use this to spit out Metan's HTML/JS table, so it looks good to me either way.

**Comment by mudler** [comment]
Isn't in this way the UI able to consume it? The result of the parsing is a specific object that can be consumed (maybe it will be a bit more clear after documentation is there )

**Comment by Martchus** [comment]
Let me summarize this to find out whether I understand correctly:

* This PR provides a way to access data of various formats *in a uniform way* by abstracting the process of parsing.
* Parsers for common formats could be contained by the openQA repository and more specific ones would go into particular test cases.
* The data is *not* directly stored in openQA's data base.
* So what openQA will do when accessing the data (through the provided abstraction) is basically still up to openQA.
    * For instance, would be possible to add them as regular job modules (I'm referring to example line `$self->insert_module($t_info);`).
    * But the data could also be rendered as some special table like the one of PR https://github.com/os-autoinst/openQA/pull/1492.
    * Or stored in the database in case openQA needs server-side filtering/sorting or to attach further information like comments.

---

The file format recognition is not clear to me.

In PR https://github.com/os-autoinst/openQA/pull/1492 I just checked whether a specific file in the test results is present and then did some specific actions like adding a new tab to the test details page. Quite simple but only a manual solution for a particular format.

How would the 'additional parsing' implemented in this PR be triggered? I mean, how is a particular format recognized and than delegated to the right parser?

**Comment by richiejp** [comment]
> Isn't in this way the UI able to consume it? The result of the parsing is already a specific object (model) that can be consumed (i called it schema, but model works too :) 

Yeah, I am just wondering if you should add an extra layer between the parser and UI because formatting data for display may be more complex than just serialising or deserialising to or from JSON/XML. So I am wondering if it would be good to have an intermediate representation of data to be displayed which describes how to display it in in abstract terms (like a template language) without specific HTML elements, CSS classes or JS.

On the other hand, maybe the UI can just read the schema from the parser object and do the right thing. However I haven't seen a way of saying "this attribute is a float which represents seconds, should be displayed to 5 significant digits and has the display name 'Test Duration'".

**Comment by mudler** [comment]
@Martchus  : 

- Correct, the aim here is to provide different parsing mechanisms and glob into one wrapping unit
- Yes this is also possible, but yet to discuss i guess (@coolo might have a stronger opinion about this)
- Parsed data is not stored within this PR, but can be stored in a DB field by other API endpoint
- Yes, i wanted to cover also the possibility to render as much as possible similar to what #1492 provided, but also the results of the parsing process (models) could still export fields that are meant to be displayed (e.g. we can have a _displayable fields_ and such to query in order to render the specific object)  so UI can read them and decide what to render - but didn't took any design decisions on that, currently what's being provided is the possibility to serialize and unserialize data extracted from the parser(s), providing a basic model which can be inherited.  

Results of the parsing process currently could be: collections of results, and/or results. That means that collections can be formed by different results type (the only caveat - better support is provided if those are subclass of OpenQA::Parser::Results and OpenQA::Parser::Result respectively).

For 'joining' the methods, and use the parsing to extract the data to be rendered (and stored) i propose we should have an additional table where we store the serialized content of the parser, the type of the file that was in origin (junit,ltp,xunit, ....) and the job associated with it. Type detection is not yet there, and honestly i see it very difficult to make it reliable (differences by junit and xunit are quite small, there could be errors on detection, and such things that could make the whole process to be invalidated)

As the parser is able to serialize as JSON, it would be _also_ possible to read the result of the parsing directly (even if it is more handy to just make it read again to the parser, and display the wanted result in another endpoint)

@richiejp :

I do think those are refinements that could be added in a second PR, since this one is getting pretty big and would be already difficult to review.

Wrt data type - Perl doesn't know about floats and such - to satisfy what you are asking we should move to a Moose implementation, that officially supports that - but i don't think that's a good idea as they could get huge behemoth pretty easily. Those kinda of checks should be done in the model, that can be extended in a second time if we _really_ need something like this (aside, what should be the safest move to do if type check doesn't pass? invalidate the whole result?)

**Comment by richiejp** [comment]
> I do think those are refinements that could be added in a second PR, since this one is getting pretty big and would be already difficult to review.

OK. 

> Wrt data type - Perl doesn't know about floats and such - to satisfy what you are asking we should move to a Moose implementation, that officially supports that - but i don't think that's a good idea as they could get huge behemoth pretty easily. Those kinda of checks should be done in the model, that can be extended in a second time if we really need something like this (aside, what should be the safest move to do if type check doesn't pass? invalidate the whole result?)

I wasn't thinking about validation. More just how to display something. Like padding with zero's or using hexadecimal instead of base 10. Of course this can be fixed later if necessary.

**Comment by mudler** [comment]
I added basic POD documentation on each class - i'm looking for feedback on it :) all the features/usages are not yet documented - but i would continue improving it after we merge and start using it.

**Comment by foursixnine** [comment]
cfe

**Pull request merged**
