### PR TITLE
Dependency cron 2020-10-27

### PR DESCRIPTION
**Pull request by openqabot**

### CODE REVIEW

**Comment by okurz** [comment]
Full stack test failure details:

```
#   Failed test 'test 1 is running'
#   at t/full-stack.t line 128.

    #   Failed test 'worker did not propagate URL for os-autoinst cmd srv within 1 minute'
    #   at /home/squamata/project/t/lib/OpenQA/Test/FullstackUtils.pm line 195.

    #   Failed test 'developer console for test 1'
    #   at t/full-stack.t line 134.
    # Looks like you failed 2 tests of 3.
[02:46:51] t/full-stack.t .. 377/? 
#   Failed test 'wait until developer console becomes available'
#   at t/full-stack.t line 135.
Bailout called.  Further testing stopped:  findElement: no such element: Unable to locate element: {"method":"css selector","selector":"#log"} at /home/squamata/project/t/lib/OpenQA/SeleniumTest.pm:101
```

We should take this did serious. We currently also have problems in OBS, likely related to the dependency upgrades

**Review by Martchus — APPROVED** [review]

**Review by perlpunk — APPROVED** [review]
The OBS failure for `./t/api/08-jobtemplates.t` will be fixed in https://github.com/os-autoinst/openQA/pull/3491

**Comment by okurz** [comment]
You can also push your fix to the branch here

**Comment by perlpunk** [comment]
See https://github.com/os-autoinst/openQA/pull/3491 instead

**Pull request closed without merging**
