### PR TITLE
Add css class no_hover to all /thumbs/

### PR DESCRIPTION
**Pull request by asdil12**
This fixes some small ui issue.

### CODE REVIEW

**Comment by coolo** [comment]
yes, but why do you have to start with commas for this? mojos coding style is using => for these arguments (yes, it's silly but that's what we use everwhere else)

**Comment by asdil12** [comment]
Changed it to `=>` - but aren't there even commas in the same line?

**Comment by okurz** [comment]
LGTM

**Comment by coolo** [comment]
yes, the convention we follow is arguments with commas, html attributes with =>

**Pull request merged**
