### PR TITLE
preprocess hdd image names

### PR DESCRIPTION
**Pull request by nadvornik**
This allows easy building of images with naming scheme
distribution-architecture-variant.qcow2
which was requested by Eric for slenkins.

### CODE REVIEW

**Comment by sysrich** [comment]
Will this be sufficiently diverse?

From what I'm reading in the code, the names produced will all be distribution-version-arch-flavour

eg. SLE-12SP1-x86_64-Desktop or SLE-12SP1-x86_64-Server

Don't we need to *at least* add $jobname in there so we know which test produced that disk image?

**Comment by lnussel** [comment]
something like that is actually what I need too to generate images for upgrades. It needs to be more generic though, like allowing all in $settings and also processing PUBLISH_HDD_ etc. I was thinking about something like this to evaluate variables, not sure whether it's safe though:
https://www.safaribooksonline.com/library/view/perl-cookbook/1565922433/ch01s09.html

**Comment by nadvornik** [comment]
Here is a version without whitelist.
The recursion was not a big problem in the end.

**Comment by coolo** [comment]
beside the print LGTM

**Comment by nadvornik** [comment]
print is fixed

**Comment by coolo** [comment]
I just reviewed the GettingStarted.asciidoc and it's horrible outdated anyway, but I suggest we add one sentense there about the format to use for variables in variables. 

A test case is optional - but if you move the code into a function of itself, you could write unit tests easily.

**Comment by coolo** [comment]
sorry to reopen that topic - but could we do that expansion in the worker and/or os-autoinst instead?
The problem I'm trying to solve is that for s390 the IP address depends on test/machine and assigned worker slot

**Comment by coolo** [comment]
expanding late would kill one usecase where you might want to START_AFTER_TEST depending on ARCH. So we need 2 places to expand?

**Comment by nadvornik** [comment]
The main reason for expanding early is that the scheduler must connect jobs with assets.

Can you give some example what variables you want to expand late?

**Comment by coolo** [comment]
"S390_NETWORK_PARAMS": "OSAHWAddr= InstNetDev=osa Domain=suse.de ReadChannel=0.0.7100 Layer2=1 PortNo=0 Portname=VSWNL2 OSAMedium=eth DataChannel=0.0.7102 Nameserver=10.160.0.1 OSAInterface=qdio WriteChannel=0.0.7101 Hostname=s390hsl@S390_HOST@.suse.de HostIP=10.161.183.@S390_HOST@/24"

The S390_HOST comes from workers.ini - I do the replacement now in the test itself

**Pull request merged**
