### PR TITLE
Write info about assets kept during cleanup to db (rebased)

### PR DESCRIPTION
**Pull request by coolo**
I rebased @Martchus PR so I can play with it

### CODE REVIEW

**Comment by foursixnine** [comment]
Take a look to sqitch, looks promising :)

**Comment by coolo** [comment]
we had a look at sqitch, but it wasn't what we needed then - as it's not DB agnostic. And now we don't start from scratch, we need something compatible with what we already have.

**Comment by coolo** [comment]
(anyway, not urgent)

**Comment by coolo** [comment]
codecov is really pissy when you simplify code :)

**Pull request closed without merging**
