### PR TITLE
Use Perl::Critic::Freenode to determine good coding style

### PR DESCRIPTION
**Pull request by kraih**
This should be a well balanced set of rules to encourage a slightly better coding style. I've also fixed the dependency on `JSON`, which was missing from `cpanfile`, and removed the dependency on `List::MoreUtils`, which was unnecessary.

Progress: https://progress.opensuse.org/issues/44597.

### CODE REVIEW

**Comment by kraih** [comment]
Severity 4 (stern) is stricter than before, but still not very strict. You can check manually with `perlcritic -1 lib` to see all rules applied. I do suggest following all rules (and will do so myself), but enforcing them seems unrealistic for now. Maybe we can lower severity over time (next step would be 3 then).

**Comment by Martchus** [comment]
You need to add `perl(Perl::Critic::Freenode)` to `t_requires` in `openQA.spec`, too.

**Comment by kraih** [comment]
Also forgot to link to the actual [rules](https://metacpan.org/pod/Perl::Critic::Freenode#POLICIES) that [Perl::Critic::Freenode](https://metacpan.org/pod/Perl::Critic::Freenode) uses. They do mostly overlap with the high severity rules from core perlcritic, but some are not included, like `BuiltinFunctions::ProhibitStringyEval` (which has many valid uses and needs to be judged on a case by case basis).

**Comment by kraih** [comment]
@Martchus Haha, and just as you say that the random cache service bug you were hunting hits.
```
    #   Failed test 'job enqueued'
    #   at ./t/25-cache-service.t line 442.
    # Looks like you failed 1 test of 2.
#   Failed test 'Test Minion task registration and execution'
#   at ./t/25-cache-service.t line 448.
Can't call method "execute" on an undefined value at ./t/25-cache-service.t line 443.
```
Not restarting the Travis job yet in case you want to look at the result first.

**Comment by Martchus** [comment]
Good, I'll have a look.

**Pull request merged**
