### PR TITLE
Make 'TEST' the only proper mandatory test setting

### PR DESCRIPTION
**Pull request by okurz**
In before there was no real check for most settings implicitly allowing
undefined settings but causing perl warnings. This commit now properly
tests job results where no setting is set besides the name composed of
'TEST' itself. It is not pretty in all cases when the individual
string components are empty but it works.

Related progress issue: https://progress.opensuse.org/issues/6762

### CODE REVIEW

**Comment by coolo** [comment]
ok, I think I made clear enough that I consider this wrong. If you can't follow, let's get old over this one here.

**Comment by okurz** [comment]
the settings are currently set as `is_nullable` in the schema which we can consider wrong for TEST but I am not sure. AFAICS there are three levels: UI, API, DB. For now it is breaking in UI when not set properly, API and DB are fine with undef/null. That is why I chose to handle it in UI in a safe way. If you think we can enforce it on the level of API even though the API never actually requires this to be set. We could go even further and waste space in the DB and make it mandatory there but neither API nor DB need the values so why care?

In short, I see the following options:
1. handle it in UI accordingly where needed (as I did even though in a way that could be improved to prevent strings like '--.')
2. handle it in API "job#create" to set a default value, i.e. empty strings,; write a script querying database for currently "undef" values and update jobs accordingly; ensure there are no other entry points to the job settings where this could be set wrong (e.g. over isos)
3. make these values required in the schema with default to empty strings; database migration scripts to find all current undef values in the database and update to empty string
4. keep it undefined, accept perl warnings and confuse users

I prefer 1, I can also follow 2 if you like.

**Comment by aaannz** [comment]
For POST /api/v1/isos they are required. POST /api/v1/jobs doesn't require them, but IMO that's mistake.

**Comment by coolo** [comment]
3 is what I want, I can agree to 2.

**Comment by sysrich** [comment]
Looks like a rebase needed

**Comment by okurz** [comment]
updated to follow approach "3", i.e. initialize values in the database with an empty string except for TEST which is now mandatory (as in the previous commits in this PR).

open point: I wrote the upgrade script https://github.com/os-autoinst/openQA/pull/1126/files#diff-dd139f35469d0636667b588967ab0c64 with @Martchus but checking on a local database it is either not called or has no effect on migration. How can I ensure the script is called before the schema is upgraded and not after the try to migrate the database which would fail because there are entries which are not allowed anymore after the schema upgrade?

**Comment by coolo** [comment]
not calling 01 but a different number

**Comment by coolo** [comment]
I.e. if you want to run it before the DB migration, name it 01 and the sql 02

**Comment by okurz** [comment]
updated:
* database migration script now properly triggered before migration
* tests fixed

I managed to still show warnings when showing some weirdly created tests locally but so far couldn't find the culprit. Anyway, a related fix would probably not require database changes and also tests should pass now already so IMHO ready to be merged although I would not mind if anyone else tests manually as well.

**Pull request merged**
