### PR TITLE
[WIP] Have an extra test that runs in parallel and sets up a full stack test

### PR DESCRIPTION
**Pull request by coolo**
The t/full-stack.t is not run on default, but runs in parallel on travis. Coveralls will then merge the results of both runs.

The main reason this is not default: it requires a compiled os-autoinst and a working dbus session.

### CODE REVIEW

**Comment by coolo** [comment]
now it will always comment twice instead of merging? If so, I need to revise my tactics

**Comment by okurz** [comment]
I guess coveralls reports twice but travis can add this multiple badge thingy. Maybe just generate some report within 2 (or more test) jobs and have a third one which actually speaks to coveralls. Would that work?

**Comment by coolo** [comment]
I don't think you can access artefacts of another job in travis - and this multiple jobs works for the build service since like forever. But it's ruby...

**Comment by coolo** [comment]
Ah, in OBS coveralls does not comment, but reviews: E.g. https://github.com/openSUSE/open-build-service/pull/2497

Now that I know it's possible, I prefer that :)

**Comment by coolo** [comment]
But it actually only comments only once if all tests pass

**Comment by okurz** [comment]
I don't mind either way, even having both would be fine for me

**Comment by coolo** [comment]
Split this PR into 3 - the top one being https://github.com/os-autoinst/openQA/pull/1122

**Pull request closed without merging**
