### PR TITLE
Fix report link for FLAVOR 'Server-DVD-Incidents'

### PR DESCRIPTION
**Pull request by Martchus**
See https://progress.opensuse.org/issues/15018#change-32718

### CODE REVIEW

**Comment by coolo** [comment]
You still miss Desktop-DVD-Updates and Server-DVD-Updates 

BTW, what about stagings? Aren't we using this there? What about not showing the icon if there is no mapping?

**Comment by Martchus** [comment]
I actually don't know, just fixed the concrete bug mentioned in the issue. But I can look for further FLAVORS in use and support them.

**Comment by Martchus** [comment]
Added all FLAVORS I found. If no mapping is possible, the icon isn't shown anymore.

**Comment by coolo** [comment]
BTW, is this solved ?

```
Nov 28 16:14:15 openqa openqa[2021]: Use of uninitialized value in join or string at template
Nov 28 16:14:15 openqa openqa[2021]: branding/openqa.suse.de/external_reporting.html.ep line 25 (#1)
Nov 28 16:14:15 openqa openqa[2021]: (W uninitialized) An undefined value was used as if it were already

**Comment by Martchus** [comment]
Likely not

**Comment by Martchus** [comment]
In which case does this happen?

**Comment by coolo** [comment]
no idea, all the time in the log

**Comment by Martchus** [comment]
Maybe I should add tests for this.

**Pull request merged**
