### PR TITLE
Bootstrap for result

### PR DESCRIPTION
**Pull request by coolo**

### CODE REVIEW

**Comment by aaannz** [comment]
I tried it now and it looks confusing to me. I would add some padding between breadcrumbs and result boxes. The left result box looks like if the css was broken.
Dependencies box is missing border and seems misaligned.
The backend section in settings is off too. Shouldn't the backend be part of regular settings now?

**Comment by coolo** [comment]
yeah, I'm not saying it's perfect. but I had to start somewhere

**Comment by coolo** [comment]
feel free to give it another try - we changed quite some aspects

**Comment by coolo** [comment]
now tidied according to the new rules :)

**Pull request merged**
