### PR TITLE
Make message about clone error unique

### PR DESCRIPTION
**Pull request by okurz**
Previously we used the same message in two locations

### CODE REVIEW

**Review by Martchus — COMMENTED** [review]
From the user's perspective it is the same problem but I agree that it can be helpful for developers to distinguish the errors. I would remove the `Unable to clone: ` suffix because the context should already be pretty clear here. (The entire purpose of the duplicate function/route is cloning jobs.)

**Comment by okurz** [comment]
@Martchus done

something on a meta-level. I think it's better to more often use the inline review comments because then the reviewee can respond to a message more easily, we can "resolve" individual conversations while other issues in a PR might still be relevant, etc.

**Review by Martchus — APPROVED** [review]

**Comment by perlpunk** [comment]
I don't understand how the PR makes something uniq.

> Previously we used the same message in two locations

Where are those two locations?

**Comment by Martchus** [comment]
`git grep 'has already been cloned as'` tells you; the error is indeed duplicated.

**Comment by perlpunk** [comment]
It's possible to link to a certain code location :)
https://github.com/os-autoinst/openQA/blob/master/lib/OpenQA/Schema/Result/Jobs.pm#L930

**Review by perlpunk — APPROVED** [review]

**Pull request merged**
