### PR TITLE
Add favicon for open.qa page

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Review by Martchus — APPROVED** [review]

**Comment by Martchus** [comment]
It has a white background (instead a transparent one like the favicon of openQA itself). I suppose a transparent background would look better in most cases.

**Comment by okurz** [comment]
Really? I just copied over the one from master. And it looked correct to me on open.qa in chrome

**Comment by Martchus** [comment]
It doesn't look correct on Firefox and Chromium. Of course you'll have to switch to another tab in Chromium because the default background color of an active tab button is white.

**Comment by okurz** [comment]
Right. I could see that now. Well, I would not mind if anyone changes that but I don't plan to do that right now.

**Pull request merged**
