### PR TITLE
Dependency cron 191013000601

### PR DESCRIPTION
**Pull request by openqabot**

### CODE REVIEW

**Comment by okurz** [comment]
hm, why does the bot add *new* dependencies? Is this because of https://github.com/os-autoinst/openQA/pull/2387 ?

**Comment by andrii-suse** [comment]
'Dependencies' is actually a bad choice of name here, because what the file serves is rather 'layout for testing' or 'testing environment'. Not sure which name is better, but idea is to have consistent environment, so we know that external dependencies don't influence test outcome.
Now, the real problem revealed by this PR, is that installing openQA-devel did install chromium and that didn't happen before.

**Comment by andrii-suse** [comment]
I've re-run the circleci workflow and now the the cache job seems passing, but probably it needs additional investigation

**Comment by andrii-suse** [comment]
Ok, probably chromedriver was added because it is different now in devel:OpenQA repo from leap 15.1 repo where in was installed here https://build.opensuse.org/package/view_file/devel:openQA:ci/base/Dockerfile?expand=1

**Comment by andrii-suse** [comment]
I think the change might be caused by 15.1 Update(?) https://build.opensuse.org/package/show/openSUSE:Leap:15.1:Update/chromium

**Pull request closed without merging**
