### PR TITLE
Vertically align progress bar with build number

### PR DESCRIPTION
**Pull request by kravciak**
Change 18px bottom margin (bootstrap default) into 8 top 8 bottom.

### CODE REVIEW

**Comment by okurz** [comment]
screenshot please. Did you check both index and group overview page?

**Comment by kravciak** [comment]
screenshot from 2016-08-24 14-13-57
screenshot from 2016-08-24 14-38-05

**Comment by aaannz** [comment]
Not that I'm an expert in css, but I would expect some property letting browser to compute it rather then hardcoding 9px. What if you increase default font size?

**Comment by kravciak** [comment]
You are probably right, WIP then :)

**Comment by okurz** [comment]
LGTM power of scss :-)

**Pull request merged**
