### PR TITLE
Fix regexp for multiple parent jobs

### PR DESCRIPTION
**Pull request by nadvornik**

### CODE REVIEW

**Comment by okurz** [comment]
Can you describe a bit more in detail where you encountered this error and what the symptoms where? Would you be able to add a test?

**Comment by aaannz** [comment]
Ah sorry, I didn't notice your post and github didn't push them. :(
The test is indeed wanted.

**Comment by nadvornik** [comment]
the bug appears when you call clone_job.pl on a job with multiple parents - for example some slenkins tests.

I will add a test

**Comment by okurz** [comment]
awesome

**Pull request merged**
