### PR TITLE
Add the job module statistics to the migration code

### PR DESCRIPTION
**Pull request by coolo**
to fix issue 20930.

Once the migration is done, there is no need more for the original function - but it's still in 3 places

### CODE REVIEW

**Comment by coolo** [comment]
tested on dump of our production database - a bit slow, but is reasonably quick. Perhaps 5 minutes.

**Comment by AdamWill** [comment]
/me ponders how it can be both 'a bit slow' and 'reasonably quick' :P

**Comment by coolo** [comment]
like a family van?

**Comment by coolo** [comment]
speed is always relative :)

**Pull request merged**
