### PR TITLE
client: Support multiple occurrences of same parameter

### PR DESCRIPTION
**Pull request by Martchus**
I just noticed that limitation when playing around with the client. Maybe we should add tests for the client on command-line level, too.

### CODE REVIEW

**Comment by coolo** [comment]
we have some in the fullstack

**Comment by coolo** [comment]
... which you broke :)

**Comment by Martchus** [comment]
I checked out the fullstack test. It relies on the current behavior which actually makes using the client more convenient in that case. Not sure whether it is worth introducing that change then.

**Comment by coolo** [comment]
So let's close it?

**Pull request closed without merging**
