### PR TITLE
Make Markdown rendering 10 times faster

### PR DESCRIPTION
**Pull request by kraih**
This is the promised followup to #2228. It replaces `Text::Markdown` with `CommonMark` (which uses the standard [cmark](https://github.com/commonmark/cmark) library) for comment rendering. Similar to how OBS already handles Markdown. It is at least 10 times faster for most cases, and has very solid security features.

While this should resolve our performance bottlenecks when rendering comments, there are a few changes to be aware of. Raw HTML is no longer allowed in comments (it is simply removed), since there is no way to sanitize HTML fast enough. Instead we now have custom template tags to generate text in different colors.
```markdown
## This is an example comment
{{color:#ff0000|This text will be red with a white background}}
{{color:#00ff00|This text will be green with a white background}}
{{color:#ffffff|This text will be white with a black background}}
This text will have the standard color.
```
There is also new logic to change the background color to black if a light text color is chosen.

### CODE REVIEW

**Comment by Martchus** [comment]
Patch for openQA review: https://github.com/os-autoinst/openqa_review/pull/126

**Comment by AdamWill** [comment]
It seems like the second commit is kind of unnecessary now, as everything it does is replaced by the third commit - at least AFAICS. Couldn't it just be ditched?

**Comment by AdamWill** [comment]
Or, well, I guess, more the last two commits could be sort of squashed together and the bit where HTML::Restrict is used and then immediately ripped out again could be avoided.

**Comment by coolo** [comment]
squashing is if one commit fixes another - these commits are just revisions. So I don't see the requirement to squash

**Pull request merged**
