### PR TITLE
Fix failing CI check for container file (static check DL3059)

### PR DESCRIPTION
**Pull request by Martchus**
This check has recently been added to the linter, see
https://github.com/hadolint/hadolint/commit/4cb8f28ebecfd0343241369952fc9b3e7e4ea866 and https://progress.opensuse.org/issues/91377

### CODE REVIEW

**Review by ilausuch — APPROVED** [review]

**Comment by ilausuch** [comment]
Please add the related ticket to the PR description https://progress.opensuse.org/issues/91377

**Review by kraih — APPROVED** [review]

**Comment by Martchus** [comment]
I'm wondering why the dynamic test fails now. The log shows that `gensslcert` is still executed but now some of the containers are unhealthy:

```
2021-04-20T09:09:17.5236319Z Creating webui_webui_db_init_1 ... 
2021-04-20T09:09:17.5286400Z Creating webui_db_1            ... 
2021-04-20T09:09:20.2328503Z Creating webui_db_1            ... done
2021-04-20T09:09:20.2477627Z Creating webui_webui_db_init_1 ... done
2021-04-20T09:09:30.4272956Z Creating webui_webui_1         ... 
2021-04-20T09:09:30.4274090Z Creating webui_webui_2         ... 
2021-04-20T09:09:31.3793760Z Creating webui_webui_2         ... done
2021-04-20T09:09:31.4580768Z Creating webui_webui_1         ... done
2021-04-20T09:09:52.5847534Z 
2021-04-20T09:09:52.5848757Z ERROR: for gru  Container "f46f2567af83" is unhealthy.
2021-04-20T09:09:52.5849349Z 
2021-04-20T09:09:52.5850035Z ERROR: for nginx  Container "f46f2567af83" is unhealthy.
2021-04-20T09:09:52.5850609Z 
2021-04-20T09:09:52.5851308Z ERROR: for websockets  Container "f46f2567af83" is unhealthy.
2021-04-20T09:09:52.5851908Z 
2021-04-20T09:09:52.5852603Z ERROR: for livehandler  Container "f46f2567af83" is unhealthy.
2021-04-20T09:09:52.5853206Z 
2021-04-20T09:09:52.5853874Z ERROR: for scheduler  Container "f46f2567af83" is unhealthy.
2021-04-20T09:09:52.5854773Z Encountered errors while bringing up the project.
```

The table at the bottom also looks strange:

```
2021-04-20T09:09:54.0999076Z         Name                       Command                   State                                        Ports                                 
2021-04-20T09:09:54.1001326Z ------------------------------------------------------------------------------------------------------------------------------------------------
2021-04-20T09:09:54.1003055Z webui_db_1              docker-entrypoint.sh postgres    Up (healthy)     5432/tcp                                                              
2021-04-20T09:09:54.1004950Z webui_webui_1           /root/run_openqa.sh              Up (unhealthy)   443/tcp, 80/tcp, 0.0.0.0:49155->9526/tcp, 9527/tcp, 9528/tcp, 9529/tcp
2021-04-20T09:09:54.1006341Z webui_webui_2           /root/run_openqa.sh              Up (healthy)     443/tcp, 80/tcp, 0.0.0.0:49154->9526/tcp, 9527/tcp, 9528/tcp, 9529/tcp
2021-04-20T09:09:54.1007698Z webui_webui_db_init_1   sh -c chmod -R a+rwX /data ...   Up (healthy)     443/tcp, 80/tcp, 0.0.0.0:49153->9526/tcp, 9527/tcp, 9528/tcp, 9529/tcp
```

There are apparently two web UIs. I hope these do not actually run anything on the ports `9527/tcp, 9528/tcp, 9529/tcp` because that would usually be services which must only be started once. I doubt that my PR changed anything here, though.

**Comment by ilausuch** [comment]
I think is because of the timeouts. Unfortunately, I cannot create a PR because depends on this PR. But please, could you try to increase the interval in the web UI healthcheck to 10s or 15s?

**Comment by Martchus** [comment]
Ok, I'll try.

**Comment by ilausuch** [comment]
I created this PR too. this is not valid because I am skipping the static check
https://github.com/os-autoinst/openQA/pull/3853

**Comment by ilausuch** [comment]
It passes here

**Comment by ilausuch** [comment]
It passes here and here https://github.com/os-autoinst/openQA/pull/3853
I think this depends on the load of the worker where this is executed, so increasing the retries if fine

**Pull request merged**
