### PR TITLE
Add documentation for softfailure result

### PR DESCRIPTION
**Pull request by Martchus**
Not sure whether the provided description is correct.

### CODE REVIEW

**Comment by okurz** [comment]
> please add 'record_soft_failure'

No, that is backend specific and not directly related to openQA

**Comment by okurz** [comment]
But @Soulofdestiny is right that there are also other means than a workaround needle to make a job module softfail

**Comment by Martchus** [comment]
I don't see any problem in mentioning `record_soft_failure`. What other means do you have in mind?

**Comment by coolo** [comment]
just for the record: I agree with @Soulofdestiny - and so didn't merge

**Comment by foursixnine** [comment]
We're talking about job states here, not (https://github.com/os-autoinst/openQA/blob/master/docs/WritingTests.asciidoc#api)[api] calls. But adding to the text something like "e.g. when record_soft_failure is called"

**Pull request merged**
