### PR TITLE
[WIP] who can get this to work? -- Add static scenario route

### PR DESCRIPTION
**Pull request by okurz**
Should always refer to most recent job for the specified scenario.

### CODE REVIEW

**Comment by coolo** [comment]
perhaps you write the test first this time? :)

**Comment by okurz** [comment]
On Tuesday 26 July 2016 07:46:10 Stephan Kulow wrote:
> perhaps you write the test first this time? :)

Yes, I had this idea. I just write the test, you implement it :-) But I wanted 
to see which code paths would be touched but did not really get that far.

**Comment by coolo** [comment]
the use case is unclear to me though

**Comment by okurz** [comment]
two benefits:

* have the same link for test development, i.e. if one retriggers tests, the person has to always update the URL. If there would be a static URL even the browser can be instructed to reload the page automatically
* for linking to the always current execution of the last job within one scenario, e.g. to respond faster to the standard question in bug reports "does this bug still happen?"

**Comment by okurz** [comment]
test added to show what I want

**Comment by coolo** [comment]
the question is where these links would come from. And why those providing the links can't create tests/latest?distri=sle&flavor=Server-DVD...

**Comment by okurz** [comment]
I just thought it would give nice URLs but as "-" is a very ambiguous separation character I guess it's safer to just go with queries, see #810

**Pull request closed without merging**
