### PR TITLE
Use update-deps script from os-autoinst

### PR DESCRIPTION
**Pull request by perlpunk**
to avoid duplicate code.

Issue: https://progress.opensuse.org/issues/56525

### CODE REVIEW

**Comment by perlpunk** [comment]
Currently tests fail in CI because the `../os-autoinst` directory is missing in the `t` job.

I would still vote for using something like git-subrepo for sharing files like this.

**Comment by okurz** [comment]
Well, you could try git submodules or sub-repo. As probably not even OBS would need this but only the git repo that should be fine.

**Comment by perlpunk** [comment]
> As probably not even OBS would need this but only the git repo that should be fine.

What do you mean by that?

> Regardless of the content the current "WIP" commits should not be approvable

What do you mean by that?

**Comment by perlpunk** [comment]
> The you need so squash / properly name them before one would approve this PR. (I'm wondering where the button for dismissing a review has been moved to.)

Well, I was experimenting and commenting out jobs in circleci, I guess noone would want to approve that even if I squashed it :)
It's a draft PR, and tests failed because of the missing os-autoinst dir, so I had to experiment.

**Comment by okurz** [comment]
No problem. I was merely mentioning what I see as prerequisities for merging as there were WIP commits but Martchus gave approval.

**Pull request closed without merging**
