### PR TITLE
scheduler: Fix warnings about undefined variables

### PR DESCRIPTION
**Pull request by okurz**
Related progress issue: https://progress.opensuse.org/issues/55319

### CODE REVIEW

**Comment by perlpunk** [comment]
Does this really fix all warnings? I would guess that, if `$j` or `$j->{id}` is undef, it will still warn in line 74, 278, 280.
Can this be reproduced somehow?

**Comment by okurz** [comment]
> Does this really fix all warnings? I would guess that, if `$j` or `$j->{id}` is undef, it will still warn in line 74, 278, 280.

yes, not all warnings fixed as I could confirm now on osd live :)

> Can this be reproduced somehow?

So far I only managed to reproduce this on osd, probably because of some custom schedule of jobs that is used there.

**Comment by okurz** [comment]
this should fix all warnings. Haven't observed anymore after running this overnight at least on osd.

**Comment by perlpunk** [comment]
I'm still wondering why there are jobs without an id, though. But I don't know the code enough...

**Comment by okurz** [comment]
Yeah I guess that's by design to end the recursion. Is there something missing for approval?

**Comment by perlpunk** [comment]
> Yeah I guess that's by design to end the recursion.

Hm. I don't understand that. Recursion ends if a job does not have `parallel_children`.
But why are there jobs without an id?

I don't like the approach much to just guess which could be undef:

    return undef unless $j;
￼    return undef unless $j->{id};

Also, is there a reason to `return undef` instead of just `return`? The return value of `_to_be_scheduled_recurse` is never used anyway.

**Comment by okurz** [comment]
> > Yeah I guess that's by design to end the recursion.
> 
> Hm. I don't understand that. Recursion ends if a job does not have `parallel_children`.
> But why are there jobs without an id?
> 
> I don't like the approach much to just guess which could be undef:

We can still debug what is going on but IMHO ignoring warnings for years is making debugging other issues harder as well :) I can put in more debug statements if you have suggestions what to look for.

> ```
> return undef unless $j;
> ```
> 
> return undef unless $j->{id};
> 
> Also, is there a reason to `return undef` instead of just `return`? The return value of `_to_be_scheduled_recurse` is never used anyway.

Yes, because @kraih said it's always better to return an explicit undef :)

**Comment by perlpunk** [comment]
> I can put in more debug statements if you have suggestions what to look for.

I guess I would add debugging in the subroutine which is returning the job list to see if it is producing empty jobs. But I really would have to have more understanding of the code.


> > return undef unless $j->{id};
> > Also, is there a reason to `return undef` instead of just `return`? The return value of `_to_be_scheduled_recurse` is never used anyway.
> 
> Yes, because @kraih said it's always better to return an explicit undef :)

Hmmm, I tend to disagree with "always" :)
I think in this case (a subroutine where the return value is not used) it looks noisy to me, and readers assume that it is supposed to have a meaning.

And for subroutines which are supposed to return a list, returning undef would actually be wrong.

For cases where the subroutine is supposed to return a scalar, and explicit undef is good, because if that subroutine is called in list context the return value would otherwise be an empty list.

This is a popular example when a simple `return` will go wrong:
```
my %params = (
    foo => $cgi->param('foo'),
    bar => $cgi->param('bar'),
);
```

But ok, this is a style issue and I don't want to argue about that.

**Comment by okurz** [comment]
@perlpunk yes, of course you are right and I would also consider "always" not a good rule :) ok, let's take it as is because I assume others would not touch this code without shouting "rewrite everything!" anyway ;)

**Comment by okurz** [comment]
I would like to give it a bit more time to see if my hotpatches on osd break the scheduling, e.g. that some jobs would never be scheduled. Monitoring http://openqa.suse.de/tests/ for this

**Comment by okurz** [comment]
sit on osd seems fine, there are tests left scheduled but this looks like a problem of the corresponding workers down or non-existant.

**Pull request merged**
