### PR TITLE
action#5918 - limit START_AFTER_TEST to Machines

### PR DESCRIPTION
**Pull request by aaannz**

### CODE REVIEW

**Comment by aaannz** [comment]
Hold on with merge, testing results seems little off.

**Comment by coolo** [comment]
I merge because it looks reasonable, but it's basically blind flight ;(

**Comment by coolo** [comment]
the comment I saw by email was deleted? you scared me :)

**Comment by aaannz** [comment]
Yes, I fixed the issue, no worries here. I was wondering how everyone will react. Whether another notification is necessary, or you check github notification regularly. :)

**Pull request merged**
