### PR TITLE
Build only on architectures with chromium

### PR DESCRIPTION
**Pull request by mimi1vx**

### CODE REVIEW

**Comment by baierjan** [comment]
`s/aarchitectures/architectures/`

**Comment by ggardet** [comment]
You added `jq` silently (no ref in commit message)

**Review by Martchus — CHANGES_REQUESTED** [review]
I guess adding jq is a good idea. So rebase and change the commit message accordingly.

**Comment by kalikiana** [comment]
Related to https://github.com/os-autoinst/openQA/pull/5171 I assume

**Comment by perlpunk** [comment]
Can we also add these?  `wget curl ack zsh tmux tmate tree perl-doc`

**Comment by kalikiana** [comment]
@mimi1vx With #5172 I think this PR is obsolete? Unless you want to repurpose it to "Make devel container a full development environment"?

> Can we also add these? `wget curl ack zsh tmux tmate tree perl-doc`

Usually I find this tricky since it adds various things most people may never use, and if we all contribute our favorite tools it becomes even bigger.
How about we instead document how to easily build your own container with the tools you like e.g. on OBS?

**Review by okurz — CHANGES_REQUESTED** [review]

**Pull request closed without merging**
