### PR TITLE
WIP -- use same approach for other scripts as well -- Use Getopt::Long::Descriptive in scripts

### PR DESCRIPTION
**Pull request by okurz**
Related progress issue: https://progress.opensuse.org/issues/68167

### CODE REVIEW

**Comment by okurz** [comment]
@os-autoinst/tools-team before I continue, do you think this is a good idea in general?

**Comment by Martchus** [comment]
It is definitely better than printing the usage manually. I don't know how usable Mojolicious' argument parser is outside of the scope of a Mojolicious application but that would of course be an alternative we might want to consider.

**Comment by kraih** [comment]
Purely a matter of taste. I prefer to have the usage message in POD for documentation purposes.

**Comment by perlpunk** [comment]
> Purely a matter of taste. I prefer to have the usage message in POD for documentation purposes.

There's https://metacpan.org/pod/Getopt::Long::DescriptivePod

(also https://metacpan.org/pod/App::Spec ;-)

both require generation after changes, though.

**Comment by okurz** [comment]
> Purely a matter of taste. I prefer to have the usage message in POD for documentation purposes.

hm, but https://github.com/os-autoinst/openQA/pull/3442/files#diff-f78261fca04961335f54a8d95edd49ec7e9c127ba01786afc60aa57341201d76L45-L54
isn't helping in this regard, right? So how would you change the code to reflect your preference?

**Comment by okurz** [comment]
There was no response to my earlier messages. I now updated the commit to be complete at least for script/upgradedb. If we like the approach we can extend it to other scripts afterwards.

**Pull request closed without merging**
