### PR TITLE
Fix the issue `_URL` in jobs post is different from that in isos post

### PR DESCRIPTION
**Pull request by Amrysliu**
Related: https://progress.opensuse.org/issues/66268

### CODE REVIEW

**Comment by Amrysliu** [comment]
Here is a verify run: http://10.67.19.103/tests/60#settings. 
I triggered this job using 
```
liuxiaojing@linux-90dc:~/code/repos/openQA/script> ./openqa-cli api --host http://10.67.19.103 -X post jobs TEST=test DISTRI=sle VERSION=15-SP2 ARCH=x86_64 FLAVOR=Online MACHINE=64bit HDD_1_URL=http://10.67.19.103/tests/56/asset/hdd/sle-15-SP2-x86_64-189.1-textmode@64bit.qcow2 BUILD=189.1
{"id":60}
```
@AdamWill I wonder how do you use the `_URL` in your test when using `isos post`?  such as `isos post HDD_1_URL=http://.../foo.qcow2`.

**Comment by AdamWill** [comment]
Pretty much, yeah. We set `ISO_URL`, `HDD_2_DECOMPRESS_URL`, `HDD_1_URL`, `KERNEL_URL` and/or `INITRD_URL` depending on the asset type. Sometimes we also specify the non-`_URL` parameter as well to give a custom name, sometimes we don't. The URLs are full URLs to images from Fedora nightly composes, so a typical job might have something like `ISO_URL=https://kojipkgs.fedoraproject.org/compose/rawhide/Fedora-Rawhide-20200505.n.0/compose/Everything/x86_64/iso/Fedora-Everything-netinst-x86_64-Rawhide-20200505.n.0.iso` .

Is that what you were asking?

**Comment by AdamWill** [comment]
So I'm not *sure* if it matters, but I do still see some ordering difference with the ISO path here. On the ISO path we do `create_downloads_list` *before* we call `$self->_generate_jobs`, which is what calls `OpenQA::JobSettings::generate_settings` on that path; even with this change, on this path we are still calling `OpenQA::JobSettings::generate_settings` *before* we do `create_downloads_list`. That means we're processing vars prefixed with `+` and doing the placeholder replacement *before* we call `create_downloads_list` on this path, but *after* we call `create_downloads_list` on the ISO path...

**Comment by Amrysliu** [comment]
Thanks for replying.

> Is that what you were asking?

yes, that is what I wonder.

> So I'm not _sure_ if it matters, but I do still see some ordering difference with the ISO path here. On the ISO path we do `create_downloads_list` _before_ we call `$self->_generate_jobs`, which is what calls `OpenQA::JobSettings::generate_settings` on that path; even with this change, on this path we are still calling `OpenQA::JobSettings::generate_settings` _before_ we do `create_downloads_list`. That means we're processing vars prefixed with `+` and doing the placeholder replacement _before_ we call `create_downloads_list` on this path, but _after_ we call `create_downloads_list` on the ISO path...

The document says `If you set both ISO_1 and ISO_1_URL, the file pointed to by ISO_1_URL will be downloaded and renamed to the name set as ISO_1` . In `jobs post` if the `ISO_1` is set in test suite settings, the download's file  will be renamed by this value (You could see that through the unit test code I added) . But in `isos post`, if the `ISO_1` is set in test suite settings or other places, the download file will not be renamed to it.  So I put the `create_downloads_list` after `_generate_jobs`.   `jobs post` is different from `isos post`, it only create one job at one time, so I think this way does not matter. This is why I wondered your workflow.

**Comment by AdamWill** [comment]
Ah, I see :)

Yeah, I don't think there is any case where we set a `_URL` arg and the matching non-`_URL` arg is set in the templates. We have some asset args in the templates but only for fixed assets. We only use the `_URL` stuff in scheduler code, so the relevant args are always coming in with the request.

**Comment by Amrysliu** [comment]
@AdamWill Do you have any suggestion about this pr? or any question? 

@okurz @Martchus May I merge this pr after confirming that AdamWill agrees on this change?

**Comment by Martchus** [comment]
Sounds good. Considering this PR only influenced posting a single job (and not scheduling an ISO) he'll be likely not influenced by the change anyways.

**Comment by okurz** [comment]
There had been no "please don't merge" so I guess we *can* merge :)

**Comment by AdamWill** [comment]
My power has been out all morning :)

I think this was fine to merge, it's certainly better than before.

**Pull request merged**
