### PR TITLE
Make overview name limit configurable by query parameter

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by coolo** [comment]
No, not more ways to break the layout. Rather remove this trim_text completely and use 
https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/

**Comment by coolo** [comment]
or ellipse in javascript, but don't add random query parameters

**Comment by okurz** [comment]
yes, all this makes sense but can you please accept simple enhancements first? There is a reason I came up with this. And I am not adding "random" parameters but replacing a magic number with something that is now configurable. I was also discussing with @Martchus how to set it in a GUI way but that is something for later or maybe never when doing it with ellipsis

**Comment by coolo** [comment]
No, I will not. I've seen what happened in the past with such random query parameters of yours.

**Comment by coolo** [comment]
let's see what comes out of #1094

**Comment by okurz** [comment]
On December 20, 2016 4:49:44 PM GMT+01:00, Stephan Kulow <notifications@github.com> wrote:
>No, I will not. I've seen what happened in the past with such random
>query parameters of yours.

Like what?

**Pull request closed without merging**
