### PR TITLE
doc: fix typos

### PR DESCRIPTION
**Pull request by pevik**
syntax '+text+' isn't working in console output (it shows '+').

Signed-off-by: Petr Vorel <pvorel@suse.cz>

### CODE REVIEW

**Comment by okurz** [comment]
I think the whole blocks should not look like code segments, e.g. see online rendering of asciidoc in https://github.com/os-autoinst/openQA/blob/master/docs/WritingTests.asciidoc#using-snapshots-to-speed-up-development-of-tests

@foursixnine didn't you prepare an update for that?

**Comment by pevik** [comment]
@okurz: sure, it would look better if only actual code was rendered as a code.

**Comment by okurz** [comment]
sure, maybe you want to propose some more rework of this section accordingly? Any please update your git commit message subject line as the `+` are certainly not a typo

**Comment by pevik** [comment]
> sure, maybe you want to propose some more rework of this section accordingly?
Maybe I'll find some other tiny fixes while reading docs.

> Any please update your git commit message subject line as the + are certainly not a typo
'+...+' output in commands was a bit confusing and not correct, even it's not a typo :-). OK, I'll improve my commit message.

**Comment by okurz** [comment]
LGTM

**Comment by foursixnine** [comment]
@pevik you may want to use [this script](https://github.com/foursixnine/openQA/blob/doc/generator_script/script/generate-documentation) to generate a single document. 

What @okurz meant with the code blocs and rendering, is mainly a rendering problem that gollum has, as it is part of an example block... gollum renders it as if it was part of a code block.

**Comment by foursixnine** [comment]
i'm against removing the +instruction+, since we heavily use this within our documentation for referencing inline code.

@pevik To understand a bit your use case, you're trying to read the documentation from a console right?

**Comment by pevik** [comment]
@foursixnine just have a look in https://github.com/os-autoinst/openQA/blob/master/docs/WritingTests.asciidoc#using-snapshots-to-speed-up-development-of-tests vs. fixed version in https://github.com/pevik/openQA/blob/doc-fixes/docs/WritingTests.asciidoc#using-snapshots-to-speed-up-development-of-tests

Wrong output:
2. set +MAKETESTSNAPSHOTS=1+ on a job. This will make openQA save a
...
3. create a job again, this time setting the +SKIPTO+ variable to the snapshot

This part of docs is rendered as a code, so '+' in '+SOME_VAR+' doesn't have formatting meaning and just show in plain text. In normal text '+....+' renders as monospace, that's why it was probably used.

**Comment by pevik** [comment]
@foursixnine I got your point. I understand that asciidoctor is important. It would be just nice to have it good also on github (newcomers will read it from github).
Thanks for link to script :-).

**Comment by coolo** [comment]
@foursixnine  So where are we with this?

**Comment by foursixnine** [comment]
It would look like this now: New version

**Comment by pevik** [comment]
@foursixnine This is exactly what I wanted. I'll push 2 tiny typo fixes in another branch.

**Comment by pevik** [comment]
foursixnine did the job, so closing it here. Some fixes which were here I moved into #1096.

**Pull request closed without merging**
