### PR TITLE
Fix issues with editable comments

### PR DESCRIPTION
**Pull request by Martchus**
- Fixes the issue https://progress.opensuse.org/issues/12116 as far as I can reproduce it.
- Editing buttons are now shown correctly when not logged-in as an admin.

### CODE REVIEW

**Comment by okurz** [comment]
did you check if you could actually add a test, still? maybe mock the authentication provider with a simple stub and return what you want from it during tests.

+1

**Comment by Martchus** [comment]
I'll work on it next week and maybe I'll discover some more bugs. In the meantime these commits should already fix two bugs.

**Comment by coolo** [comment]
please port your javascript to jquery

**Comment by Martchus** [comment]
I can port it to JQuery. But why do you prefer JQuery for such simple things which can easily be achieved without? The only reason I can think of is consistency.

**Comment by coolo** [comment]
... which is good enough

**Comment by Martchus** [comment]
Saves us 2 lines per function and actually looks a little bit tidier: https://github.com/os-autoinst/openQA/pull/701

**Pull request merged**
