### PR TITLE
[WIP][DISCUSSION] fail on warnings in tests

### PR DESCRIPTION
**Pull request by okurz**
all tests fail because the no warnings is one test that would need explicit counting -- use Test::NoWarning to fail on any warning

also see https://rt.cpan.org/Public/Bug/Display.html?id=66485
and https://rt.cpan.org/Public/Bug/Display.html?id=36603
about the "test plan" issue.

see http://search.cpan.org/~adamk/Test-NoWarnings-1.04/lib/Test/NoWarnings.pm
for the manual

### CODE REVIEW

**Comment by coolo** [comment]
TOO LONG SUMMARY!

**Comment by aaannz** [comment]
Is it only for me, or do I need to explicitly look up error in travis log now?

**Comment by okurz** [comment]
you mean travis web interface has changed? I have always clicking on "Details" here when a check failed, linking to travis. Within there it would show the log and the error message within. *now* I have to click "Raw log" on travis to get the actual log.

**Comment by okurz** [comment]
@coolo the summary lines could be shorter if I as a developer would have the possibility to assign a label myself ;-P

**Comment by okurz** [comment]
obsoleted by #570

**Pull request closed without merging**
