### PR TITLE
Document the configuration to enable the packages comparation feature

### PR DESCRIPTION
**Pull request by ilausuch**
This commit completes #3303 with the docuemntation to enable this feature and an example

### CODE REVIEW

**Review by kalikiana — APPROVED** [review]
Excellent! Thank you for adding that!

**Comment by kalikiana** [comment]
For the unrelated OBS failure see [poo#72196](https://progress.opensuse.org/issues/72196)

**Comment by okurz** [comment]
Typo in git commit message.

My suggestion for the complete git commit message with shorter subject line:

```
Document configuration of worker package diff

This commit complements #3303 with documentation of the necessary configuration
variable to enable this feature.
```

**Review by okurz — APPROVED** [review]
You need to rebase

**Pull request merged**
