### PR TITLE
Add workaround for missing 'lsof' dependency

### PR DESCRIPTION
**Pull request by okurz**
See https://build.opensuse.org/request/show/668410

### CODE REVIEW

**Comment by Martchus** [comment]
So my [previous comment](https://github.com/os-autoinst/openQA/pull/1971#discussion_r250689064) was wrong? We're only one SR away from the proper fix so I'd say no.

**Comment by okurz** [comment]
Yes, I think we *can* fix it dynamically. See the workaround in the test job https://travis-ci.org/os-autoinst/openQA/jobs/484299460#L499 fixing the individual test job. Only the neighboring test job https://travis-ci.org/os-autoinst/openQA/jobs/484299462#L1115 was "stalled" again. I don't know what that means but I would appreciate if we can merge this so that I can fix the openQA packages still *today* to prevent the o3 workers being down again tomorrow because of missing https://github.com/os-autoinst/openQA/pull/1972

**Comment by okurz** [comment]
@coolo this is what I mean. I rebased this branch on https://github.com/os-autoinst/openQA/pull/1976 and now https://travis-ci.org/os-autoinst/openQA/builds/484845341?utm_source=github_status&utm_medium=notification is all green again, no "stalled build". Could be coincidence but I think it's related to the cache test.

**Comment by coolo** [comment]
ah. anyway - the request is in factory

**Pull request closed without merging**
