### PR TITLE
Use more common 'qw()' style

### PR DESCRIPTION
**Pull request by okurz**
Seems this is the preferred style in all cases, e.g. see
* https://perlmaven.com/qw-quote-word
* http://perlmeme.org/howtos/perlfunc/qw_function.html
* http://www.perlmonks.org/?displaytype=print;node_id=401006
* http://perl101.org/arrays.html

### CODE REVIEW

**Comment by coolo** [comment]
I like it, but as I'm breaking all other PRs I would like to have some feedback :)

**Comment by kraih** [comment]
👍 Although in cases like `use Data::Dump qw(pp);` i do prefer the look of `use Data::Dump 'pp';`.

**Comment by aaannz** [comment]
Fine by me :+1:

**Comment by coolo** [comment]
@kraih - don't make it more complicated :)

**Comment by coolo** [comment]
merged manually

**Pull request closed without merging**
