### PR TITLE
Turn warning about missing assets when restarting jobs into error

### PR DESCRIPTION
**Pull request by Martchus**
* Allow forcing the restart via API
* Suggest restarting parent job if there is one
* See https://progress.opensuse.org/issues/34783
---
screenshot_20200401_113614

### CODE REVIEW

**Comment by Martchus** [comment]
Some tests are failing now. Likely these tests rely on restarting fixture jobs with missing assets. I'll upload a screenshot.

**Comment by okurz** [comment]
all good now

**Comment by Martchus** [comment]
I'm merging this now. If we need to add yet another exception we can do it similarly to https://github.com/os-autoinst/openQA/pull/2807. (I'm just saying. There is no reason to revert the entire PR if this becomes problematic just for yet another special case.)

**Comment by okurz** [comment]
sure. Haven't merged it earlier because package tests were not yet done.

**Pull request merged**
