### PR TITLE
WIP: Documentation Testapi Table

### PR DESCRIPTION
**Pull request by MalloZup**
Add a table instead of list.

API commands should be discussed.

### CODE REVIEW

**Comment by okurz** [comment]
I prefer the list instead of the table as the length of individual commands with all options differs and this makes wrapping inside the table happening often causing the commands to be less readable. If you care about documentation then I suggest to not invest time into manual tuning of output that should be autogenerated from the os-autoinst POD.

**Comment by MalloZup** [comment]
Oliver, look, at list, we have deprecated api there, so it less readable. (wait_idle is there). I prefer the table because the api is more visible.

**Comment by okurz** [comment]
> we have deprecated api there

what do you mean?

**Comment by MalloZup** [comment]
like wait_idle

**Comment by coolo** [comment]
the rendering in a table is horrible. And wait_idle is *not* deprecated - it's usage should be limited in portable tests, that's all.

**Comment by MalloZup** [comment]
it's not horrible i would say debatable, the list for moment look not nice, too. imho. 

ok i don't mind, we have different estetic point of views

**Comment by MalloZup** [comment]
ok i close the table stuff, since i don't see any interest from others.

**Pull request closed without merging**
