### PR TITLE
Require fixed version of AssetPack plugin

### PR DESCRIPTION
**Pull request by coolo**

### CODE REVIEW

**Comment by coolo** [comment]
Unfortunately broken too

```
Uncaught exception from user code:
	Unable to load "assetpack.def". at /home/travis/perl_modules/lib/perl5/Mojolicious/Plugin/AssetPack.pm line 184.
	Mojolicious::Plugin::AssetPack::_process_from_def('Mojolicious::Plugin::AssetPack=HASH(0x9b9e898)', undef) called at /home/travis/perl_modules/lib/perl5/Mojolicious/Plugin/AssetPack.pm line 62
	Mojolicious::Plugin::AssetPack::process('Mojolicious::Plugin::AssetPack=HASH(0x9b9e898)') called at lib/OpenQA/WebAPI.pm line 120
	OpenQA::WebAPI::startup('OpenQA::WebAPI=HASH(0x94e2748)') called at /home/travis/perl_modules/lib/perl5/Mojolicious.pm line 174
	Mojolicious::new('OpenQA::WebAPI') called at /home/travis/perl_modules/lib/perl5/Mojo/Server.pm line 17
	Mojo::Server::build_app('Mojo::Server=HASH(0x94eabc0)', 'OpenQA::WebAPI') called at /home/travis/perl_modules/lib/perl5/Test/Mojo.pm line 244
	Test::Mojo::new('Test::Mojo', 'OpenQA::WebAPI') called at ./t/ui/04-api_keys.t line 30

**Comment by coolo** [comment]
It's looking in the wrong places:

```
coolo@gertrude#openQA>strace -f perl t/api/02-iso.t  2>&1 | grep assetpack
stat("/space/prod/openQA/lib/assets/assetpack.def", 0x118b298) = -1 ENOENT (No such file or directory)
stat("/usr/lib/perl5/vendor_perl/5.24.0/Mojo/../Mojolicious/resources/public/assetpack.def", 0x118b298) = -1 ENOENT (No such file or directory)
        Unable to load "assetpack.def". at /usr/lib/perl5/vendor_perl/5.24.0/Mojolicious/Plugin/AssetPack.pm line 184.

**Comment by coolo** [comment]
@kraih please take over. This is internally to assetpack and nothing we do.

**Comment by kraih** [comment]
I'll take a look.

**Comment by jhthorsen** [comment]
Does `$app->home->to_string` report the expected location? I wonder if https://github.com/jhthorsen/mojolicious-plugin-assetpack/blob/master/lib/Mojolicious/Plugin/AssetPack.pm#L29 could return the wrong location...

`assetpack.def` is located here: https://github.com/jhthorsen/mojolicious-plugin-assetpack/blob/master/lib/Mojolicious/Plugin/AssetPack.pm#L179-L180

**Comment by coolo** [comment]
app->home is lib/ subdir - which is not the home as far as I can tell. So mojo bug

**Comment by kraih** [comment]
I will release Mojolicious 7.18 later today, it should fix the problem.

**Pull request merged**
