### PR TITLE
previous: Move current limit where other options are

### PR DESCRIPTION
**Pull request by okurz**
Example screenshot:
openqa_previous_move_limit_where_options_are

### CODE REVIEW

**Comment by coolo** [comment]
Not quite. "Show 20 / 50 / 100 / 400 previous results, limited to 50" is just nonsense.

I wanted you to "Show 20 / *50* / 100 / 400 previous results" where 50 is not a link, but bold or italic or whatever

**Comment by coolo** [comment]
So italic surrounded by / just doesn't work :)

So I'm happy with how "Show [10](#) / [20](#) / __50__ / [100](#) / [400](#) previous results" looks

**Comment by okurz** [comment]
If I can adapt this in the cool `map` call I would be happy :-)

**Comment by coolo** [comment]
no wristband colour for "just don't give into the temptation to apply a hack"? :)

**Comment by okurz** [comment]
The problem I see with "Show [10](#) / [20](#) / __50__ / [100](#) / [400](#) previous results" is that it's not clear for the user why less results could be shown. What about

1. Show up to [10](#) / [20](#) / __50__ / [100](#) / [400](#) previous results
2. Show [10](#) / [20](#) / __50__ / [100](#) / [400](#) previous results (max)
3. Limit to [10](#) / [20](#) / __50__ / [100](#) / [400](#) previous results

**Comment by coolo** [comment]
3 preferred over 1

**Comment by okurz** [comment]
updated:
* rebased
* integrated proposal to mark current limit as bold (see example screenshot)

**Pull request merged**
