### PR TITLE
Fix api/v1/job_templates for empty groups/machines

### PR DESCRIPTION
**Pull request by okurz**
As observed with local database.

### CODE REVIEW

**Comment by coolo** [comment]
this includes the other PR, no idea what happens when I merge this so I would rather not

**Comment by okurz** [comment]
It includes one commit which is already in master now so merging will just include the difference, i.e. the one commit "Fix api/v1/…". If unsure, try to merge locally. It works. Also with a rebase it would do the same, skip the already existing commit.

**Comment by coolo** [comment]
merged locally

**Comment by coolo** [comment]
s,locally,manually,

**Pull request closed without merging**
