### PR TITLE
t: Increase statement coverage of 25-cache-service.t to reliable 100%

### PR DESCRIPTION
**Pull request by okurz**
* t: Fix coverage of separate process in 25-cache-service.t
* t: Increase statement coverage ratio in 25-cache-service.t
* t: Delete unused function _port in 25-cache-client.t

### CODE REVIEW

**Review by kalikiana — COMMENTED** [review]
I like the explicit bails.

Did you use a particular command to verify the coverage improvements?

**Comment by Martchus** [comment]
Seems like tidy doesn't like it.

**Comment by okurz** [comment]
> I like the explicit bails.
> 
> Did you use a particular command to verify the coverage improvements?

Yes, `env OPENQA_TEST_TIMEOUT_SCALE_COVER=6 make coverage KEEP_DB=1 TESTS=t/25-cache-service.t` which is basically what we have described in http://open.qa/docs/#testing to conduct a coverage analysis

> Seems like tidy doesn't like it.

Yeah, the past days I was stuck with a mismatching tidy version locally due to a newer version being available in cpan. But I did `cpanm -U Perl::Tidy` to *fix* that :)

Updated:
* Tidied

**Review by kalikiana — APPROVED** [review]

**Comment by okurz** [comment]
I just deleted two redundant, duplicated test statements.

**Pull request merged**
