### PR TITLE
Add screenshots table

### PR DESCRIPTION
**Pull request by coolo**
This is not finished yet as I need to write the 2nd part of the migration.

But I'm not really sure if this will scale up to our production instances. So I would like to hear 2nd oppinions

### CODE REVIEW

**Comment by Martchus** [comment]
The parts of the code I understand look good, tables are like we discussed. But when reading the travis log it seems that lots of things are broken now. Even `t/api/10-jobgroups.t` which seems very unrelated fails now.

**Comment by coolo** [comment]
Wo gehobelt wird, fallen Späne :)

As I said: I'm not done here.

**Comment by coolo** [comment]
So this is the result of running the migration on my instance: http://pasteall.org/117701

Not sure how to express left outer joins in DBIX yet :)

**Comment by coolo** [comment]
-1% sounds bad

**Comment by coolo** [comment]
I'm not so motivated to cover more as I'm still not sure if this approach will work in production :(

What I tested manually though:
  - migrate sqlite database with existant images
  - that tons of images are deleted
  - that all links of recent jobs are still there
  - that deleting a job will delete some images
  - that a running job will correctly save images and links both into file system and DB

So I would like to merge this and deploy it on opensuse.org and monitor how it behaves. We can then add more tests to get over 73% again

**Comment by coolo** [comment]
so I decided against merging it, but I deployed it from the branch. One scan_images task takes about 30 seconds and there are 3903 left to go, so in about 32 hours we will know if the index holds to run the scan_images_link jobs.

**Comment by coolo** [comment]
7 hours later, it didn't slow down (first good news) - so we're down to 2957 TODO. And are up to 3.3M screenshots

**Comment by coolo** [comment]
I just had a frightening thought: if something/someone deletes a job while the background migration is in process, we will delete all images not symlinked *at that point*. And if scan_images_link didn't even start at that point, this will be alot.

So I need some kind of marker that that the last migration ran - but I lack a good idea where to put that. Ideas? I don't really want to ask gru_tasks table

**Comment by coolo** [comment]
the migration is done (I stopped it before the final deletion). There are 11.941.491 screenshots. 1.154.134 of them are linked from 15498 jobs. Which is puzzling as we have 28.839 jobs in the database. So I need to double check that part

**Comment by coolo** [comment]
ok, there are tons of jobs created between 24 and 27 days ago that have no details uploaded whatsoever. This explains the problem. On to deleting 10 million pngs :)

**Comment by coolo** [comment]
First the good news: files are deleted:
image

The bad news: jobs running during the migration have tons of dangling symlinks. There are some safety measures to take

**Pull request merged**
