### PR TITLE
Include all relevant distros when linking overview

### PR DESCRIPTION
**Pull request by Martchus**
* Required for Tumbleweed/Kubic's release process
* See https://progress.opensuse.org/issues/23914

### CODE REVIEW

**Comment by sysrich** [comment]
Will this also work on the group_overview page, eg https://openqa.opensuse.org/group_overview/1 ?

**Comment by Martchus** [comment]
Yes, I tested that manually. I have no explicit automatic test for it because internally the same code is used on both pages.

**Comment by Martchus** [comment]
I haven't had performance in mind, just simplicity/readability of the code: In this case the order doesn't matter. However, sorting something implies the order matters (at least I assume that when reading code which explicitly sorts something).

But I can change it if you like because I don't really care about this detail.

**Comment by Martchus** [comment]
Order is now consistent.

**Comment by okurz** [comment]
LGTM

**Pull request merged**
