### PR TITLE
Fix AppArmor rules for git

### PR DESCRIPTION
**Pull request by baierjan**
The change was tested within openQA-in-openQA test, the issue should be visible in https://openqa.opensuse.org/tests/4423875

### CODE REVIEW

**Comment by perlpunk** [comment]
How can it be explained that the openqa-in-openqa test only failed sporadically?

**Comment by baierjan** [comment]
You mean in context of https://progress.opensuse.org/issues/165408? For me in my setup, I can reproduce it every time. Maybe we have workers where AppArmor is not enforced (succeeds)  and where it is enforced (fails)?

**Comment by baierjan** [comment]
> Maybe we have workers where AppArmor is not enforced (succeeds) and where it is enforced (fails)?

Although that does not make sense as the AppArmor needs to be enforced inside to fail at that stage...

**Comment by perlpunk** [comment]
Yes, I mean https://progress.opensuse.org/issues/165408
I still don't understand it.
Maybe I'm confusing what's running on the o3 worker and what's running inside of qemu in the openqa-in-openqa test.

So in https://github.com/os-autoinst/os-autoinst-distri-openQA/pull/199 you are enabling apparmor inside of the test.

Can an apparmor installation on an o3 worker influence whether the service is enabled inside the test?

**Comment by perlpunk** [comment]
And I thought we do actually have apparmor enabled already:
https://openqa.opensuse.org/tests/4422620/logfile?filename=test_running-journal.log.txt#filter=apparmor
```
Aug 22 06:54:31 susetest apparmor.systemd[690]: Restarting AppArmor
Aug 22 06:54:31 susetest apparmor.systemd[690]: Reloading AppArmor profiles
```

**Comment by baierjan** [comment]
AppArmor in the inner test will be enabled after https://github.com/os-autoinst/os-autoinst-distri-openQA/pull/199. The AppArmor itself is installed and enabled from the boot, but after the profile is installed (which happens during the test itself) the newly added profiles are not loaded as AppArmor needs reload and the binaries needs to be restarted (there might be maybe the room for some sporadic behaviour?).

**Comment by perlpunk** [comment]
right, I also thought about it being an issue with timing...

**Review by kalikiana — APPROVED** [review]

**Review by perlpunk — APPROVED** [review]

**Comment by baierjan** [comment]
As mergify already merged the other one, I will proceed here; otherwise we will see https://openqa.opensuse.org/tests/4423875#step/test_running/8 more often.

**Pull request merged**
