### PR TITLE
display all needles

### PR DESCRIPTION
**Pull request by lnussel**

### CODE REVIEW

**Comment by coolo** [comment]
Thanks ludwig for throwing this at us and leaving for vacation ;)

**Comment by nilxam** [comment]
I can't see the wrong here, the <=> operator is correct.

I am not so sure what is the subject mean "display all needles" that comparing between old if..elsif..else and if..if..!if though :)

**Comment by coolo** [comment]
I *assume* this is about showing all needles even if succeeding the match

**Comment by nilxam** [comment]
well, it won't. if it has a succeeded to match a needle, it's only have contains 'needle': $needlename in details-xxx.json(the higher similarity one), and haven't 'needles'  object there, vice versa. if failing the match, will have 'needles' there then...

**Pull request merged**
