### PR TITLE
Improve error handling when deleting needle

### PR DESCRIPTION
**Pull request by Martchus**
Fix https://progress.opensuse.org/issues/11796

### CODE REVIEW

**Comment by coolo** [comment]
please delete the needles one by one - and report *which* needle failed, but keep deleting the rest (and offer a cancel).

**Comment by Martchus** [comment]
The rest will be deleted. If at least one needle couldn't be deleted an error message is shown (with all failed needles and the reason for each needle).

The only advantage of deleting needles on by one would be offering a cancel. (But in theory could be done even with the single request approach.) The disadvantage would be that it likely takes longer when deleting lots of needles at once.

**Comment by coolo** [comment]
No, there is one *huge* advantage of deleting one by one: progress report and avoiding timeouts.

**Comment by coolo** [comment]
because as soon as you delete more than 10 your error will be '504 timeout' - and you have no idea what needles are deleted

**Comment by Martchus** [comment]
Ok, haven't thought about timeouts. So then I'll make it delete one by one.

**Comment by okurz** [comment]
can the list of needles be auto-refreshed after a deletion was requested? It's stil showing the needles after deleting for me.

**Comment by Martchus** [comment]
Both issues are fixed now.

**Comment by Martchus** [comment]
I'll re-trigger this when https://github.com/os-autoinst/openQA/pull/946 has been merged.

**Comment by coolo** [comment]
That didn't work too well:

```
[Tue Oct 18 20:45:24 2016] [17181:debug] Remove needle /var/lib/openqa/share/tests/opensuse/products/opensuse/needles/yast2_snapper-snapshots-gnome-20160905.json and /v
ar/lib/openqa/share/tests/opensuse/products/opensuse/needles/yast2_snapper-snapshots-gnome-20160905.png
[Tue Oct 18 20:45:24 2016] [17181:error] Undefined subroutine &OpenQA::Schema::Result::Needles::commit_git_return_error called at /usr/share/openqa/script/../lib/OpenQA
/Schema/Result/Needles.pm line 209.

**Pull request merged**
