### PR TITLE
Remove resource allocator

### PR DESCRIPTION
**Pull request by kraih**
When i started replacing the dbus methods in `OpenQA::ResourceAllocator` with a redis alternative i noticed that dbus was only used for blocking RPC calls. And that means that we could have just as well used `OpenQA::Resource::Locks/Jobs` directly from the API controllers, making the resource allocator obsolete. So that's what i ended up doing. This pull request removes the resource allocator completely, and i will have to use another service for introducing redis into openQA (most likely the scheduler).

The only noticeable difference should be the removal of the single process bottleneck that blocking RPC calls to `OpenQA::ResouceAllocator` caused. And that means there is a small risk that new race conditions will be introduced once locks/barriers can be managed with the prefork daemon. But looking through the code in `OpenQA::Resource::Locks/Jobs` (and having done a few tests) it seems rather defensive and i'm cautiously optimistic that it will "just work". 😉 Worst case, we need to add one or two transactions to `OpenQA::Resource::Locks` later.

Progress: https://progress.opensuse.org/issues/46778

### CODE REVIEW

**Comment by coolo** [comment]
please give a good test with multi machine jobs on staging

**Comment by Martchus** [comment]
This looks already good and also complete with all the adjustments to the spec file and bootstrap script. Let's see how it works on staging.

**Comment by kraih** [comment]
Multi machine tests will take a little more time i'm afraid, since our staging machines aren't working properly at the moment (and i'm still learning while trying to fix them 😉).

**Comment by coolo** [comment]
you learning about them has priority over merging this :)

**Comment by kraih** [comment]
Small progress update, ran CaaSP multi machine tests so far and everything looks fine.

**Comment by Martchus** [comment]
I'm wondering on which instance. Only openqa-staging-1 has CaaSP jobs but they failed as incomplete.

**Comment by kraih** [comment]
@Martchus I restarted the CaaSP jobs right away yesterday to try again after they were successful, but it looks like the API keys expired around the same time...

**Comment by kraih** [comment]
@ldevulder also ran some independent HA/HPC tests successfully on his lab with this pull request applied.

**Pull request merged**
