### PR TITLE
spec: Move critic to -devel as we do not use it in %build or %check

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by okurz** [comment]
Interesting, chrome now fails to start. I doubt it is related to the changes in this PR

**Comment by okurz** [comment]
failed in package test with

```
[  192s] ! Finding Perl::Critic::Freenode on cpanmetadb failed.
[  193s] ! cannot open file '/home/abuild/.cpanm/sources/http%www.cpan.org/02packages.details.txt.gz': No such file or directory opening compressed index
[  193s] ! Couldn't find module or a distribution Perl::Critic::Freenode
[  193s] ! Finding Perl::Critic on cpanmetadb failed.
[  193s] ! cannot open file '/home/abuild/.cpanm/sources/http%www.cpan.org/02packages.details.txt.gz': No such file or directory opening compressed index
[  193s] ! Couldn't find module or a distribution Perl::Critic
[  193s] ! Installing the dependencies failed: Module 'Perl::Critic' is not installed, Module 'Perl::Critic::Freenode' is not installed
[  193s] ! Bailing out the installation for ..
[  193s] !
[  193s] ! Can't write to /usr/lib/perl5/site_perl/5.28.1 and /usr/bin: Installing modules to /home/abuild/perl5
[  193s] ! To turn off this warning, you have to do one of the following:
[  193s] !   - run me as a root or with --sudo option (to install to /usr/lib/perl5/site_perl/5.28.1 and /usr/bin)
[  193s] !   - Configure local::lib in your existing shell to set PERL_MM_OPT etc.
[  193s] !   - Install local::lib by running the following commands
[  193s] !
[  193s] !         cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
[  193s] !
[  193s] --> Working on .
[  193s] Configuring /home/abuild/rpmbuild/BUILD/openQA-4.6.1575359332.0e4ea4c45 ... OK
[  193s] ==> Found dependencies: Perl::Critic::Freenode, Perl::Critic
[  193s] error: Bad exit status from /var/tmp/rpm-tmp.IDjHF7 (%check)
[  193s] 
```

**Comment by kalikiana** [comment]
Is this change blocking on an OBS issue?

**Comment by okurz** [comment]
not really an "OBS issue". OBS executes tests and somehow they require Perl::Critic but can't find it though should have it in the devel environment.

**Comment by okurz** [comment]
@AdamWill Originally I created this because you mentioned that you don't have the Critic package avaible. However as we execute `cpanm --installdeps --with-feature=test .` within the package build-time tests we need the dependency as build-time requirement. So in the current state this PR will not be mergeable.

**Comment by AdamWill** [comment]
Aha, I see. It's not really a problem, I keep the diffs from our spec to yours documented so it's still relatively easy to follow changes. I just wondered why it was there at all, but this answers that :)

**Comment by okurz** [comment]
There is the option to optionally exclude cpan checks with a flag. This flag can then also be evaluated to distinguish if the packages need to be required upon or not. Feel free to suggest if/else's in the spec file if it also helps you.

**Pull request closed without merging**
