### PR TITLE
Add link to openQA review

### PR DESCRIPTION
**Pull request by asdil12**

### CODE REVIEW

**Comment by coolo** [comment]
you're aware that no one reads these boxes? human brains really quickly learned to ignore everything in coloured boxes above web pages. So the more text you add here, the more people have to scroll - but don't expect anyone to find this. 

if this is just about providing the links for convenience, you better add it into some footer to be available for those that know.

**Comment by Martchus** [comment]
The box as it currently is takes indeed much space because of large padding, font size, line height, ...
If we would improve this, there should be enough room for this convenience link.

**Comment by coolo** [comment]
This is not about room - web pages are endless (vertically). This is about humans actually finding the information they require. The box you're abusing is basically the entrance point. Those that have no idea what they are looking for should be able to get an idea what openqa.suse.de does. So the first 2 links of the 4 (now proposed 5) belong there. 

Because as soon as you know what openqa.suse.de is, your eyes will ignore this box and look for things below it. Your "make it smaller, it takes space" is because you want to optimize the 2nd use case. But I tell you: it's there for a reason. It's large for a reason.

So if you need a place for convenient links to those familiar with openqa.suse.de (and unable to use bookmarks), find such a place - but don't abuse existant places.

**Comment by Martchus** [comment]
I understand now why you don't like the link in the box. Applying this criteria the last 2 links are indeed odd.

The intention with the link is making people who are already familiar with openQA find the review script more easily (and not providing a bookmark). Where would you put the link for that purpose?

**Comment by okurz** [comment]
branding for footer, too?

**Comment by coolo** [comment]
the navigation bar is pretty empty too. 'Misc Links'?

**Comment by okurz** [comment]
navigation bar sounds good, but where to fill the "misc links". `openqa.ini`? It's a pretty instance specific setting I guess

**Comment by Martchus** [comment]
I think the can use the same approach as for docbox and sponsorbox.

**Comment by okurz** [comment]
That would be branding but I would prefer better configurability over the INI file

**Comment by coolo** [comment]
Having a list of URLs in openqa.ini sounds reasonable to me. With the menu not shown when there are none.

**Comment by coolo** [comment]
Wait, you need a href and a title - that becomes messy. So I take that back - and go for site branding :)

**Comment by coolo** [comment]
How about supporting really site branding, i.e. files we read but that aren't in git?

**Comment by okurz** [comment]
Under etc directory?

Or use some yaml title+href definitions in files

**Comment by coolo** [comment]
I guess yaml makes it more flexible for later theme changes.

**Comment by okurz** [comment]
didn't you want the links in an external file and fill these into a footer rather than the approach here?

**Comment by coolo** [comment]
sure I want to, but 2 or 3 links in the wrong place don't hurt for the time being. I'm certain you already track the feature elsewhere

**Comment by okurz** [comment]
sure I do [poo#13954](https://progress.opensuse.org/issues/13954)

**Comment by coolo** [comment]
see?

**Pull request merged**
