### PR TITLE
Administration API

### PR DESCRIPTION
**Pull request by nadvornik**
https://progress.opensuse.org/issues/5568

The API works OK for web pages where the main entry (machine. product, test suite) is created first and the variables are added later. For load_tempates script it is usable but not efficient so I will probably have to add
another function that creates whole entry at once.

### CODE REVIEW

**Comment by ancorgs** [comment]
There are some things that I'm not completely happy about. The original code was far from perfect but we could live with it because it was "just" a preliminary HTML interface for admins, but if we are moving things into the API, we should be more strict.

1. The routes under /api should be as REST as possible. The management of variables is not REST at all. I'd treat them just as another attribute of the container object. Nested resources is also an option, but probably overkill.
2. The routes under /api should never respond to HTML. If we want to use API methods from the interface, we should process the JSON in the browser using javascript, as it's done, for example, in the live view.
3. I'd not name the routes like "apiv1_admin_job_templates", but simply "apiv1_job_templates"
4. (optional) We should take the opportunity to reduce code redundancy. All the controllers are essentially equal.

**Comment by ancorgs** [comment]
As requested by @nadvornik. I'll elaborate on first point.

First of all, this proposal is just a preliminary idea, the first thing that came to my mind when reading the routes defined in the PR, maybe there are cleaner solutions.

A query like ```GET /api/v1/test_suites/10``` should return a whole JSON structure with the settings just as an additional attribute. That is, something like:
```json
{
  "test_suite": {
    "name": "update_13.1-kde",
    "prio": "50",
    "settings": {
      "DESKTOP": "kde",
      "UPGRADE": "1"
    } 
  }
}
```

For POST and PUT actions exactly the same structure should be used. We have two options to send a "complex" (not only key-value pairs) structure:

1. Set the content type to application/json and simply send a JSON structure as the content of the request
2. Use "[]" in the name of some params to implement nesting

I'd go for (2) because it's more coherent with the rest of our current API (creating jobs, workers, commands, etc.). Moreover, it's the Rails way and our current API is already completely Rails influenced, so it makes sense. ;-)

That means that a creation query would be something like:
```
POST /api/v1/test_suites
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

name=update_13.1-kde&prio=50&settings[DESKTOP]=kde&settings[UPGRADE]=1
```

With some frameworks (like Ruby on Rails) variable names with "[]" would result in a nested structure server-side right away. With mojolicious we'll probably need some extra parsing of the param names.

Of course, if you don't like it, we still have the option of modeling settings as a nested resource, with urls like:
```
GET /api/v1/test_suites/10/settings
GET /api/v1/test_suites/10/settings/DESKTOP
POST /api/v1/test_suites/10/settings/UPGRADE
```
But I find it quite overkill, to be honest.

**Comment by ancorgs** [comment]
I've just remembered that I already looked into the problem of passing structures as parameters in mojolicious and I ended up here http://search.cpan.org/~ivsokolov/Mojolicious-Plugin-GroupedParams-0.04/lib/Mojolicious/Plugin/GroupedParams.pm

Is a solution that uses "." (my proposal used "[]" as Rails does) for nesting things.

**Comment by ancorgs** [comment]
Even better, fits the Rails way and it's packaged :-)

http://software.opensuse.org/package/perl-Mojolicious-Plugin-HashedParams

**Comment by nadvornik** [comment]
Ok, I am rewriting it with HashedParams.

**Comment by nadvornik** [comment]
Ok, here is the reworked api.
It does not touch the admin pages, I will do it in separate request.

**Comment by coolo** [comment]
looks good to me.

**Comment by ancorgs** [comment]
LGTM

**Pull request merged**
