### PR TITLE
Add script "rneedles.py"

### PR DESCRIPTION
**Pull request by yifanjiang**
This is a very simple local needles viewer providing an easier
way to check a local needle on demand.

### CODE REVIEW

**Comment by okurz** [comment]
LGTM

**Comment by coolo** [comment]
I have a couple of comments, sorry :)

- what does the r stand for? and why plural? I see it only handling one needle. 
- it only handles one area, when there can be multiple - which can be quite important. One area matches and one doesn't
- you show the area always as green (btw, you should add a comment before the color, most people are not familiar with BRG) even when it's an exclude area. You should only show 'match' areas as green, and exclude areas as red.

**Comment by yifanjiang** [comment]
Hey coolo,

1. _r_ stands for _read_. rneedle.py or read_needle.py sounds good to me.

2. 3. Good points. I admit I wanted to show the way to do that instead of fully complete functions :-) I can handle those multiple areas before the PR gets accepted. I agree they are important. 

@All, 

BTW. how do you feel a local needle editor helps? Something like:

   - people draw rectangles in a png, define "match" or "unmatch" 
   - the editor then generates an needle compatible json?

**Comment by yifanjiang** [comment]
Hopefully something like this looks better:)

https://github.com/yifanjiang/openQA-1/commit/cf2405d70fbcf3d974035f470153be8437eaca6a

**Comment by okurz** [comment]
> BTW. how do you feel a local needle editor helps?

@yifanjiang Yes, I think that would help for some use cases. Some don't want to install a local openQA instance. I don't know where the limitations of the editor will be as one needs the screenshots anyway.

I would just include the script within openQA but I am ok with keeping it in a separate repo if others suggest it.

**Comment by yifanjiang** [comment]
@okurz 

Thanks for the comments, it may even makes sense if we can edit the existed needle by drag/drop the rectangles :-)  

@coolo 

I have got the code rebased to handle multiple areas. Please feel free to propose another proper file name :-)

**Comment by lnussel** [comment]
please don't add python code to openqa. Bad enough that we still have https://github.com/os-autoinst/os-autoinst/blob/master/crop.py which should actually do what you want.

**Comment by yifanjiang** [comment]
@lnussel Wow, that's a nice one I was looking for :-) Thanks for working on that. I'd withdraw my PR.

**Pull request closed without merging**
