### PR TITLE
Migrate to Bootstrap 4

### PR DESCRIPTION
**Pull request by Martchus**
Most pages look ok now. The list of broken pages mentioned in https://progress.opensuse.org/issues/34519 is much smaller now. This is maybe done in just another day.

### CODE REVIEW

**Comment by Martchus** [comment]
I'll deploy this on e212. This also includes restructuring the stylesheets (before there wasn't really a structure). I basically splitted the huge stylesheet into multiple parts. Those are combined via SCSS import in openqa.scss.

**Comment by coolo** [comment]
if this is deployed on e212, then I'll eat a broom.

**Comment by Martchus** [comment]
I thought I'd manage to deploy this yesterday but run into issues with the `update-cache.sh` script. I fixed them but though haven't had the time to deploy.

BTW: The issue was that the script sets the locale to "C" which prevents SASS to handle UTF-8 correctly (and some comments in the Bootstrap 4 code use UTF-8 characters).

**Comment by coolo** [comment]
I̶̢ ̵̀t̨̨h͝ì̀n͏͜k un̕ic̶͘ǫ̸́d҉e̴͠ ̴͘s̵̷ḩ͢o͡u͢ld҉̶̢ ̡b̧́e̕ ͡f́̀o̕͜͟r̸͝bi̷d̸͜d̨e̸̡ń̕͞

**Comment by Martchus** [comment]
To summarize what's still missing:
* deployment for Leap 42.3
```
[  107s] Error: Invalid CSS after "...lor}: #{$value}": expected "{", was ";"
[  107s]         on line 4 of /home/abuild/rpmbuild/BUILD/openQA-4.5.1523528167.c75fd5a2/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.0.0/scss/_root.scss
[  107s]         from line 11 of /home/abuild/rpmbuild/BUILD/openQA-4.5.1523528167.c75fd5a2/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.0.0/scss/bootstrap.scss
[  107s]         from line 7 of standard input
[  107s]   Use --trace for backtrace.
[  109s] Archive::Extract will be removed from the Perl core distribution in the next major release. Please install it from CPAN. It is being used at /home/abuild/rpmbuild/BUILD/openQA-4.5.1523528167.c75fd5a2/script/../lib/OpenQA/Schema/Result/Assets.pm, line 25.
[  110s] Error: Invalid CSS after "...lor}: #{$value}": expected "{", was ";"
[  110s]         on line 4 of /home/abuild/rpmbuild/BUILD/openQA-4.5.1523528167.c75fd5a2/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.0.0/scss/_root.scss
[  110s]         from line 11 of /home/abuild/rpmbuild/BUILD/openQA-4.5.1523528167.c75fd5a2/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.0.0/scss/bootstrap.scss
[  110s]         from line 7 of standard input
[  110s]   Use --trace for backtrace.
```

Note that the error does not occur under Tumbleweed, so it is likely the scss version.  (https://build.opensuse.org/build/home:mkittler:branches:devel:openQA/openSUSE_Leap_42.3/x86_64/openQA/_log vs. https://build.opensuse.org/build/home:mkittler:branches:devel:openQA/openSUSE_Tumbleweed/x86_64/openQA/_log)

* test suite basically passes, only full stack test always fails (not sure whether this is related)
```
#   Failed test 'Test 3 is scheduled'
#   at t/full-stack.t line 220.
#                   'State: assigned
# Clone of 2
# Assigned worker: travis-job-e51af43c-2fe9-4989-989a-d07b0f9dba1f:1'
#     doesn't match '(?^:State: scheduled)'
```

**Comment by coolo** [comment]
I linked sass 3.5 into devel:openQA:Leap:42.3 - let's see

**Comment by coolo** [comment]
your test failure sounds like the fullstack is too slow to fetch the web page.

**Comment by Martchus** [comment]
I deployed the latest changes on e212. The link colors and badges look now like in the Bootstrap 3 version.

Note that I also deployed the replacement for the combo box (https://progress.opensuse.org/issues/34195) which is WIP and *not* part of this PR.

**Comment by Martchus** [comment]
Card/panel on test result overview should be fixed now, too.

**Pull request merged**
