### PR TITLE
Enable JSON representation of the test overview

### PR DESCRIPTION
**Pull request by Martchus**
@nicksinger This would be the required change to render the overview as JSON. Maybe it gets merged.

### CODE REVIEW

**Comment by Martchus** [comment]
I just showed @okurz. I tested it locally. I *could* also add a test, but since it is the same as the regular page - just in JSON - I don't think it is necessary.

**Comment by Martchus** [comment]
I can't reproduce the failing `./t/05-scheduler-dependencies.t` and `./t/ui/21-admin-needles.t`. I suppose those are false positives.

**Comment by foursixnine** [comment]
Isn't this the same as doing: `/api/v1/jobs?build=BUILD`  and you can also add the groupid too: `&groupid=`

**Comment by Martchus** [comment]
@foursixnine No, it isn't. This API would return *all* job IDs for that build. The `.json` route enabled by this PR provides the same *filtered* view as the regular group overview.

**Comment by coolo** [comment]
We need a bit fat "don't use the json routes next to /api in scripts" though - the JSON will change whenever we change the controller. And that's fine!

**Comment by coolo** [comment]
As such I even support not adding a test for it - to showcase the !support state of this route :)

**Comment by Martchus** [comment]
Yes, that's an important note. The .json routes do not provide a stable API.

**Comment by okurz** [comment]
Not adding a test because you want to allow source code to change is a very interesting argument though ;)

**Pull request merged**
