### PR TITLE
clone_job: Add convenience option '--remote'

### PR DESCRIPTION
**Pull request by okurz**
Tested locally.

### CODE REVIEW

**Comment by coolo** [comment]
Hmm, I like the feature - but I find --remote a confusing name as it sounds pretty much like --host if not localhost. 
Just brainstorming: --within-instance ?

**Comment by Martchus** [comment]
`--within-instance` sounds good

**Comment by okurz** [comment]
changed to `--within-instance`

**Comment by okurz** [comment]
checks passed now. Anyone wants to merge or approve?

**Pull request merged**
