### PR TITLE
Prefer bulk insert for job settings

### PR DESCRIPTION
**Pull request by coolo**

### CODE REVIEW

**Comment by aaannz** [comment]
:+1:

**Comment by okurz** [comment]
It doesn't make the code cleaner. The "delete" looks weird, too. Can you refactor the stuff which comes before?

**Comment by aaannz** [comment]
I don't care about "weird" delete, but he has a point. The settings are inserted to `%new_job_args` just before this code on [line 187](https://github.com/os-autoinst/openQA/pull/590/files#diff-48251958508548f106b8c017c4e855b7R187).

**Comment by coolo** [comment]
Et tu, Brute?

**Comment by coolo** [comment]
I refactored and ...

**Comment by okurz** [comment]
LGTM

**Pull request merged**
