### PR TITLE
Change striped name from IPA results

### PR DESCRIPTION
**Pull request by cfconrad**
The short test names created from IPA results didn't produce a list
of unique names.
Keeping the extra words after the IP, makes the name unique.

Invite @mudler to have a look.

### CODE REVIEW

**Comment by mudler** [comment]
And i thought we nailed it ... :smile: .. changes looks good, do you have a local test url so we can double-check ?

**Comment by mudler** [comment]
I'm testing other changes on staging, so i just applied your patches on : http://e122.suse.de/tests/21358 ( still running )

**Comment by cfconrad** [comment]
http://fromm.arch.suse.de/tests/1096

**Comment by mudler** [comment]
All fine here as well: http://e122.suse.de/tests/21437 awesome, thanks!

**Pull request merged**
