### PR TITLE
Fix flaky test t/api/11-bugs.t

### PR DESCRIPTION
**Pull request by perlpunk**
See https://progress.opensuse.org/issues/55457

If there is a short delay between the update and the fetching of
"created_since=500" the test fails.

Now with 10 seconds it should usually pass.

### CODE REVIEW

**Comment by okurz** [comment]
"usually"? :) Wouldn't it be better to mock out any time dependance?

**Comment by perlpunk** [comment]
> "usually"? :) Wouldn't it be better to mock out any time dependance?

I pushed a commit. It does not mock.
It will now only fail if 10 seconds pass between the `$now = time` and the request.
Is this ok?

**Comment by okurz** [comment]
I guess. Please squash the fixup commit into the first

**Comment by perlpunk** [comment]
> I guess. Please squash the fixup commit into the first

done

**Comment by okurz** [comment]
Would you mind stating in the git commit subject line what the motivation for this change is? E.g. "Fix flaky t/api/11-bugs.t"? You can put your current line of the what you changed in the detailed commit description.

**Comment by perlpunk** [comment]
@okurz if this ever fails because it took longer than 10 seconds than I'll buy you a beer ;-)

**Comment by perlpunk** [comment]
> Would you mind stating in the git commit subject line what the motivation for this change is? E.g. "Fix flaky t/api/11-bugs.t"? You can put your current line of the what you changed in the detailed commit description.

done

**Comment by okurz** [comment]
tests failed in tidy referencing test modules, not openQA test code, weird. Retriggered as https://travis-ci.org/os-autoinst/openQA/jobs/572317117

**Comment by okurz** [comment]
still fails, dunno what's happening right now. Please crosscheck locally by running e.g. `script/tidy`

**Comment by perlpunk** [comment]
Oh right, I hadn't run tidy after my latest change. Done now

**Pull request merged**
