### PR TITLE
utils: add kernel bugzilla bugref

### PR DESCRIPTION
**Pull request by pevik**

### CODE REVIEW

**Comment by okurz** [comment]
LGTM

**Comment by Martchus** [comment]
No complaints about the add not being capitalized? Besides, LGTM. The failing test seems unrelated.

**Comment by pevik** [comment]
@Martchus : I thought that text after colon doesn't need to be capitalized, but ok, pushed new version -  capitalized.

**Comment by Martchus** [comment]
Actually I'm not sure. @okurz is expert :-)

**Comment by okurz** [comment]
@Martchus it's because of the component markers. @coolo convinced me I undermined my own rules with that. That is when I stepped back and need to reflect (3 months tibetian monastery or something) about this.

**Pull request merged**
