### PR TITLE
Improve buttons in interactive mode

### PR DESCRIPTION
**Pull request by Martchus**
* Show stop button in interactive mode (again)
* Remove spinner
* Builds on top of https://github.com/os-autoinst/openQA/pull/1082
* Still experimental / allows "exploring" further bugs

### CODE REVIEW

**Comment by coolo** [comment]
the travis failure appears random

**Comment by Martchus** [comment]
Like the travis check for the overall project which failed, too.

**Comment by coolo** [comment]
new assetpack release again? ;(

**Comment by coolo** [comment]
Undefined subroutine &OpenQA::WebAPI::Controller::Step::needle_info called at /home/travis/perl5/perlbrew/perls/5.18/lib/site_perl/5.18.4/Mojolicious.pm

**Comment by Martchus** [comment]
Yes, and I can reproduce locally.

**Pull request merged**
