### PR TITLE
Do not rely on WebAPI to find home - require and use an harmless class

### PR DESCRIPTION
**Pull request by coolo**

### CODE REVIEW

**Comment by aaannz** [comment]
Hmm.. why can't we use `$ENV{MOJO_HOME} = Mojo::Home->new->detect('OpenQA::Scheduler');` for scheduler and similarly for ws?

**Comment by coolo** [comment]
I guess we can. But what is the benefit of having diff for the diff sake?

**Comment by okurz** [comment]
you are duplicating code, can you add a function to Utils.pm maybe?

**Comment by coolo** [comment]
I can add functions, yes. But I can't use them during bootstrap

**Comment by coolo** [comment]
I tested out of curiousity: this is the result:
Failed to open /usr/share/openqa/lib/OpenQA/WebSockets/etc/openqa/openqa.ini:

**Comment by aaannz** [comment]
Ok, then OpenQA::Utils it is. :+1:

**Pull request merged**
