### PR TITLE
Fix production mode setting for cache service tests

### PR DESCRIPTION
**Pull request by kraih**
You can now actually see the output of other tests again. 😉

Progress: https://progress.opensuse.org/issues/44387.

### CODE REVIEW

**Comment by coolo** [comment]
now that's suprising - increasing project coverage with 0% patch coverage. Is that even possible logically? :)

**Comment by coolo** [comment]
https://travis-ci.org/os-autoinst/openQA/jobs/460278741 is still pretty spammy. Wasn't this your plan to fix?

**Comment by kraih** [comment]
@coolo It works locally, does something set `DEBUG=1` on Travis?

**Comment by coolo** [comment]
no idea.

**Comment by kraih** [comment]
Ok, then i amend the description. 😄This pull request gives you the option not to set `DEBUG` to make cache service tests less verbose.

**Comment by kraih** [comment]
I've just removed the `DEBUG` and `LOGDIR` environment variables, since they didn't appear to serve any real purpose. The cache service tests are now more consistent with other tests.

**Comment by kraih** [comment]
Ok, rebased and new commit message.

**Comment by okurz** [comment]
Thank you for this change, I can ~~finally read test output again~~ read test output a little bit better now ;) :heart:

**Pull request merged**
