### PR TITLE
Prevent double logline output in autoinst-log.txt

### PR DESCRIPTION
**Pull request by okurz**
Related ticket: https://progress.opensuse.org/issues/52235

### CODE REVIEW

**Comment by okurz** [comment]
This is an alternative to #2092 relying on https://github.com/os-autoinst/os-autoinst/pull/1162 to not add the "-d" parameter on more recent versions of os-autoinst

**Comment by asdil12** [comment]
That would require the backend version to be incremented as it hasn't happened, yet.

**Comment by okurz** [comment]
@asdil12 true, https://github.com/os-autoinst/os-autoinst/pull/1162 is needed for this

**Comment by coolo** [comment]
Still having 2 processes writing the same file is very dangerous. It is just stupid to open a file and then start another process to write to it. I veto this insanity - because in a couple of days you guys will file tickets for truncated log files and complain.

I repeat what I said: if isotovideo wants to catch log output, this should be a Mojo::Log subclass that does not write. And leave autoinst-log.txt alone.

**Comment by okurz** [comment]
@coolo unfortunately I still do not know what commit or PR should have introduced that. Are you arguing with https://github.com/os-autoinst/os-autoinst/pull/1149 ? or is it something else?

**Comment by coolo** [comment]
yes, #1149 needs to be disarmed - and the rest reverted

**Comment by asdil12** [comment]
> there is a reason the worker writes this file - because we add additional infos to it. And as this change is just as untested as all previous attempts, I really favor a complete rollback

And my patch keeps that - isotovideo will then write the normal log and the worker will then write the additional infos to the logfile. I thought that I already made that clear in my previous comments.

**Pull request closed without merging**
