### PR TITLE
Enable coverage analysis for important script folder as well

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by okurz** [comment]
hm, ok. I don't think this will help because most likely we never want to include the perl code from "script/" but just call the scripts as black box executables which won't work with gathering perl coverage. I guess I will try to move more business logic from the scripts to lib/ instead.

**Comment by perlpunk** [comment]
I think it's a good idea to include the files in `script` in the coverage. Just need to find out why it doesn't show up in the coverage summary.

**Comment by perlpunk** [comment]
lines 264 and 266 in `.circleci/config.yml` still only have `cover -select_re '^lib/'`

**Comment by perlpunk** [comment]
I created #2967 instead

**Comment by okurz** [comment]
https://github.com/os-autoinst/openQA/pull/2967 is a better alternative. We have found some duplication though which we might want to follow up with.

**Comment by perlpunk** [comment]
> #2967 is a better alternative. We have found some duplication though which we might want to follow up with.

Which duplication do you mean?

**Comment by okurz** [comment]
The multiple places where cover opts are defined

**Pull request closed without merging**
