### PR TITLE
Nilxam dbix profiling

### PR DESCRIPTION
**Pull request by coolo**

### CODE REVIEW

**Comment by coolo** [comment]
while we're at it we should also use the log file specified instead - and possibly include that in 'debug' already or make it its own log level instead of a special key

**Comment by ancorgs** [comment]
Since we are passing the schema as a parameter, placing ```enable_sql_debugging``` in the ```openqa``` module does seem to make much sense. I proposed initially (in the other PR) to put the function there so it could access the state ```$schema``` variable.

With this code it makes more sense to have the function in some database related place, like ```db_profiler``` (so it's self-contained) or ```Schema``` (so it can be called as ```$self->schema->enable_sql_debugging```).

**Comment by nilxam** [comment]
hmm...missing sql_traces in %defaults?

**Comment by coolo** [comment]
please recheck. I now enable sql debugging when the log is_debug

**Comment by ancorgs** [comment]
looks good

**Pull request merged**
