### PR TITLE
Add direct link to video position (poo#19300)

### PR DESCRIPTION
**Pull request by StefanBruens**
In case a time range is provided for a screenshot, use it to create a
link to the appropriate position of the screen recording.

This uses media fragments: https://www.w3.org/TR/media-frags/#naming-time

Signed-off-by: Stefan Brüns <stefan.bruens@rwth-aachen.de>

### CODE REVIEW

**Comment by coolo** [comment]
you would need one test in the fixtures with a frame, so you can verify the webui loads it and maps it

**Comment by okurz** [comment]
nice :-)

**Comment by StefanBruens** [comment]
@coolo: can you give some pointers for the fixture?

**Comment by okurz** [comment]
take a look within the folder t/fixtures. All files within there are loaded by tests to simulate a production database content for testing. You would need to add `$module_detail->{frametime});` thingy in there and then ensure that the URL shows the right thing for that, i.e. in a corresponding test. `ui/18-tests-details.t` might be the right test to add it to.

**Comment by okurz** [comment]
@StefanBruens just wanted to say a big "thank you" to you. This feature is really great and works good so far. Only in case we have tests with "NOVIDEO=1" where we don't upload a video the link is still shown and points to a 404 but that's not a big issue. In any case, thanks :-)

**Pull request merged**
