### PR TITLE
WIP: Add bootstrap tour to project with example

### PR DESCRIPTION
**Pull request by krauselukas**
Related to https://progress.opensuse.org/issues/16376

http://bootstraptour.com/

Added a quick example tour with bootstrap tour.  It is easy to use, just have to add a few lines of javascript to introduce a new feature. By default it stores the state (already seen etc.) locally. Its possible to navigate through sub domains (wasn't able to accomplish this yet).

screenshot_tour01

### CODE REVIEW

**Comment by coolo** [comment]
that progress issue is not about a tour through openqa - it's about a notification of new features.

**Comment by krauselukas** [comment]
@coolo yes, my example does not show new features, but i was thinking we could use this bootstrap tour thing to do so, just wanted to see if those notification popovers could do the job?

**Comment by coolo** [comment]
but the tour only makes sense on one page. But the 'cool feature' maybe in the needle editor or might be a new parameter to some existant route, or ...

So no, I don't think a tour helps any

**Comment by okurz** [comment]
As I read it bootstraptour can provide both. I think it goes along with the user epic "Simple and clean starting page for newbies with simple tasks to follow first to gain some experience" as mentioned on https://progress.opensuse.org/issues/16534 as well.

**Pull request closed without merging**
