### PR TITLE
Dependency cron 200829

### PR DESCRIPTION
**Pull request by openqabot**

### CODE REVIEW

**Comment by perlpunk** [comment]
I know why `45-make-update-deps.t` is failing. will try to fix tomorrow
https://github.com/os-autoinst/openQA/blob/master/.circleci/config.yml#L148
`dependencies.yaml` needs to be added.

**Comment by Martchus** [comment]
Ah, the tidying changes are now applied automatically. Likely I can close my manually prepared PR then.

**Comment by perlpunk** [comment]
I created #3343 to fix the problem with the forgottendependencies.yaml.
Not sure if this will also fix the checkstyle failure

**Comment by perlpunk** [comment]
Ah, I see, checkstyle failed because of `dbicdh/_common/upgrade/76-77/001-migrate-audit-events-to-scheduled-products.pl`
in `tools/tidy` we search for all `*.pl`, but in the PR we don't add that directory.

**Pull request closed without merging**
