### PR TITLE
Do not quote identifiers, solves problem with uppercase column

### PR DESCRIPTION
**Pull request by aaannz**
-  jobs columns TEST, DISTRI, etc.. were for pgsql translated as  "TEST", "DISTRI", etc.. This lead to errors with column not found  since unquoted strings are autotranslated to lowercase in pgsql

### CODE REVIEW

**Comment by aaannz** [comment]
This should not be merged without some caution. I may not know what I am actually doing here. @coolo needs to approve.

**Comment by okurz** [comment]
LGTM

**Comment by aaannz** [comment]
Removed the last commit, I will do it in different schema upgrade. It would be unfair to the one tester to mess his database once again.

**Comment by coolo** [comment]
I don't see the point - what errors is this fixing?

**Comment by aaannz** [comment]
Deployment files for pgsl contains quoted column names. That means for Jobs table it creates column names literally "TEST", "DISTRI", etc.. However when we access this in code, we don't explicitly quote. We just use 'TEST', 'DISTRI', etc. which is then translated to lowercase as I managed to google out.
Result is than that when you deploy new psql instance, webui will fail with message 'jobs.test' column does not exists and similar.

Reported on IRC by someone from Nue, @okurz has more details I think.

**Pull request merged**
