### PR TITLE
Fix exit code returned by client

### PR DESCRIPTION
**Pull request by okurz**
Fixes a problem introduced with 5c9068a3d.

### CODE REVIEW

**Comment by okurz** [comment]
Currently products are not correctly synced on o3. See https://progress.opensuse.org/issues/66060 . Maybe this has something to do with the wrong exit code of the client script? I pulled out that fix from https://github.com/os-autoinst/openQA/pull/2985 as that PR does not have approval yet and I will merge this PR as soon as checks are finished. I hope everyone is ok with that in an effort to fix the problem soon.

**Comment by perlpunk** [comment]
https://github.com/okurz/openQA/blob/fix/client/lib/OpenQA/Client.pm#L87
Shouldn't this line now be: `return undef;` ?

**Comment by okurz** [comment]
yes, of course. Thx. Fixed.

**Comment by okurz** [comment]
@perlpunk thanks for your support. This annoying UI test prevented my auto-merge :D

**Pull request merged**
