### PR TITLE
Start fedmsg-logger async

### PR DESCRIPTION
**Pull request by Martchus**
To reduce impact of fedmsg plugin on event loop

This is likely not the final solution but already a slight improvement.

### CODE REVIEW

**Comment by kraih** [comment]
Does this not result in zombie processes? Looks to me like `IPC::Run::finish()` is the function that actually calls `waitpid()` when you use `IPC::Run` asynchronously.

**Comment by Martchus** [comment]
What we don't want to do is waiting for this process (and `waitpid` might be a blocking call). We need to just start it and then don't care anymore about it.

I assumed this IPC module would do all the magic required to prevent zombie processes (handling `SIGCHLD`). The [documentation](http://search.cpan.org/~toddr/IPC-Run-0.94/lib/IPC/Run.pm#run()_vs._start();_pump();_finish();) is not really nice to read.

**Comment by kraih** [comment]
There are different flavours of `waitpid()` calls, you can block until the process exits (`waitpid $pid, 0`), or call it non-blocking over and over until the process exits (`waitpid $pid, WNOHANG`). And it doesn't look like `IPC::Run` has any magic for that, just functions like `IPC::Run::finish` which need to be called manually.

Also worth mentioning is that `$SIG{CHLD}` is not particularly reliable in this case, because event loop backends like `EV` might hijack the signal.

Native `Mojolicious` features like [subprocesses](https://metacpan.org/pod/Mojolicious::Guides::Cookbook#Subprocesses) or a plugin like [Mojo::IOLoop::ReadWriteFork](https://metacpan.org/pod/Mojo::IOLoop::ReadWriteFork) might be better choices here.

**Comment by Martchus** [comment]
Since this would be only a temporary solution I'd say it is not worth it.

But yes, using Mojolicious features would probably the way to go. If this would be just a 5 minutes task for you, then you can do it of course.

**Comment by Martchus** [comment]
Since this would be only a temporary solution I'd say it is not worth it.

But yes, using Mojolicious features would probably the way to go. If this would be just a 5 minutes task for you, then you can do it of course.

**Pull request closed without merging**
