### PR TITLE
Enhance/speedup tests

### PR DESCRIPTION
**Pull request by okurz**
https://progress.opensuse.org/issues/72082

Comparing the execution times of complete pipelines on
https://app.circleci.com/pipelines/github/os-autoinst/openQA/5800/workflows/1c455a9b-553b-4b28-bf37-8ab31eb40f17
I can observe that (by rough estimation) with this change
execution finishes faster than the previous mean value :)

### CODE REVIEW

**Comment by okurz** [comment]
Trying to find out why t/ui/07-file.t fails to find data from fixtures. Help would be appreciated :)

**Comment by Martchus** [comment]
Looks like only `t/ui/07-file.t` fails anymore.

**Comment by okurz** [comment]
Yes, which I unfortunately do not understand why that is the case. Help would be appreciated :)

**Comment by okurz** [comment]
ok, solved. Thank you teddy bear team chat channel 🙂

**Review by Martchus — APPROVED** [review]

**Review by kalikiana — APPROVED** [review]

**Pull request merged**
