### PR TITLE
Store result size of jobs

### PR DESCRIPTION
**Pull request by Martchus**
* Assets are not considered
* Logs are taken into account
* Screenshots taken into account, also if shared with other jobs
* Results written by the parser for external results are taken
  into account
* Other artefacts are taken into account
* Group-wide statistics can be easily queried using SQL, e.g.
  `select group_id, sum(result_size) from jobs
     group by group_id order by group_id;`

---

I've only done a local fullstack test (some LTP test) so far. It *looks* like this works but I better add some unit tests.

There's also a commit for parameter validation of the route to upload artifacts. It might not be perfect but better than failing with a 500 error.

### CODE REVIEW

**Comment by Martchus** [comment]
I'll create a ticket how I understand the problem.

> but I don't even know how this will be used

The commit message contains an example SQL query and that's for now the only way. I'm not very familiar with the Grafana/InfluxDB side but you said it can be filled from such SQL queries. So I guess this PR is actually useful although it is only the first step of course.

**Comment by Martchus** [comment]
I created the ticket (feel free to improve it if you like). So can we proceed with that? To me it seems that collecting the figures is required for all conceivable ways we want to address the problem so this PR would always be a good first step.

**Comment by Martchus** [comment]
> not automatically used by any other feature

It will be used by us as admins. With that argumentation we could scrap everything not used internally but only by users.

> I recommend to keep database migrations as much separated from other changes as possible

I separated the commits so we can revert commits individually as needed (except the db migration because we just can never revert them).

**Comment by coolo** [comment]
No idea on what missing @okurz is again - this was clearly discussed and worked on. We'll have to start somewhere

**Comment by okurz** [comment]
What I was missing is something better than "coolo told us something in verbal meetings". This was resolved. Then I only suggested to better split which Martchus also did. So I wasn't missing anything anymore :)

The "clearly discussed" is something I think we can improve: IMHO – according to how I understand remote collaboration best practices – decisions should be properly documented and publically available.

**Pull request merged**
