### PR TITLE
Mark t/ui/12-needle-edit.t as unstable after recent CI failures

### PR DESCRIPTION
**Pull request by okurz**
Related progress issue: https://progress.opensuse.org/issues/95009

### CODE REVIEW

**Review by perlpunk — APPROVED** [review]

**Comment by perlpunk** [comment]
Looking at the failing job, only `t/ui/26-jobs_restart.t` seems to be executed (and fails) in the unstable now

**Comment by okurz** [comment]
> Looking at the failing job, only `t/ui/26-jobs_restart.t` seems to be executed (and fails) in the unstable now

Right. I have reported https://progress.opensuse.org/issues/95024

**Review by kalikiana — APPROVED** [review]

**Review by ilausuch — APPROVED** [review]

**Review by perlpunk — DISMISSED** [review]
I think this isn't the right thing to do.

We are seeing timeouts in several tests since yesterday. All seem to be related to timeouts, and an earlier commit pushed has the same problems.

Just marking all of them as unstable wouldn't make sense I believe.

**Review by kraih — APPROVED** [review]

**Comment by okurz** [comment]
> I think this isn't the right thing to do.
> 
> We are seeing timeouts in several tests since yesterday. All seem to be related to timeouts, and an earlier commit pushed has the same problems.
> 
> Just marking all of them as unstable wouldn't make sense I believe.

Ok, that means we block all pull requests until we can solve this problem. I am fine with that unless we need to fix another urgent problem.

**Review by Martchus — CHANGES_REQUESTED** [review]
The test failure doesn't look specific to `t/ui/12-needle-edit.t`. It looks more like a general problem of our UI tests and I think I have seen this kind of error already elsewhere. It could even be just a timeout with a very messed-up error message and in the last few days (from last Thursday) CircleCI was just extraordinarily slow.

**Comment by perlpunk** [comment]
This was solved by #4009

**Pull request closed without merging**
