### PR TITLE
Fix back button on results page

### PR DESCRIPTION
**Pull request by asdil12**

### CODE REVIEW

**Comment by okurz** [comment]
I think we already have this with https://github.com/os-autoinst/openQA/pull/755 or what else do you fix? Can you add a test like https://github.com/os-autoinst/openQA/pull/756 ?

**Comment by asdil12** [comment]
I don't really understand, what you do in #755, but you do not touch the line, that pushes to the history.
I simple replace the history, so that the back button always leads to the page, that linked to the results page.
The current behaviour looks like as if someone included the tabs and the preview-needle-diff in the history. The test for that is written by you, so here is, what I think about this:

In my opinion we should *not* include tabs and result-preview in the history.
The first reason is, that the current implementation is broken and sometimes the back button needs to be pressed two times to make one thing happen (go to results, click the log tab, click back a few times).
The second reason is, that this prevents a user from quickly returning to the results matrix (or whatever page he came from) after browsing some results.

**Comment by asdil12** [comment]
Added a test.

**Comment by okurz** [comment]
change looks correct but I am torn if this behaviour is desired. LGTM, someone else can merge if agreed.

**Comment by coolo** [comment]
Users actually expected the tabs to change back on pressing back

**Comment by asdil12** [comment]
As a user *I* wouldn't.

But anyway: There is no real advantage - every tab can be clicked by the user. He doesn't need browser history for that.
The previous page is only available via browser history.

**Comment by coolo** [comment]
The previous step is not. If you are provided a step url (at e.g. Bugzilla)  then look at the comments, press back you need to be at the step url. But even if you switch steps you want to switch back - and you're breaking that expectation.

**Comment by asdil12** [comment]
As a user - maybe after some clicking around in the tabs and looking at some preview images, I might want to return to the overview page that linked to the test results page that I'm currently browsing.
Spamming the history with this makes it hard to find the back link.

I don't have any idea, what you mean with "The previous step is not."
When I want to switch steps, I use the arrow keys.
So let's at least remove the steps from the history - the tabs are bad enough.

Also the current implementation is broken (see my 1st comment).

**Comment by coolo** [comment]
that's true - if you navigate with keys, it should not pollute the history.

**Comment by coolo** [comment]
https://github.com/os-autoinst/openQA/pull/765 is my variant of the javascript - I didn't yet check how it behaves with your additional test

**Comment by coolo** [comment]
reviewing the test it's invalid, so I do not see anything left here

**Pull request closed without merging**
