### PR TITLE
Use signatures for all OpenQA::CacheService::Client methods

### PR DESCRIPTION
**Pull request by kraih**
This conversion was started in #3704 with one method. Converting the rest now too should be very harmless.

### CODE REVIEW

**Review by Martchus — APPROVED** [review]

**Review by okurz — APPROVED** [review]

**Review by perlpunk — APPROVED** [review]

**Comment by kraih** [comment]
The failed ui test is unrelated, other PRs hang there too it seems.

**Comment by okurz** [comment]
Hm, the tests failed in

```
[11:26:20] t/ui/12-needle-edit.t .................. 17/? Bailout called.  Further testing stopped:  test exceeds runtime limit of '120' seconds
FAILED--Further testing stopped: test exceeds runtime limit of '120' seconds
```

haven't seen that in before. Maybe related to other recent dependency updates. However we should not simply accept unstable tests. I suggest you either look into that as part of the PR even though for sure it's very unlikely to cause these failures or you create a ticket for that.

**Comment by kraih** [comment]
Running `t/ui/12-needle-edit.t` locally the test output looks clean, and it takes about 34 seconds. Also checked with current master, and it's exactly the same. So this PR has nothing to do with it. But i changed the timeout to 40 seconds to fix the problem.

**Review by ilausuch — APPROVED** [review]

**Comment by okurz** [comment]
and now

```
[14:07:17] t/api/14-plugin_obs_rsync.t ........ 11/? Bailout called.  Further testing stopped:  test exceeds runtime limit of '180' seconds
FAILED--Further testing stopped: test exceeds runtime limit of '180' seconds
```

😕

**Comment by kraih** [comment]
Tests passed. 😁

**Pull request merged**
