### PR TITLE
t: Add OpenQA::Test::TimeLimit to all test modules where applicable

### PR DESCRIPTION
**Pull request by okurz**
https://progress.opensuse.org/issues/71467

### CODE REVIEW

**Comment by okurz** [comment]
@os-autoinst/tools-team I wonder what you think about the style guide in https://github.com/os-autoinst/openQA/pull/3398/files#diff-85239ef1560108578afc632ac6cd356bR79 and following.

**Review by kalikiana — APPROVED** [review]

**Comment by Martchus** [comment]
Seems like tidy is too slow:

```
[07:57:25] t/00-tidy.t ............... Bailout called.  Further testing stopped:  test exceeds runtime limit of '200' seconds
FAILED--Further testing stopped: test exceeds runtime limit of '200' seconds
make[1]: *** [Makefile:174: test-unit-and-integration] Error 255
```

**Comment by okurz** [comment]
changed t/00-tidy.t from 200s to 400s

**Review by Martchus — APPROVED** [review]
If the tests are passing - no.

**Pull request merged**
