### PR TITLE
Downgrading selenium drivers during test phase

### PR DESCRIPTION
**Pull request by mudler**
bomb

### CODE REVIEW

**Comment by coolo** [comment]
< 1.20 won't work - for sure.

**Comment by coolo** [comment]
they released '1.22 - Now with less bugs?' - I think sticking with 1.21 should do best

**Comment by mudler** [comment]
https://travis-ci.org/mudler/openQA/builds/333759626

**Comment by mudler** [comment]
See https://github.com/os-autoinst/openQA/pull/1567 for a test with 1.21, this is the good one

**Comment by coolo** [comment]
I wonder at what point you're going to revert this to make the packages build again.

**Comment by mudler** [comment]
If we do revert, Travis tests won't work - or we adapt obs build specs or I don't see other solution here

**Comment by mudler** [comment]
Why obs should run selenium tests?

**Comment by coolo** [comment]
to verify our test suite runs on recent/packaged perl

**Pull request merged**
