### PR TITLE
Update documentation to commit 94bf36033

### PR DESCRIPTION
**Pull request by openqabot**

### CODE REVIEW

**Comment by Martchus** [comment]
It looks still broken. I assume the code should have been removed completely.

**Comment by okurz** [comment]
> I assume the code should have been removed completely.

What do you mean with that?

**Comment by okurz** [comment]
I will try to generate the documentation manually with the asciidoctor conversion before submitting a new PR for os-autoinst. Previously rendering of direct POD conversion looked fine but it seems Pod::Asciidoctor behaves different

**Comment by okurz** [comment]
https://github.com/os-autoinst/os-autoinst/pull/1747

**Pull request closed without merging**
