### PR TITLE
add possibility to extract downloaded assets

### PR DESCRIPTION
**Pull request by garretraziel**
Ability to append `_URL` after asset is convenient, but our HDD images (which we need to test because of ARM) are distributed in compressed form (xzipped). This commit add possibility to append `_URL_EXTRACT` to parameter and gru then decompresses downloaded asset.

Archive::Extract is needed from CPAN. It is part of core library, but according to warning, it will be removed soon.

### CODE REVIEW

**Comment by AdamWill** [comment]
next unless ($param =~ /_URL$/ || $param =~ /_URL_EXTRACT$/);

we have regexes so you don't have to 'or' everything ;)

    $param =~ /(_EXTRACT)?_URL$/

should do the trick (not tested). Aside from that, looks mostly fine. The guys are gonna want you to extend the tests to cover all this stuff, though. And is it always the case that `EXTRACT` is only useful when combined with `URL`, or should it be usable independently? Not sure.

**Comment by coolo** [comment]
please add tests

And I think I'd prefer EXTRACT_URL too

**Comment by coolo** [comment]
but there is one catch: We extract ISOs using bsdtar and add the resulting directory as REPO - as such we will need EXTRACT soonish too.

What you do is purely UNCOMPRESS, no?

**Comment by garretraziel** [comment]
I will add tests ASAP and change `_URL_EXTRACT` to `_UNCOMPRESS_URL`.

**Comment by aaannz** [comment]
Can you rebase the changes to get rid of merge commits?

**Comment by garretraziel** [comment]
I'll rebase it correctly once I'll have tests finished. I'm developing them in different branch and I wanted this branch to get rebased to newest master in upstream so I did it in rather dirty way, forgetting that my pull request will also be updated 😊.

**Comment by garretraziel** [comment]
This should be final version.

**Comment by aaannz** [comment]
LGTM.

For the future, we should come up with some mechanism to inform user when something failed, i.e. decompressing. So far only warning is logged, but that's accessible only to the openQA admin.

**Comment by AdamWill** [comment]
note for openQA folks: you'll need to update the RPM spec to require Archive::Extract.

**Comment by aaannz** [comment]
done, thanks for reminder

**Pull request merged**
