### PR TITLE
Make t/ui/21-admin-needles.t work for every timezone

### PR DESCRIPTION
**Pull request by perlpunk**
Issue: https://progress.opensuse.org/issues/167635

### CODE REVIEW

**Review by okurz — APPROVED** [review]
I would appreciate a comment for the non obvious code line

**Comment by kalikiana** [comment]
[  558s] error: %prein(openQA-worker-4.6.1727714539.ff293526-7225.2.x86_64) scriptlet failed, exit status 6
[  558s] error: openQA-worker-4.6.1727714539.ff293526-7225.2.x86_64: install failed

for [openSUSE Tumbleweed x86_64](https://build.opensuse.org/package/live_build_log/devel:openQA:GitHub:os-autoinst:openQA:PR-5965/openQA/openSUSE_Tumbleweed/x86_64)

**Comment by okurz** [comment]
@mergifyio rebase

**Comment by perlpunk** [comment]
> I would appreciate a comment for the non obvious code line

done

**Review by kalikiana — APPROVED** [review]

**Pull request merged**
