### PR TITLE
Use :report_warnings feature of Test::Warnings

### PR DESCRIPTION
**Pull request by perlpunk**
It will report all unexpected warnings at the end, to avoid having to search
through the whole output.

### CODE REVIEW

**Comment by okurz** [comment]
we have 0.030 by now. Can you rebase and retrigger?

**Comment by perlpunk** [comment]
> we have 0.030 by now. Can you rebase and retrigger?

But in `.circleci/dependencies.txt` there's still `perl-Test-Warnings-0.026`?

**Comment by okurz** [comment]
Interesting ...

19.05.2020 17:51:19 Tina Müller (tinita) <notifications@github.com>:

**Comment by perlpunk** [comment]
I linked the module into https://build.opensuse.org/project/show/devel:openQA:Leap:15.0, https://build.opensuse.org/project/show/devel:openQA:Leap:15.1, and https://build.opensuse.org/project/show/devel:openQA:Leap:15.2
So with the next nightly we should get the new version

**Pull request merged**
