### PR TITLE
Don't do 'rpm -i' when there is no package in cache

### PR DESCRIPTION
**Pull request by Amrysliu**
Relate: https://progress.opensuse.org/issues/98496

### CODE REVIEW

**Comment by Amrysliu** [comment]
Not sure if it's the right way for [poo#98469](https://progress.opensuse.org/issues/98496). Please help to confirm that.

**Comment by okurz** [comment]
Can you say what you see as benefit of this approach? In the end we need the packages installed anyway.

**Comment by Amrysliu** [comment]
> Can you say what you see as benefit of this approach? In the end we need the packages installed anyway.

According to the ticket's description,  the nightly CI will fail when there is no rpm in `/var/cache/zypp/packages/`.
My thought is to avoid this scenario.
BTW if no rpm in cache directory, how to get them and install them? I checked other nightly CI process, not all rpms (listed in ci-packages.txt) are stored in cache directory.

**Comment by okurz** [comment]
> According to the ticket's description, the nightly CI will fail when there is no rpm in `/var/cache/zypp/packages/`.
> My thought is to avoid this scenario.
> BTW if no rpm in cache directory, how to get them and install them?

I don't know, haven't checked details. Maybe resort to zypper

**Comment by okurz** [comment]
We discussed about this and found that my initial request was no good. We use the cached packages also to define our consistent, version specific set of packages that we want to rely on. Resorting to a generic zypper call on errors might work but defeat the purpose as we would not realize if there are problems on saving and loading the cache so eventually we would end up always downloading different versions with zypper on the fly which we wanted to avoid. For now I don't have any better idea than https://github.com/os-autoinst/openQA/pull/4238 for now, it's really not much.

Our next best bet would be to find the job on circleCI that actually failed to properly save the cache and prevent the error the next time.

**Pull request closed without merging**
