### PR TITLE
Avoid forking in t/24-worker-jobs.t to collect coverage of upload code

### PR DESCRIPTION
**Pull request by Martchus**
* See https://progress.opensuse.org/issues/95170
* This also removes the necessity of using `shared_hash` simplifying the
  test setup

### CODE REVIEW

**Review by perlpunk — APPROVED** [review]

**Review by okurz — CHANGES_REQUESTED** [review]
Looks nice. But your changes include uncovered code section in critical worker code. I would feel saver if we would have this code included in tests. If you plan to do that anyway then I would appreciate if you can do that first or include here. If you see this unfeasible for now then just say so and we can go ahead as is

**Comment by Martchus** [comment]
I've been testing the refactored code locally by running a few jobs and it seems to work. I also extended tests to cover all lines of the refactored code.

Note that the refactoring of actual worker code is only a small part of the diff. The big part of the diff is refactoring of the of the test code.

**Comment by okurz** [comment]
Good enough for an "acceptance-tests". Now to fix the other test problems. Little hint: Just retriggering without handling it properly will make me mad ;)

**Comment by Martchus** [comment]
I haven't realized there were test problems (besides the ones about timeouts which are already handled). The webui-docker-compose check seems to fail everywhere now.

**Pull request merged**
