### PR TITLE
Dependency cron 200621

### PR DESCRIPTION
**Pull request by openqabot**

### CODE REVIEW

**Comment by perlpunk** [comment]
I think we should actually merge this PR now. It's using the fixed Mojolicious version, and the failures are not related to the bug. They are happening in CircleCI since a couple of days, even for older commits. I tested several older commits that were all passing at the time they were merged.

**Comment by okurz** [comment]
I don't see the point in merging the PR when tests still fail. We can push any fixes into the same branch and merge after verifying that it fixes things.

**Comment by Martchus** [comment]
https://github.com/os-autoinst/openQA/pull/3152 shows the same error so it seems a general problem within the CI and not related to these version updates.

**Comment by kraih** [comment]
See also #3189 for why we need those versions.

**Comment by perlpunk** [comment]
I wrote:

> and the failures are **not related** to the bug. They are happening in CircleCI since a couple of days, even for older commits.

Not sure why that was unclear.
I had already been mentioning this in the chat.
The last master commit was passing in circleci. But every branch made from master or from older commits is failing in circleci now.
Every! You cannot find a single passing circleci job for the last days. The last passing job was 5 days ago.

So if https://github.com/os-autoinst/openQA/commit/7390623c6a0ca18c2d1fb703a81d62932475fd7e was passing when merged, why does it fail now when I branch from this commit and push to my fork?

**Pull request closed without merging**
