### PR TITLE
Make "last good" a link to a job instead of plain job ID

### PR DESCRIPTION
**Pull request by ilausuch**
https://progress.opensuse.org/issues/19720

Replace the job ID text plain by a direct link

### CODE REVIEW

**Comment by ilausuch** [comment]
This depends on the merge of https://github.com/os-autoinst/openQA/pull/3257

**Comment by Martchus** [comment]
I've reviewed #3257 in the meantime. It seems you're aware of the issue then. Since I've already pushed a fix I suggest to merge #3257 first and then rebase this one.

**Comment by okurz** [comment]
I am worried that this is putting too much logic into JavaScript which should focus on displaying only at best. Is it better here than in perl?

**Comment by ilausuch** [comment]
I think it could be interesting move the code to perl

**Comment by Martchus** [comment]
This logic is about displaying so I guess it isn't generally bad. But of course one could also expose some generic "meta information" from the Perl-side to the frontend which allow the frontend to be more ignorant about details such as certain key names. (E.g. each key has not only a value but also a type. The type is determined by the backend using whatever logic and then read by the frontend which only needs to know how to deal with these generic types.)

**Comment by ilausuch** [comment]
And in the current version if we don't have a previous good it's going to link to /tests/not found, that is not a valid url

**Comment by ilausuch** [comment]
> I am worried that this is putting too much logic into JavaScript which should focus on displaying only at best. Is it better here than in perl?

Alternative in https://github.com/os-autoinst/openQA/pull/3261

**Comment by okurz** [comment]
We can go with https://github.com/os-autoinst/openQA/pull/3261 or it's alternative

**Pull request closed without merging**
