### PR TITLE
t: Reuse "collect_coverage_of_gru_jobs" to reduce duplication

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by okurz** [comment]
Not sure what

```
t/25-cache-service.t | 98.02% <100.00%> (-0.03%)
```

is supposed to mean. https://codecov.io/gh/os-autoinst/openQA/commit/5ad5ce7e8a70ea6b97d3e39b919f5e4652e6662d looks still like 100% coverage and not 98.02%.

**Comment by Martchus** [comment]
That's just the diff coverage which is 100 %. The coverage for the file in general is 98.02 % because there are indeed some lines missing: https://codecov.io/gh/os-autoinst/openQA/src/5ad5ce7e8a70ea6b97d3e39b919f5e4652e6662d/t/25-cache-service.t

**Review by Martchus — APPROVED** [review]
But regardless of the missing coverage we can still merge this PR.

**Comment by okurz** [comment]
not so sure. I thought I had covered t/25-cache-client.t with 100%. I can reproduce 98% coverage locally. Will crosscheck.

**Pull request merged**
