### PR TITLE
Increase version requirement for some dependencies

### PR DESCRIPTION
**Pull request by kraih**
This week we've had quite a few important upstream fixes.

1. Minion 10.07 - Fixes a problem where all cache service restarts would
   result in unclean shutdowns because of ignored signal handlers.
   https://github.com/mojolicious/minion/commit/0505c1259990904c28aa69f8f8ade2bdf743cf9e

2. Mojolicious 8.55 - Fixes a regression where some CSS selectors from
   our tests were not working anymore, resulting in
   `Not an ARRAY reference at /usr/lib/perl5/vendor_perl/5.30.1/Mojo/DOM/CSS.pm line 237.`
   error messages.
   https://github.com/mojolicious/mojo/commit/7521e9611cc9906e1cd41ec73422c419912d63d4

3. Minion::Backend::SQLite 5.0.0 - Fixes a problem where cache service
   restarts would not just clear existing Minion locks, but the whole
   Minion database (inlcuding all job data).
   https://github.com/Grinnz/Minion-Backend-SQLite/commit/b35729e365c57bf83573e0ed68f0d9a0b133d198

### CODE REVIEW

**Comment by kraih** [comment]
We are still waiting for two requests to make it into Factory. https://build.opensuse.org/request/show/815729 and https://build.opensuse.org/request/show/815594

**Comment by perlpunk** [comment]
`.circleci/dependencies.txt` also needs an update.
That means currently the old versions will be used.

**Comment by kraih** [comment]
@perlpunk oh, i thought `make update-deps` would update everything now.

**Comment by kraih** [comment]
There should probably be a comment with a reminder in `dependencies.yml` then.

**Comment by perlpunk** [comment]
> @perlpunk oh, i thought `make update-deps` would update everything now.

That's currently not possible.
`.circleci/dependencies.txt` lists *all* installed packages with their versions, including dependencies from os-autoinst.
I can't do that from simply using dependencies.yaml.

I'm working on a different strategy for os-autoinst, and maybe we can use that for openQA as well if it works.

**Comment by kraih** [comment]
Just waiting for Mojolicious to make it into Factory now.

**Comment by kraih** [comment]
This PR should be ready now, the failed tests are unrelated.

**Comment by okurz** [comment]
Currently we can't fulfill the requirements in our common environments, e.g. https://openqa.opensuse.org/tests/1311407#step/openqa_webui/21 shows based on latest Tumbleweed . So I would say the PR was correct but should not yet have been merged. Also https://build.opensuse.org/package/show/openSUSE:Factory/perl-Minion-Backend-SQLite is not linked to https://build.opensuse.org/project/show/devel:openQA:Leap:15.1 neither to https://build.opensuse.org/project/show/devel:openQA:Leap:15.2 . I understand that the new upstream versions provide helpful bugfixes but I do not see them as hard requirements. As soon as newer package versions are present we benefit from them but they are not hard requirements. I recommend to revert this PR.

**Comment by okurz** [comment]
see https://github.com/os-autoinst/openQA/pull/3196

**Pull request merged**
