### PR TITLE
Enable nightly circleci dependency job on master

### PR DESCRIPTION
**Pull request by andrii-suse**
File `dependencies.txt` will become outdated unless somebody updates it regularly.
The nightly job is intended to create PR with updates.

### CODE REVIEW

**Comment by Martchus** [comment]
I'm wondering why changing this value from `circleci` to `master` would have the effect stated in the commit message so I haven't approved it yet.

**Comment by coolo** [comment]
because there is no circleci branch, so it's a toothless setting?

**Comment by coolo** [comment]
btw, 'ci skip' makes sure admins have to merge it - as we *require* a CI status check.

**Comment by andrii-suse** [comment]
> I'm wondering why changing this value from `circleci` to `master` would have the effect stated in the commit message

The bot did run on `circleci` branch in original PR to test dependency tracking (and protect master from potential error). His PRs were created in the fork and e.g. you can see that https://github.com/andrii-suse/openQA/pull/5 was created against `circleci` branch as was configured in config.cfg
The branch in config.cfg had to be changed to `master` when testing completed and before merging original PR, but it is something I forgot to make. 
The bot will create PR for any branch listed in configuration, but since there is no `circleci` branch at all - it doesn't do anything

**Pull request merged**
