### PR TITLE
Bootstrap 4 feedback

### PR DESCRIPTION
**Pull request by Martchus**
For the particular changes, just look at the commit messages.

Full screen mode:  
screenshot_20180419_125644

A bit more padding also on small screen width:  
screenshot_20180419_125852

Exact same colors for cards/panels as before:  
screenshot_20180419_130056

### CODE REVIEW

**Comment by coolo** [comment]
now fix that damn test :)

**Comment by Martchus** [comment]
Interesting that this still fails with the replaced combo box and also replaced test code to find the concerning elements on the page.

**Comment by Martchus** [comment]
Test `19-tests-links.t` actually fails because of https://github.com/os-autoinst/openQA/pull/1624/commits/bd06f6b01ebca2172f754cfac4361fb3fd3d85e7. I have currently no idea how to fix the tooltips. My hack only works when the tooltip is displayed above. However, despite setting `data-placement="top"`, the tooltip is sometimes shown below.

I also looked into `18-test-details.t` again. But it is really hard to figure something with only the information from the Travis log. I ran this test locally in a loop and couldn't reproduce. Maybe I should make the tests more verbose. Contents of the JSON files and screenshots could be useful.

**Comment by Martchus** [comment]
I fixed the failing tests except the annoying `18-test-details.t`. Let's see whether it passes on Travis.

The changes are also deployed on e212. Unfortunately there are no test results to verify the tooltip fix there.

**Comment by Martchus** [comment]
Ok, now really only `ui/18-tests-details.t` fails. I think I better fix this one on another branch.

**Comment by asdil12** [comment]
LGTM

**Comment by Martchus** [comment]
Failing `ui/18-tests-details.t` is fixed in https://github.com/os-autoinst/openQA/pull/1625 and has nothing to do with this. So I think the PR can be merged.

**Comment by coolo** [comment]
please rebase

**Pull request merged**
