### PR TITLE
Add influxdb route to poll stats of running and scheduled jobs

### PR DESCRIPTION
**Pull request by coolo**
https://progress.opensuse.org/issues/40583

### CODE REVIEW

**Comment by coolo** [comment]
Sunday afternoon experiment with grafana:

screencapture-e120-suse-de-3001-d-6nr0g91iz-openqa-jobs-2018-10-14-18_05_21

**Comment by coolo** [comment]
the split by worker and arch is ok, but both would benefit from having a 'queued' state that sums blocked+scheduled+running, otherwise it's a lot of copy&pasting in grafana.

And the job group split doesn't work like this. For job group it would be better to have speaking names in influxdb, otherwise you need to do this tagging in granfana, which kind of will not happen. And then there is the question if we shouldn't add up the parent groups instead of using the job groups (there are quite a lot of them - 72 distinct groups on osd last week)

**Comment by coolo** [comment]
To make the dashboard any reasonable, we need to tag the data - and this means using line format directly. e.g.

openqa_jobs_by_worker,server=https://openqa.opensuse.org,worker=openqa-arch64 running=1i
openqa_jobs_by_worker,server=https://openqa.opensuse.org,worker=openqaworker1 running=5i

openqa_jobs_by_group,server=https://openqa.opensuse.org,group=openSUSE Tumbleweed running=5i,scheduled=10i,blocked=3i,unfinished=19i

Then you can write templated dashboards:
SELECT mean("unfinished") FROM "autogen"."openqa_jobs_by_group" WHERE ("server" = 'https://openqa.opensuse.org') AND $timeFilter GROUP BY time($__interval), "group" fill(0)

ALIAS AS $tag_group

**Comment by Martchus** [comment]
Tests are missing, but otherwise looks good to merge. Since it is an API which is not supposed to be adjusted in an incompatible way anymore I would wait to merge until it is clear that this kind of output is really what we need on the Grafana-side.

**Comment by coolo** [comment]
Marius and me discussed that it's easiest to export the influxdb format directly - and as this wouldn't be an official API we should look for a different route.

**Comment by coolo** [comment]
screencapture-e120-suse-de-3001-d-nrdab3jiz-openqa-jobs-2018-10-15-16_06_21

**Comment by coolo** [comment]
added a minimal test case

**Pull request merged**
