### PR TITLE
new perltidy options

### PR DESCRIPTION
**Pull request by aaannz**
- the main thing is in 'new tidy options' commit. The rest is autogenerated.
- see action#6990

### CODE REVIEW

**Comment by lnussel** [comment]
srsly?

**Comment by aplanas** [comment]
+1, even there is an increase of test coverage by +0.02%

**Comment by aaannz** [comment]
@lnussel What seems to be a problem?

**Comment by lnussel** [comment]
no problem I just wonder whether a few white space justifies this. Note that the same needs to be done to os-autoinst and the tests then.

**Comment by aaannz** [comment]
That's probably for one's taste and I don't mind. From my perspective the sooner, the better.

And yes, I have same commit for os-autoinst, but I'm waiting with that for feedback on this one so we'll have same tidy rules. This is still open for discussion, I'll have to rebase that anyway.

**Comment by lnussel** [comment]
I'm not exactly a fan of the current style either but what's worse is reformatting all the time. Are you sure this is the last time we need to do this or will next week some dislike how braces are placed?

**Comment by aaannz** [comment]
The point is I'm not sure. That's why I opened this PR and associated action in progress.
But yes, my plan is that once we agree on some perltidy config it will stick for some reasonable amount of time.

**Comment by coolo** [comment]
I don't mind - either way. I'm so used to run the tidy script before I run make test

**Comment by coolo** [comment]
I merged this now

**Pull request closed without merging**
