### PR TITLE
test for _PARALLEL_JOBS as comma separated string

### PR DESCRIPTION
**Pull request by nadvornik**
test for https://github.com/os-autoinst/openQA/pull/694

### CODE REVIEW

**Comment by okurz** [comment]
well, easy ;-) But we are not testing the old behaviour then anymore so I guess the test can be a bit more "duplicating" and call first for the old behaviour, as list, but also as comma separated string. I think you can simply create the jobs once with both ways, crosscheck that they return the equivalent and delete the jobs created by one of the two ways to preserve the state for the rest of the test.

**Comment by aaannz** [comment]
There is still test for 'old way', see [L592](https://github.com/os-autoinst/openQA/blob/master/t/05-scheduler-dependencies.t#L592)

**Comment by coolo** [comment]
then why not merge it?

**Comment by okurz** [comment]
why didn't the coverage increase then?

**Comment by coolo** [comment]
you're either kidding or just annoying. But to answer the question: because #694 is a change in a regexp and the coverage displayed is just counting lines executed. And the line this regexp was on was executed before and is executed now.

**Comment by okurz** [comment]
I am not kidding (so I am annoying). Isn't the coverage the complete statement+branch+path coverage?

**Comment by coolo** [comment]
how does this relate to what I said?

**Comment by okurz** [comment]
I was just confused by your statement regarding line coverage. The line you were mentioning has different branches that the code can take that's why I asked for clarification. Nevermind.

**Pull request merged**
