### PR TITLE
Display serial results similar to external parser results

### PR DESCRIPTION
**Pull request by Martchus**
See https://progress.opensuse.org/issues/70648

---

This simplifies the code because serial results are no longer something special. I likely still need to adapt some tests.

---

Before:  
screenshot_20200828_143816

After:  
screenshot_20200828_143502

So the new view uses more vertical space but this page usually has vertical scroll bars anyways. Before all the "terminal icons" didn't have much value because one had to click on them to see something specific at all (after a short loading time). Now one can expand the individual results much faster.

It is now consistent with external results but I've kept the familiar terminal ">" so the results are still distinguishable from external results.

### CODE REVIEW

**Comment by asdil12** [comment]
Nice work - just 2 things:

- It is a bit hard to see when a command ends and the next one begins. - Could each command get it's own border?
- Is it possoble to show the command return code? The `Result:` seems to be empty here

**Comment by Martchus** [comment]
> It is a bit hard to see when a command ends and the next one begins. - Could each command get it's own border?

Yes, that should be quite simple (and would also an improvement for the external results).

> Is it possoble to show the command return code? The Result: seems to be empty here

It is quite unfortunate that the height in the collapsed state is slightly too less to display the result. However, it would likely make more sense to remove the blank line before `# Result:` instead of increasing the height.

**Comment by Martchus** [comment]
> Could each command get it's own border?

The background was missing (compared to external parser results).

It looks now like this with your os-autoinst change:

screenshot_20200828_161816

**Review by kalikiana — APPROVED** [review]
That looks so much better, it's the fix I've wanted for a long time without knowing what it was.

The `title=wait_serial` checks feel a little odd, but I guess you didn't wanna blow up the diff unnecessarily so just mentioning it for future consideration.

**Pull request merged**
