### PR TITLE
Add global settings support for clone job

### PR DESCRIPTION
**Pull request by mitiao**
See: https://progress.opensuse.org/issues/25412

### CODE REVIEW

**Comment by coolo** [comment]
Please put a little more text into the commit log than just the link, so you can find out what the reason for this change is even if progress.oo is down

**Comment by Martchus** [comment]
I also messed with that part of the code recently and noticed that it isn't well covered in our test suite and would also require some refactoring. Improving this is out of the scope of the PR but I assume you tested the change at least manually?

**Comment by mitiao** [comment]
Yes, I tested it manually to clone some cluster jobs and single job, seems work fine. I agree to do some refactoring to improve this, any idea?

**Comment by coolo** [comment]
well, one way to make it easier to test is moving the logic what settings to clone where into a module and then write unit tests for it. So clone_job will then fetch the original job, call into the module and then post the resulting job settings.

**Comment by Martchus** [comment]
The refactoring looks like a good start.

I tested it locally and also created reduced the deep nesting in the function. I also added a test for `_GROUP/_GROUP_ID` handling. If you like, you can cherry-pick the commits from https://github.com/os-autoinst/openQA/pull/1734.

**Comment by mitiao** [comment]
@Martchus where are your commits, i could not find :)

**Pull request merged**
