### PR TITLE
Mark workaround needles as such in the overview

### PR DESCRIPTION
**Pull request by coolo**
https://progress.opensuse.org/issues/9922

### CODE REVIEW

**Comment by aaannz** [comment]
Interesting colour choice. Wouldn't this make it less visible? From what I briefly tried it looked less dominant than ok result. I think we want opposite. But LGTM the rest.

**Comment by okurz** [comment]
color choice is always difficult. In this case I would also opt for a more dominant color. Why not use real yellow? Text in this color is not readable but we only use it as a border color for something that does not need to look nice but catch the eye and be distinguishable from red and green. I would say yellow (#ffff00) or maybe magenta (#ff00ff). If you like less Augenkrebs, maybe *blueviolet* (#8a2be2) from http://www.w3.org/TR/css3-color/#svg-color . your choice #A3C16C is fully custom color selection?

**Comment by coolo** [comment]
thanks for your comments, but the colour for softfail was chosen by our designer.

**Comment by okurz** [comment]
ok, can I talk to the designer?

**Pull request merged**
