### PR TITLE
Move LiveHandler to WebAPI where used

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by okurz** [comment]
@kraih can you approve and merge?

**Comment by kraih** [comment]
I was still trying to separate livehandler and webapi. https://github.com/os-autoinst/openQA/compare/kraih/live_refactor

**Comment by okurz** [comment]
I see. That would be a better alternative. So I will wait some days if you can finish it :)

**Comment by kraih** [comment]
Yea, unfortunately it will take at least a few more days. In my branch webapi and livehander still share authentication logic, and i need to think a bit more about the cleanest way to share that between the two. It's tricky because our authentication logic is not particularly clean itself.

**Comment by okurz** [comment]
I will close this PR to let kraih have his chance without causing conflicts by keeping this open

**Pull request closed without merging**
