### PR TITLE
Add a switch to enable the symlink feature

### PR DESCRIPTION
**Pull request by Amrysliu**
Compare #3712, this pull request includes a switch to enable the symlink feature.
The related code can be found in the separate commit.

### CODE REVIEW

**Review by okurz — APPROVED** [review]
The switch looks easy. We should have done that from the beginning :D

**Comment by okurz** [comment]
I pushed a rebase to get CI tests going

**Review by kalikiana — APPROVED** [review]
Excellent!

**Comment by okurz** [comment]
The OBS project is now "broken", likely due to the timely forced pushes by me and Amrysliu.

**Pull request merged**
