### PR TITLE
Add 'match' query parameter for index page

### PR DESCRIPTION
**Pull request by okurz**
Related progress issue: https://progress.opensuse.org/issues/13742

### CODE REVIEW

**Comment by aaannz** [comment]
I don't understand why 'match' keyword. Somehow I don't feel to like it.
Why not just use `group` even for matching?

**Comment by okurz** [comment]
seems like a good idea, I will try

**Comment by Martchus** [comment]
@aaannz Using the group for matching would make filtering for the particular group _opensuse_ difficult if there are two groups _opensuse_ and _opensuse test_.

**Comment by aaannz** [comment]
I'm aware of that and I'm not sure if it is a big deal. For exact matches is should be possible to add `$` at the and of the match :)

From my POV, I would rather have to put `$` at the end of the match than extra `match` query option.

**Comment by Martchus** [comment]
Ok, that sounds easy enough.

**Pull request merged**
