### PR TITLE
Use Codecov-related env variables from orga context

### PR DESCRIPTION
**Pull request by Martchus**
* Make configured token available by specifying context
* See https://progress.opensuse.org/issues/163187

### CODE REVIEW

**Review by okurz — APPROVED** [review]

**Comment by Martchus** [comment]
This unfortunately didn't work. As mentioned in https://progress.opensuse.org/issues/163187#note-8 I'm really wondering how OBS does it.

**Comment by Martchus** [comment]
It seems like the report cannot be generated in the first place when running only a reduced number of tests. So I'll have to run the full test suite again to see whether it now works after adding security groups on CircleCI.

**Comment by Martchus** [comment]
My tests revealed that the `CODECOV_TOKEN` environment variable is simply empty and that the Orb then passes an empty token leading to the the 401 auth error we see. This can be worked around by not using the token at all by also not using the Orb, see https://github.com/os-autoinst/openQA/pull/5751.

This means the culprit is the environment variable passing of CircleCI. I haven't found anything useful about it [on the forums](https://discuss.circleci.com/search?q=environment). So maybe I'll ask there myself considering we definitely followed the [documentation](https://circleci.com/docs/env-vars).

**Comment by Martchus** [comment]
Looks like all I had to do was enabling the setting "Pass secrets to builds from forked pull requests", see https://github.com/os-autoinst/openQA/pull/5751. I tested that on this PR which showed the correct checksum.

We may still merge the initial change of this PR. I removed the additional commits again and reworded the first commit as "[Use Codecov-related env variables from orga context](https://github.com/os-autoinst/openQA/pull/5750/commits/6c665edd877c5e671b88f9b3886f969512f9f466)".

**Review by okurz — APPROVED** [review]

**Review by kalikiana — APPROVED** [review]

**Pull request merged**
