### PR TITLE
Blocked_by revert

### PR DESCRIPTION
**Pull request by mudler**
Just for reference, this is what is currently deployed on osd and o3

### CODE REVIEW

**Comment by coolo** [comment]
So is this revert reverted again?

**Comment by foursixnine** [comment]
@coolo how so? But indeed, this is what got reverted

**Comment by coolo** [comment]
Please revert to the new scheduler for master

**Comment by coolo** [comment]
Sorry, I call this BS. You reverted *the very same day I went on vacation* and there was no 'very broken build' before my vacation. So if you had a very broken build then not because of this revert.

So revert this revert

**Comment by Martchus** [comment]
The revert got merged on 17. Aug. So when I remember dates correctly, the new scheduler was on master the whole week first week of your vacation.

One more thing to mention is that the new scheduler broke the testsuite. That impaired developing other aspects of openQA. Note that there's still a big pile of outstanding PRs.

**Comment by coolo** [comment]
what's on master doesn't matter too much - on 13th @mudler deployed this branch

**Comment by mudler** [comment]
https://progress.opensuse.org/issues/39560 https://progress.opensuse.org/issues/39629

**Comment by coolo** [comment]
I'm not saying there is nothing left to fix - I'm saying: revert the revert

**Pull request merged**
