### PR TITLE
docker: remove ssl apache conf from web UI

### PR DESCRIPTION
**Pull request by ilausuch**
The web UI container cannot be run because the current SSL configuration for Apache (openqa-ssl.conf) uses some certificates that don't exist.

This PR removes the SSL configuration for Apache and only keeps the HTTP port.

[poo#80520](https://progress.opensuse.org/issues/80520)

### CODE REVIEW

**Review by kalikiana — COMMENTED** [review]
What's the expectation going forward? I strongly prefer SSL even "for development" because you'll expose the server somewhere down the line. Do we have a ticket to track it? Some place to document what's missing?

**Review by Martchus — COMMENTED** [review]
I guess the need to supply or automatically generate certificates is the only problem here. I'm wondering how other projects which provide a container setup deal with this. Maybe we can provide a default certificate or generate a certificate on-the-fly?

**Review by okurz — CHANGES_REQUESTED** [review]
* Please start the git commit message with a capital letter after the component marker, i.e. `docker: Remove …`

* In https://github.com/os-autoinst/openQA/pull/3612/files#diff-556bfd867ae6eeb0082f6c1f39df5f8159b51e07cfbe47a737badd4f622b6e5eR13 gensslcert is called but this seems to create files that end up elsewhere. Maybe the behaviour of gensslcert changed over time. Please crosscheck the git history for this as well. But still generating certs and configuring apache with SSL but not using it does not make sense to me, either fix the SSL config to use the generated one or remove it completely or, maybe even better, define a SSL variant Dockerfile and one without

**Comment by ilausuch** [comment]
I think the PR #3632 is a better solution than this. So I close this PR

**Pull request closed without merging**
