### PR TITLE
Fix network dependency for cache service

### PR DESCRIPTION
**Pull request by nicksinger**
Maybe this makes @coolo more happy :)

### CODE REVIEW

**Comment by okurz** [comment]
but do we know we actually need this?

**Comment by nicksinger** [comment]
All I really *know* is: ["network.target has very little meaning during start-up. It only indicates that the network management stack is up after it has been reached."](https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/) which is what @coolo send me after proposing network.target as dep.

**Comment by okurz** [comment]
yes, this is what we learned in https://github.com/os-autoinst/openQA/pull/1884#issuecomment-441164333 and this is why I stated exactly that in my commit message in #1878 hence my question: "Do we know we actually need this?"

**Comment by Martchus** [comment]
And that comment also states "The problem should be fixed in the code itself" which is what the systemd documentation suggests as well.

@kraih Maybe there's a switch in Mojolicous so it behaves like https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget describes "well-written" software?

**Comment by okurz** [comment]
@foursixnine I wonder are you just blindly hitting merge buttons in error or do you follow the discussion here? Probably it's your secret #qa-tools room discussion where I was pseudo-banned from ;)

**Comment by foursixnine** [comment]
@okurz Not really :) I missed the network-online target in the previous PR, @nicksinger was kind enough to provide the new pr :), I hit merge after double checking, that's it.

**Comment by okurz** [comment]
@Martchus I agree with you, can you please make sure that this is being followed on, e.g. with a ticket or something? Depending on if you and @kraih maybe have discussed further already

**Comment by kraih** [comment]
I don't think there is anything Mojolicious could do differently.

**Pull request merged**
